### ISSUE TITLE
recording feature

### ISSUE THREAD

**Issue by paper555555555555555555555555555** [NatroTeam/NatroMacro#116]
### Have you searched the existing suggestions?

No

### What is your suggestion?

this feature would like the user presses the record button and then after they are done recording the user  names  the recording  and then the recording is in the pattern shape drop downs one the user selects their recording the macro copys the recording and repeats it until the time is up or what % of their container until the macro goes to their hive (i would give a recording limit of 5 because people might spam record and then the macro breaks)

### How will this improve Natro Macro?

it would help because people can record their playing style and the macro would copy it so users dont have a limited option of  12 pattern styles

### What is your Discord username?

lko_qqq

**Comment by paper555555555555555555555555555** [comment]
how

**Comment by Noobyguy775** [comment]
> how

Join the discord, finish the tutorial and then click [this link](https://discord.com/channels/1012610056921038868/1037835913742536724)

**Comment by paper555555555555555555555555555** [comment]
i did the tutorial what do i do now
