### ISSUE TITLE
somthing doesnt make sense

### ISSUE THREAD

**Issue by luclyb** [NatroTeam/NatroMacro#118]
### Have you searched the existing bug reports?

No

### What happened?

im using natromacro on bee swarm sim but when i try to go to a location lets say mountain top or pineapple patch. it takes me to the tree stump every time

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i hope that you can fix it

### Natro Macro version

v0.9.8

### What is your Discord username?

lybeck_

**Comment by luclyb** [comment]
no i dont have quests enabled or turned on the setting to kill the stump
snail


Den søn. 31. dec. 2023 kl. 00.39 skrev Aspect ***@***.***>:

**Comment by misc-et** [comment]
Have you resolved this issue? We will go ahead and close it as it's been inactive, but please feel free to head to our Discord for further troubleshooting support if needed.
