### ISSUE TITLE
Auto SSA

### ISSUE THREAD

**Issue by okcs121** [NatroTeam/NatroMacro#119]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

You can give it which stats it needs to get to keep it, and even the minimum amount. Maybe It can spend an "x" percent of the daily honey made

### How will this improve Natro Macro?

For me, Im so lazy to go for a 5/5 Ssa, and I think, not im the only 

### What is your Discord username?

szarokazujfelhasznalonevek

**Comment by Noobyguy775** [comment]
Use Birb Lit Club, It has an auto-SSA and an auto-mutate feature. https://birblit.club/
