### ISSUE TITLE
sprinkler bear morph bug

### ISSUE THREAD

**Issue by asketchybanana** [NatroTeam/NatroMacro#125]
### Have you searched the existing bug reports?

No

### What happened?

when you have a bear morph that increases jump power, sprinklers dont work because youre too high off the ground and the game wont let you place the sprinkler

### Steps to reproduce

1.get a bear morph
2.jump and try to place a sprinkler
3.

### What would you expect to happen?

the "you must be standing in a field to place sprinkler" message shows up

### Natro Macro version

v0.9.7

### What is your Discord username?

twizfur

**Comment by zspz** [comment]
Thanks, this will be fixed in the next version, there will be detection of a failed sprinkler placement and the macro will attempt to adjust the delay appropriately.
