### ISSUE TITLE
Quests Gumdrop Option

### ISSUE THREAD

**Issue by KJ76539** [NatroTeam/NatroMacro#126]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I suggest adding a gumdrop hotbar setting.

### How will this improve Natro Macro?

This would mostly be used for the purpose of completing quests for riley bee and bucko bee.

**Comment by misc-et** [comment]
Thanks, this suggestion has been made and is under consideration for potential future inclusion in the macro.

**Comment by Noobyguy775** [comment]
#449
