### ISSUE TITLE
Selecting ant passes to donate to the wind shrine.

### ISSUE THREAD

**Issue by wwoowwlol** [NatroTeam/NatroMacro#128]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Being able to donate ant passes to the wind shrine from the item selector.
There are currently no options to auto-donate ant passes to the wind shrine.

### How will this improve Natro Macro?

This way lower-leveled macroees can receive ant passes and donate them to the wind shrine autonomously.

### What is your Discord username?

kaixinx

**Comment by zspz** [comment]
Thanks for the suggestion, Ant Pass and Cloud Vial donation options will be added to the next version.
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/5c4bb043-c1f4-46e2-be79-ae9f64d3b01a)
