### ISSUE TITLE
Automatic ant challenge grind

### ISSUE THREAD

**Issue by 01legends** [NatroTeam/NatroMacro#13]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

You can activate the continuous ant challenge grind option which will cause the macro to make you go through the ant challenge repetitively until you have no more ant passes left. We can toggle the ant challenge macro section for what our ideal amulet stats would be which the macro can use to decide if the amulet should be kept or replaced, for example if I set minimum 40% crit power  since i had 30% crit power and I get a 42% crit power, then the macro would replace the amulet due to the critea being met, i understand that there are multiple stats which would cause the Natro Macro a headache to decide whether to keep or replace which is why we have a *minimum replace* stat option so that if one or more of the minimum stat is not met, the Natro Macro will keep the current amulet.

This would be one of the simplest and easiest things to implant as the Natro Macro already automatically does ant challenge for quests, all that would be needed to be done is to copy and paste with some modifications.

### How will this improve Natro Macro?

This will allow for players to potentially gain a better supreme amulet and gain materials such as jelly beans and robo passes which are extraordinary useful for us end game players to have but we would not have the motivation to sit at our pc for 50+ minutes actively checking/playing ant challenge so that we can use up all 10 of our ant passes.

### What is your Discord username?

luoen.

**Comment by Noobyguy775** [comment]
This somewhat already exists in Collect tab
Ant from pass to challenge

But it’s pretty hard to get supreme amulets unless you have a full red hive and can gather enough before the mowers come, and dodging is out of the question aswell (would either be incredibly difficult or straight up impossible)

Leaving ant amulets on the screen similar to snail and king beetle amulets is already on the suggestion board and can be implemented pretty easily i’d say

**Comment by 01legends** [comment]
This is exactly why i say it’s for us end game players. and it does not exist yet. also if you do 10 any challenges, you will only be left w the last amulet of left on screen.

**Comment by 01legends** [comment]
> This is exactly why i say it’s for us end game players. and it does not exist yet. also if you do 10 any challenges, you will only be left w the last amulet of left on screen.



> This somewhat already exists in Collect tab Ant from pass to challenge
> 
> But it’s pretty hard to get supreme amulets unless you have a full red hive and can gather enough before the mowers come, and dodging is out of the question aswell (would either be incredibly difficult or straight up impossible)
> 
> Leaving ant amulets on the screen similar to snail and king beetle amulets is already on the suggestion board and can be implemented pretty easily i’d say

This is exactly why i say it’s for us end game players. and it does not exist yet. also if you do 10 any challenges, you will only be left w the last amulet of left on screen.

**Comment by zspz** [comment]
Yes, it's important to note that it is generally accepted that Ant Amulet quality increases with Ant Challenge score. If obtaining the minimum threshold of 150 meant that you can still earn amulets with high stats, then I would've considered this.

Since that is not the case, I don't see a benefit in leaving Ant Amulets on screen **nor** training the macro to specifically obtain high scores in Ant Challenge. You are almost guaranteed to get a better amulet when doing the Ant Challenge manually.

The only improvement I see worth considering is perhaps some slight movement or detection so that each Ant Pass run for quests will kill more of the desired mob. However, this is not a priority.

**Comment by zspz** [comment]
Marked as not planned.
