### ISSUE TITLE
Memory Match

### ISSUE THREAD

**Issue by TheCruisingCrusader** [NatroTeam/NatroMacro#130]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add a feature where you can choose which memory matches you would like to use, how many attempts you have for that memory match, how often you want to do memory match and, like an allow gather interrupt thing.

### How will this improve Natro Macro?

This would improve Natro Macro by improving the player's progress in bee swarm simulator by obtaining materials through memory match, and in some cases completing some quests.

### What is your Discord username?

@crxssfiring

**Comment by Noobyguy775** [comment]
#70
