### ISSUE TITLE
idk how to use github but like unethical bug report, for clover field if you use corner x snake pattern shape it will take you off the field, this is also the same for cactus field.

### ISSUE THREAD

**Issue by cryolator** [NatroTeam/NatroMacro#132]
### Have you searched the existing suggestions?

No

### What is your suggestion?

d

### How will this improve Natro Macro?

d

### What is your Discord username?

paige0741

**Comment by misc-et** [comment]
These two fields don't have reliable corners on field to align to, so cornerxsnake is not recommended for them.

If you don't have supreme saturator, it's recommended to use stationary, or try a custom pattern from our Discord.
