### ISSUE TITLE
Planter in a field

### ISSUE THREAD

**Issue by ARG20091** [NatroTeam/NatroMacro#133]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I would like to force certain fields to only have certain planters. 

### How will this improve Natro Macro?

This is benefit macro users because it will maximize the efficiency of the macros ability to collect nectars.

### What is your Discord username?

arg20091

**Comment by misc-et** [comment]
If you'd like to choose specific planter/field combinations, the best option is to use Manual Planters (toggle the slider on the top right of planters tab to Manual).

The Planters+ option is based around an inbuilt algorithm that uses information such as growth time and nectar bonuses to optimise nectars.
