### ISSUE TITLE
When the pollen is full, it will not automatically return to the nest

### ISSUE THREAD

**Issue by xiaoniangaoh** [NatroTeam/NatroMacro#134]
### Have you searched the existing bug reports?

Yes

### What happened?

The first 3~4 hours of digging up the pollen will automatically return to the nest, and then one will dig and will not return to the nest
Here's the configuration：
![QQ截图20240110121059](https://github.com/NatroTeam/NatroMacro/assets/112637370/4b7547ad-bc0f-4ebf-82a3-0b79f240037c)

![QQ截图20240110121114](https://github.com/NatroTeam/NatroMacro/assets/112637370/05a28501-3912-4338-8dca-8bc0193359d8)
![QQ截图20240110121130](https://github.com/NatroTeam/NatroMacro/assets/112637370/355c1653-5451-4841-b70e-8e2d7f6a7449)

### Steps to reproduce

1.initiate
2.Wait for 3~4 hours
3.It's not going back to the nest anymore

### What would you expect to happen?

Return to the nest

### Natro Macro version

0.9.8

### What is your Discord username?

xiaoniangaoh_24982

**Comment by misc-et** [comment]
I think you may also have opened a support post at our Discord for this issue? 

That would be the best place for us to help troubleshoot.

**Comment by xiaoniangaoh** [comment]
> I think you may also have opened a support post at our Discord for this issue?我想您可能也在我们的 Discord 上为这个问题打开了一个支持帖子？
> 
> That would be the best place for us to help troubleshoot.这将是我们帮助排除故障的最佳场所。

https://discord.com/channels/1012610056921038868/1194567543923425371

**Comment by xiaoniangaoh** [comment]
Wait for me to test it for two days

**Comment by xiaoniangaoh** [comment]
The language of the game should be English, and the language of the account should also be English
