### ISSUE TITLE
Farm doesn't work

### ISSUE THREAD

**Issue by Takirima** [NatroTeam/NatroMacro#135]
### Have you searched the existing bug reports?

No

### What happened?

when I turn on the computer my screen only turns up and then it just resets, my friend didn’t have this before also help solve this problem

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I want you to help me solve this problem

### Natro Macro version

Last version

### What is your Discord username?

.katexx

**Comment by misc-et** [comment]
Can you provide some further details about your issue? 

Or alternatively, go to our Discord where you can find troubleshooting guides and make a macro-help post for support.
