### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 5f4d5** [NatroTeam/NatroMacro#136]
### Have you searched the existing bug reports?

No

### What happened?

![KakaoTalk_20240111_095436659](https://github.com/NatroTeam/NatroMacro/assets/156266898/02b87420-fb6e-42b0-9677-08758a4770ba)

### Steps to reproduce

1.walk pls

### What would you expect to happen?

good

### Natro Macro version

v0.8.9

### What is your Discord username?

enlwlsek

**Comment by Noobyguy775** [comment]
If you mean dying from bugs, decrease your hive bees in settings tab.
