### ISSUE TITLE
Randomly using micro converters.

### ISSUE THREAD

**Issue by 1max12** [NatroTeam/NatroMacro#137]
### Have you searched the existing bug reports?

No

### What happened?

I was macroing and when i came back i went from 12 to 0. To test this, i looked while i was macroing 1 day and it was taking up my micro converters. My micro converters are in slot 1 and for some reason 0.98 doesnt have slot 1.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

e

### Natro Macro version

0.98

### What is your Discord username?

1m_x1

**Comment by misc-et** [comment]
To fix this, you'll need to remove micro-converters from slot 1, and put your sprinkler there instead. Slot 1 is for your sprinkler, and the macro will click it to place your sprinkler when you enter a field to start gathering.
