### ISSUE TITLE
Auto gifted basic bee not working, the macro doesn't click transform to confirm the egg or royal jelly.

### ISSUE THREAD

**Issue by BodiThom** [NatroTeam/NatroMacro#138]
### Have you searched the existing bug reports?

No

### What happened?

The macro doesn't work as intended, it doesn't click confirm on the transformation of the bee.

### Steps to reproduce

1.Open macro
2.Use macro
3.Click on bee hive
4. Doesn't work

### What would you expect to happen?

I expected it to transform the bee into a other bee instead of doing nothing.

### Natro Macro version

0.9.8

### What is your Discord username?

Thombirg

**Comment by BodiThom** [comment]
My name is "Thomburg" on discord not Thombirg.

**Comment by misc-et** [comment]
Thanks for flagging this issue. A fix can now be found here https://github.com/NatroTeam/NatroMacro/issues/160
