### ISSUE TITLE
doesnt click after rejoin

### ISSUE THREAD

**Issue by catisprogts** [NatroTeam/NatroMacro#139]
### Have you searched the existing bug reports?

No

### What happened?

When i natro macro rejoin it doesnt click but still like do my macro

### Steps to reproduce

1.
2.
3.
i

### What would you expect to happen?

i

### Natro Macro version

0.98

### What is your Discord username?

AAAA#5442

**Comment by zspz** [comment]
Join our Discord for support, this is only for bugs and suggestions.
