### ISSUE TITLE
New auto-click

### ISSUE THREAD

**Issue by notahero05** [NatroTeam/NatroMacro#141]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Onett has disabled auto-click which make the player when use normal auto-click can't auto farm, can you add a new auto-click to replace the old one, which can't run in bss now.

### How will this improve Natro Macro?

this will be a great new feature because it can help us farm manualy without holding the left mouse button

### What is your Discord username?

finalfantastic15

**Comment by zspz** [comment]
An autoclicker with click duration has been added, fixing this problem.
It will be included in the upcoming patch.
