### ISSUE TITLE
Sticker Stacker

### ISSUE THREAD

**Issue by Elaflynts** [NatroTeam/NatroMacro#142]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Adding a collect sticker stacker buff would be super useful Idk how exactly it would work if someone doesnt have extra stickers to stack but there could be an option to use tickets to activate the stacker for richer players.

### How will this improve Natro Macro?

Because it could increase how much honey someone could earn a lot.

**Comment by rpertusio** [comment]
Related Pull Request: https://github.com/NatroTeam/NatroMacro/pull/173
