### ISSUE TITLE
Character reset at hive issues with 0.9.9

### ISSUE THREAD

**Issue by RobloxPlayer2024** [NatroTeam/NatroMacro#143]
### Have you searched the existing bug reports?

No

### What happened?

After resetting character at hive, instead of camera changing to down looking view, it just rotates around the hive.  Trying to use it because of new BSS update.  V0.9.8 worked fine but doesn't work with v0.9.9 update.  I checked troubleshooting guides and didn't see anyone else posting about this.  It is almost like the app may be using the incorrect keyboard layout or something and doesn't use the correct camera tilt key.  Settings were copied from v0.9.8.  I also did a fresh unzip with no update and still didn't work correctly.

### Steps to reproduce

1. After setting up
2. Log into BSS and claim hive
3.Start Natro v0.9.9
4. Watch after the character reset sequence, the camera doesn't go to down looking view when hive turns to detect player is at the hive.

### What would you expect to happen?

Camera would turn to a downward view of hive, spin 4 times to verify I am on the hive

### Natro Macro version

0.9.9

### What is your Discord username?

mygameaccount2019

**Comment by M1dnight-ofcl** [comment]
I had the same problem. I had it run for 2 hours and it only made 4 mil (compared to like 20 mil). I checked, kept reseting and rejoining. Idek why, maybe it's the new hive design that dropped earlier today.

**Comment by xiaoniangaoh** [comment]
> I had the same problem. I had it run for 2 hours and it only made 4 mil (compared to like 20 mil). I checked, kept reseting and rejoining. Idek why, maybe it's the new hive design that dropped earlier today.

Me too, but I found that version 0.9.8 had no problem collecting pollen for honey

**Comment by zspz** [comment]
Reset issues are being worked on, join our Discord server for support.
