### ISSUE TITLE
Parachute/Glider option

### ISSUE THREAD

**Issue by TheNoobyPro1** [NatroTeam/NatroMacro#145]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Give a setting if the player is using glider or parachute, then adjust the gliding time in the air.

### How will this improve Natro Macro?

It will improve Natro Macro by helping lower bee players who cannot get glider yet.

### What is your Discord username?

TheNoobyPro

**Comment by misc-et** [comment]
Thanks for this suggestion. Currently, the macro accommodates players with top shop glider (move method cannon in macro settings) and without top shop glider (move method walk in macro settings).

It may be possible to add further adjustment based on whether players own glider or parachute in future, but this is likely to remain a lower priority for now.

**Comment by TheNoobyPro1** [comment]
Okay thanks.

**Comment by rpertusio** [comment]
I'll try to implement this. (Don't set your expectations high.)

If someone else decides they would rather do it, please let me know.

**Comment by TheNoobyPro1** [comment]
Aight

**Comment by rpertusio** [comment]
@TheNoobyPro1 : I did some testing today and realized the parachute is the same speed (or slower than walking). Can you test and let me know? Is the parachute adding any advantage over walking that I'm not thinking of?

**Comment by TheNoobyPro1** [comment]
I could test it but I think the parachute would have an advantage over
walking because it is aerial instead of walking around an entire area then
another area.

**Comment by zspz** [comment]
I'm going to close this because I don't think it's worth using Parachute instead of walking anywhere, as it is in some cases for Glider.
You can disable Glider use in paths by setting your Hive Bees below 25, so I don't think an option for this would be worth adding.
