### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by n4tsukii** [NatroTeam/NatroMacro#148]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Auto run at start-up 
there will be a box to turn on or off in macro setting tab, it's gonna be easier for rdp user whenever macro update

### How will this improve Natro Macro?

.

### What is your Discord username?

n4tsuki

**Comment by zspz** [comment]
This is already implemented, check out Auto-Start Manager in Misc tab.
