### ISSUE TITLE
Script wont open

### ISSUE THREAD

**Issue by mahtismies** [NatroTeam/NatroMacro#149]
### Have you searched the existing bug reports?

No

### What happened?

The program simply doesnt open, keeps saying that theres an error at line 19341.
![image](https://github.com/NatroTeam/NatroMacro/assets/156510240/0dd9fd60-d3ba-4809-916a-b46bcc2d5015)

### Steps to reproduce

1. i press start
2. the error pops up
3. i die internally

### What would you expect to happen?

FOR THE PROGRAM TO OPEN

### Natro Macro version

v0.9.9

### What is your Discord username?

Emzed

**Comment by zspz** [comment]
Join our Discord for support, this is only for bugs and suggestions.
This is a known issue, you can fix it by simply redownloading.
