### ISSUE TITLE
start progress problem

### ISSUE THREAD

**Issue by thisnameisnotavailableforsomereason** [NatroTeam/NatroMacro#151]
### Have you searched the existing bug reports?

No

### What happened?

When the macro progresses, it walks a bit and jumps once then kept on walking towards the red canon. As soon as the character reaches the end of the wall, it won't jump anymore. And so, the program decides to reset the whole thing by resetting over and over again. That causes the character is unable to do anything but keep on resetting.

### Steps to reproduce

1.character resets itself as usual to ensure its in the right position.
2.character walk towards the hive and turns left towards where the red canon is at
3.after like 1 sec of walking, it jumps for no reason and then kept walking
4.when reaches the wall between the closest hive to the red canon and the red canon, it just kept on walking until it decides resets.

### What would you expect to happen?

The normal process before the sticker update comes.

### Natro Macro version

v0.9.9

### What is your Discord username?

randomkid5505

**Comment by rpertusio** [comment]
Please check your Hive number set in Natro.  The "unnecessary jump" is probably because it thinks it is next to the ramp/cannon already.   (Example: If you've set Natro to be Hive 2 and you're actually in Hive 4)
