### ISSUE TITLE
problem with the macro.reconect

### ISSUE THREAD

**Issue by brakensito2ip09** [NatroTeam/NatroMacro#153]
### Have you searched the existing bug reports?

No

### What happened?

Hello, good day, I wanted to say that if you can help me because when I activate the natro macro, after a while it reconnects (it goes out and comes in) then afterwards it stays looking for a slot and it's like this all the time afterwards. Can it be fixed?

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

a

### Natro Macro version

9.9

### What is your Discord username?

igna7878

**Comment by M1dnight-ofcl** [comment]
I haven't encountered a bug like this, but 0.9.9 has also has issues like spam reseting without gathering.

**Comment by brakensito2ip09** [comment]
a ok thanks

**Comment by zspz** [comment]
Join our Discord for support, this is only for bugs and suggestions.

**Comment by brakensito2ip09** [comment]
Thanks for the tip!

**Comment by brakensito2ip09** [comment]
nadie me responde en discord
