### ISSUE TITLE
Infinite Resets into a disconnect

### ISSUE THREAD

**Issue by elitecodesx14** [NatroTeam/NatroMacro#155]
### Have you searched the existing bug reports?

Yes

### What happened?

Keeps resetting at hive after doing tasks such as going to field boosters, wealth clock, placing and picking up planters etc. This wastes a lot of time as it has to essentially reconnect after all of those. ALSO PLEASE UNBAN ME FROM YOUR DISCORD SERVER.

### Steps to reproduce

1. Start up the macro
2. Boom it does it off the rip
3. Sit back and enjoy

### What would you expect to happen?

Verify that I'm at the hive and waddle along to whatever it needs to do, instead it stays in a reconnect cycle

### Natro Macro version

v0.9.9

### What is your Discord username?

elitex14

**Comment by M1dnight-ofcl** [comment]
This is a known problem with 0.9.9. It happened to me and I've seen others with it too. I switched back to 0.9.8 and it works just fine again.

**Comment by xiaoniangaoh** [comment]
> This is a known problem with 0.9.9. It happened to me and I've seen others with it too. I switched back to 0.9.8 and it works just fine again.

me too

**Comment by zspz** [comment]
Reset issues are being worked on, join our Discord server for support.
