### ISSUE TITLE
gifted basic bee auto hatcher error on version 0.9.9

### ISSUE THREAD

**Issue by cube123343** [NatroTeam/NatroMacro#156]
### Have you searched the existing bug reports?

Yes

### What happened?

![nateo makeo ewow](https://github.com/NatroTeam/NatroMacro/assets/120473876/1f1926e5-b9d3-4bba-88a0-1bfa2e88ee6b)
basic bee auto hatcher doesn't work on natro macro v0.9.9

### Steps to reproduce

1.open natro macro v0.9.9 and go to "misc"
2.left click on Gifted "Basic Bee Auto-Hatcher"
3.and then there will be an error.

### What would you expect to happen?

fix the issue

### Natro Macro version

Natro Macro v0.9.9

### What is your Discord username?

kasper2675

**Comment by misc-et** [comment]
Thanks for flagging this issue. A fix can now be found here: https://github.com/NatroTeam/NatroMacro/issues/160
