### ISSUE TITLE
"Allow macro to use tickets to buy ant pass" option mainly for the bucko/riley bee quests

### ISSUE THREAD

**Issue by cube123343** [NatroTeam/NatroMacro#157]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

"Allow Macro to buy ant pass with tickets" option from the ant pass shop
![image](https://github.com/NatroTeam/NatroMacro/assets/120473876/d84b1b14-c2da-4c09-83dc-113695e7a3de)

### How will this improve Natro Macro?

whenever i afk overnight with natro macro and have bucko bee quest's on I always run out of ant passes making the macro unable to do any more bucko bee quests until I wake up and refill with ant passes. this feature would help do Bucko/Riley bee quest repeatedly

### What is your Discord username?

kasper2675

**Comment by zspz** [comment]
I agree that this would be a nice option to have. It will come soon 😃

**Comment by zspz** [comment]
Thanks for the suggestion, this will be added in the next update.
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/af059a83-571b-4a75-94a7-598357fd45a0)

**Comment by cube123343** [comment]
Thanks!
