### ISSUE TITLE
i have a bug

### ISSUE THREAD

**Issue by brakensito2ip09** [NatroTeam/NatroMacro#158]
### Have you searched the existing bug reports?

No

### What happened?

![Captura de pantalla 2024-01-13 135626](https://github.com/NatroTeam/NatroMacro/assets/156525360/9e0eeb92-8f70-4f9e-9841-8b86a89ad6f5)
i have this bug,what i do

### Steps to reproduce

![Captura de pantalla 2024-01-13 135626](https://github.com/NatroTeam/NatroMacro/assets/156525360/7d1b99f1-d01e-4ad2-97cc-0b280f57869d)

### What would you expect to happen?

![Captura de pantalla 2024-01-13 135626](https://github.com/NatroTeam/NatroMacro/assets/156525360/41397808-cdbf-42a4-8b37-c76b723b8d5d)
a

### Natro Macro version

0.9.9

### What is your Discord username?

igna7878

**Comment by misc-et** [comment]
This message appears when there are some settings on your PC or in Roblox that can prevent the macro from running well.

Would you be able to join our Discord, where we have information about how to correct these and support?
