### ISSUE TITLE
why does my macro keep resetting and leaving?

### ISSUE THREAD

**Issue by smilyemochi** [NatroTeam/NatroMacro#163]
### Have you searched the existing bug reports?

No

### What happened?

last night i turned on my macro and watched it for around 10 minutes and all it was doing was resetting 9 times leaving the game then joining back and doing one thing lick collecting a machine.

### Steps to reproduce

1. started macro
2.it started resetting itself and leaving the game
3.

### What would you expect to happen?

not sure

### Natro Macro version

0.9.9

### What is your Discord username?

smilye_mochi

**Comment by zspz** [comment]
Reset issues are being worked on, join our Discord server for support.
