### ISSUE TITLE
Blue hive colour problem

### ISSUE THREAD

**Issue by ulysses66** [NatroTeam/NatroMacro#164]
### Have you searched the existing bug reports?

No

### What happened?

when the player is walking back to the hive if it comes across a blue hive colour then it stops on that hive whether it is yours or not. Maybe same colour as balloon causing a problem?

### Steps to reproduce

1.Set a blue hive colour to hive one 
2.set your hive to any other 
3.fill backpack and try to walk back to hive (except hive 3 in some circumstances like walking back from pine tree) then it stops

### What would you expect to happen?

you stop at hive 1 and try to convert backpack/balloon there in stead or your own hive

### Natro Macro version

0.9.9

### What is your Discord username?

0gn0p

**Comment by zspz** [comment]
This will be fixed in the upcoming patch.
The issue was that the owner of the hive had a name with the letters "lle" which confused the macro as it was looking for the "Collect Pollen" message.
