### ISSUE TITLE
Customizable hourly reports

### ISSUE THREAD

**Issue by RahatGD2008** [NatroTeam/NatroMacro#165]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Although almost every macro player is a blue hive, but it would be nice for us white hive players, red players, and even mixed players be able to customize what buffs will show on the report. (ex: white hives can record gummyball, gummyball combo, or gummy star)

### How will this improve Natro Macro?

It will benefit other hive colors a little more.

**Comment by zspz** [comment]
Thanks for the suggestion.
Feel free to give your ideas in #20, the issue on this topic.
