### ISSUE TITLE
Sticker stacker

### ISSUE THREAD

**Issue by Lavawheat** [NatroTeam/NatroMacro#166]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Sticker stacker
it does the sticker stacking on its own, it gives good boost and it stacks over time

### How will this improve Natro Macro?

As i said before it stacks over time, this could be better for people who are macroing and they can get more honey while they are away from keyboard.

### What is your Discord username?

lavawheat

**Comment by misc-et** [comment]
Thanks for this suggestion. It's being considered for inclusion in a future update of the macro.

**Comment by 5Viper** [comment]
![image](https://github.com/NatroTeam/NatroMacro/assets/140934099/611ac552-9d27-488d-a476-dde370b08409)
Said this in a server with my friend, blacklisting could be implemented with image recognition.

**Comment by zspz** [comment]
Refer to the existing issue for this: #142.
