### ISSUE TITLE
auto royal jelly system?

### ISSUE THREAD

**Issue by eddieeeeeeeeeee** [NatroTeam/NatroMacro#167]
### Have you searched the existing suggestions?

No

### What is your suggestion?

some sort of system where we enter what bee and gifted/mutated etc then it automatically uses jelly till we get it 

eg: i want a gifted honey bee with convert mutation

### How will this improve Natro Macro?

it will help with people who want a specific bee which doesnt fit under the conditions of autojelly

### What is your Discord username?

e.d.die

**Comment by zspz** [comment]
You can try https://birblit.club/ by @ninjubaer and @johnfree817.
It was planned to include something like this in Natro Macro but it has always been low priority, mainly because it already exists and it's fairly simple to create a personal one.
