### ISSUE TITLE
The player only moves on hive

### ISSUE THREAD

**Issue by M1dnight-ofcl** [NatroTeam/NatroMacro#168]
### Have you searched the existing bug reports?

No

### What happened?

I don't know how  to describe this, but my macro only moves down one hive instead of all the way to the ramp, and then resets after it gets confused. It's done this twice and both times reseting my data fixed it. I really don't feeling like doing that though because it I have a pretty decent macro now.

### Steps to reproduce

I don't know why or how it does this. just run it, and it will randomly start doing it one day.

### What would you expect to happen?

I expected it to go all the way down like it normally does.

### Natro Macro version

0.9.8

### What is your Discord username?

m1dnightdev

**Comment by misc-et** [comment]
Have you tried checking your hive slot in the Natro settings tab? 

It goes right to left. Slot 1 is closest to the red cannon, and slot 6 is closest to the honey dispenser
