### ISSUE TITLE
Easy settings backup/export

### ISSUE THREAD

**Issue by M1dnight-ofcl** [NatroTeam/NatroMacro#169]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I think it may be cool to be able to backup all settings super easily and have them stored in a folder. I'm not sure if AHK can do this, but imagine writing all the data to a json file and saving to a renamed `.zip` file. It would make it extremely easy to export settings, import them, and backup known working settings. The file extension could be possibly `.natro` or something like that. 

I know you can just duplicate your settings folder, but it could be cool to do something like this. Honestly, it may better write something like this in python. Just zip the settings folder using `shutil` then rename and save. I know a lot of `pyqt5` too, so we could make it look nice as well. I may start this as a side project tbh.

If I do make it a side project, I'll open up a pull request prob

### How will this improve Natro Macro?

It would be really practicle, whether that be for sharing op settings with friends are just saving settings that you know still work if you ever break ur settings.

### What is your Discord username?

m1dnightdev

**Comment by zspz** [comment]
Thanks for the suggestion.
The `settings` folder already does exactly as you say, all settings are stored there and it can be shared, exported and imported at will.
Other than zipping that folder for you, I don't see how this would make that process easier, but you can always make a PR if you'd like to work on it!

**Comment by misc-et** [comment]
Can be achieved through https://github.com/NatroTeam/NatroMacro/issues/77
