### ISSUE TITLE
Auto reset

### ISSUE THREAD

**Issue by roosterbeast** [NatroTeam/NatroMacro#170]
### Have you searched the existing bug reports?

No

### What happened?

So when i began the macro it would keep reseting and this a problem only for the 0.9.9V since i tried the other ones and it worked not sure why my character would infinitely reset at my hive than leave after around 8 trys

### Steps to reproduce

1.Set up e_lol with orginal settings but with drift comp and shift lock than begin
2.
3.

### What would you expect to happen?

After doing this your character should infinitely reset and after a bit leave the game

### Natro Macro version

0.9.9V

### What is your Discord username?

roosterbeast

**Comment by zspz** [comment]
Reset issues are being worked on, join our Discord server for support.
