### ISSUE TITLE
planter

### ISSUE THREAD

**Issue by XxArmanxX22** [NatroTeam/NatroMacro#171]
### Have you searched the existing bug reports?

No

### What happened?

hello sir/ma'am, the macro cant plant any planter so pleas tell me what is problem?

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

https://github.com/NatroTeam/NatroMacro/assets/156583770/dd1a037e-b492-4a2d-bacc-204a896d9346

### Natro Macro version

v0.9.9

### What is your Discord username?

iamnot_arman

**Comment by zspz** [comment]
Join our Discord for support, this is only for bugs and suggestions.
