### ISSUE TITLE
Can't get to the blueberry supply machine

### ISSUE THREAD

**Issue by xiaoniangaoh** [NatroTeam/NatroMacro#172]
### Have you searched the existing bug reports?

Yes

### What happened?

It should be because the hive has been updated, and the distance has deviated so that you can't walk to the blueberry supply machine

### Steps to reproduce

1.start
2.Go to the Blueberry Supply Machine
3.Unreachable reset

### What would you expect to happen?

Arrive at the blueberry supply machine

### Natro Macro version

0.9.9

### What is your Discord username?

xiaoniangaoh_24982

**Comment by zspz** [comment]
Thanks, this will be fixed in the upcoming patch.
