### ISSUE TITLE
Natro Macro doesn't work 

### ISSUE THREAD

**Issue by parset** [NatroTeam/NatroMacro#177]
### Have you searched the existing bug reports?

No

### What happened?

Everytime I try to start the program a message appear "unable to detect in-game GUI offset"

### Steps to reproduce

1.Dowload the newest version from the discord 
2.Extract the file with Winrar
3.Click at the document "START"
4.Set what field i want to Macro
5- Try to start the program
6- Message Unable to detect in-game GUI offset appear

### What would you expect to happen?

I would expect the program would work, and start marcroing

### Natro Macro version

v0.9.9

### What is your Discord username?

parsec12

**Comment by misc-et** [comment]
This message appears when there are some settings on your PC or in Roblox that can prevent the macro from running well. 

Would you be able to join our Discord, where we have information about how to correct these and support?
