### ISSUE TITLE
Tunnel bear takes 48 hours to respawn, Natro says 2 hours.

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#179]
### Have you searched the existing bug reports?

Yes

### What happened?

When you kill Tunnel Bear, it resets the "Next Bear" status to 2 hours. Even though it takes 48 hours normally.

### Steps to reproduce

1. Have Natro kill Tunnel Bear
2. Check time it thinks Tunnel Bear will respawn
3. See that it will be 2 hours instead of 48 hours

### What would you expect to happen?

I expected it to say 48 hours, unless it's checking it every 2 hours, in which case mark this as closed and ignore it.

### Natro Macro version

v0.9.9.1

### What is your Discord username?

ZackAttack4987

**Comment by Noobyguy775** [comment]
It's setting the cooldown to two hours to check for a tunnel bear every two hours because it couldn't find any health bars
