### ISSUE TITLE
Auto Memory Match

### ISSUE THREAD

**Issue by Nounours14** [NatroTeam/NatroMacro#180]
### Have you searched the existing suggestions?

No

### What is your suggestion?

The feature will basically go up to any Memory Match selected and play it. In order to play it, it will select the first one and then the second one, and basically each time it does that, a screen reader will see which item was where, and if it sees two items corresponding, it will select them both. That feature could be useful to gather a little bit more ingredient.

### How will this improve Natro Macro?

This feature would be great to farm a little bit more things for your hive.

### What is your Discord username?

nounours14

**Comment by Noobyguy775** [comment]
Refer to #70
