### ISSUE TITLE
Reset bug

### ISSUE THREAD

**Issue by Pips2604** [NatroTeam/NatroMacro#182]
### Have you searched the existing bug reports?

No

### What happened?

When i die or reset, adjusting the cam it doesnt recon i think that it is in his place and continues reseting all the time, making me stop the macro and trying again, but each time the macro resets me then it keeps doing it to the infinity (sorry i speak spanish, my english is not that good). I can send a video if you guys want. But it says that is too heavy for this place so talk to me in ds and i will send it (ds name: pipasro)

### Steps to reproduce

1.Starts the macro
2.Farms
3.Reset because x reason
4.Moves the camera
5.Reset again
6. continues reseting

### What would you expect to happen?

I suppose that reset the caracter and continue the macro 

### Natro Macro version

0.9.9.1

### What is your Discord username?

pipasro

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Level set to 1 and a normal avatar size.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
