### ISSUE TITLE
The bug with the hike to the hive

### ISSUE THREAD

**Issue by ROMSHEKC** [NatroTeam/NatroMacro#183]
### Have you searched the existing bug reports?

No

### What happened?

when the backpack is full, it rises from the tree to the top of the polar bear and just jumps for a couple of seconds, walks and resets, but although it should fly to the hive

### Steps to reproduce

1First, I collect pollen in the Christmas tree field
2.I'm filling my backpack
3.After it is filled, he runs to the polar bear
4 He jumps over the side
5 and he has to activate the parachute, but he doesn't do it.
6because of this, he does not reach the hive and dies

### What would you expect to happen?

he must activate the parachute

### Natro Macro version

0.9.9.1

### What is your Discord username?

zzbiba

**Comment by rpertusio** [comment]
Hi. Can you tell me if this occured in previous versions?

And, can you tell me if you have the yellow glider or the grey parachute?

**Comment by RobbieSpeedyNL** [comment]
this is an fps issue when u drop under 25 fps when walking back at that time it drops the input

**Comment by zspz** [comment]
Yes, this issue is commonly caused by FPS drops at that moment.
