### ISSUE TITLE
more efficient brown bear quest macro

### ISSUE THREAD

**Issue by RobbieSpeedyNL** [NatroTeam/NatroMacro#184]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Make the brown bear quest more efficient by making it go for the fields before collect x (color) pollen since most of the time u get red with mushroom or blue with pinetree etc 

### How will this improve Natro Macro?

make the macro faster and more efficient since the fields u need to collect pollen already has that color it already counts towards the color pollen goal

### What is your Discord username?

RikoSakurauchi_

**Comment by zspz** [comment]
Thanks, this is a great suggestion and will be implemented soon!
