### ISSUE TITLE
Hive Hub Macro

### ISSUE THREAD

**Issue by mikeysomthing** [NatroTeam/NatroMacro#185]
### Have you searched the existing suggestions?

No

### What is your suggestion?

to let you macro in the hub 

to go to tha hub for the sticker sprout

also some sort of way to ato stack  in the sticker stacker

### How will this improve Natro Macro?

i think that many people are going for the stickers and some reqire you too camp at the hub and for the hub badge 

the sticker stacker can constantly give out many useful buffs and gets beter the more you stack but it desint last long unless its constantly being stacked it can make people an lot more honey and help with the badge also many people will find this to be really useful and an way too get rid of stickers faster 

### What is your Discord username?

mikey29574

**Comment by peacocksir** [comment]
I am currently working on this feature and plan to make a pull request within the next few days.

**Comment by peacocksir** [comment]
This feature is now added in a pull request #327

**Comment by Noobyguy775** [comment]
merging with #379
