### ISSUE TITLE
Sticker printer

### ISSUE THREAD

**Issue by Mongyyy** [NatroTeam/NatroMacro#188]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

This feature would put an requested egg into the sticker printer every hour

### How will this improve Natro Macro?

I see this as a great improvement to natro, seeing how invested players are at collecting all necessary stickers, a lot of people would use this feature.

### What is your Discord username?

mongy_got_real

**Comment by zspz** [comment]
Thanks for the suggestion, there is a PR for this (#194) and it will be implemented to the macro soon.
