### ISSUE TITLE
Natro Macro Bug

### ISSUE THREAD

**Issue by xSxloz** [NatroTeam/NatroMacro#189]
### Have you searched the existing bug reports?

No

### What happened?

The reconnect private server isn't working anymore after onett updated Roblox today. It just stays on bee swarm simulator loading screen.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

Please get back to me and help me fix it, thankyou.

### Natro Macro version

Natro Macro v0.9.9.1

**Comment by zspz** [comment]
This is a Roblox or private server issue, there is nothing in the macro that would cause this. Please create a support post on Discord if the issue persists.
