### ISSUE TITLE
inf reset character and leave srv bug

### ISSUE THREAD

**Issue by xh3795** [NatroTeam/NatroMacro#190]
### Have you searched the existing bug reports?

No

### What happened?

My macro won't work at all, whenever I start macro, the macro would just reset my character 9 time and at 9th time, it will close my roblox automatically and rejoin back to a BSS server and loop reset my character and leave not long after. I watched tons of video how to solve this reset character bug but none of them work, like screen resolution, layout and etc. Can someone please give me solution?

### Steps to reproduce

-

### What would you expect to happen?

-

### Natro Macro version

v0.9.9.1

### What is your Discord username?

liew6666

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 and a normal avatar size.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
