### ISSUE TITLE
When I reset bot flicks to the wrong side and runs to the shop 

### ISSUE THREAD

**Issue by m4dpatboll** [NatroTeam/NatroMacro#193]
### Have you searched the existing bug reports?

No

### What happened?

When I go to get wealth clock it works fine but when the bot resets again it turns towards the fields and then starts walking into the shop and resets then repets.

### Steps to reproduce

1. Activate the go get wealth clock
2.Turn on the macro and watch it reset 
3.Will walk into the shop instead of towards the cannon

### What would you expect to happen?

Your character should have been in a long loop of resetting and walking towards the shop

### Natro Macro version

0.9.9.1

### What is your Discord username?

average__asian

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically a normal avatar size (the false positive you described happens for small avatars) and Graphics Quality set to 1.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
