### ISSUE TITLE
Sticker stacker

### ISSUE THREAD

**Issue by BomboKlatt** [NatroTeam/NatroMacro#195]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add a sticker stacker and sticker printer path 
Sticker stacker: adding the option to use a new sticker on using 25 tickets
Sticker printer: adding the option to buy basic or gold eggs and donating them

### How will this improve Natro Macro?

Its a good way to macro faster optimazing honey and pollen per hour and will make easier and faster any task

**Comment by zspz** [comment]
There is already a PR for this (#173, #194).
They are coming soon!
