### ISSUE TITLE
reset over and over

### ISSUE THREAD

**Issue by Ppoprocks1** [NatroTeam/NatroMacro#196]
### Have you searched the existing bug reports?

No

### What happened?

when going to collect ticket, after he dies and resets, the camara angles flips like it spawnd in wrong place and it resets over and over

### Steps to reproduce

1.just start with ticket collect enabled
2.
3.

### What would you expect to happen?

to go collect

### Natro Macro version

9.9.1

### What is your Discord username?

poprocks7020

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 (likely to be your issue) and a normal avatar size.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
