### ISSUE TITLE
Macro bug

### ISSUE THREAD

**Issue by Bombsquadpro** [NatroTeam/NatroMacro#198]
### Have you searched the existing bug reports?

No

### What happened?

So basically what happens is when your macro resets the character, the camera faces behind the hive.  This makes the macro confused and it walks to the beginner shop and just run into the wall until it resets.  Reseting sometimes doesn't fix the problem.

### Steps to reproduce

1.start your macro
2.face camera behind hive
3.done

### What would you expect to happen?

It should make your character walk at the glass of the beginner shop.

### Natro Macro version

Newest version

### What is your Discord username?

@babu1140

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically a normal avatar size (the false positive you described happens for small avatars) and Graphics Quality set to 1.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
