### ISSUE TITLE
Macro glitch

### ISSUE THREAD

**Issue by RaGERiP** [NatroTeam/NatroMacro#200]
### Have you searched the existing bug reports?

No

### What happened?

When I start the macro it the ticket clock works but when it tries walking to pine tree field it walks the wrong way and goes to the basic shop. 

### Steps to reproduce

1._
2._
3._

### What would you expect to happen?

_

### Natro Macro version

9.9.1

### What is your Discord username?

.

**Comment by Noobyguy775** [comment]
It's probably your camera setting in roblox, so change that to the default. For any future help ask in the [discord](https://discord.gg/natromacro)
