### ISSUE TITLE
Opportunity to gather without going to convert pollen to hive 

### ISSUE THREAD

**Issue by arsenaaal** [NatroTeam/NatroMacro#201]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Hello, it would be nice if players will have an opportunity to gather without going to convert pollen to hive 

### How will this improve Natro Macro?

For example, i have a blue hive and my backpack is filling to fast to gain a bubble bloat bonus, so i cant farm as much as i can without converting my backpack

### What is your Discord username?

arsenal6022

**Comment by zspz** [comment]
I don't see why anyone would enable this if it were added, but I guess I'll leave it as a suggestion.
