### ISSUE TITLE
Broke The Macro

### ISSUE THREAD

**Issue by Reash1** [NatroTeam/NatroMacro#202]
### Have you searched the existing bug reports?

No

### What happened?

Whenever i try using the macro. It resets like normal, but when I respawn at the hive it still resets. I Don't know why, I've tried fullscreen, I've tried different camera methods. But it just keeps reseting.

### Steps to reproduce

1. start macro
2. wait
3. resets nonstop, just happens to me.

### What would you expect to happen?

The macro to reset then respawn at hive and to what i put in.

### Natro Macro version

9.9.1

### What is your Discord username?

Reash

**Comment by T-DexParty** [comment]
This happens to me as well

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 (likely to be your issue) and a normal avatar size.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!

**Comment by Reash1** [comment]
Thx
