### ISSUE TITLE
Natro macro made my screen break

### ISSUE THREAD

**Issue by remagorp** [NatroTeam/NatroMacro#203]
### Have you searched the existing bug reports?

No

### What happened?

not sure if it was natro macro but happend right afteri got it, i was installing natro macro on my laptop  and working fine after i turned it off and on again it just didnt work the moniter wasnt working when i turned it on and its on because gpu was running sooo

### Steps to reproduce

idk

### What would you expect to happen?

.

### Natro Macro version

v0.9.9.1

**Comment by zspz** [comment]
It's not Natro Macro.
