### ISSUE TITLE
Big gub

### ISSUE THREAD

**Issue by spinnysheep** [NatroTeam/NatroMacro#204]
### Have you searched the existing bug reports?

No

### What happened?

I was macroing when my macro started repeatedly resetting because i guess it couldnt identify where i was, while i was standing right there on my hive. So the resetting keot going until it closed roblox and opened it again and still kept going.

### Steps to reproduce

1.choose a dispenser you want to collect and a field
2. Start macro
3.and then it will reset and either go collect dispenser or keep resetting. If it went for dispenser then it will reset to hive and then keep resetting

### What would you expect to happen?

for it to reset once and then start walking to the field

### Natro Macro version

0.9.9.1

### What is your Discord username?

Lexui26

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 (likely to be your issue) and a normal avatar size.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!

**Comment by spinnysheep** [comment]
I am using 0.9.9 and its working fine so I'll just wait for 1.0.0
