### ISSUE TITLE
The glitch isnt solved

### ISSUE THREAD

**Issue by RaGERiP** [NatroTeam/NatroMacro#205]
### Have you searched the existing bug reports?

No

### What happened?

So I changed my camera mode to classic because the default classic won't work it still walks to the basic shop 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I expected it to go to pine tree and collect pollen 
For 20 minutes then reset and convert balloon and then go repeat the process again but it walks to the basic shop. 

### Natro Macro version

V9.9.1

### What is your Discord username?

pepsi.2023 display=imisstherage

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically a normal avatar size (the issue of going to Basic Shop happens for small avatars) and Graphics Quality set to 1.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
