### ISSUE TITLE
resetting when bag is full

### ISSUE THREAD

**Issue by kevinharttwo** [NatroTeam/NatroMacro#207]
### Have you searched the existing bug reports?

No

### What happened?

Whenever my bag is full after a macro, it resets my character so i lost all my pollen. 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I dont understand

### Natro Macro version

.0.9.9.1

### What is your Discord username?

death#4082

**Comment by zspz** [comment]
This is not a bug, join our Discord server for support.
