### ISSUE TITLE
Infinite reset

### ISSUE THREAD

**Issue by namename24** [NatroTeam/NatroMacro#208]
### Have you searched the existing bug reports?

Yes

### What happened?

On versions like 0.9.9 below its working normally, but, with the new sticker update is not working anymore and (because of the trashy thing called trade like 0.9.8 below the send trade request he think its make honey), well when i download the 0.9.9 or 0.9.9.1 i press F1 and it resets until he leave the game, claim a new hive, reset, do some quests, reset, and keep resetting. another thing, if i try do it on 0.9.9 he rotate camera 2 times and reset 10 times

### Steps to reproduce

1. I downloaded the 0.9.9 and 0.9.9.1
2. i open it
3. i started it.

### What would you expect to happen?

Infinite resets

### Natro Macro version

0.9.9/0.9.9.1

### What is your Discord username?

stilts1

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 (likely to be your issue) and a normal avatar size.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
