### ISSUE TITLE
inf reset

### ISSUE THREAD

**Issue by remagorp** [NatroTeam/NatroMacro#209]
### Have you searched the existing bug reports?

Yes

### What happened?

Keeps resetting when I try to macro and when my graphics is on 1 I try to change my avatar size to normal with blocky settings still doesn't work these are my settings 

Height100%
Width100%
Head100%
Proportions0%

and i tryed changing avatars to something else and it walks to the shop and does nothing and ive read the stuff on discord

### Steps to reproduce

1.Download Natro Macro v0.9.9.1
2.Start A macro
3.Infinitley resets

### What would you expect to happen?

for it to macro normally and not inf reset

### Natro Macro version

v0.9.9.1

**Comment by zspz** [comment]
Please check your other settings using the Troubleshooting Guide on our Discord.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!

**Comment by remagorp** [comment]
its walking to shop

**Comment by remagorp** [comment]
nevermind its inf resetting
