### ISSUE TITLE
When our backup is full there will be an option to equip before converting and after equipping the old mask you had before.

### ISSUE THREAD

**Issue by Arsiw23** [NatroTeam/NatroMacro#21]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Honey Mask is usefull because of the 80 convert rate when equipped. So I think that will be a good idea to have it. It will help us get our backup emptied faster. 

### How will this improve Natro Macro?

For example if the time of converting my backup is 2m with honey mask it would be 1min for example. I think many will like this.

### What is your Discord username?

arsios

**Comment by AsianRiceFarmer365** [comment]
blud aint no way the macro has to go equip the honey mask everytime u finish gathering in a field. Also, the macro might fail at going to the mask after gathering, meaning all that pollen is wasted in ur bag

**Comment by Noobyguy775** [comment]
> Also, the macro might fail at going to the mask after gathering, meaning all that pollen is wasted in ur bag

What @AsianRiceFarmer365 said, pathing to diamond/demon mask is hard, and is unreliable. Also you have to account for travel time since I don't think it's reliable at all to cannon to the platform near the entrance to diamond mask
