### ISSUE TITLE
macro bug report

### ISSUE THREAD

**Issue by Davi12340** [NatroTeam/NatroMacro#210]
### Have you searched the existing bug reports?

No

### What happened?

the macro is reseting at the hive
![image](https://github.com/NatroTeam/NatroMacro/assets/157283134/44319a20-7607-472f-9120-fe4e39c48c13)

### Steps to reproduce

1.reset first time
2.move the camera away for see the hive
3.move to destination

### What would you expect to happen?

the macro is resetig in the hive oftentimes

### Natro Macro version

0.9.9.1

### What is your Discord username?

dada11011

**Comment by zspz** [comment]
Please ensure your settings are correct using the guides on Discord, specifically Graphics Quality set to 1 (likely to be your issue) and a normal avatar size.
Alternatively, you can wait (or use v0.9.9 if that works) for the next version which will no longer have these requirements.
If it still doesn't work, create a macro support post over on Discord and we can help troubleshoot!
