### ISSUE TITLE
i have had problems with the macro not converting the baloon and not being able to use the cannons. 

### ISSUE THREAD

**Issue by probssplayer** [NatroTeam/NatroMacro#211]
### Have you searched the existing bug reports?

Yes

### What happened?

when i start the macro and i have a balloon it doens't convert it. and when i am using the cannon option to go to a field it doesn't see the e button to use the cannon or it doesnt press the e. and it walks past the cannon and wont be used. and keeps reseting.

### Steps to reproduce

1  i have pine field selected and convert baloon on.
2 i have my graphics setings on the lowest and my tansperency setings to.

### What would you expect to happen?

that u can fix it. if it is posible.

### Natro Macro version

v0.9.9.1

### What is your Discord username?

kaaskroketjes#2109

**Comment by zspz** [comment]
This is not a bug, join our Discord server for support.
This issue sounds like your game language is not set to English.
