### ISSUE TITLE
add hive hub

### ISSUE THREAD

**Issue by popguy2** [NatroTeam/NatroMacro#212]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I think it would be a good idea to add an option to afk farm in the hive hub just like its any other feild.

### How will this improve Natro Macro?

It would be helpful to farm in the hive hub to get stickers that can take awhile to get normally get, as well as help people be able to get benifits whenever the sticker sprout activates.

### What is your Discord username?

@popguy2

**Comment by zspz** [comment]
Refer to #185, feel free to comment under the existing suggestion.
