### ISSUE TITLE
cant swing my belt in bee swarm

### ISSUE THREAD

**Issue by beeswarmplayer314** [NatroTeam/NatroMacro#213]
### Have you searched the existing bug reports?

No

### What happened?

i cant swing my beld in bee swarm simulator 

### Steps to reproduce

1.7
2
3.

### What would you expect to happen?

i excpect to see it that it works good tbh

### Natro Macro version

v0.9.9

### What is your Discord username?

soldier_3413

**Comment by zspz** [comment]
Join our Discord server for support!
