### ISSUE TITLE
Romote macro

### ISSUE THREAD

**Issue by Lavawheat** [NatroTeam/NatroMacro#214]
### Have you searched the existing suggestions?

No

### What is your suggestion?

My suggestion that would make macro better is checking your inventory while you are not infrount of your laptop/pc. Just like the hive check where it opens the bees index and look at all the bees you have, I think macro should add a feature where you could click the button and it would check all the times you have and send it on weebhook or something. 

### How will this improve Natro Macro?

I don't know about other people, but I stop my macro alot to check my tickets, stinger, glue, gumdrops, ect. So adding a feature like that would help the community alot. For example I could be in school and see how much blueberry I have. 

### What is your Discord username?

lavawheat

**Comment by zspz** [comment]
There is an internal branch for this feature, it has been developed by @DullSmallmega176.
It is coming soon!
