### ISSUE TITLE
My natro macro 0.9.9.1 doesn't work

### ISSUE THREAD

**Issue by Jojozinho-hub** [NatroTeam/NatroMacro#216]
### Have you searched the existing bug reports?

No

### What happened?

Well, my macro try to go collect the wealth clock but it bugs in the noob shop outdoor wall. The move method is the cannon but it goes to the opposite way

### Steps to reproduce

1.Star in my hive
2.go to the right
3.bug into the noob shop wall

### What would you expect to happen?

[robloxapp-20240121-1822417.zip](https://github.com/NatroTeam/NatroMacro/files/14002869/robloxapp-20240121-1822417.zip)

### Natro Macro version

V0.9.9.1

### What is your Discord username?

jojo3005

**Comment by zspz** [comment]
Join our Discord server for support!
