### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Plxas** [NatroTeam/NatroMacro#217]
### Have you searched the existing bug reports?

No

### What happened?

When i leave my macro on for the night i wake up and its not mining its just moving in the field and i get less honey . If youd fix this it would mean the world to me
Love your work❤️

### Steps to reproduce

1.leave macro on in coconut field for the night
2.its gonna macro for like 1hour normaly
3.wake up and its just running

### What would you expect to happen?

I would excpect it to mine but it doesnt

### Natro Macro version

The latest 0.9.9 i think

### What is your Discord username?

plxas/Plixis

**Comment by zspz** [comment]
Join our Discord server for support!

**Comment by Plxas** [comment]
Hey i dont know where to seek help in discord there is no tickets no help
button.
