### ISSUE TITLE
Natro macro is buggy and not working properly

### ISSUE THREAD

**Issue by CunningRev** [NatroTeam/NatroMacro#220]
### Have you searched the existing bug reports?

No

### What happened?

Hello Natro macro team! I've been using your service for 400+ hours and today i have encountered a rather unsettling issue which doesn't let me use the app. So the macro drops the player outside of the designated place or far from it. This doesn't allow for the collection of wealth clock, and cannot even farm in a particular field due to the undesignated drop of the player after using the red cannon. It seems that not only me has been suffering from this bug but also some other fellow mates.

### Steps to reproduce

1.starting of the macro
2.Using the red cannon
3.being dropped outside the designated place

### What would you expect to happen?

I would gladly like the fix of this bug. It doesn't let me play the game anymore because i only macro

### Natro Macro version

0.9.9.2

### What is your Discord username?

Devil666

**Comment by rpertusio** [comment]
Please check that your Movespeed (BEFORE you claim a hive) matches what's in the Settings tab of Natro.
Please also verify you're using the yellow Glider (and not the Parachute)

**Comment by zspz** [comment]
This also seems like a system (performance) issue rather than anything to do with the macro, especially if the macro used to work before.
