### ISSUE TITLE
Inf resetting STILL

### ISSUE THREAD

**Issue by remagorp** [NatroTeam/NatroMacro#221]
### Have you searched the existing bug reports?

No

### What happened?

same avatar same inf reset annoying so annoying

### Steps to reproduce

.

### What would you expect to happen?

.

### Natro Macro version

0.9.9.2

**Comment by zspz** [comment]
This is not a bug, it is most probably caused by your avatar size being incorrect.
Review the guides on Discord, and make a macro support post there if the issue persists.
