### ISSUE TITLE
Constant reset after updating natro version

### ISSUE THREAD

**Issue by xygithubs** [NatroTeam/NatroMacro#222]
### Have you searched the existing bug reports?

Yes

### What happened?

![image](https://github.com/NatroTeam/NatroMacro/assets/131320057/adbb4e69-2d25-4a24-9ec4-eede86210e5f)
![image](https://github.com/NatroTeam/NatroMacro/assets/131320057/e56aafcf-e408-4865-b023-a19721c893c2)

Even after reopening the previous version of natro that was working before started doing the same thing of resetting character

### Steps to reproduce

1. updating the version from 9.9.1  to 9.9.2
2. Extracting it and opening it , boot it up and it starts resetting right after collecting from honey dispenser
3. Rebooting previous version again, and it starts resetting repeatedly after getting the hive slots

### What would you expect to happen?

Was expecting it to work as per normal from 9.9.1 after updating but it seems to be lacking in that sense. sorry for bad english

### Natro Macro version

9.9.2

**Comment by rpertusio** [comment]
If you watch your screen, where is it resetting? At your hive, or the default spawn point?

**Comment by xygithubs** [comment]
at hive, the screen also doesnt zoom out

**Comment by xygithubs** [comment]
as of now after reinstalling the older version 3rd time then it works again. seems like only the newer version doesnt work well for me
