### ISSUE TITLE
Macro Keeps Resetting Character... Unusable. 

### ISSUE THREAD

**Issue by turbopug2735** [NatroTeam/NatroMacro#223]
### Have you searched the existing bug reports?

Yes

### What happened?

When i press F1 to start the macro, there is continuous resetting of my character. 

### Steps to reproduce

1. Open the macro on 0.9.9.2. 
2. Use CornerXSnake on Pine Field.
3. Press F1 and watch your character be reset over and over, forever. 

### What would you expect to happen?

Avatar will constantly reset. 

### Natro Macro version

Latest Version - 0.9.9.2

### What is your Discord username?

_blob.

**Comment by zspz** [comment]
This is not a bug, it is most probably caused by your avatar size being incorrect.
Review the guides on Discord, and make a macro support post there if the issue persists.
