### ISSUE TITLE
FIX THE GIFTED BASIC AUTO HATCHER

### ISSUE THREAD

**Issue by MysticalityReal** [NatroTeam/NatroMacro#224]
### Have you searched the existing bug reports?

No

### What happened?

was using gifted basic auto hatcher, did nothing to interfere and it just BASIC EGGS MY TADPOLE FOR NO REASON. IM MID GAME, SPENT ROBUX ON THE MYTHIC EGG AND YOU LEFT ME FRICKING CRYING BRO. THE LEAST THAT COULD HAPPEN IS A 1200 ROBUX REFUND BECAUSE THE ISSUE BASICALLY DELETED THE MYTHIC EGG I BOUGHT WITH THAT MUCH AND THE ISSUE BEING FIXED.

### Steps to reproduce

1. YOU DONT ITS AN ISSUE I WOULD ATLEAST WANT 
2.
3.

### What would you expect to happen?

just fix the gosh dang bug please. maybe a 1200 robux refund (after the tax or group payout)

### Natro Macro version

1.9.9.1

**Comment by MysticalityReal** [comment]
(forgot on steps to reproduce, to finish the sentence in the moment.) (im about to quit bee swarm because of this issue as well...)

**Comment by MysticalityReal** [comment]
the robux back is ok since i just got the tadpole back in 1.5k jelly (thank god for that bro)

**Comment by zspz** [comment]
One of the reasons we are an open source project is because of ridiculous and pathetic accusations like these.
It is not possible for the macro to do this without user interaction, as you can see in the code.

**Comment by MysticalityReal** [comment]
my bad to the natro team, im still at the point where i let my anger get over me. i was just doing this out of emotion and it was probably user error.
