### ISSUE TITLE
Macro is getting lost and resetting

### ISSUE THREAD

**Issue by Kaleczek** [NatroTeam/NatroMacro#226]
### Have you searched the existing bug reports?

Yes

### What happened?

After macro is done collecting pollen from pine tree field its getting stuck on a rock close to polar bear and just getting lost. After like 10 seconds it's resetting the player.(The screenshot was taken some time ago so the version isnt the same as the newest release but I am on 9.9.2)

### Steps to reproduce

![IMG_20240123_064512](https://github.com/NatroTeam/NatroMacro/assets/157449950/08e1885a-f018-4d43-b777-f978ad33fa78)
1. Use the settings I have for pine tree 
2. If it really matters I have 33.6 walking speed without the haste token 
3. Just let it run

### What would you expect to happen?

The player walking back to Hive to convert pollen without getting stuck or lost

### Natro Macro version

9.9.1 - 9.9.2

### Notes

I'm sorry for my bad English. I hope everything is good enough to understand my problem.

**Comment by zspz** [comment]
Yes, your movespeed matters, it must be set correctly in Settings tab.
