### ISSUE TITLE
H

### ISSUE THREAD

**Issue by Yiiiioo** [NatroTeam/NatroMacro#229]
### Have you searched the existing bug reports?

No

### What happened?

Macro changes max planters can be placed from 3 to 2 by itself

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

V

### Natro Macro version

0.9.9

**Comment by zspz** [comment]
It does this if you have configured your planters incorrectly (e.g. forgot to harvest a planter, chosen a planter that you don't have, etc.), so this is not a bug.

**Comment by Yiiiioo** [comment]
oh okay thank you

вт, 23 січ. 2024 р. о 16:57 SP ***@***.***> пише:
