### ISSUE TITLE
gifted vicious on cactus field

### ISSUE THREAD

**Issue by bomb9ravod9ra** [NatroTeam/NatroMacro#230]
### Have you searched the existing bug reports?

Yes

### What happened?

Hello, I'm tired of the problem with killing a gifted vicious on a cactus field - it doesn't find it and doesn't kill it (3rd time)

### Steps to reproduce

make new moves on this field

### What would you expect to happen?

fix

### Natro Macro version

0.9.9

### What is your Discord username?

woll_yg

**Comment by zspz** [comment]
If you can post a video, that would be great!

**Comment by bomb9ravod9ra** [comment]
> If you can post a video, that would be great!

I dont have any video, but i have many screens with it. Write to me on discord, I can explain in more detail there and provide about 4 screenshots with proof
