### ISSUE TITLE
constantly resetting bug

### ISSUE THREAD

**Issue by PerspireCyrus** [NatroTeam/NatroMacro#231]
### Have you searched the existing bug reports?

No

### What happened?

Anytime I disconnect I will get reconnected then constantly reset.

### Steps to reproduce

1.Disconnect from game
2.attempt to reconnect
3.once you do reconnect stuck at spawn resetting and not claiming hive

### What would you expect to happen?

I get in game and goes to each hive to see if available.

### Natro Macro version

v0.9.9.2

### What is your Discord username?

perspire_cyrus

**Comment by Noobyguy775** [comment]
#223
