### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by SatisfyingVial** [NatroTeam/NatroMacro#233]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Create a option to ''creat your path'' in path options  so your record a path liike  for example: in Op Auto Cliker   you can create  a path for your mouse. So for natro u create the same thing but its for keyboard
Thank you,
Satisfying Vial

### How will this improve Natro Macro?

Sometime  its  glitchy and it farms  somwhere else 

### What is your Discord username?

thatrandomguy0479

**Comment by zspz** [comment]
You can already create your own paths and use them in Natro Macro, there are detailed guides on how to do this on our Discord server.
