### ISSUE TITLE
Field Drift

### ISSUE THREAD

**Issue by IwoChcePiwo** [NatroTeam/NatroMacro#236]
### Have you searched the existing bug reports?

Yes

### What happened?

25th January my macro started drifting off the field, it was working fine before. Please help.

### Steps to reproduce

1.Help

### What would you expect to happen?

My character not going off the field

### Natro Macro version

v0.9.9.2

### What is your Discord username?

iwochcepiwo_60301

**Comment by misc-et** [comment]
This is most likely not a bug. Check the guides in our Discord knowledge base, and make a support post there if it doesn't resolve.
