### ISSUE TITLE
An issue with honey dispenser.

### ISSUE THREAD

**Issue by Tajdzis** [NatroTeam/NatroMacro#239]
### Have you searched the existing bug reports?

Yes

### What happened?

There is an error in collecting the honey dispenser because it is not updated. The map in bee swarm has been slightly changed and that is why our character has a problem collecting this dispenser.

### Steps to reproduce

1. Read my messages.
2. Update the way to the honey dispenser.
3. Add this to macro.

### What would you expect to happen?

People who use it will definitely be happy.

### Natro Macro version

Natro Macro v0.9.9.2

### What is your Discord username?

tajdzis

**Comment by zspz** [comment]
Thanks for letting us know, the path needs to be updated.

**Comment by zspz** [comment]
Fixed in the next version 👍
