### ISSUE TITLE
natro macro disconnection

### ISSUE THREAD

**Issue by goodiesx** [NatroTeam/NatroMacro#242]
### Have you searched the existing bug reports?

No

### What happened?

if macro disconnects which it shouldnt because i do not disconnect by internet ever but macro wants to rejoin for a reason then it just stays in spawn and doesnt go for the hives. sometimes disconnects completely for idle sometimes just stays in one spot for 10 ish hours

### Steps to reproduce

1.i put macro on i disconnect my mouse and keyboard at night so the rgb wont disturb my sleep 
2.i also turn off my monitor for the same reason
3.sometimes it kills about 100 bugs before disconnecting sometimes it disconnects without killing any mobs then doesnt know how to claim hive for 12 hours

### What would you expect to happen?

it not even to disconnect because when i play for about 5-10h a day of roblox i have never disconnected but if it really does then atleast to know how to claim hive

### Natro Macro version

0.9.9.2

### What is your Discord username?

goodiesc

**Comment by misc-et** [comment]
This can be caused by turning the monitor off for some users, or other settings. Check the guides in our Discord knowledge base, and make a support post there if it doesn't resolve.
