### ISSUE TITLE
Failed to go to the right hive to convert pollen + Stuck at wall

### ISSUE THREAD

**Issue by xNenji** [NatroTeam/NatroMacro#243]
### Have you searched the existing bug reports?

No

### What happened?

1. Failed to go to the right Hive
I set the Natro Macro on Pine Tree field to make as much money as possible and after a while my backpack is completely filled up, then the macro started the process to go the hive (I was Hive 1 + the settings were correct) and worked well, then my character ran to the right hive and after he corrected his possiotion he just kept going towords the beginner shop and did character reset. After i restared my PC it is working again but as soon as i stop the process or close the macro it is broke again and needs a restart again. 

2. Stuck at wall
If the macro sets the Supreme Saturator (with Drivt Comp on) it goes to the sprinkler but sometimes if my character is too fast, my character jumped on the Supreme Saturator and aktivated the glider, then my charcter glided to the wall and was stuck there.

### Steps to reproduce

Settings:
Gathering: Pine Tree (Drift Comp: on)
Pattern Shape: e_lol (Length: M, Width: 3, Rotate Camera: 2, Invert: N/A)
Backpack: Until 100% or 25 mins (walk to Hive)
Sprinkler: Center (Supreme Saturator)
Hive Slot: 1

### What would you expect to happen?

That the character after reproducing dont make the same mistake again.

### Natro Macro version

v0.9.9.2

### What is your Discord username?

xnenji

**Comment by misc-et** [comment]
This can happen due to incorrect settings. Check the guides in our Discord knowledge base, and make a support post there if it doesn't resolve.
