### ISSUE TITLE
Keeps on going to the wealth clock doesn't work. Natro Macro

### ISSUE THREAD

**Issue by amongen123** [NatroTeam/NatroMacro#244]
### Have you searched the existing bug reports?

No

### What happened?

"I tried every field it did not worl it just went to the wealth click pls fix this.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I thought it would work so i can go to the field but didn't work.

### Natro Macro version

v0.9.9.2

### What is your Discord username?

299V

**Comment by misc-et** [comment]
The macro will attempt to collect wealth clock twice before moving on to other tasks. Try letting it run longer. If there's still an issue, check the guides in our Discord knowledge base, and make a support post there for support.

**Comment by amongen123** [comment]
ty
