### ISSUE TITLE
Auto memory match

### ISSUE THREAD

**Issue by LucasLiorLE** [NatroTeam/NatroMacro#245]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Auto memory match feature

### How will this improve Natro Macro?

Automatically does memory matches to grind for mats/memory lb

### What is your Discord username?

LucasLiorLE

**Comment by misc-et** [comment]
Thanks for the suggestion! This one's already on our suggestion board, so closing it here.
https://github.com/NatroTeam/NatroMacro/issues/70
