### ISSUE TITLE
Macro stops using Tool after Reconnect

### ISSUE THREAD

**Issue by JackKillerqq** [NatroTeam/NatroMacro#247]
### Have you searched the existing bug reports?

No

### What happened?

I don’t know, but for some reason the tool stops farming, apparently after relogging to the server

### Steps to reproduce

1.idk
2.idk
3.idk

### What would you expect to happen?

i cant 

### Natro Macro version

for any but my is :0.9.9.2

### What is your Discord username?

bigflopppaman

**Comment by zspz** [comment]
This has been reported a few times on the server, but I am yet to experience it myself or see a detailed report.
I'll leave this issue open until this bug's status is confirmed.

**Comment by zspz** [comment]
Thanks for the report, I was able to recreate this issue so it will be fixed in the next update.

**Comment by zspz** [comment]
Fixed in the next version 👍

**Comment by JackKillerqq** [comment]
Thank You

вт, 30 янв. 2024 г. в 19:13, SP ***@***.***>:
