### ISSUE TITLE
Mythic auto-rolling function

### ISSUE THREAD

**Issue by blin322** [NatroTeam/NatroMacro#248]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Usually, many players don't have enough royal jelly to hatch out mythic bees, so they use auto hatching with the settings: until legendary and until mythic. It gives you a better chance of hatching out the mythic bees, but it takes time and a strong finger. I suggest adding an auto-rolling mythic bees function

### How will this improve Natro Macro?

This will add more users to Natro Macro due  this functionality

### What is your Discord username?

@blin4ik322

**Comment by zspz** [comment]
1. There is no significant evidence that Until Legendary improves chances of rolling Mythics, I have always felt that this is a myth in the community (one of many).
2. This would be better to have in a separate macro, not built into Natro Macro.
