### ISSUE TITLE
reset character

### ISSUE THREAD

**Issue by Nuggets013** [NatroTeam/NatroMacro#249]
### Have you searched the existing bug reports?

No

### What happened?

when i have full backpack macro make reset character and didn't converting pollen

### Steps to reproduce

1. idk?
2.
3.

### What would you expect to happen?

idk?

### Natro Macro version

v0.9.9.2

### What is your Discord username?

_nuggets_

**Comment by misc-et** [comment]
This can happen due to incorrect settings. Check the guides in our Discord knowledge base, and make a support post there if it doesn't resolve.
