### ISSUE TITLE
Remote control commands

### ISSUE THREAD

**Issue by XDe0** [NatroTeam/NatroMacro#25]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Hi, when I using Discord remote control I often need some commands, that don't exist yet, and here are them:
--------------------------------------------------------------------------------------
**So first, is make a skip function. It works like:**
1. (Status) Attacking Werewolf
2. ?skip
3. (Status) Looting Werewolf
So it skips actions and I think it can be very useful

**Second is a screen capture function. It's very simmilar to ?screenshot (?ss) but it works another:**
1. ?sc 15 (video screen capture 15 sec length)
2. ?sc on (starts screen capture on infinite time until off)
3. ?sc off (ends screen capture and sends it in webhook channel)
Also I understand that maybe bot's are also have file size limit(like non-nitro users). So it can be limit on screen capture like 15MB or 30sec etc.

**Third - is command that change's state of killing Stump Snail and Commando Chick.**
?set StumpSnailState 5m(10m, 15m or Kill)
?set CommandoChickState Kill(5m, 10m or 15m)

**And fourth - is a command that can open game buttons like:**
?open Quest (opens quests menu)
?open Items (opens items menu)

**And also continue of this command is use command, works that way:**
?use ItemTab Glitter (uses glitter from items tab)
?use BadgeTab Pumpkin (opens badges tab and presses on pumpkin badge(hotshot, ace, etc.))

### How will this improve Natro Macro?

That's all definetly will help users that use remote control and will do it easier!

### What is your Discord username?

bebrik_varenik

**Comment by Milo123459** [comment]
this wouldn't work without a massive redesign of how the webhook works, and probably wouldn't be very secure
