### ISSUE TITLE
More Versatile Remote Control 

### ISSUE THREAD

**Issue by awesomegamer22350** [NatroTeam/NatroMacro#251]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Somewhat similar to #78, I'd like to suggest making the remote control webhook more versatile such as activating and deactivating bug runs or questgivers as well as changing settings

### How will this improve Natro Macro?

This would be helpful as you could better fine-tune the settings of the macro from a distance as the current options are quite limited

### What is your Discord username?

awesomegamer22350

**Comment by awesomegamer22350** [comment]
You can? What commands?

**Comment by zspz** [comment]
Yes, you can change almost every setting in the maceo with the `?set` command, it is documented in the Remote Control channels in our Discord server.
There have been suggestions to create shorthand commands for e.g. disabling all Bug Runs or pasting Field settings (#78), but these have been quite low priority as they're already possible (but slower and more complicated) with `?set`.

**Comment by awesomegamer22350** [comment]
Oh neat I must have missed it, thank you very much!
