### ISSUE TITLE
auto star amulet

### ISSUE THREAD

**Issue by waiker12** [NatroTeam/NatroMacro#252]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

add auto star amulet function.
you need to enter the type of amulet required characteristics (passives too)
and every 25M,50M,250M,1B,10B of honey twist the star amulet

### How will this improve Natro Macro?

this function is useful when you cannot approach the device for a long time and you need a good star amulet
(I came across such a function but they didn’t mention the star amulet)

### What is your Discord username?

.Rol.

**Comment by zspz** [comment]
This would be more useful as a separate macro instead instead of being built into Natro Macro.
I would not consider adding a setting in Natro Macro for this (unless it's a separate feature in Misc tab) because incorrect settings could replace a user's Star Amulet.
