### ISSUE TITLE
Mondo Kill

### ISSUE THREAD

**Issue by DimkaPro22809** [NatroTeam/NatroMacro#253]
### Have you searched the existing suggestions?

No

### What is your suggestion?

When natro kills mondo after killing him, he waits 1 or even more minutes before going to collect loot from him; during this time, up to 40% of resources can be lost

### How will this improve Natro Macro?

don't lost resources from mondo if you so lucky you can lost mythic egg\star treat

### What is your Discord username?

reddi8s

**Comment by DimkaPro22809** [comment]
And I forgot my macro when completing polar bear quests when killing mantises, without killing them he moves on to the next ones, it’s better to make the macro see that he killed him through imagesearch

**Comment by zspz** [comment]
Thanks, this is a known issue, refer to #56 (and feel free to give your input there).
The Mantis issue you described is also a consequence of health detection issues.
