### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by BeamNawapat** [NatroTeam/NatroMacro#254]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I believe it should also be compatible with macOS. When I attempted to run a .bat file on my Mac, I noticed it can only be used on Windows, as it calls a file from the Windows directory.

### How will this improve Natro Macro?

I believe there will be macOS users who would like to use it as well!

**Comment by zspz** [comment]
AutoHotkey is only available for Windows.
The most we can do is modify the macro so that it can run with Wine, but none of us have devices to test this and it is not planned.
