### ISSUE TITLE
Unable to detect game GUI offset

### ISSUE THREAD

**Issue by RoKPandA** [NatroTeam/NatroMacro#256]
### Have you searched the existing bug reports?

Yes

### What happened?

![Screenshot 2024-01-30 211451](https://github.com/NatroTeam/NatroMacro/assets/94900652/37d149b0-fbe6-48f0-8af6-f8df6e1ffc81)

### Steps to reproduce

1. For me i just run it and the message opens and the character doesn't stop reseting
2.
3.

### What would you expect to happen?

to run the macro 

### Natro Macro version

v.0.9.9.2

### What is your Discord username?

rokpanda_

**Comment by zspz** [comment]
This is not a bug, this means your settings are incorrect.
Check them with our guides in Discord.
