### ISSUE TITLE
details of doing a quest

### ISSUE THREAD

**Issue by GAMEEYCKER** [NatroTeam/NatroMacro#258]
### Have you searched the existing suggestions?

No

### What is your suggestion?

i would like to suggest how you can do your quests: for example i enable to do brown bear quest but it gives me some random pattern shape and when i do like dandellion and it gives me cornerXsnake it just goes out of the field, if we can choose which patern and lenght/width it could help me macro easily has i dont go out of the field because i choose either stationary or e_lol

### How will this improve Natro Macro?

ill help players macro easily and dont have problems like me that the character just goes out of the field and it spends more time doing the quest with the macro or making the user do it by hand

### What is your Discord username?

gameeycker

**Comment by zspz** [comment]
You can already do this by overriding the field defaults using this button:
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/1168c2e2-fae4-4a1b-9866-b68a9eea840b)
in the Gather tab.
