### ISSUE TITLE
Toggles to prevent donating certain stickers to the sticker stack

### ISSUE THREAD

**Issue by KJ76539** [NatroTeam/NatroMacro#259]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

The toggles would disable the macro from donating hive skins, or cub buddy skins. How it would work is the macro would detect the little icons in the donation screen and keep moving the mouse across when it reaches a sticker it can donate. (i hope you understood this im bad at explaining)

### How will this improve Natro Macro?

This will improve Natro by enabling people (like me) to finally be able to use the auto sticker donation without the risk of losing a rare cub skin.

### What is your Discord username?

KJ76539

**Comment by zspz** [comment]
Thanks, this is a great suggestion and has been added in the next version (released soon).

**Comment by zspz** [comment]
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/e85547c1-4903-415b-a6db-a6b45db63445)
