### ISSUE TITLE
Strawberry field collision

### ISSUE THREAD

**Issue by beatcat6** [NatroTeam/NatroMacro#260]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I have a problem when I macro the strawberry field because when returning to the hive with a full backpack the collision with the strawberry in the bottom left messes up the run path for the return script. This makes me unable to convert a full backpack 80% of the time and it has made my macroing experience less than satisfactory. I am hoping that you guys might be able to change the return script for the strawberry field so that there is less to no chance of colliding with an object and messing up your rates.

### How will this improve Natro Macro?

Adding a different hive return script from the strawberry field would give anyone who macros there a better experience because they will be able to make more honey with the backpack conversion rates. This would be greatly appreciated from me and many other users who have this silent problem.

### What is your Discord username?

sharksquid671

**Comment by zspz** [comment]
I checked this and it doesn't seem to hit any collidable strawberries, so I assume this is due to an incorrect MoveSpeed setting.
If it's not, please create a macro support post on Discord first to confirm whether the path actually needs updating.
