### ISSUE TITLE
Keeps running into the mud ramp next to the red cannon

### ISSUE THREAD

**Issue by AwildLratiobozo** [NatroTeam/NatroMacro#261]
### Have you searched the existing bug reports?

No

### What happened?

once it starts it walks over to the second hive before the red cannon, jumps and then stops at the ramp and resets can it just keeps doing that over and over again

### Steps to reproduce

1. set gather to 1: cactus, e_lol, 2: Clover, e_lol 3 Sunflower CornerXSnake, all the other settings are just the basic ones that it auto sets
2. click run and then it does what i described above, btw the older version works perfectly fine  
3.

### What would you expect to happen?

It to not just stop at the ramp and actually work

### Natro Macro version

not sure where to find the version but it was the lastest version on Jan 31, 2024 at like 12:30 AM

**Comment by Noobyguy775** [comment]
Your hiveslot is probably wrong, hiveslot 1 is closest to cannon, 6 is closest to the honey dispenser/noob shop
![hiveslot image demo](https://github.com/NatroTeam/NatroMacro/assets/109582490/416a0093-e596-47ba-a804-5905815f4cce)
