### ISSUE TITLE
Natro Macro Bug

### ISSUE THREAD

**Issue by xSxloz** [NatroTeam/NatroMacro#262]
### Have you searched the existing bug reports?

Yes

### What happened?

My macro used to work fine until i switched from windows 10 to 11, after that whenever i start the macro it resets like it used to but then it just keeps opening and closing my badges, quests, bees and settings

### Steps to reproduce

1.I dont know
2.what to
3.do about it

### What would you expect to happen?

I really just need help with this, please get back to me as soon as possible thanks.

### Natro Macro version

v0.9.9.2

**Comment by Noobyguy775** [comment]
Join the [discord](https://discord.gg/natromacro/) and ask for assistance there.
