### ISSUE TITLE
absolutely nothing working for me

### ISSUE THREAD

**Issue by alaurenw** [NatroTeam/NatroMacro#264]
### Have you searched the existing bug reports?

No

### What happened?

i put in all the settings in the macro, but when i start it my character keeps resetting, running into walls, wont select a hive slot, tries to place planters in the wrong spot, walks in circles, and leaves the game. 

I tried to let it run for an hour and then reset the settings 3 times. However nothing is working at all

### Steps to reproduce

1. launching the macro 
2. resetting the settings on macro
3. rejoining server on macro

### What would you expect to happen?

I would like to know how to get it to operate properly please. Some tips and some pointers on how I can fix it. 

### Natro Macro version

v0.9.9.2

### What is your Discord username?

jusepie#8044

**Comment by Noobyguy775** [comment]
Join the [discord](https://discord.gg/natromacro/) and ask for assistance there.
