### ISSUE TITLE
Auto Nectar Condenser

### ISSUE THREAD

**Issue by Danielakadanny** [NatroTeam/NatroMacro#265]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Allows the macro to automatically condense any nectar into their respective vials.

### How will this improve Natro Macro?

This will allow players to focus more on loot from Planters while also obtaining nectar so those who wish to boost while farming mats can be efficient and plentiful for the boosts.

### What is your Discord username?

reflectionic

**Comment by zspz** [comment]
#159
