### ISSUE TITLE
Resetting

### ISSUE THREAD

**Issue by laporka** [NatroTeam/NatroMacro#266]
### Have you searched the existing bug reports?

No

### What happened?

It just resetting me for all time

### Steps to reproduce

1.Peeked Pine Tree
2.Pressed F1
3.

### What would you expect to happen?

I expected that i'll go to pine tree

### Natro Macro version

0.9.9.2

### What is your Discord username?

laporka

**Comment by zspz** [comment]
This is not a bug, check that your settings are correct with our guides on Discord and create a macro support post there if the issue persists.

**Comment by remagorp** [comment]
there isnt a support channel there
