### ISSUE TITLE
Resource priority for planters

### ISSUE THREAD

**Issue by h79ru0** [NatroTeam/NatroMacro#267]
### Have you searched the existing suggestions?

No

### What is your suggestion?

--Wax Priority--
most planters have guaranteed swirled/caustic when placed in a specific field (usually has cooldown of 36 days)
Having a premade setting to automatically collect those wax would be great

--Material Priority--
if someone wants blue extracts specifically then macro will have blue planters as priority and those planters will be placed on blue fields 
This can vary between resource 

### How will this improve Natro Macro?

Lets assume that resources are the main priority for someone and nectars dont matter
that user will be able to switch priority from nectar to resource 
so if someone wants blue extracts then macro will priorise blue fields

### What is your Discord username?

@magicbs @bsmagic Contact either one

This is what Im referring to when talking about the wax probabilities 
![wax-list-v20-v0-2d35xaehafda1](https://github.com/NatroTeam/NatroMacro/assets/158511626/39bb27e0-059b-471c-9723-171386fa15a1)

**Comment by Redlgn** [comment]
This would be very helpful.

**Comment by misc-et** [comment]
See https://github.com/NatroTeam/NatroMacro/issues/425, for monthly planters, and https://github.com/NatroTeam/NatroMacro/issues/77 for the option to create and share preset settings towards achieving other specific collection goals
