### ISSUE TITLE
Option to Update Leaderboards

### ISSUE THREAD

**Issue by TCoelhoUA** [NatroTeam/NatroMacro#270]
### Have you searched the existing suggestions?

Yes

### **Suggestion**
Add an "Update Leaderboards" option in the Settings tab that would lead the player to the Trading Hub and then go back to the main server using the portal. This would happen roughly 20 minutes before the leaderboard timer resets (this is due to Onett warning us about possible data loss in the 15 minutes before the leaderboard reset). This action would happen as soon as the game detects it is time to update the leaderboards and would overwrite any action that was being executed at that time.

### **Note**
This reason why this differs from the "Daily Reconnect" option is because most of the time simply rejoining the game doesn't do the job, so it is mandatory to go to the Trading Hub and then go back to the main server.

### **Context**
Most BSS players know that the current leaderboard system that Onett added does not update properly. Most of the time players have to either rejoin the server, join a different server or even going to the Trading Hub and going back to the main server using the portal. This works perfectly if the player is active. Since I'm writing this from a macro player perspective I wrote this suggestion that I think is a must needed one for extreme end-game players.

I really hope you consider this feature as being part of Natro Macro, if you have any more questions feel free to dm me on Discord, I'll be glad to reply :)

### What is your Discord username?

tc1010tiago

**Comment by zspz** [comment]
I don't really see why this would be worth adding to the macro, what does it affect?
I'm closing this for now, but feel free to elaborate.
