### ISSUE TITLE
doesn't kill bugs

### ISSUE THREAD

**Issue by GhostRunner302** [NatroTeam/NatroMacro#271]
### Have you searched the existing bug reports?

No

### What happened?

The macro goes to the strawberry field to kill lady bugs for a quest and then it goes there and the bees are stil sleeping (this happens with a lot of bugs like spider etc.)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I would like you to add a delay like 20 seconds ish before going to killl bugs and/or add a kill bug detection (wait untill it sees defeated ... and then gather loot)

### Natro Macro version

v0.9.9.2(newest version currently )

### What is your Discord username?

Devious_Waffle

**Comment by zspz** [comment]
There are already 2 ways to increase the delay: reduce the number of Hive Bees or increase the Delay after Convert, both in Settings tab.
