### ISSUE TITLE
Quest macro

### ISSUE THREAD

**Issue by GhostRunner302** [NatroTeam/NatroMacro#272]
### Have you searched the existing suggestions?

No

### What is your suggestion?

id like if the macro could do random quest and memory match

### How will this improve Natro Macro?

allow the macro to scroll in the quest tab and if it sees (not the quest name but) collect ... pollen then it will add that to a list of fields to grind until the quest turns green and allow it to do memory match by making a grid system and allowing it to tap it and then saves the item that was there on the grid then combind the same ones

### What is your Discord username?

Devious_Waffle

**Comment by zspz** [comment]
- The first suggestion would only be useful for completing non-repeatable quests, which we have no plans in adding to the macro.
- Memory Match is already a suggestion: #70.
