### ISSUE TITLE
Auto Claim Slot Update

### ISSUE THREAD

**Issue by SultanPewimer** [NatroTeam/NatroMacro#273]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Right now NatroMacro will claim the hiveslot that are put on the settings if its empty (example slot 6) and it will skip slot 1 even if its empty,
make it that you can toggle claim lowest slot available or keep the hive slot unless its occupied

### How will this improve Natro Macro?

of course this will improve the macro, lower hive slot = faster path

### What is your Discord username?

averageunusualuser

**Comment by zspz** [comment]
The macro claims your original Hive Slot at first preference, then if this is already taken it claims the Hive Slot closest to cannon.
There are no plans to change this, so if you want your macro to always claim Hive Slot 1, set this as your initial slot or change it with remote control and force a reconnect.
