### ISSUE TITLE
Freelance

### ISSUE THREAD

**Issue by dondreak** [NatroTeam/NatroMacro#274]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Have a "Roaming" "Freelance" feature. Where you can start the macro.  It will not check for the hive.  It does not reset your character.  It just initiates your character walking around the field in the pattern you set it for.

### How will this improve Natro Macro?

It will allow people to use the feature in random situations like walking around the Hive Hub. There have been times when I was in a specific field and did not want to go back to my hive.  It wasn't the field I had set in Natro.

### What is your Discord username?

dondreak

**Comment by Noobyguy775** [comment]
Click on the version number in the natro gui a few times, and then a new tab should open. In the test patterns/paths groupbox, select the pattern you want. Uncheck reset and check infinite. Press start and it should work. Keep in mind you'll probably drift if its the hive hub (Considering the lag and weird field shape)

**Comment by dondreak** [comment]
Hi

I love it. You guys are amazing.

The skill of my AutoHotKey is one or multiple line text to fill in ticket details. I've tried game macro writing but I gave up and went with only walking back and forth.

Thank you for the work you guys do.
🖖🥰

Take care,
Kevin

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
