### ISSUE TITLE
using gumdrops when you have collect goo quest from bucko and reily bee

### ISSUE THREAD

**Issue by megaballe** [NatroTeam/NatroMacro#275]
### Have you searched the existing suggestions?

No

### What is your suggestion?

when i have the goo quest from bucko and reily bee it takes a long time to complete due to ony having gummy bee to spawn gumdrops and the gummy boots. and if you could add this feture it would make those qust much faster to complete

### How will this improve Natro Macro?

it makes you alot faster to complete the goo quests

### What is your Discord username?

mega.balle

**Comment by zspz** [comment]
#126
