### ISSUE TITLE
macro keeps on leaving and rejoining my server nonstop

### ISSUE THREAD

**Issue by ATREonYT** [NatroTeam/NatroMacro#277]
### Have you searched the existing bug reports?

No

### What happened?

Whenever i go overnight or just grind in general, after around an hour+- the macro leaves and rejoins goes to grind for around 10 mins and leaves again rejoins and continues. I have my private server link in the macro and fallback to public server and after a few rounds of joining and leaving the macro goes to a public server and continues.

### Steps to reproduce

1. Start the macro for me in pine tree field. 
2. Macro goes afk and after an hour starts leaving and rejoining
3. 

### What would you expect to happen?

I usually expect the macro to go for the whole night and not disconnect which causes me to not earn any honey.

### Natro Macro version

v0.9.9.3d

### What is your Discord username?

ATRE#0001

**Comment by misc-et** [comment]
This seems likely to be related to settings rather than a bug, please join our Discord server for troubleshooting guides and macro support.
