### ISSUE TITLE
Natro macro keeps going past the sticker printer and then resets because it cannot print 

### ISSUE THREAD

**Issue by Bensonchen200912** [NatroTeam/NatroMacro#278]
### Have you searched the existing bug reports?

Yes

### What happened?

/
![IMG_0208](https://github.com/NatroTeam/NatroMacro/assets/158843380/ee681757-c2ef-4780-b92a-665744bfadc9)

### Steps to reproduce

1. Walks me to cannon
2.launches me to mountain top field 
3. Walks over to sticker printer and goes past it 
4. Resets and tries again 

### What would you expect to happen?

I expected it to print a sticker every hour but it fails 

### Natro Macro version

0.9.9.3

### What is your Discord username?

Kizaru3093

**Comment by Noobyguy775** [comment]
Please join the [discord](https://discord.gg/natromacro) and ask for help there.
