### ISSUE TITLE
I can't use cannon and convert at my hive with Macro

### ISSUE THREAD

**Issue by MaaLyx** [NatroTeam/NatroMacro#279]
### Have you searched the existing bug reports?

No

### What happened?

When my macro pass on a cannon he don't take it and continue like he don't care and reset
same things when i put on "walk" mode, he gonna collect pollen in the field but when he come back he step on my hive and continue and reset
A video here to show you
https://www.youtube.com/watch?v=S0OhOzCzIZQ

### Steps to reproduce

1. Just start the macro with normal settings
2.
3.

### What would you expect to happen?

I want to the macro to convert and take cannon

### Natro Macro version

The last One 0.9.9.3

### What is your Discord username?

MaaLyx

**Comment by misc-et** [comment]
You'll need to change your Roblox account and in-game language to English.

If the issue persists, head to our Discord server for troubleshooting guides and macro support.
