### ISSUE TITLE
My Macro has a dangerous file/virus.

### ISSUE THREAD

**Issue by MyNatroMacroHasAvirus** [NatroTeam/NatroMacro#28]
### Have you searched the existing bug reports?

Yes

### What happened?

I personally want to use natro macro but when i tried to run it it said, dangerous file/virus detected, do not use this program.
I tried a lot of times, same thing. 
Another person had this same error.
I hope this can be fixed quickly!

### Steps to reproduce

1. Open natro extracted file
2. Press the ahk file and run it (I tried all the files same thing)
3. Virus/dangerous file danger sign appears.
4. 
5.

### What would you expect to happen?

Natro running.

### Natro Macro version

0.9.6

### What is your Discord username?

gamingxnow

**Comment by Noobyguy775** [comment]
#27
