### ISSUE TITLE
Mondo on Bee Swarm Sinulator

### ISSUE THREAD

**Issue by citronthomas68** [NatroTeam/NatroMacro#280]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Hello, 

When mondo spawns, can you add return to hive without converting balloon. Every-time it mondo spawns and comes back to the hive it converts balloon and by the time it gets to mountain top mondo is already dead and we miss out on the chick blessings.

### How will this improve Natro Macro?

this will improve the game and allow macro players to all get the mondo check blessings.

### What is your Discord username?

citronthomas68

**Comment by misc-et** [comment]
Which version of the macro are you using? In the latest version, the macro will skip converting before going to Mondo https://github.com/NatroTeam/NatroMacro/releases/tag/v0.9.9.3

**Comment by citronthomas68** [comment]
Omg i didn’t realize that, is that the setting for convert balloon should be set to gather and not always, am I correct?Thank you so much for responding AndrewOn Feb 4, 2024, at 8:54 PM, misc ***@***.***> wrote:﻿
Which version of the macro are you using? In the latest version, the macro will skip converting before going to Mondo https://github.com/NatroTeam/NatroMacro/releases/tag/v0.9.9.3

**Comment by misc-et** [comment]
Yeah it's a nice addition! It shouldn't matter what convert setting you use, as the convert function should be completely skipped at hive when going to Mondo.

**Comment by misc-et** [comment]
I'll go ahead and close this now, as it's been added.
