### ISSUE TITLE
Downloaded 0.9.9.3 and it bugged out and now i cant use macro ever again

### ISSUE THREAD

**Issue by Sobnn** [NatroTeam/NatroMacro#281]
### Have you searched the existing bug reports?

Yes

### What happened?

Downloaded the latest natro macro, which somehow bugged out my entire natro macro (i cant even use past versions) and something happened inside the sub macros and autohotkey which made it so i cant use the macro (I can open up the macro but i cant use it)

### Steps to reproduce

1.
2.
3.
( i dont understand what you mean, since english is not my first language)

### What would you expect to happen?

^^

### Natro Macro version

0.9.9.3

### What is your Discord username?

slkkz

**Comment by Noobyguy775** [comment]
Go to the [discord](https://discord.gg/natromacro/)for help, if your language has a support channel, you can use that. Your issue seems to be with an antivirus, but please continue to get help on discord
