### ISSUE TITLE
Amulet pop-up makes macro think ant challenge instantly ended, fails to press keep old

### ISSUE THREAD

**Issue by despacitosimulator** [NatroTeam/NatroMacro#283]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro sometimes fails to close the amulet pop-up, resulting in the macro assuming that the ant challenge instantly ended, thus resetting and keeping the amulet on screen. This causes it to waste passes and accomplish nothing but waste time and tickets. If it was a scale issue I'd expect it to fail 100% of the time but this is seemingly random. Also happens if any other amulet comes up on screen via snail or king beetle. I have the setting to keep the old amulet on.
![ss](https://github.com/NatroTeam/NatroMacro/assets/48863157/ffe1ab7e-1632-46d7-86f0-281824607d9b)
The images are 1 minute apart.
![ss](https://github.com/NatroTeam/NatroMacro/assets/48863157/0482793b-8056-4aa5-9eb9-4b0984d9d0dd)
Here it is persisting on a wealth clock screenshot
![ss](https://github.com/NatroTeam/NatroMacro/assets/48863157/fd434f65-5e5e-46d3-8e54-1af24084a744)

### Steps to reproduce

1. Get an amulet pop up
2. Let macro start ant challenge
3. Will instantly reset, thinking it ended due to the pop-up and fail to press keep old.

### What would you expect to happen?

It selects keep old and resumes, instead I have to go and manually press keep old to fix it

### Natro Macro version

v0.9.9.3

**Comment by despacitosimulator** [comment]
Double uploaded image, my bad

**Comment by Noobyguy775** [comment]
It's because there are no images for bronze, silver and supreme ant amulets. I'll fix it with the upcoming bugrun rework :)

**Comment by zspz** [comment]
The coordinates also need fixing as it uses a `"center"` `nm_imgSearch()` but the amulet prompt is not in that region for all resolutions.

**Comment by Noobyguy775** [comment]
merging with #502
