### ISSUE TITLE
spirit bear quest

### ISSUE THREAD

**Issue by euluci** [NatroTeam/NatroMacro#284]
### Have you searched the existing suggestions?

No

### What is your suggestion?

To add spirit bear quest

### How will this improve Natro Macro?

because it helping alot of people

### What is your Discord username?

gogutza

**Comment by Noobyguy775** [comment]
Spirit Bear's quests are long and tedious, so a lot of users ask for a macro for them. However, there are a few problems with macroing spirit bear quests. One of the main problems is the impossible stuff to macro, like windy bee, stickbug, jellybean tokens, sparkles, etc. The main point of natro is to make the grind less hard, and not to play the game for you.
