### ISSUE TITLE
Planter (Pestecide) (Spider) Time Eror

### ISSUE THREAD

**Issue by DimkaPro22809** [NatroTeam/NatroMacro#285]
### Have you searched the existing bug reports?

No

### What happened?

I noticed an error in the macro related to the pesticide of the seeder on the spider, when the macro time was up, the seeder had grown, he went to collect it but in the end found 90-93% and set it for another 30 minutes, set the growth, please correct it

### Steps to reproduce

1.add 30 minutes to pesticide growth time
2.
3.

### What would you expect to happen?

fix it

### Natro Macro version

0.9.9.3

### What is your Discord username?

RedDi

**Comment by Noobyguy775** [comment]
That's because you enabled "Harvest at Full Grown".
![image](https://github.com/NatroTeam/NatroMacro/assets/109582490/55ebacbe-7a98-47dd-80c9-55b109dfbe7e)

(Uncheck it if you dont want the planters to be at full growth)
