### ISSUE TITLE
Internet off

### ISSUE THREAD

**Issue by DimkaPro22809** [NatroTeam/NatroMacro#286]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Macro check internet status if internet disconnected it close roblox and waiting to internet connecting
if internet connected it send to discord
[Time]: Macro Restarted
Reason: Internet disconnected
Time Internet Disconection:(time how internet long disconnected)

### How will this improve Natro Macro?

macro can stuck with problem and get error while try send to webhook or bot msg

**Comment by Noobyguy775** [comment]
You can't send messages over the internet to say that your internet is out 😭
