### ISSUE TITLE
Alt account linking (further talked thru misc)

### ISSUE THREAD

**Issue by chasemurray** [NatroTeam/NatroMacro#288]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

this is something me and wilalwil came up with when we were experimenting with things, and its alt connections, basically how it works is you have (and this doesnt have to be final obv, if theres an easier way then do that) the main account macro, and your alt(s), now you alt account macro will connect to the main account and be properly functional, but what makes it good is it will react to the main account. for example, field booster chasing, lets say main account gets blue flower boost, and it goes to chase, it would communicate to the alts, and the alts would go with it and start macroing in blue flower field.
a second part to this would be with items, such as alts providing gumdrops if needed, or jelly beans, etc.. but this is questionable considering a lot of things.

### How will this improve Natro Macro?

this would allow a whole new strategy to just the game in general, and bring so many people to natro if this were to be a thing

### What is your Discord username?

chaxe (chase)

**Comment by ninjubaer** [comment]
this is actually something ive been playing around since v0.9.6 and has been done multiple times for vichop or mondo hop macros

**Comment by misc-et** [comment]
Just closing this, based on agreement that alt account linking is a cool but fairly niche thing that sits outside of the general macro scope
