### ISSUE TITLE
Change hive color in macro

### ISSUE THREAD

**Issue by clonesasharopa** [NatroTeam/NatroMacro#290]
### Have you searched the existing suggestions?

No

### What is your suggestion?

i think need add to macro changers hive color bc when macro send me hourly report i didnt se how mach times scorching star will be activated and 

### How will this improve Natro Macro?

people will be able to see how different their farm is per hour with different amounts of activations gummy and scorching star

### What is your Discord username?

clonesasharopa

**Comment by Noobyguy775** [comment]
#20
