### ISSUE TITLE
sticker stack collector

### ISSUE THREAD

**Issue by TedB010** [NatroTeam/NatroMacro#291]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I want a feature that can give stickers to the sticker stack automaticly. You chould be able to choose what kind of stickers you want to use or not use. 

### How will this improve Natro Macro?

The reason i want this feature is because then i can get an extra buff when macroing, and also, when i am boosting i can get a lot more buffs from the sticker stacker than giving stickers manually. 

### What is your Discord username?

tedb and the numbers are 6937.

**Comment by Noobyguy775** [comment]
This already exists, but I'll keep the suggestion open since you can't select which stickers you want to donate. (Currently it uses any sticker inside your inventory besides Cub & Hive skins)

**Comment by zspz** [comment]
I'm closing this because I don't think it would be worth the development time and added inefficiency to exclude certain stickers.
