### ISSUE TITLE
Sprout party

### ISSUE THREAD

**Issue by paper555555555555555555555555555** [NatroTeam/NatroMacro#293]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

It does how many sprouts you want and field so you can gets lot of stuff you usually get from that field

### How will this improve Natro Macro?

It will help natro macro because some people want a little extra fruit for crafting

**Comment by Noobyguy775** [comment]
What advantages does this have besides doing it yourself?

**Comment by paper555555555555555555555555555** [comment]
When you use it when it gets that many sprouts then it does the sprout party so you can collect a lot of stuff.
