### ISSUE TITLE
about the gui offset...

### ISSUE THREAD

**Issue by eddieeeeeeeeeee** [NatroTeam/NatroMacro#297]
### Have you searched the existing suggestions?

No

### What is your suggestion?

is it possible to create a system which can identify the images even after distortion or being moved to a different part of the screen?

(by items i mean the gui stuff. eg. planters bitterberries eggs rj etc

### How will this improve Natro Macro?

this would benefit many users who i see in the discord server have troubles with the gui offset as majority have some problem with resolution or screen size etc

### What is your Discord username?

e.d.die

**Comment by zspz** [comment]
No.
GUI offset is not a bug, but rather a flag to tell the user that their settings are incorrect.
The macro already works for all resolutions excluding in-game limitations e.g. inventory being cut off on minimum height windows, or equipment being shown on top of screen (interferes with buff detection).
