### ISSUE TITLE
More Quest Macro Bears

### ISSUE THREAD

**Issue by postingrandomcrap** [NatroTeam/NatroMacro#300]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

So, there are already a fair amount of bears you can macro but if you're more early game (the point where you're more likely to macro quests unless its polar) you would want some additional bears. Let me go over this:

You can already macro some bears like polar bear, black bear (after questline), brown bear etc which is mainly due to the fact the quests aren't as "complicated" to make but I feel like there could be "greater" limits to what you can actually macro.

**Black Bear (before questline)**

Now, even though black bear is already a option it will only work *after* the main questline. I can see why this is but for black bear itself the majority of the quests is just farming fields in not very large amounts. I don't see why this couldn't be added as black bear usually doesn't give killing bug quests which even if, the macro can just go macro on fields or do other bear's quests while it waits.

**Science Bear**

I can see why science bear isn't added as it has quests usually to do with killing bugs although as mentioned in black bear, this isn't a extremely complicated thing to go to fields where bugs are and kill them, and as mentioned earlier if the bugs are on cooldown it can just farm fields or do the other quests.

I aren't about to go over every bear it could do with some obvious exceptions like panda bear due to ant challenges etc but I don't think theres a reason to push away certain bears.

### How will this improve Natro Macro?

This will help people just generally complete quests way faster and better with more accessibility. Don't really know what else you would like me to say as it's a bit *obvious* about my point.

### What is your Discord username?

duhphil (1124249028729786479)

**Comment by misc-et** [comment]
Thanks for this suggestion. It is true that some mainline quest tasks would be more difficult and inefficient to macro than others. 
However the decision not to include the main questlines is mostly not based on the potential complexity of implementation, but on the basis that the macro is designed as a supplement rather than full replacement for active game play, so therefore there aren't plans to add these to the macro.
