### ISSUE TITLE
Updating natro config after pause

### ISSUE THREAD

**Issue by postingrandomcrap** [NatroTeam/NatroMacro#301]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

If you want to for example change planter settings, bear quests, settings, gather settings etc you have to actually restart the whole macro which an be annoying if you dont want your whole report to reset or have your character reset and lose your pollen + start back at the hive.

So my suggestion is if you press F2 to pause and change settings they get applied after unpausing like if you were using discord remote control.

### How will this improve Natro Macro?

It'll stop people from having to reset their hourly discord reports and restart grinding from their hive if they want to change the settings lmao.

### What is your Discord username?

duhphil (1124249028729786479)

**Comment by zspz** [comment]
This should already work for almost all settings, there are only some exceptions where the variable is not properly updated within the macro.
If you can confirm that this is the case for any specific setting, please open a new Bug issue listing all of them. Thanks!
