### ISSUE TITLE
Broken Health Detection in Bug Run

### ISSUE THREAD

**Issue by Wasim-jr** [NatroTeam/NatroMacro#303]
### Have you searched the existing bug reports?

Yes

### What happened?

basically i have polar bear quests on, and theres this 1 quests where u gotta kill 16 rhino's everytime my character goes to a field for that it resets and goes on to the next field, but in bamboo field the character resets tooo quick, it resets so quick that my bees doesnt even have time to arrive and kill the rhino's, i hope yall will fix that soon by adding more time to kill the rhino's at bamboo field 

### Steps to reproduce

1. after being done with the rhino at clover field, my character resets
2. after spawning i use the red canon to go to bamboo field
3. after arriving there, my character resets in 5 secs..

### What would you expect to happen?

for my roblox character to have more time to kill the rhino's

### Natro Macro version

Natro Macro v0.9.9.3

### What is your Discord username?

@wasim

**Comment by Wasim-jr** [comment]
the same goes with the spiderfield, it resets too fast, which doesnt give enough time to kill the spider..

**Comment by Noobyguy775** [comment]
These issues should be fixed with a `nm_Bugrun()` rewrite, which I am currently working on.

**Comment by lordlevstar** [comment]
This also happens for me but for mantises, occasionally my bees can kill the one in pineapple.  However they never make it to pine tree in time to kill either of those mantises

**Comment by Noobyguy775** [comment]
merging with #502
