### ISSUE TITLE
waiting bees to come

### ISSUE THREAD

**Issue by cemsuat** [NatroTeam/NatroMacro#304]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

the character will wait in a spot that is safe from dying, and when the set time by the user ends ( maybe in the settings ) it will go to the field. this isnt needed in fields that dont have mobs. 

also this could mean that there would be another setting to FORCE wait after every reset, to wait the bees wake back up/be working again.

### How will this improve Natro Macro?

lets say someone with slow bees wants to afk in rose field. he wants to go there and all but then the scorpions kill that person. this repeats over and over again with him gaining nothing or really small amounts of what he could actually get.

### What is your Discord username?

cemsuat (724295222682583041)

**Comment by Noobyguy775** [comment]
![image](https://github.com/NatroTeam/NatroMacro/assets/109582490/a35cdeff-4ff4-44ed-b30a-326b00fe9a36)
Set your hive bees to a lower amount, or force waiting longer with the "wait *x* seconds after convert" setting
