### ISSUE TITLE
Use coco crab glitch for new players that just reached 35 bee zone

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#306]
### Have you searched the existing suggestions?

No

### What is your suggestion?

This feature would be toggleable for players who have op damage stats.
There is a glitch in the game where every once in a while, when the coco crab goes to spawn, it's character doesn't show up. When this happens, it goes through its normal movements except it doesn't hit you, and doesn't drop coconuts on you, (the only way it deals damage is if you go into its character where it's supposed to be. The macro could utilize this by searching for the coco crab and the timer. If there is a timer, there is no coco crab. If there is no timer and a coco crab, repeat. If there is no timer and no coco crab, sit in the middle of the field or something so your cub buddy can collect all the bee ability tokens in one spot or something.

### How will this improve Natro Macro?

This would help users who can barely defeat the coco crab, and players who just aren't skilled, and the macro is really bad at killing the crab. Sometimes it gets lucky and survives 15 minutes, but that's rare and it usually immediately dies.

However, if this glitch is patched then the feature would be meaningless so I can see why it wouldn't be added.

### What is your Discord username?

ZackAttack4987

**Comment by ZackAttack4987** [comment]
Alternatively, you could add a similar feature that isn't based off rng, and add the glitch where you stand *perfectly* on that ledge and make the macro able to avoid hits by jumping at the perfect time, which would just be checking a few pixels rbg values and jumping when it equals a specific value.

**Comment by zspz** [comment]
I think both of these glitches have already been patched, but I could be wrong. Do you have a recent video of any of them? I'll reopen the issue if you do.
Even then, it wouldn't be as easy as it seems to get the precision required for the macro to use the second glitch.

**Comment by ZackAttack4987** [comment]
Sometimes I see the macro accidentally perform the first glitch, and as for
the second, it's still possible, but requires *extreme* precision that is
hard to get even with shift lock.

**Comment by ZackAttack4987** [comment]
I GOT PROOF FOR THE FIRST GLITCH
![Uploading Screenshot 2024-02-28 045731.png…]()

**Comment by ZackAttack4987** [comment]
Why won't it upload... :(
