### ISSUE TITLE
Backpack Not Converting

### ISSUE THREAD

**Issue by vampishone** [NatroTeam/NatroMacro#308]
### Have you searched the existing bug reports?

No

### What happened?

When I checked my macro, I noticed that it would go to the hive then not convert as I would use the discord plug in to check it every few hours
![IMG_3012](https://github.com/NatroTeam/NatroMacro/assets/155204348/d951f6e5-5c1f-481e-ace9-3d07abadde7f)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

To convert my hive every time

### Natro Macro version

9.9.3

### What is your Discord username?

coolbeaned

**Comment by fenixJK** [comment]
Its getting lost on the return path. If you are using any custom paths try redownloading the default path and checking if thats the issue.

**Comment by vampishone** [comment]
I am using E_lol and idk how to fix

**Comment by vampishone** [comment]
it’s using e_lol and idk how to fix

**Comment by fenixJK** [comment]
e_lol is a pattern not a path. did you download any wf-pinetree files?

**Comment by fenixJK** [comment]
Join the discord server to receive support.
