### ISSUE TITLE
infinite reset bug using macro how do i fix this?

### ISSUE THREAD

**Issue by progamerbssrizzler** [NatroTeam/NatroMacro#31]
### Have you searched the existing bug reports?

No

### What happened?

each time i start macro it resets i cant really use it.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i was expecting it to work :\

### Natro Macro version

natro.macro main

**Comment by Noobyguy775** [comment]
Join the [discord](https://discord.gg/natromacro/), this is a known user error.
