### ISSUE TITLE
Unable to detect in game GUI offset!

### ISSUE THREAD

**Issue by chuanchuan114** [NatroTeam/NatroMacro#310]
### Have you searched the existing bug reports?

No

### What happened?

I did all the steps but still having this problem

### Steps to reproduce

1.Incorrect graphics settings(check Troubleshooting Guide!)
2.Your 'Experience Language' us nit set ti English
3.Something is covering the top of your roblox window

### What would you expect to happen?

![image](https://github.com/NatroTeam/NatroMacro/assets/159986869/ff33c0f7-0b4c-40e4-94fa-d42a5724b8da)

### Natro Macro version

v0.9.9.3

### What is your Discord username?

callmeyoumom

**Comment by zspz** [comment]
This is not a bug. Join our Discord server for support.
