### ISSUE TITLE
reconnecting

### ISSUE THREAD

**Issue by ZomBiekrit** [NatroTeam/NatroMacro#311]
### Have you searched the existing bug reports?

yes

### What happened?

natro macro reconnects all the time, I did not make a reconnection command

### Steps to reproduce

1.I'm launching
2.he works
3.and reconnect in 15 minutes

### What would you expect to happen?

I wanted natro macro to understand for himself where he is in order to get there

### Natro Macro version

v0.9.9.3

### What is your Discord username?

2.2shodowmoon

**Comment by zspz** [comment]
This is not a bug. Join our Discord server for support.
