### ISSUE TITLE
Freezing 

### ISSUE THREAD

**Issue by vampishone** [NatroTeam/NatroMacro#314]
### Have you searched the existing bug reports?

No

### What happened?

When ever I turn my monitor back on I notice that it will just be stuck on the screen and it won’t move for hours then i have to reset my whole computer to fix it 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

It should macro throughout the night

### Natro Macro version

9.9.3

### What is your Discord username?

coolbeaned

**Comment by zspz** [comment]
This is unrelated to the macro: whether or not the macro works with your monitor off is completely dependent on your system.
Go to our Discord server for support and more information.
