### ISSUE TITLE
Strawberry, blueberry and glue dispensers  don't work

### ISSUE THREAD

**Issue by Milo123459** [NatroTeam/NatroMacro#32]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro goes to the blueberry, strawberry and glue dispensers twice before resetting and not actually collecting them.
<img width="379" alt="image" src="https://github.com/NatroTeam/NatroMacro/assets/50248166/27a3272e-9100-4adc-bc1a-d5a08f138fb0">

### Steps to reproduce

1. Turn on one of the above dispensers (blueberry, strawberry, glue)

### What would you expect to happen?

It should collect them

### Natro Macro version

0.9.6

### What is your Discord username?

milo123459

**Comment by Noobyguy775** [comment]
@Milo123459 Can you record a video/ provide more details?
Does the macro actually make it to the dispenser, or does it just reset at your hive or fail the path?

**Comment by Milo123459** [comment]
Reinstalling the macro seems to have fixed it
