### ISSUE TITLE
Planter Time Innacurate

### ISSUE THREAD

**Issue by postingrandomcrap** [NatroTeam/NatroMacro#320]
### Have you searched the existing bug reports?

No

### What happened?

So the tittle explains itself mainly, I have 3 planters and it places them all down and starts a 2h timer. One of them being a plastic planter which should be full grown in 2h by itself anyways but the thing is even though the planter isnt degrading (brown) after the macro came to collect it the planter was at about 96% even though the planter takes 2 hours to grow and the gather time is at 2 hours.

### Steps to reproduce

1. Set the macro to place planters down
2. Wait at least 2 hours
3. See that its a bit offset

### What would you expect to happen?

To have a bit more of an accurate time as it was a few minutes off at the least.

### Natro Macro version

v0.9.9.3

### What is your Discord username?

duhphil (1124249028729786479)

**Comment by postingrandomcrap** [comment]
No

**Comment by misc-et** [comment]
Can you screenshot your webhook at the time of planting and harvesting it?

**Comment by zspz** [comment]
From what I remember, degradation is also calculated incrementally, so it's very possible that the planter was very only slightly degraded.

**Comment by misc-et** [comment]
This does seem most likely to be slight field degradation, which can be avoided by cycling through more planter fields. I'm going to go ahead and close the issue, but feel free to reopen if you have further concerns or reason to believe this is not the case.

**Comment by postingrandomcrap** [comment]
this is defo not the case cause i come back to a 46% (out of 50%) health planter but okay..
