### ISSUE TITLE
Crab/Snail Health Report

### ISSUE THREAD

**Issue by remizuwu** [NatroTeam/NatroMacro#321]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

A timed webhook report for the health value of either coconut crab or stump snail depending on the selected field. ex: **Stump Snail Report | 128966/30000000 HP**
Alongside this, a detection script to see whether the boss is spawned in or not to prevent nonsense reports.

### How will this improve Natro Macro?

I would like this feature because while not major it would be nice to be able to check in on stump snail or coco crab's HP every so often. There isn't much benefit it's rather more-so QOL but it would just be nice to have.

### What is your Discord username?

Remizu

**Comment by remizuwu** [comment]
Forgot to add this but it would be nice if it was included in the report 
eg:
damage dealt during the time period
time to kill (if it died during the time period)
and average damage per second

**Comment by Noobyguy775** [comment]
This already exists for snail, unless i'm missing something.
You should get a report every few minutes for snail and commando chick. I'll add the same estimations to coco crab with the bug run rewrite.
> Snail
![image](https://github.com/NatroTeam/NatroMacro/assets/109582490/1e0c07c1-72bd-44d7-b4bd-fb2ace26cf0d)


> Commando chick
![image](https://github.com/NatroTeam/NatroMacro/assets/109582490/5071c9e5-3160-4c8f-ab4f-e4e1ecc8ca82)
