### ISSUE TITLE
Use glitter for Planters+

### ISSUE THREAD

**Issue by djdudkin** [NatroTeam/NatroMacro#323]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Basically, you can use glitters when doing manual planters. Why not to add the same feature for Planters+

### How will this improve Natro Macro?

If planters grow faster, players will be receiving more nectar when gathering every _n_ hours or when gathering fully grown planters

### What is your Discord username?

i.am.parents.do.not.love.me

**Comment by Noobyguy775** [comment]
Good idea!

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/39
