### ISSUE TITLE
Option to wait at hive for a select amount of seconds before killing each mod

### ISSUE THREAD

**Issue by Phandoxx** [NatroTeam/NatroMacro#325]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I would like to make my macro wait at hive for 5-10 seconds after a reset to kill mobs, this way i can get baby love before killing the mobs, giving me more blue/red extracts, glue and most importantly honeysuckles for turps. Please DM on discord (username: Phandox) to chat more if you would like. BTW i changed my hive to have 11 baby bees bc i bug macro to get gummy boots/gummy baller and if my bees are resting after reset i don't get baby love

### How will this improve Natro Macro?

get baby love before killing the mobs, giving me more blue/red extracts, glue and most importantly honeysuckles for turps. Maybe magic beans from spider and ect

### What is your Discord username?

Phandox

**Comment by zspz** [comment]
You can already do this by decreasing the number of Hive Bees or increasing the wait time after convert in the Settings tab.

**Comment by Phandoxx** [comment]
> You can already do this by decreasing the number of Hive Bees or increasing the wait time after convert in the Settings tab.

That does not work, if you set it to 10 for example after kill a mob it will not wait another 10 seconds after it resets for the next mob/mob chain, could this be changed? decreasing bees and making longer wait does not help
