### ISSUE TITLE
Webhook color change option

### ISSUE THREAD

**Issue by 24kH4Z3L** [NatroTeam/NatroMacro#33]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I want to suggest making changes to the discord webook. I think it will be better to add more customizeabilty to this. IE: adding more color settings, adding what things to take pictures of, what to send in the hourly report, etc. 

### How will this improve Natro Macro?

Natro macro is very robot-like with its UI, and the only thing you can really do is change the color of the setup. Changing the webhook customizabilty, at least, would make users more interested in natro and won't make them feel like they are a robot and all they do is set up the macro. Additionally, adding what pictures to send to the discord server would make things better and give players an idea of what the macro is doing while they're gone. Overall, changing the customizabilty and the user interface of the discord webhook would make everything better and won't negatively affect anything at all. So it would be a positive change for the good.

### What is your Discord username?

Derpilost

**Comment by Noobyguy775** [comment]
You can already change what the macro will screenshot, using the discord integration menu (Versions 0.9.3+).
![image](https://github.com/NatroTeam/NatroMacro/assets/109582490/5dc2e796-1e37-4917-b4f7-b1ce5ef3e3fd)
Changing colours is a good idea, we already have an easter-egg in place to make the webhook colours a rainbow, but as I said it's an easter-egg so it's not well known.

**Comment by zspz** [comment]
I changed the title because as Nooby said it's already possible to customise screenshots and hourly report suggestions are already discussed in #20.
Make sure you check existing suggestions and the macro itself before making one!

The ability to change colours will be nice, but the current colour scheme is in place partly to reduce confusion during support (you'll notice that important errors are in red, gather/convert is green/amber (matching hourly report), etc.)

**Comment by 24kH4Z3L** [comment]
> I changed the title because as Nooby said it's already possible to customise screenshots and hourly report suggestions are already discussed in #20. Make sure you check existing suggestions and the macro itself before making one!
> 
> The ability to change colours will be nice, but the current colour scheme is in place partly to reduce confusion during support (you'll notice that important errors are in red, gather/convert is green/amber (matching hourly report), etc.)

**Comment by 24kH4Z3L** [comment]
Thanks for replying back. What I mean by changing the colors is naybe by adding a color wheel? Something like that just in case people who don't know the Easter egg or some people who want to organize stuff and make this action want it to be this color. About the screeenshots, I personally think that it doesn't send enough and maybe could add more options for what it does screenshot? Like when it started to gather or when it kills any mob.

**Comment by misc-et** [comment]
Closing this suggestion due to inactivity, but if anyone wishes to work on it or we get further requests it can be reopened.
