### ISSUE TITLE
Nectar condencer

### ISSUE THREAD

**Issue by dragonapnts** [NatroTeam/NatroMacro#330]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an option to condence your nectar when you have 12+ hours in the planters menu

### How will this improve Natro Macro?

Easier to boost when ever you want because you dont have to macro for many hours to get full nectar

### What is your Discord username?

dinoryan.

**Comment by Noobyguy775** [comment]
Refer to #282 for additions about the Nectar Condenser
