### ISSUE TITLE
my hourly report is completely broken

### ISSUE THREAD

**Issue by myzterium** [NatroTeam/NatroMacro#335]
### Have you searched the existing bug reports?

Yes

### What happened?

![file mac](https://github.com/NatroTeam/NatroMacro/assets/157909380/f4cefcab-ddef-4fe1-88f2-96ee600eea09)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

its supposed to say my hourly average and not be this like this

### Natro Macro version

v0.9.9.3

### What is your Discord username?

th30o

**Comment by zspz** [comment]
This is not a bug, your language is not correct, join our Discord server for guides and support.
