### ISSUE TITLE
Natro Broken due to the new Roblox UI that is slowly being rolled out to users

### ISSUE THREAD

**Issue by CrossiDevCH** [NatroTeam/NatroMacro#336]
### Have you searched the existing bug reports?

No

### What happened?

Roblox New UI buggs the BSS Gui resulting in the Honeybar not being at the top of the screen anymorebut also making it so that the macro can't do stuff with the inventory anymore because of the placement (i marked where the mouse pointer is now instead of where it would normally be next to the inventory row)
![Screenshot 2024-02-21 140136](https://github.com/NatroTeam/NatroMacro/assets/139925973/2ffe61c7-2ba3-4947-b82c-521831ef41fb)

### Steps to reproduce

As said the bug is only with the new ui that not all players have yet. But soon all players will have it

### What would you expect to happen?

Adapt Natro to it.

### Natro Macro version

v.0.9.9.3

### What is your Discord username?

CrossiDev

**Comment by zspz** [comment]
There is already detection and adjustment in place for this.
Update your macro, and if you get the "unable to detect GUI offset" warning, do not ignore it and use our Discord guides to fix it.

**Comment by CrypticSyn** [comment]
> There is already detection and adjustment in place for this. Update your macro, and if you get the "unable to detect GUI offset" warning, do not ignore it and use our Discord guides to fix it.

My macro is already updated to the latest and unable to detect GUI offset doesn't even pop up. It just goes on without warning, now if you must, I need some real help with this. 😭
