### ISSUE TITLE
Too fast or something idk

### ISSUE THREAD

**Issue by paper555555555555555555555555555** [NatroTeam/NatroMacro#338]
### Have you searched the existing bug reports?

No

### What happened?

When I was watching the macro 1 time I noticed that I died in coconut and I didn’t put anything for collect besides wealth clock and I put gather on pepper and 1 second before I saw my avatar when going back to the hive land on the on green spot from pepper to coconut and so my only conclusion is that it died to coconut crab when accidentally going in coconut field

### Steps to reproduce

1.checked speed it was correct
2.
3.

### What would you expect to happen?

I expected to not land in coconut filed

### Natro Macro version

9.9.2

**Comment by paper555555555555555555555555555** [comment]
Well it was old so maybe it was fixed because I never ran in coconut again but just asking

**Comment by misc-et** [comment]
It's hard to say from this information, but it sounds like it may have been an isolated incident, perhaps relating to a lag spike during travel. I'll go ahead and close this, and you're welcome to join our discord server if you'd like more information and support.
