### ISSUE TITLE
macro can't receive blueberry and glue

### ISSUE THREAD

**Issue by xiaoniangaoh** [NatroTeam/NatroMacro#340]
### Have you searched the existing bug reports?

Yes

### What happened?

Macro will be blocked by a sign when picking up blueberries, so he will not be able to reach them
Macro was unable to reach the glue because the distance was not right

### Steps to reproduce

There will be a bug in the route after firing the red cannon

### What would you expect to happen?

Pick up glue and blueberries

### Natro Macro version

0.9.9.3

### What is your Discord username?

xiaoniangaoh_24982

**Comment by misc-et** [comment]
These issues are most likely to be related to your settings and/or lag. Please feel free to join our discord server where you can find more information on troubleshooting, and raise a support ticket for help.
