### ISSUE TITLE
Drift comp not working

### ISSUE THREAD

**Issue by spinnysheep** [NatroTeam/NatroMacro#341]
### Have you searched the existing bug reports?

No

### What happened?

Drift comp wont work and my charachter will keep on drifting out of the field

### Steps to reproduce

1.macro in any field 
2.
3.

### What would you expect to happen?

after some time it will drift off th field

### Natro Macro version

0.9.9 and 0.9.9.3

### What is your Discord username?

Lexui26

**Comment by misc-et** [comment]
This is likely to be an issue with your gather or other settings. Make sure your movespeed is set correctly, and try using the default gather settings that appear when you select a field name in the gather tab. If you have any further issues, please feel free to join our discord server for more information and support.
