### ISSUE TITLE
Bug "Unable to detect in-game GUI offset!" sometime it work sometime not. Game seting and Window setting are all right. When got buged press OK it work but delay so much

### ISSUE THREAD

**Issue by NemChua2310** [NatroTeam/NatroMacro#343]
### Have you searched the existing bug reports?

No

### What happened?

![10fc5749-d0b3-4c18-8a78-3024c9e53dbd](https://github.com/NatroTeam/NatroMacro/assets/161043657/02b7e6de-87b7-4d01-bef6-ad2296677d3f)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

Not saw that bug again

### Natro Macro version

v0.9.9.3

### What is your Discord username?

NemChua

**Comment by misc-et** [comment]
This isn't a bug, but a notification that one or more of your game/pc settings may not be configured correctly for the macro to work best. Please join our discord server for more information and support.
