### ISSUE TITLE
Festive Blessing for planters

### ISSUE THREAD

**Issue by LangtonsPants** [NatroTeam/NatroMacro#344]
### Have you searched the existing suggestions?

No

### What is your suggestion?

The feature will be similar to baby love options where on planters, you can enable it to wait for a festive bee to give gifts, then it collects festive blessing for insta conversion, and then it collects all the pollen from the planter.

### How will this improve Natro Macro?

It will increase honey production for people with planters that give more pollen than their backpack can hold.

### What is your Discord username?

LangtonsAnt

**Comment by Noobyguy775** [comment]
The extra pollen from planters is instantly converted to honey, so it shouldn't matter (besides backpack space, which already has an option, although only in planters+)

**Comment by misc-et** [comment]
Thanks for this suggestion. As Nooby says, the extra pollen that doesn't fit into your backpack is already instantly converted into honey, so an extra option for this shouldn't be needed. I'll go ahead and close this issue.
