### ISSUE TITLE
Integrating Natro Controller

### ISSUE THREAD

**Issue by iSimpp** [NatroTeam/NatroMacro#345]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

**There are already Natro Macro controllers**, __but they aren't official__. What I'm asking is to **implement a controller when you install Natro Macro**. It shouldn't that that much time, as it's just forking a repo and adding it to GitHub and the batch file that opens Natro Macro. Thanks for reading.

### How will this improve Natro Macro?

Instead of searching for one, it will already be implemented. There aren't any downsides, and it's not hard to implement.  There won't be users complaining about it being added, and I can't think of any reason to not add it.

### What is your Discord username?

isymbol

**Comment by misc-et** [comment]
Can you clarify what you mean by controller? If you mean the ability to communicate with and control the macro remotely, this feature is already included in the macro (Remote Control). You can find more information on this feature and how to use it in our Discord server.

**Comment by iSimpp** [comment]
Oh, sorry! Didn't see it
