### ISSUE TITLE
Specific server hop for vicous/ or manual reconect time settings

### ISSUE THREAD

**Issue by jarode10** [NatroTeam/NatroMacro#347]
### Have you searched the existing suggestions?

No

### What is your suggestion?

for vicous kills just add a server hop night time detecting file or smth. And for the manual reconect timer just let people write the time they want to reconect.

### How will this improve Natro Macro?

it ill make natro macro more flexible and lucrativ for getting lot more stingers then yet

### What is your Discord username?

jarode10

**Comment by misc-et** [comment]
Thanks for your suggestions. Vicious bee server hop is on the suggestion list (see https://github.com/NatroTeam/NatroMacro/issues/12). 

Can you clarify what you mean by writing the time you want to reconnect? As this can already be achieved in the current macro by selecting frequency and inputting time of day.

**Comment by jarode10** [comment]
> Thanks for your suggestions. Vicious bee server hop is on the suggestion list (see #12).
> 
> Can you clarify what you mean by writing the time you want to reconnect? As this can already be achieved in the current macro by selecting frequency and inputting time of day.

Yes my point is to be abl to put in minuts aswell not only the hours 1,2,3,4,6,8,12 and 24 so u can reconect like every half hour or 10 minuts

**Comment by zspz** [comment]
I don't see a benefit of reconnecting more often than 1 hour.
You are also not guaranteed to join a different server (in general, you join the same one), so this wouldn't work for hopping.
