### ISSUE TITLE
SSA roler

### ISSUE THREAD

**Issue by Eternal5623** [NatroTeam/NatroMacro#348]
### Have you searched the existing suggestions?

No

### What is your suggestion?

The title is kinda self-explanatory. Basically there are options on what you want on the ssa. and you pick like gummy-saw and then it rolls until it gets gummy-saw. I would like this feature because most of the time its pretty boring just waiting and keeping focus trying to get a good double passive with good stats. Me myself a white hive trying to get a good ssa after a boost is boring because of how rare it is to get an 5/5 amulet, and i sometimes even skip good amulets  by accident.

### How will this improve Natro Macro?

I want this feature because it can benefit of times usage and makes it easier to roll ssa. And it can help many like when it comes to using hundreds of trillions on ssa. Especially people like Mikey/FragileSilence to get better amulets with their massive amounts of honey. But in general a level 18 blue hive that got a 4/5 ssa could really get use of the feature so he can just make it roll until a 5/5 amulet. 

### What is your Discord username?

eternal_dpx

**Comment by zspz** [comment]
There are already macros that can do this, see https://birblit.club/
We have no plans currently to add this to Natro Macro, which serves as a general all-purpose macro.
