### ISSUE TITLE
Add a way to DISABLE reconnects completely.

### ISSUE THREAD

**Issue by Ohheffgee** [NatroTeam/NatroMacro#349]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

It's pretty self explanatory, but, in other words, add a way to somehow disable reconnects/rejoins from the macro.

### How will this improve Natro Macro?

This is aimed to benefit people with lower-end devices, as most of the time when you are reconnected, the rejoin will (most of the time) put you in a server with pro players, which will slow down the game, making the macro be inaccurate, and mostly put you in a reconnection loop, which is very unfavorable for honeymaking. Adding this would fix this by removing the reconnection altogether.

### What is your Discord username?

@conxetumadre

**Comment by zspz** [comment]
Reconnects outside of the Daily Reconnect option in Settings tab only happen when absolutely necessary.
If reconnects are removed, the macro will do *nothing* after being disconnected.
I think what it does currently is more favourable for honeymaking than doing absolutely nothing.
