### ISSUE TITLE
Reset bug (???)

### ISSUE THREAD

**Issue by FortyTwo69** [NatroTeam/NatroMacro#35]
### Have you searched the existing bug reports?

No

### What happened?

So my macro always collects the wealth clock and then goes to the field, it gathers for like 30 seconds and then it makes me reset and it happens over and over non stop forever. Any idea on how to fix this? 

### Steps to reproduce

1.I go to field.
2.I gather 30 seconds.
3.Macro make me reset over and over.

### What would you expect to happen?

Please help

### Natro Macro version

v0.9.6

### What is your Discord username?

forty_twoo

**Comment by Noobyguy775** [comment]
https://github.com/NatroTeam/NatroMacro/releases/latest
