### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Ch3ckMat** [NatroTeam/NatroMacro#350]
### Have you searched the existing suggestions?

No

### What is your suggestion?

You could add something for poor people like me who don't get the supreme saturator. It would seek one in the field ur macroing in and if there is one u stay if there is no supreme saturator u will hop server.

### How will this improve Natro Macro?

It could help noob like me .

### What is your Discord username?

.checkmat

**Comment by zspz** [comment]
I don't think this would provide a substantial benefit, and "server hopping" is also not viable without third party tools.
