### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Dirpguy** [NatroTeam/NatroMacro#353]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I think natro could have save slots for EVERYTHING. Im not saying a lot, just 2 or 3 slots, but it would take all your slots and put them in a save slot. Then you could make a new set of patterns for maybe an alt, then with a push o a button, you can switch to your main's pattern.  This would be nice for tad alts.

### How will this improve Natro Macro?

It would be nice to have for alt accounts. also if someone wanted to macro one field, but wanted to have a backup, they could easily switch from one set of settings to another, to maybe switch fields or boost patterns.

### What is your Discord username?

.acorn_

**Comment by zspz** [comment]
#77
