### ISSUE TITLE
reset bug

### ISSUE THREAD

**Issue by r32hbh3ur3** [NatroTeam/NatroMacro#354]
### Have you searched the existing bug reports?

No

### What happened?

hello if i activate my macro it keeps resetting me

### Steps to reproduce

1.i reset everytime
2.same
3.same

### What would you expect to happen?

thet i dont be resetting everytime

### Natro Macro version

v0.9.9.3.zip

### What is your Discord username?

gdfrg_09439

**Comment by zspz** [comment]
This is not a bug, join our Discord for support.
