### ISSUE TITLE
pepper patch macro

### ISSUE THREAD

**Issue by pindakaas9002** [NatroTeam/NatroMacro#355]
### Have you searched the existing bug reports?

No

### What happened?

i wanted to afk on pepper but it walked just past the 35 bee gate and then it started jumping to place sprinklers and then is starts walking the patterns i chose without being een close to the field

### Steps to reproduce

1.open natro macro
2.select pepper field
3.start the macro

### What would you expect to happen?

the same thing that happens to me every time

read the what happend thng

### Natro Macro version

the newest

**Comment by zspz** [comment]
This is not a bug, join our Discord server for support
