### ISSUE TITLE
Natro Macro indefinity resets my character when monitor is on a high refresh rate

### ISSUE THREAD

**Issue by NotThePancake101** [NatroTeam/NatroMacro#356]
### Have you searched the existing bug reports?

Yes

### What happened?

I've been trying to get my macro to work for weeks after getting a new monitor for my computer. Today, I just discovered that if i changed the refresh rate down to my monitor's lowest (59.95 Hz) my macro works.

### Steps to reproduce

Step 1: make my refresh rate 155.01 Hz (max refresh rate)
To fix: put refresh rate at 59.95 Hz

### What would you expect to happen?

I expected that my monitor was too big for Natro Macro so after getting all the settings right it still didn't work. So, I had the smart idea to change the refresh rate and then Boom! it works!

### Natro Macro version

The newest

**Comment by zspz** [comment]
Refresh rate doesn't affect this, it's possible that these issues are caused by some other graphics settings that are changed when altering your refresh rate.
Join our Discord server for support.
