### ISSUE TITLE
Skip current task

### ISSUE THREAD

**Issue by IanVilj** [NatroTeam/NatroMacro#357]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

You can add a button like F6 to skip the current task, this could be useful if you see that if you are grinding a quest. Ie: your character is grinding blue flower for X goo pollen but your character isn't putting down any gumdrops, you can press F6 to skip this. Idk I thought this could be useful

### How will this improve Natro Macro?

It will reduce wasted time macroing. And more accessibility.

### What is your Discord username?

ian_rocket

**Comment by xdjoee** [comment]
ive also wanted something like this

**Comment by Bocon778** [comment]
This is close to impossible to add to be honest.
