### ISSUE TITLE
Reset Character

### ISSUE THREAD

**Issue by PELONXD** [NatroTeam/NatroMacro#36]
### Have you searched the existing bug reports?

No

### What happened?

So my macro goes to the field, builds up for about 30 seconds and then makes me restart and it happens over and over again nonstop forever. Any idea how to fix this? it also says in webhook (idle honey)

### Steps to reproduce

1.I go to field.
2.I gather 30 seconds.
3.Macro make me reset over and over.

### What would you expect to happen?

let it be solved please

### Natro Macro version

v0.9.6

### What is your Discord username?

matiasbrotm

**Comment by Noobyguy775** [comment]
#35
https://github.com/NatroTeam/NatroMacro/releases/latest
