### ISSUE TITLE
i keep resetting my character?

### ISSUE THREAD

**Issue by Eitanionlol** [NatroTeam/NatroMacro#361]
### Have you searched the existing bug reports?

No

### What happened?

when i start the macro it keeps resetting

### Steps to reproduce

1. i
2. dont
3. know what to write here

### What would you expect to happen?

for my macro to work

### Natro Macro version

0,9,9,3

### What is your Discord username?

eitan.levi

**Comment by misc-et** [comment]
This is likely not a bug, but related to settings. You can join our Discord for more information and support.
