### ISSUE TITLE
Add option to collect in field with guiding star.

### ISSUE THREAD

**Issue by HogRider000** [NatroTeam/NatroMacro#364]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an option for macro to collect in field with guiding star.

### How will this improve Natro Macro?

This would help hives that use guiding star an INSANE amount.

### What is your Discord username?

thechickenstrip

**Comment by wikiepeidia** [comment]
tbh i don't think this is good because guiding targets your worse fields and they aren't worth it. 
like blue it targets mushroom field and who even like it
