### ISSUE TITLE
Vic Server Hop

### ISSUE THREAD

**Issue by Redlgn** [NatroTeam/NatroMacro#365]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Just a specific setting that allows the macro to continuously server hop until night time and search for vicious bee, repeatedly.  You can set the amount of time it does this, and the fields it searches in. After the set time, it would go back to macroing normally as it should. Would definitely help as a red hive or a white hive.

### How will this improve Natro Macro?

It would be incredibly beneficial to red and white hives who are in constant need of stingers, including myself!

### What is your Discord username?

redlgn

**Comment by zspz** [comment]
#12
