### ISSUE TITLE
Rejoin problem

### ISSUE THREAD

**Issue by BSSPLAYAYER** [NatroTeam/NatroMacro#366]
### Have you searched the existing suggestions?

No

### What is your suggestion?

You should fix the rejoin claiming hive thing like if i put hive 5 and it reconects don't search a server until it finds a hive slot 5 free it need to pick any hive and automaticly set

### How will this improve Natro Macro?

not that many rejoin atempts which saves macroing time

### What is your Discord username?

mexicanoalero

**Comment by zspz** [comment]
It already does this. If it doesn't work for you, then you have an issue with one of your settings (e.g. Movement Speed, graphics).
Join our Discord server for support.
