### ISSUE TITLE
Stump Snail

### ISSUE THREAD

**Issue by beeswarmbosskid** [NatroTeam/NatroMacro#368]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Make a feature that stops killing Stump Snail when it reaches a certain Hp percentage that way you get be active for the kill an see the loot/amulet

### How will this improve Natro Macro?

it will improve QOL feature

### What is your Discord username?

beeswarmbosskid

**Comment by Bocon778** [comment]
Smart!

**Comment by Winstondbeast** [comment]
They have added this feature. Not sure if this feature existed 3 weeks ago….

**Comment by Noobyguy775** [comment]
> They have added this feature. Not sure if this feature existed 3 weeks ago….

There's an option to set the snail's (current) HP, but it will keep returning to the snail until it is killed.

**Comment by Noobyguy775** [comment]
merging with #502
