### ISSUE TITLE
Please ignore this, my classmates are dumbasses

### ISSUE THREAD

**Issue by ghost** [NatroTeam/NatroMacro#369]
### Have you searched the existing bug reports?

No

### What happened?

i say giga you say nigga
GIGA GIGA.....

### Steps to reproduce

1. YOU SAY IT
2.
3.

### What would you expect to happen?

YOU SAY IT N WORD

### Natro Macro version

NEGRO

### What is your Discord username?

necapro35

**Comment by Neca2-retard** [comment]
urgent needs
