### ISSUE TITLE
natro macro

### ISSUE THREAD

**Issue by ABF23415** [NatroTeam/NatroMacro#370]
### Have you searched the existing bug reports?

No

### What happened?

whenever my screen closes the natro macro lag out the game it like reset when i open the natro macro then my screen closes and the natro macro lag me out the game and it happened to me and it crashed me out and i have video of it happening i closed my screen and it lagged me out  whille resetting me  i hope you fix the problem because it is a problem from the natro macro

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i thought that it will keep doing macro while my screen closed and i go to sleep

### Natro Macro version

the old one because the new one isnt working good

### What is your Discord username?

ABF#8384

**Comment by Noobyguy775** [comment]
Go to the discord for support. https://discord.gg/natromacro
