### ISSUE TITLE
Reconnect doesnt work when montior is off.

### ISSUE THREAD

**Issue by bruh213123** [NatroTeam/NatroMacro#371]
### Have you searched the existing bug reports?

Yes

### What happened?

Some nights when I keep my monitor off my macro disconnects. Then joins back onto Roblox correctly. But right after it doesn't walk to the hive and says, Error: No BSS Found, on the webhook. Also I'm using display port as my monitor port so that could be a reason too. BTW I am using the correct Roblox and display settings.

### Steps to reproduce

1. Open macro.
2. Pick any field and start macro.
3. Turn off your monitor and wait for disconnect.

### What would you expect to happen?

I expected for the macro to work and reconnect and claim a hive and continue to collect.

### Natro Macro version

v0.9.9.3

### What is your Discord username?

pleasework#2281

**Comment by Noobyguy775** [comment]
It's not something we can control, you just have to leave on or find a work around.
A work-around is RDP, you can find a guide for it on the [discord](https://discord.gg/natromacro).
