### ISSUE TITLE
Clicked join with Microsoft Roblox instead of Roblox Game Client and now I can't switch back.

### ISSUE THREAD

**Issue by derekShark** [NatroTeam/NatroMacro#372]
### Have you searched the existing bug reports?

No

### What happened?

Clicked join with Microsoft Roblox instead of Roblox Game Client and now I can't switch back.

### Steps to reproduce

1. Join with Deeplink
2. Natro asks if you want to join with Roblox or Roblox Game Client
3. Pick Roblox
4. Suffer because it's the wrong one and you can't switch back

### What would you expect to happen?

You will be stuck with joining the wrong way and Natro won't work properly.

### Natro Macro version

v0.9.9.3

**Comment by Bocon778** [comment]
You will just need to change this in windows settings, join discord.gg/natromacro for more information.
