### ISSUE TITLE
Failing to Detect BSS Screenshot

### ISSUE THREAD

**Issue by happyhabba** [NatroTeam/NatroMacro#375]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Right now I am out and can see from the webhook that natro is opening roblox however failing to find BSS. 

> Detected: Roblox Open
> Error: No BSS Found
> Attempting: Public Server

I am aware this is most likely happening due to something else appearing over the top of Roblox, however I cannot see what it is. Therefore, I think it could be useful if Natro would send a screenshot of my screen over the webhook so that I could find what the issue was and remedie it, or ask someone else nearby my household to fix it whilst I am away.

_Apologies if this is already a setting, but at the time of suggesting I am away and therefore cannot check Natro._

### How will this improve Natro Macro?

This would benefit Natro users such as myself, so that we can discover what is causing issues for the script, and fix said issues to prevent them from happening again. As previously mentioned, it could also help to give guidance to others nearer the gadgets as to the steps to fix it for us. I think this would be a minor update which could massively help a lot of users.

### What is your Discord username?

@happyhabba

**Comment by Noobyguy775** [comment]
Turn on the "Critical Events" Screenshots in the discord integration settings
