### ISSUE TITLE
macro broken?

### ISSUE THREAD

**Issue by pindakaas9002** [NatroTeam/NatroMacro#381]
### Have you searched the existing bug reports?

No

### What happened?

it doesnt matter wich field i select it always goes to strawberry field idk if its just me or a bug

### Steps to reproduce

1.select field
2.turn macro on
3.

### What would you expect to happen?

it works or not idk but for me it goes to strawberry each time

### Natro Macro version

the newest

### What is your Discord username?

pindakaas09

**Comment by Noobyguy775** [comment]
Join the discord for support
