### ISSUE TITLE
huge vulnerability

### ISSUE THREAD

**Issue by Necapro35** [NatroTeam/NatroMacro#382]
### Have you searched the existing bug reports?

No

### What happened?

Hey, I found a huge huge bug that needs to be fixed ASAP. Please contact me on Discord I'll tell you about it

### Steps to reproduce

Add me on discord i can't explain here please

### What would you expect to happen?

///

### Natro Macro version

0.9.9.3

### What is your Discord username?

@NecaPRO35 (URGENT)

**Comment by HamzaWakkas** [comment]
Did you dm an admin
