### ISSUE TITLE
Add a planter option to go for the lowest 3 nectars you have.

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#383]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

This feature would be a button that overrides the "nectar priority" section in the Planters tab.
The button would be labeled something like "nectar dispersion" and it would:
Try to spread out the nectars you collect as much as possible, it wouldn't focus on your priority list so much as it would see the time left on the nectars you have and the ones absent, and collect for those nectars.

### How will this improve Natro Macro?

I would love this feature because currently as a blue hive with my Invigorating nectar as the last one in the priority list it sucks that I never have the extra 5% honey gotten from a full Invigorating nectar bonus included with the other four nectars in the game.

### What is your Discord username?

ZackAttack4987

**Comment by Bocon778** [comment]
This is already possible in planters plus.
