### ISSUE TITLE
resets character when it does not need to

### ISSUE THREAD

**Issue by Aguythatusesgithub** [NatroTeam/NatroMacro#384]
### Have you searched the existing bug reports?

No

### What happened?

While coming back from  Strawberry field to convert backpack to honey, the character gets stuck and resets character.

### Steps to reproduce

1. go to strawberry
2. fill up backpack
3. reset character

### What would you expect to happen?

the character to go to hive and convert

### Natro Macro version

0.9.9.3

**Comment by NecaGigaChadSkibidiOhioRizz** [comment]
please respond giga...

**Comment by Noobyguy775** [comment]
Join the discord for support.
