### ISSUE TITLE
Hive building

### ISSUE THREAD

**Issue by jkl071812** [NatroTeam/NatroMacro#385]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add a feature where you can make a hive composition while being afk 

### How will this improve Natro Macro?

I want this feature because it is really annoying and hard for me and it will help others thats experiencing the same thing as me

### What is your Discord username?

jkl1948

**Comment by NecaGigaChadSkibidiOhioRizz** [comment]
please respond giga...
