### ISSUE TITLE
Reconnect The macro cannot find BSS 

### ISSUE THREAD

**Issue by k1wy** [NatroTeam/NatroMacro#387]
### Have you searched the existing bug reports?

No

### What happened?

After several hours of farming, a crash occurs, but this is normal, it is not normal that after the crash, the macro cannot log back into the server

### Steps to reproduce

1.Crash
2.bss dont work
3.end

### What would you expect to happen?

idk
![image](https://github.com/NatroTeam/NatroMacro/assets/164008826/b9c94e8c-f065-432f-b308-d76da9a72e55)
![image](https://github.com/NatroTeam/NatroMacro/assets/164008826/77b9cb86-d6d3-4531-8b9a-803414c5858a)
![image](https://github.com/NatroTeam/NatroMacro/assets/164008826/5201da03-ec76-4ce4-a193-4ba0136e6a0d)
![image](https://github.com/NatroTeam/NatroMacro/assets/164008826/ea388783-69a9-483a-8b66-5b83fc7220b6)

pls help me

### Natro Macro version

9.9.3

### What is your Discord username?

k1wy.

**Comment by Noobyguy775** [comment]
Join the discord for support.
