### ISSUE TITLE
Add more NPC to the quest bar, please

### ISSUE THREAD

**Issue by Bilaluyar123** [NatroTeam/NatroMacro#388]
### Have you searched the existing suggestions?

No

### What is your suggestion?

So Add the Spirit bear please

### How will this improve Natro Macro?

It will help players that cant have time to do the spirit bear questline so it will be usefull

### What is your Discord username?

Jiraya69420

**Comment by Bocon778** [comment]
The macro is not meant to play and complete the whole entire game for you.
