### ISSUE TITLE
Add the things Natro is known not to do

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#389]
### Have you searched the existing suggestions?

No

### What is your suggestion?

- Add non-repeatable quests
- If you have a boss's amulet on the screen for k/r don't do something that will overwrite it (ex: you beat Stump Snail and haven't told the macro to k/r then it does Ant Challenge and the Ant Amulet shows over the Shell Amulet)
- Do the memory matches
- Add gathering in the Hub Field (Does more quests, drops every favorite treat type, etc.)
- Have an option to farm in fields shown on any quest that aren't completed (I would LOVE this)
- Have a kill option for Stickbug and Windy Bee
- Have an option to do meteor showers and recycle the tracking of meteors on falling coconuts

### How will this improve Natro Macro?

Well, Natro is meant to be the macro that "does it all", according to everyone that talks about it, and if that's even if that's not the case, it's what it's known for.
And besides, 
- The non-repeatable quests would be useful for people who are scared to change their macro settings and/or are early-to-mid-game,
- The boss amulet override one would be lovely for those who are trying to farm amulets,
- Memory matches are known to have GREAT rewards, but I never do them because I forget they exist,
- Hive Hub has all the Sticker Stack quests but it also drops every bee's favorite treats,
- Killing Stickbug/Windy-Bee allows you to farm the amulets passively like we do with Stump Snail, and we already somewhat do this with Vicious Bee, though these one's change fields as they are killed, however with Stickbug it shows what field it's at, so only Windy Bee gets a pass here,
- And Meteor Showers are SO useful, and if you implemented a way to track the circles then you could recycle that on coconuts too, yours and the Coconut Crabs!
All these reasons show what Natro is noticeably missing, and why they would be useful, Natro is and continues to be the best macro though, so even if it didn't have these I'd still use it. :)

### What is your Discord username?

ZackAttack4987

**Comment by Bocon778** [comment]
The macro is not meant to play the whole entire game for you.
