### ISSUE TITLE
if quest is completed

### ISSUE THREAD

**Issue by theproateverything1** [NatroTeam/NatroMacro#390]
### Have you searched the existing suggestions?

No

### What is your suggestion?

in my game after i do my bucko bee quests i reset if i have this feature enabled. and im asking you to make a option to not do the quests but if the quest is completed then it will turn it in/accept a new quest i think this is a great feature

### How will this improve Natro Macro?

better time management and losing out on honey

### What is your Discord username?

coolmonkey0602

**Comment by Noobyguy775** [comment]
Do you want it to not work on the quests and only hand them in if they are completed or do you want to not reset after collecting for a quest?
