### ISSUE TITLE
Have the macro zoom out when gathering

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#391]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

The macro would zoom out the camera as much as it can while gathering, especially if the gathering setting "Drift Comp" is selected to be on.

### How will this improve Natro Macro?

This feature would do two things,
1. Allow the player to help the macro as it gathers and adjust it as needed,
2. Give the macro more area to spot the Supreme Saturator as it has a tendency to be _just_ out of viewing range leading to drift.

This would help in fields such as but not limited to: Stump, Bamboo, and Mountain Top, as I've noticed this happening in these fields. I use the recommended "best" field pattern settings available in the discord and it still happens, but when I zoom out the camera for the macro, it causes no issues and improves gathering performance.

### What is your Discord username?

ZackAttack4987

**Comment by Bocon778** [comment]
This is already possible with custom patterns.
