### ISSUE TITLE
Does not show profit per hour

### ISSUE THREAD

**Issue by blin322** [NatroTeam/NatroMacro#392]
### Have you searched the existing bug reports?

No

### What happened?

When farm, shows backpack stats, but honey not.
Tried to re-install NatroMacro, it didn't help.
![file](https://github.com/NatroTeam/NatroMacro/assets/91912552/0e70f4a8-d86e-4b86-8e71-5a5d0b94df89)

### Steps to reproduce

1.Just turn on natro Macro

### What would you expect to happen?

It's always been like this

### Natro Macro version

v0.9.9.3

### What is your Discord username?

@blin4ik322

**Comment by Bocon778** [comment]
The honey is probably being covered, join discord.gg/natromacro for steps to solve the issue.
