### ISSUE TITLE
Memory match glitch

### ISSUE THREAD

**Issue by menoobatbeeswarmsim** [NatroTeam/NatroMacro#395]
### Have you searched the existing bug reports?

Yes

### What happened?

In the new update, if you use the memory match and it just matched a pair, when it flips over the next card, if it is one that was just matched, it chooses it. Then it just sits there. It is waiting for them to flip back over, but it has only flipped one. I think it just needs to check for newly flipped matches and knows not to choose them.

### Steps to reproduce

1.choose a memory match and just run it
2.rng carries the rest
3.

### What would you expect to happen?

it will choose a random item and if it has the right conditions, it freezes and waits forever.

### Natro Macro version

1.0.0

### What is your Discord username?

menoobatbeeswarmsim

**Comment by Noksispacking** [comment]
this happens to me its not a infinite wait its just a really long wait cause whoever made the MM function was not cooking we need SP back 😭

**Comment by Noobyguy775** [comment]
merged with #501
