### ISSUE TITLE
Hive claim syntax issue

### ISSUE THREAD

**Issue by Noksispacking** [NatroTeam/NatroMacro#396]
### Have you searched the existing bug reports?

Yes

### What happened?

When rejoining server theres a syntax issue with claiming hive
the 28*tiles is the movespeed 
![image_2024-03-26_033559316](https://github.com/NatroTeam/NatroMacro/assets/147272387/fb39928a-47ae-4f50-9134-1314348d6aee)

### Steps to reproduce

1.disconnected from a server 
2.Use natro macro to rejoin
3.On rejoin tries to claim hive 

### What would you expect to happen?

No syntax issues 

### Natro Macro version

v1

**Comment by Noksispacking** [comment]
I also just found it this happens when movement speed correction is turned off for some reason 
it works if i turn it on

**Comment by ninjubaer** [comment]
Hi @Noksispacking 
Thank you for reaching out to us!
You are totally right, this is a bug that is currently in the v1.0.0 of natro macro
Please wait for the fix that should release soon

**Comment by Noobyguy775** [comment]
fixed in v1.0.0.1

**Comment by Noksispacking** [comment]
Hi @ninjubaer ur so bad
