### ISSUE TITLE
AFB and memory match interpret each other 

### ISSUE THREAD

**Issue by HamzaWakkas** [NatroTeam/NatroMacro#397]
### Have you searched the existing bug reports?

No

### What happened?

If you enable gather interrupt for memory while auto field boost is enabled the two actions will repeatedly cancel each other out leading to a loop 

### Steps to reproduce

1. Enable auto field boost
2. Enable gather interrupt for memory match 
3. Run the macro and wait 

### What would you expect to happen?

Do memory match then continue to farm in boosted field

### Natro Macro version

1.0.0

### What is your Discord username?

catsfx

**Comment by Noobyguy775** [comment]
merged with #501
