### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MelodyHeart1** [NatroTeam/NatroMacro#399]
### Have you searched the existing bug reports?

No

### What happened?

![image](https://github.com/NatroTeam/NatroMacro/assets/165133762/0d765e0e-3fd1-4b5f-a162-336910cd99c5)
When entering location 35, the character simply jumps but does not bounce off the wall
This bug has been present for a long time, my macro has never gotten there
I understand that this is most likely some kind of problem for me, since it would have been solved a long time ago, but I still hope for an answer or advice (The speed is set with precision)

### Steps to reproduce

1.The character jumps without falling
2.And repeats this 3 times
3.

### What would you expect to happen?

Bounce off the wall to get to location 35

### Natro Macro version

1.0.0

### What is your Discord username?

songen.

**Comment by DullSmallmega176** [comment]
if you are in the discord server alr, there is a whole troubleshooting guide alr 
https://discord.com/channels/1012610056921038868/1175954578605346947/1176010170703282236
this is more of jump boost, avatar scaling and other stuff to take in to be able and climb the gap![image](https://github.com/NatroTeam/NatroMacro/assets/133727755/2fb4fac5-6375-438c-baf1-107bd26a9a99)
