### ISSUE TITLE
beesmas active determined by files on github

### ISSUE THREAD

**Issue by Noobyguy775** [NatroTeam/NatroMacro#4]
### Is there an existing suggestion that is already proposing this?

- [X] I have searched the existing suggestions

### What is your suggestion?

Basically, instead of having to update BeesmasActive every time beesmas comes around, (which requires an update), we could have file on github to say if it is or not (similar to the new contributors system)

that being said, it would still be able to be overidden by updates after we are ready to realease the next version

the downside to this is that you would need internet connection but you need internet connection to use roblox so I don't think its a problem

### How will this improve Natro Macro?

it would be easier for the devs 😭 and natro wouldnt need to update for beesmas

### What is your Discord username?

noobyguy

**Comment by zspz** [comment]
great idea, this will be added in the next version
what I can do is:
- if the user does not have an internet connection or the value could not be fetched, show a warning symbol next to the beesmas items
- when clicking the symbol the user is prompted to try again, or maybe even manually select that beesmas is active

**Comment by zspz** [comment]
thanks for the suggestion! this feature has been added in the dev repo and is ready for release with the next update
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/80265621-fd8f-477f-83d1-c0dbaec5e46c)
https://github.com/NatroTeam/.github/blob/main/profile/data/beesmas.txt
