### ISSUE TITLE
v3xdf

### ISSUE THREAD

**Issue by v3xdf** [NatroTeam/NatroMacro#400]
### Have you searched the existing bug reports?

No

### What happened?

my macro doesnt work it kep reseting

### Steps to reproduce

1.i dont know

2.can you help me reduce it
3.
pls

### What would you expect to happen?

im asking you to help me

### Natro Macro version

1.0.0

### What is your Discord username?

b_z9

**Comment by DullSmallmega176** [comment]
there is a whole discord server for troubleshooting the macro, care to join :) discord.gg/natromacro
