### ISSUE TITLE
Find Item RC Command

### ISSUE THREAD

**Issue by remizuwu** [NatroTeam/NatroMacro#401]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

While this already exists in the form of Dully's code it requires a lot of setup.
My idea is to clean up the code and fix some of the issues and officially add it to the command list in a future update.

### How will this improve Natro Macro?

While not something major, I believe it would be a helpful addition to the RC command list. To be able to see how many of a certain item you have when you aren't home, or any other circumstances where you cant access your device would overall just be helpful whether it be to track a material used for crafting or maybe how many glitter you have left to use.

### What is your Discord username?

Remizu

**Comment by ninjubaer** [comment]
this is one for @DullSmallmega176 😄

**Comment by DullSmallmega176** [comment]
i have a working version on this suggestion alr, i just need to code it to ahk v2.0, also change all the bitmaps for it 🥲
