### ISSUE TITLE
talk to bears

### ISSUE THREAD

**Issue by notnicknamed** [NatroTeam/NatroMacro#403]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I would like a feature where the macro can go to the various shopkeepers and interact with them to keep them company. It will not equip anything, I just wish for it to quickly interact. It will however gradually buy items that you do not currently have to demonstrate your respect and to show appreciation.

### How will this improve Natro Macro?

Talking to the bears will guarantee a closer relationship and thus cheaper prices and more honey.

### What is your Discord username?

beezes

**Comment by xdjoee** [comment]
same
