### ISSUE TITLE
Bss Macro Error need help

### ISSUE THREAD

**Issue by Buzzer1237** [NatroTeam/NatroMacro#404]
### Have you searched the existing bug reports?

No

### What happened?

When I open up the macro, every time my character tries to move and error pops up Error: Missing ")" before "}" HyperSleep(4000/26*tiles Send "{" MoveKey1 " up}" (MoveKey2 ? "{" MoveKey2 " up}... My macro sends this pop up error every time it tries to move and I don't know how to fix it. 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

to have an answer on how to fix this 

### Natro Macro version

1.0.0

**Comment by Noobyguy775** [comment]
Update to the latest version.
