### ISSUE TITLE
natro macro is sooo broken because my charackter is going to mushroom field and i type pine tree

### ISSUE THREAD

**Issue by Clownlaughingatyou999** [NatroTeam/NatroMacro#407]
### Have you searched the existing bug reports?

No

### What happened?

it is brokennnnn

### Steps to reproduce

1.broken
2.weird
3.complicated

### What would you expect to happen?

is broken

### Natro Macro version

1.00

### What is your Discord username?

Lucio101

**Comment by Noobyguy775** [comment]
join the discord, https://discord.gg/natromacro
