### ISSUE TITLE
Natro macro camera is looking in to the sky and drifting out

### ISSUE THREAD

**Issue by MrDragon076** [NatroTeam/NatroMacro#409]
### Have you searched the existing bug reports?

No

### What happened?

When I start macroing and when I get in to the field, macro starts looking in to the sky and after a few seconds, when I get my haste, I start drifting out of the field. It also don't let me to move the camera to look forward. I have enabled the Drift Comp and it don't help.

### Steps to reproduce

1. I started macro
2. It went to the field
3. It placed a sprinkler
4. It started to look up

### What would you expect to happen?

It had to look ahead, not in to the sky.

### Natro Macro version

1.0.0

### What is your Discord username?

misterdragon076

**Comment by vimert3** [comment]
> ### Have you searched the existing bug reports?
> No
> 
> ### What happened?
> When I start macroing and when I get in to the field, macro starts looking in to the sky and after a few seconds, when I get my haste, I start drifting out of the field. It also don't let me to move the camera to look forward. I have enabled the Drift Comp and it don't help.
> 
> ### Steps to reproduce
> 1. I started macro
> 2. It went to the field
> 3. It placed a sprinkler
> 4. It started to look up
> 
> ### What would you expect to happen?
> It had to look ahead, not in to the sky.
> 
> ### Natro Macro version
> 1.0.0
> 
> ### What is your Discord username?
> misterdragon076

**Comment by ninjubaer** [comment]
Hello @MrDragon076 
Yes this is a bug that we are aware of and will be fixed in the near future
A temporary fix for this issue is to just disable shiftlock while gathering and enable it again when the fix is released.

**Comment by Noobyguy775** [comment]
Update to the latest version and it should be fixed.
