### ISSUE TITLE
please help me mz macro dont work i always keep resseting helpppp

### ISSUE THREAD

**Issue by wqard** [NatroTeam/NatroMacro#411]
### Have you searched the existing bug reports?

No

### What happened?

i just keep reseting 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

to fix it

### Natro Macro version

the newest

### What is your Discord username?

bestht2

**Comment by Brookgaming5137** [comment]
my macro not working it just keep resetting

**Comment by Noobyguy775** [comment]
Join the discord for macro support, https://discord.gg/natromacro
