### ISSUE TITLE
my macro not working it just keep resetting me help plssss

### ISSUE THREAD

**Issue by Brookgaming5137** [NatroTeam/NatroMacro#412]
### Have you searched the existing bug reports?

No

### What happened?

my macro keeps resetting me 

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i expected the macro to farm the pine tree feild for 60 minutes up to 95 percent of my pack then go and collect the pollen

### Natro Macro version

v1.0.0

### What is your Discord username?

blasterxXx

**Comment by Noobyguy775** [comment]
Go to the discord if you still need help. https://discord.gg/natromacro
