### ISSUE TITLE
Materials earned from macro list

### ISSUE THREAD

**Issue by NeuroZ1** [NatroTeam/NatroMacro#413]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I want this feature because, it would be a quality of llife update on materials earned from mondo chick, amount of stingers earned from vicious bee macro, and amount of all materials earned from the newly added memory match system, so i can see how many extracts, enzymes, oil, tickets I earned directly from macro, instead of having to keep track of materials in my inventory.

### How will this improve Natro Macro?

A quality of life update, so you can keep track of how many materials you earned by yourself, and how many come directly from macroing.

### What is your Discord username?

thedailyprotein

**Comment by ninjubaer** [comment]
hi @NeuroZ1 
Thank you for your suggestion!
I Really like the idea and I think we could implement this for the future although this would probably be limited to only "rare" items and maybe stringers from vicious bee.

**Comment by Noobyguy775** [comment]
merging with #232
