### ISSUE TITLE
my macro doesn't work

### ISSUE THREAD

**Issue by mirko2012** [NatroTeam/NatroMacro#414]
### Have you searched the existing bug reports?

Yes

### What happened?

it resets everytime my character

### Steps to reproduce

1.i press f1 and it says warning
2.my character resets
3.loop

### What would you expect to happen?

my character should've doing macro

### Natro Macro version

1.0.0

### What is your Discord username?

mirko2012

**Comment by Noblewarriorsf2** [comment]
Same thing happens with me, no warning tho

**Comment by ninjubaer** [comment]
Hello @mirko2012  
check out our [troubleshooting guide](https://discord.com/channels/1012610056921038868/1175954578605346947) on our [discord server](https://discord.gg/natromacro) and make sure your [graphics settings](https://discord.com/channels/1012610056921038868/1175946241801195521)
regards ninju
