### ISSUE TITLE
Nacro Macro Resetting Bug

### ISSUE THREAD

**Issue by Noblewarriorsf2** [NatroTeam/NatroMacro#415]
### Have you searched the existing bug reports?

Yes

### What happened?

I don't know why this is happening but for some reason whenever I launch and start nacro It keeps resetting me. Yes, I've checked my bee slot and movement speed. I've done evrything I've seen on the internet.

### Steps to reproduce

1.Launch Nacro
2.Plug in settings
3.Press start
4. keeps resetting

### What would you expect to happen?

For someone who has an idea how to fix this, come and help me.

### Natro Macro version

v1.0.0

### What is your Discord username?

otaku3747

**Comment by ninjubaer** [comment]
Hello @Noblewarriorsf2 
Go through our [troubleshooting guide](https://discord.com/channels/1012610056921038868/1175954578605346947) on our [discord server](https://discord.gg/natromacro) and to check your [graphic settings](https://discord.com/channels/1012610056921038868/1175946241801195521)
regards ninju, gumdrop gang
