### ISSUE TITLE
end game tool farmings

### ISSUE THREAD

**Issue by cheesybee** [NatroTeam/NatroMacro#417]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I think you guys should add a setting for farming waxes ,super smoothies, turpentine and etc. you can do this by making planters go in fields that have chances dropping those items and or making a puffshroom setting that collects and does puffshrooms.

### How will this improve Natro Macro?

it will help for grinding end game tools in time for a type of bss update and help players like me don't have endgame tools to help and also increase the honey rates . Thanks

### What is your Discord username?

@bigmarlin

**Comment by Alder7270** [comment]
as someone who is trying to get tide popper right now, this is the best idea I've ever heard

**Comment by ninjubaer** [comment]
Hello @cheesybee and @Alder7270 
You could try to use `manual planters` in the planter tab where you can say exactly where each planter should go.
You can also find assets like a guide that tells you what combinations can give you those waxes.
Sadly there is no guaranteed turpentine drop from any planter.

**Comment by Noobyguy775** [comment]
merging with #267
