### ISSUE TITLE
Kill Vicious Bee Not Working.

### ISSUE THREAD

**Issue by Someone890** [NatroTeam/NatroMacro#419]
### Have you searched the existing bug reports?

No

### What happened?

Hi, I been experiencing an issue with a feature that says  Kill Vicious bee in your macro, i turned it on and it didnt work. It didnt killed vicious bee at all, please fix this. Thanks!

### Steps to reproduce

1.1
2.2
3.3

### What would you expect to happen?

Hi, I been experiencing an issue with a feature that says  Kill Vicious bee in your macro, i turned it on and it didnt work. It didnt killed vicious bee at all, please fix this. Thanks!

### Natro Macro version

1.0

### What is your Discord username?

Xo#1815

**Comment by ninjubaer** [comment]
Hi @Someone890 
Make sure to check all your settings and to go through the troubleshooting guide on our [discord server](https://discord.gg/natromacro)
If that doesnt help me, ping me or any active helpers on discord
