### ISSUE TITLE
Sharonlees place

### ISSUE THREAD

**Issue by FailingPig** [NatroTeam/NatroMacro#421]
### Have you searched the existing bug reports?

No

### What happened?

I noticed in my recently played games, sharonlees place. I logged on after turning off my macro and saw that there were other people there, clearly using natro macro. They were walking in a straight line upon joining and resetting character after not spawning at their hive. They would repeat this until they eventually left the game and joined back on bss. I just wanted an explanation on why this happens please.

### Steps to reproduce

1. Launch Natro
2. Wait long enough and join sharonlees place
3. Witness mass legendary dog water pokemon occur

### What would you expect to happen?

I should have stayed in bee swarm and shouldn't have joined any other experience on roblox

### Natro Macro version

1.0.0

### What is your Discord username?

FailingPig

**Comment by Bocon778** [comment]
This is already a known issue. More info @ [DISCORD](https://discord.com/channels/1012610056921038868/1193977066320830515/1194066572403286036)

**Comment by Noobyguy775** [comment]
closed because this is a roblox issue and not our problem
