### ISSUE TITLE
resetting when it shouldn't

### ISSUE THREAD

**Issue by botman90k** [NatroTeam/NatroMacro#423]
### Have you searched the existing bug reports?

Yes

### What happened?

i was using natro macro v1.0.0.1, i set "to hive by" to walk because im still relatively early game, and it would get the needed pollen, then reset and lose all the pollen then repeat

### Steps to reproduce

1. open natro macro v1.0.0.1
2. set "to hive by to walk"
3. start macroing then wait

### What would you expect to happen?

character resets even though it is set to walk

### Natro Macro version

v1.0.0.1

### What is your Discord username?

osama zyn laden, unless you mean handle, then its 3rd_grade_dropout

**Comment by Noobyguy775** [comment]
Join the discord for support. https://discord.gg/natromacro
