### ISSUE TITLE
Coconut crab capacity

### ISSUE THREAD

**Issue by lordlevstar** [NatroTeam/NatroMacro#427]
### Have you searched the existing bug reports?

Yes

### What happened?

When natro fights coconut crab it collects pollen.  When the capacity eventually reaches the limit (95% as the default setting) it leaves coconut crab to convert at the hive.  This is a problem as it resets coconut crab's health, never allowing it to be defeated.

### Steps to reproduce

1. Turn on fight coconut crab in natro
2. Watch natro go to coconut crab and start fighting it

### What would you expect to happen?

When your capacity reaches 95% (or whatever setting you have it set to) natro will stop fighting coconut crab and go to convert at the hive

### Natro Macro version

1.0.0

**Comment by Noobyguy775** [comment]
merging with #502
