### ISSUE TITLE
Hourly Chart Pop Star Sizes

### ISSUE THREAD

**Issue by CuzImSlymi** [NatroTeam/NatroMacro#428]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Basically, in the Hourly charts you can also see above Blue/Red/white boosts, Focus, Haste, Bombs, Balloon aura, Inspire and Reindeer fatch the average Buff, for example 7.501x or so, and the idea would be to add this to Pop star, what the average size of it is. It would display it the same as Blue pollen and such, but of course more something like 200x (The size of a popstar, just a example) instead of 9x. (In hourly charts buffs cant go beyond 10x)

i drew something simple as how it would look in the hourly charts (Pop star image would have to be a bit lowered tho to fit the number, or be repositioned somewhere else.)

![natro_idea_popstar](https://github.com/NatroTeam/NatroMacro/assets/147297026/dc861b1d-24e8-4d23-86e1-ab8ebb6fe30d)

### How will this improve Natro Macro?

Blue hives are using this macro so much, and Pop star is just the main thing of blue hives, so it would be good to find out what your average Pop star size is, i mean yes you could just watch it, but that wont be as accurate, as none will sit there some hours, putting notes on my pop star size and then calculating the average. This would also help to test patterns and such, Alt positions etc... 

### What is your Discord username?

slymih

**Comment by Noobyguy775** [comment]
Merging this with #20
