### ISSUE TITLE
Mythic Bee auto jelly feeder

### ISSUE THREAD

**Issue by RedWoodHotel** [NatroTeam/NatroMacro#429]
### Have you searched the existing suggestions?

No

### What is your suggestion?

For newer(mid-game players, or those who can't use a bunch of royal jellies) it could be helpful to make a tool that could use the needed legendary setting in the game, then feed royal jellies until a mythic is generated. 

### How will this improve Natro Macro?

It could make it easier and help newer players get further in the game, without having to spend a lot of time manually feeding royal jelly.

### What is your Discord username?

arca_plazum

**Comment by Noobyguy775** [comment]
Using the "until mythic" toggle functions the same as this, with the only difference being the bee you end up with if a mythic is not obtained.
