### ISSUE TITLE
Add a feature that makes you jump while entering a field so that you kill everything

### ISSUE THREAD

**Issue by froginalog** [NatroTeam/NatroMacro#43]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

You should add a feature that makes you jump after entering a field so that your bees can kill an enemy before you start macroing.

### How will this improve Natro Macro?

It would allow players of all skill levels to use natro macro because

### What is your Discord username?

@froginalog_

**Comment by zspz** [comment]
This was actually added in a previous version, but caused far too many in-game issues where the mobs would despawn because of the jumping. It probably never made it to release since our testers had very inconsistent bug runs, and will probably not be considered.
