### ISSUE TITLE
Keeps resting at hive

### ISSUE THREAD

**Issue by britishegg** [NatroTeam/NatroMacro#431]
### Have you searched the existing bug reports?

Yes

### What happened?

It keeps on resting at the hive when you start the macro

### Steps to reproduce

1. join the game and start the macro
2. it wil try to get a hive but it won't most of the time
3. if it does get a hive it will try to get something like a dispenser
4. it will normally fail and the rest loop will start because it gets stuck on a hive floor

### What would you expect to happen?

I expected it to see that it was at the hive and start going to the cannon to get things.

### Natro Macro version

1.0.0.1a

**Comment by Noobyguy775** [comment]
Join the discord for support, https://discord.gg/natromacro
