### ISSUE TITLE
Hourly graphs + Specific convert hour

### ISSUE THREAD

**Issue by BIOFRI3NDLY** [NatroTeam/NatroMacro#432]
### Have you searched the existing suggestions?

No

### What is your suggestion?

My first suggestion is hourly graphs being optionally organized in a separated channel. I understand that's already an option with rdp but not many people use it and I'm convinced a lot of people if not most would love their hourly graphs in a separated webhook channel.

My second suggestion is customizing convert. To make my point clear, I'll use an example and why I thought of this. 
If my macro has reconnect every 3h at 0000UTC, that means it's disconnecting sometimes with x44-50 balloons to convert. However, if there was a specific time to convert where I could manually set, for instance, *always* convert *at: 23:58*, this would send my character to the hive before reconnecting. 

Thank you for listening. 

### How will this improve Natro Macro?

This would improve Natro in comfortability and flexibility. 

### What is your Discord username?

Zlaive/BIOFRI3NDLY

**Comment by DullSmallmega176** [comment]
@BIOFRI3NDLY the first one is already in the macro (through remote control) and you probably meant that, and for your suggestion on the first one, did you mean it through webhook ?

and for your second suggestion, i suggested it with ninju if it should be added to natro macro, soo @ninjubaer GUESS WHO ELSE NEEDS IT LOL, i'll probably work on it later on

**Comment by BIOFRI3NDLY** [comment]
> @BIOFRI3NDLY the first one is already in the macro (through remote control) and you probably meant that, and for your suggestion on the first one, did you mean it through webhook ?
> 
> and for your second suggestion, i suggested it with ninju if it should be added to natro macro, soo @ninjubaer GUESS WHO ELSE NEEDS IT LOL, i'll probably work on it later on whenever, sooooo 😁

Hello sorry for the delay. 

Yes I meant adding that option to webhook only users, I'm aware that's possible on RC, but I think it would be huge addition to webhook/normal discord settings if we could add hourly graphs to a specific channel. 

And pretty cool that you are working on that second point, would make a huge honey difference long term wise, specially for those who RC every 3h.

👍

**Comment by ninjubaer** [comment]
Hey @BIOFRI3NDLY 
I dont think that the seperate channel is needed in webhook but you can obviously change it yourself. Open a post in [ahk-discussion](https://discord.com/channels/1012610056921038868/1190836918804561971) and i will show you how to do it step by step
