### ISSUE TITLE
Sticker Seeker - Rainbow Sticker Tokens

### ISSUE THREAD

**Issue by lordlevstar** [NatroTeam/NatroMacro#433]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

When the sticker seeker is equipped, it make rainbow sticker tokens appear on a random flower in your field.  It would be great if natro detected that a rainbow sticker was found and searched for it.  It could be similar to field drift comp. where when the dialogue pops up, it searches the screen for a certain coloured pixel and goes to it.

### How will this improve Natro Macro?

It would help with the sticker seeker quests, collecting the rainbow sticker tokens for you.  Also it would collect sticker for you

**Comment by Noobyguy775** [comment]
It's virtually impossible to search for a pixel, but it is possible, albeit hard to detect the message in the bottom right and start a movement to search for the sticker. However, there are a few stickers I can think of that don't spawn in the same field as you, which could cause problems. Ex. triple exclamation. Ill leave this open for a (very) far future possibility

**Comment by misc-et** [comment]
While this may be possible, it's felt that it may be fairly unreliable. If someone wishes to work on it or we get further requests, it can be reopened, but closing it for now.
