### ISSUE TITLE
Memory match path improvements

### ISSUE THREAD

**Issue by Dzlem** [NatroTeam/NatroMacro#434]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

So basically, it seems like the path for the night memory match is guaranteed to fail, now obviously in the rare cases of it working it usually just takes a wrong turn and resets the character, which is why i suggest (if possible) to use the neon light from the moon parkour to avoid it failing, or making a more guaranteed path by making the character much closer/ different walk method, I'd appreciate it if you can fix it! thank you :D

### How will this improve Natro Macro?

Pretty much it will, because its one of the very used features as the night memory match is an easy way of earning decent materials like moon charms, glitter, star jelly, and stingers, mythic eggs and enzymes.

### What is your Discord username?

dzlem_

**Comment by lordlevstar** [comment]
This would be great, as it has never successfully gotten to the night memory match for me

**Comment by Penrosian** [comment]
> This would be great, as it has never successfully gotten to the night memory match for me

same here, and with many others in the discord. Adding this would improve it substantially.

**Comment by peacocksir** [comment]
We will be improving this soon.

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/501
