### ISSUE TITLE
i cannot open natromacro and it says:error

### ISSUE THREAD

**Issue by edgarzxc** [NatroTeam/NatroMacro#435]
### Have you searched the existing bug reports?

No

### What happened?

i have tried like 20 times to open natromacro and it says there is an error with the system and the file doesnt exist 

### Steps to reproduce

1.by executing natromacro
2.it appeared after that
3.it has ''edit'' ''abort'' and  accept i think

### What would you expect to happen?

i cannot enter

### Natro Macro version

the newest version

### What is your Discord username?

edgarzz

**Comment by Noobyguy775** [comment]
Join the discord for support, https://discord.gg/natromacro
