### ISSUE TITLE
Oversight regarding King Beetle boss

### ISSUE THREAD

**Issue by aqts-aqts** [NatroTeam/NatroMacro#436]
### Have you searched the existing bug reports?

Yes

### What happened?

Due to an oversight in the King Beetle path, some custom blue flower field paths make it impossible to kill king beetle.

### Steps to reproduce

1. Use a custom blue flower field path, one that does not position you close to the king beetle boss
2. Enable king beetle

### What would you expect to happen?

The macro will not have correctly placed the player in the boss room.

### Natro Macro version

v1.0.0.1a

### What is your Discord username?

aqts

**Comment by Noobyguy775** [comment]
merging with #502
