### ISSUE TITLE
Hourly Report Override

### ISSUE THREAD

**Issue by ZackAttack4987** [NatroTeam/NatroMacro#437]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro was converting for over a minute.
During this minute, :00 came around.
After this minute, it was :01
The macro decided it would not be giving me my hourly graph.

### Steps to reproduce

1. Have bad convert rate.
2. The macro must convert right before it will send the graph.
3. The macro spends all its focus on the converting, not the graph.
4. No graph.

### What would you expect to happen?

I expected for it to put it on hold or realize that it is past the last :00 and it hasn't done a graph yet. Then it does graph.

### Natro Macro version

1.0.0.1

### What is your Discord username?

ZackAttack4987

**Comment by Noobyguy775** [comment]
Hi, this is likely a problem with your internet, or an external factor.

https://discord.com/channels/1012610056921038868/1190617274097356820/1190617537579339876
You'll need to join the discord to access this link ^ https://discord.gg/natromacro

**Comment by Mrjamedd** [comment]
Womp

**Comment by ZackAttack4987** [comment]
Thank you for your opinion, I do not care anymore
