### ISSUE TITLE
Sticker stack exceptions/auto discard stickers

### ISSUE THREAD

**Issue by lordlevstar** [NatroTeam/NatroMacro#438]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

When turning on the add stickers to sticker stack setting, it will add the first sticker that comes up.  What I am suggesting is a way of making it so that certain stickers won't get added.  This would make it so that natro adds other stickers instead, or if there are none available than nothing will get added.
I know that valuable stickers can be traded to an alt account, but it becomes quite tiresome having to constantly trade them back and forth.
Edit: Also you could have an auto-discard feature.  When obtaining stickers from the sticker printer, you can set it to automatically discard stickers that you have selected it discard. (This could be in the same menu as the sticker stack exceptions)

### How will this improve Natro Macro?

It will ensure that valuable stickers wont get added to the sticker stack, and can be used for trading
Edit: The auto-discard feature will ensure that the player's inventory dosen't get filled up with useless stickers

**Comment by Noobyguy775** [comment]
This would be a lot of work- but it is possible for the future.

**Comment by misc-et** [comment]
In addition to being a fairly large task, this may also be a higher-risk option, with the possibility of losing valuable stickers. Closing for now, but it may be reopened if someone wishes to work on it or we receive further requests.
