### ISSUE TITLE
Mondo buff bug?

### ISSUE THREAD

**Issue by pedjabss** [NatroTeam/NatroMacro#439]
### Have you searched the existing bug reports?

Yes

### What happened?

i hit the time limit so i was walking back to the hive when i was sitting over the hive mondo chick spawned and since i have mondo buff on it wanted to kill it but it didnt convert what i had in the backpack so then it went to top and did what it should then it reset so i lost all the pollen 

### Steps to reproduce

1.Have mondo buff on
2.Hit time limit
3.Let it walk back to the hive 
4.Mondo Chick spawns 

### What would you expect to happen?

I expected for it to convert atleast what was in the backpack and after that to go kill mondo chick

### Natro Macro version

v1.0.0.1

### What is your Discord username?

.pedja.

**Comment by Noobyguy775** [comment]
merging with #502
