### ISSUE TITLE
doing the badges

### ISSUE THREAD

**Issue by paper555555555555555555555555555** [NatroTeam/NatroMacro#440]
### Have you searched the existing suggestions?

No

### What is your suggestion?

there would be a button and you click it and it would turn on and when you start it it will check which badge is closet to being grandmaster and then it will start doing what the badge needs to be done (i recommend only using fields because yeah)

### How will this improve Natro Macro?

i want this so i can get supreme saturator faster and for other users if they already have supreme saturator they could use it for tickets

### What is your Discord username?

lko_qqq

**Comment by ninjubaer** [comment]
Hello @paper555555555555555555555555555 
Im sorry but this is not planned sonce natro macro is intended to be a tool for faster progression/honeymaking rather than a tool that finishes the game for you.
