### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Axelisael** [NatroTeam/NatroMacro#441]
### Have you searched the existing bug reports?

No

### What happened?

![Captura de pantalla 2024-04-21 111040](https://github.com/NatroTeam/NatroMacro/assets/167697892/7dfb5b33-7efd-49bc-ac78-5b3b6c1b91b2)

### Steps to reproduce

1.I was farming normally and suddenly this happens
2.
3.

### What would you expect to happen?

I should reconnet and continue farming

### Natro Macro version

1.0.0.1

### What is your Discord username?

Heishel

**Comment by Noobyguy775** [comment]
https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-security/mbam-client-fails-event-id-4-0x8004100e#resolution

TLDR:
Winkey+R, type in cmd
paste this in `sc query winmgmt`
if it's running, see the link above (run the `mofcomp.exe` command)
if not, paste in `net start winmgmt`, if it still has the error, do the fix above ^
