### ISSUE TITLE
10x reset issue

### ISSUE THREAD

**Issue by mortimer-7** [NatroTeam/NatroMacro#442]
### Have you searched the existing suggestions?

No

### What is your suggestion?

If you have bad internet it's possible for the macro to reset character 10 times in a row because it keeps respawning on the spawn platform, this happened to me many times in the middle of macroing (yes I did claim my hive). My suggestion is that you add that when it checks what direction it spawns in but realises its on the spawn platform instead of at the hive it will try walking to hive slot 1 just like how it does when it rejoins the game, and if it finds hive slot 1 it will just continue as normal. If it doesnt find hive slot 1 it will reset and look for it again.

Another thing I would want is that you can add a time that it waits at the hive after resetting character, this would be good for killing bugs since sometimes it starts picking up bug loot before even killing them, and sometimes it leaves the field before the bees even get there.

### How will this improve Natro Macro?

As I said this will help people with bad internet, and in my opinion it could even be faster than resetting to get back to hive, and it will make so that bees don't sleep when the macro goes to kill mobs. This will make killing mobs faster and more consistent. Hive wait timer would also make killing mobs consistent.

### What is your Discord username?

mortimer7

**Comment by mortimer-7** [comment]
I will also add that the 10x reset issue makes it so that I get way less tickets from the wealth clock.

**Comment by Noobyguy775** [comment]
#186
