### ISSUE TITLE
Ticket clock

### ISSUE THREAD

**Issue by collinstrm** [NatroTeam/NatroMacro#443]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I would like for the macro to be able to read the time on the clock so you don't have to start the macro when the clock is ready to be collected.

### How will this improve Natro Macro?

It saves so much time so if your going on vacation or something and you forgot to start your macro earlier you can not do the clock because it will glitch the macro.

### What is your Discord username?

collinstrm

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/593
