### ISSUE TITLE
it keeps resetting me losing all the pollen

### ISSUE THREAD

**Issue by ongbrxh** [NatroTeam/NatroMacro#444]
### Have you searched the existing bug reports?

No

### What happened?

it just kills me

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i want it to actually work 

### Natro Macro version

V.1.0.0.1

### What is your Discord username?

ongbrxh.

**Comment by CosmicRT** [comment]
This is happening with me

**Comment by Noobyguy775** [comment]
@CosmicRT @ongbrxh Join the discord for support, https://discord.gg/natromacro
