### ISSUE TITLE
Reset Glitch

### ISSUE THREAD

**Issue by CosmicRT** [NatroTeam/NatroMacro#445]
### Have you searched the existing bug reports?

No

### What happened?

So I my friend is trying to macro. And it keeps on resetting him over and over again. And we tried for 10 minutes and it still didn't work

### Steps to reproduce

1.Spawn in 
2.Turn on macro 
3.Wait

### What would you expect to happen?

You will keep resetting 

### Natro Macro version

1.0.0.1

### What is your Discord username?

cosmicrt

**Comment by Noobyguy775** [comment]
#444
