### ISSUE TITLE
Vic Bee Serverhop macro with night detect

### ISSUE THREAD

**Issue by GiroyRBLX** [NatroTeam/NatroMacro#446]
### Have you searched the existing suggestions?

No

### What is your suggestion?

So basically vicious bee serverhop macro with night detect for single account

### How will this improve Natro Macro?

It will greatly improve Natro Macro, because many red hives and white hives are having extremely large lack of stingers, so this will make Natro Macro community bigger and will help many players.

### What is your Discord username?

giroyrblx

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/12
