### ISSUE TITLE
Gumdrops

### ISSUE THREAD

**Issue by iwkwiwwkwkw** [NatroTeam/NatroMacro#449]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I have a suggestion to add to the macro whenever your doing a quest and it requires gumdrops there should be a button that you can activate before macroing that uses gumdrops during needed quest so like, get 30m goo from the bamboo field. And it’ll only use gumdrops when needed and alerts your discord bot whenever you ran out of gumdrops.

### How will this improve Natro Macro?

Used for quest that needs goo from a field. It can decrease the time finishing the quest instead of waiting for gummy bee to drop some ability tokens.

### What is your Discord username?

reachforthestar

**Comment by iwkwiwwkwkw** [comment]
It can help benefit players of spending less time on one quest and can move on to the other one.

**Comment by Noobyguy775** [comment]
Can also implement #329 (using gumdrops after glue dispenser boost)
