### ISSUE TITLE
Reconnecting, hive problems

### ISSUE THREAD

**Issue by Avan53221** [NatroTeam/NatroMacro#452]
### Have you searched the existing bug reports?

Yes

### What happened?

I was using macro and when I was disconnected after reset character 9 times, and reconnected. Natro macro couldn't find a hive to continiue farm. When there is was someone it's just gave me status with: fail to claim a hive, that means, that place is allready in use, but there is other hives that are free, and I couldn't continiue macro without collecting hive. Pls help!

### Steps to reproduce

1. When I was reseting my character 9 times, i've got disconnected and I join a public serer again.
2. Then I join from other device to see, how macro works, and i realized that macro couldn't take free places because my hive number "1" was allready in use, and macro gives me status with issues: fail to take hive slot.
3. I tried to join from other device to my friend when there is one free place, and device where i had macro just couldn't join to my friend with free, number "1" hive slot.

### What would you expect to happen?

I expect if developers could sett automatically hive slot to take ( from 1-6), there would be best idea to macro without problem, and other thing I expect that if macro device could join my friend to macro at that server with that "1" free hive slot to make solution easier, with some issues.
![image](https://github.com/NatroTeam/NatroMacro/assets/168771860/fe14bcc9-f854-447d-8412-706f488cb00a) That image describes, where could automatically decision to hive slot be.
Other thing that i could add in addiction, is developer could add reset character times before disconnecting from the server. exmple: "After reset character more than 20 times we will disconnect your device to other server".

### Natro Macro version

v1.0.0

### What is your Discord username?

therock2080

**Comment by misc-et** [comment]
Thanks for your report. The macro already searches for an alternative hive slot if the slot indicated in settings is taken, and updates settings accordingly. If you are having issues with this functionality there may be an issue with your settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.

I'll link this issue in https://github.com/NatroTeam/NatroMacro/issues/186, as your last point about optionally specifying a number of resets before rejoin is related.
