### ISSUE TITLE
Making our own pattern

### ISSUE THREAD

**Issue by jkl071812** [NatroTeam/NatroMacro#453]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Give us the freedom to make our own pattern because some of us just want to do our own and make our own pattern

### How will this improve Natro Macro?

We can farm in many fields and we dont need to worry about some other things

### What is your Discord username?

jkl1948

**Comment by DullSmallmega176** [comment]
@jkl071812 
channel to public patterns people share - https://discord.com/channels/1012610056921038868/1190858036898709524
channel showing how to make patterns - https://discord.com/channels/1012610056921038868/1037835913742536724
(outdated at the moment)
