### ISSUE TITLE
My natro cant control my mouse

### ISSUE THREAD

**Issue by SkeWanjer** [NatroTeam/NatroMacro#454]
### Have you searched the existing bug reports?

No

### What happened?

My natro cant control my mouse

### Steps to reproduce

1My natro cant control my mouse
2.My natro cant control my mouse
3.My natro cant control my mouse

### What would you expect to happen?

My natro cant control my mouse

### Natro Macro version

Natro_Macro_v1.0.0.1a

### What is your Discord username?

popkagitlera

**Comment by Noobyguy775** [comment]
Try running natro as an administrator

**Comment by ninjubaer** [comment]
if that also didnt work try to unplug your mouse while using the macro
