### ISSUE TITLE
Not landing in the field 

### ISSUE THREAD

**Issue by Nayeske** [NatroTeam/NatroMacro#455]
### Have you searched the existing bug reports?

Yes

### What happened?

I start the macro, most of the time it’s having trouble collecting things like blueberries and landing in fields…it’s way off 

It eventually makes it to the field but it will sit there (like picture) and then reset 

![IMG_6112](https://github.com/NatroTeam/NatroMacro/assets/168966934/bbd9bbbe-ad4b-4bce-99d8-cdc1f7e0ccda)

### Steps to reproduce

1. I’ve made sure my movement speed is correct 
2. I’ve restarted my computer and the macro 
3.
4.

### What would you expect to happen?

I was hoping it was going to help but didn’t. 

### Natro Macro version

The latest version

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
