### ISSUE TITLE
Solving the Natro Macro problem on a laptop (please help)

### ISSUE THREAD

**Issue by ness1077** [NatroTeam/NatroMacro#456]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Hello! I'm using Natro Macro from a laptop and I have a question. How can I make sure that the macro continues to work after closing the laptop lid? (after closing the lid the character is simply reset)

### How will this improve Natro Macro?

Will help other users farm at night.

### What is your Discord username?

dssx0

**Comment by DullSmallmega176** [comment]
@ness1077 this is not a macro suggestion 😭 
but look around to see how to do it (mainly closing the lid on a laptop is software or hardware controlled, or both)

**Comment by Noobyguy775** [comment]
https://discord.gg/natromacro
