### ISSUE TITLE
Don't convert Honey

### ISSUE THREAD

**Issue by 777edi** [NatroTeam/NatroMacro#458]
### Have you searched the existing bug reports?

No

### What happened?

I was macroing and for some reason its walking to my hive but then starts walking in a diferent direction and just resets so I lose all my honey.
I checked the settings but it seems fine there

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

That it starts converting my honey.

### Natro Macro version

v1.0.0.1

### What is your Discord username?

777edi

**Comment by Noobyguy775** [comment]
Check your balloon setting
