### ISSUE TITLE
windy bee

### ISSUE THREAD

**Issue by Mryeet4678** [NatroTeam/NatroMacro#460]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

kills windy bee 

### How will this improve Natro Macro?

help with unlocking windy bee

### What is your Discord username?

mryeet4678

**Comment by DullSmallmega176** [comment]
@Mryeet4678 this will be so unethical to add

**Comment by Noobyguy775** [comment]
It's basically impossible to detect windy bee, and her attacks that blow you away make it even harder. I'll close this because it's not happening anytime soon, but maybe in a few years.
