### ISSUE TITLE
presets/profiles for different accounts/objectives

### ISSUE THREAD

**Issue by G3org3-S** [NatroTeam/NatroMacro#461]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I think that adding profiles would be very useful because for example, sometimes I want to macro for materials/quests (so I have mondo, bug run, quests, etc) and sometimes I just want to macro for honey with no interruption for maximum profits, without having to turn off all the options.

### How will this improve Natro Macro?

I think this will benefit macro because it is a very useful feature that would improve the quality of life of the macro.

### What is your Discord username?

vlonetrooperalt

**Comment by Noobyguy775** [comment]
#77
