### ISSUE TITLE
Toggle current honey/pollen

### ISSUE THREAD

**Issue by SillyBleh** [NatroTeam/NatroMacro#462]
### Have you searched the existing suggestions?

Yes, there are no good options.

### What is your suggestion?

Add an ability to toggle whether to send updates about current honey/pollen.

### How will this improve Natro Macro?

Sending images every second to discord does not only load your traffic, slowing the internet connection, but also risks being temporarily banned from discord api for "spamming". Currently the only way to turn this feature off is to turn the screenshots off, which is quite annoying.
I hope this helped.

### What is your Discord username?

expilon

**Comment by Noobyguy775** [comment]
Coming soon™️
