### ISSUE TITLE
Honeymask Coin scatter collect

### ISSUE THREAD

**Issue by Mehluwhat** [NatroTeam/NatroMacro#463]
### Have you searched the existing suggestions?

No

### What is your suggestion?

1. Honey mask coin scatter ability collect 

### How will this improve Natro Macro?

1. Achieve maximum efficiency using Honey Mask (lots of pollen are wasted if not collected)
2. More options for mid-game players like myself

**Comment by Noobyguy775** [comment]
We can't detect tokens, but to work around this you can:
1. use a different mask, for example bubble mask
2. use a bigger pattern size, such as XL or L
