### ISSUE TITLE
Bug Run Bug

### ISSUE THREAD

**Issue by FunkletonJazz** [NatroTeam/NatroMacro#469]
### Have you searched the existing bug reports?

No

### What happened?

My character ends up dying to the enemies whenever the macro tries to bug run in Pineapple Patch. I double checked my settings and they all should be right.

### Steps to reproduce

1. Character moves to Pineapple Patch.
2. Character walks into the field before the bees arrive, spawning the enemies.
3. Character stands still waiting for bees, and is killed by the time they arrive.

### What would you expect to happen?

I imagine my character would enter the field at the same time as the bees, so the enemies die first. I also wanna note the macro still tries to loot, even after my character dies.

### Natro Macro version

v1.0.0.1

### What is your Discord username?

funkletonjazz

**Comment by Noobyguy775** [comment]
#473 for the waiting, #303 for bugrun bugs
