### ISSUE TITLE
Auto Gifted bee

### ISSUE THREAD

**Issue by blin322** [NatroTeam/NatroMacro#47]
### Have you searched the existing suggestions?

No

### What is your suggestion?

It will be pretty good, if to Nacro Macro add "Auto bee feeder" that means u can place a cursor like in "Auto Gifted basic bee " and macross will feed ur bee by 50 100 150 200 or more bitterberies, strawberries or sunflower seeds, it makes more chances to make a bee gifted

### How will this improve Natro Macro?

It will add more functions and more users will use it to get gifted bees, cuz they are lazy, like me

### What is your Discord username?

@blin4ik322

**Comment by Noobyguy775** [comment]
For mutations, there's already a bitterberry feeder (make sure the bee is radioactive. Also this is broken with the new gui changes, so use natro v0.9.6 using the ms store version of roblox.)
For fruit, there's a built in option in bss

**Comment by blin322** [comment]
> For mutations, there's already a bitterberry feeder (make sure the bee is radioactive. Also this is broken with the new gui changes, so use natro v0.9.6 using the ms store version of roblox.) For fruit, there's a built in option in bss

But, thats more chances to make bee gifted
