### ISSUE TITLE
waiting after reset

### ISSUE THREAD

**Issue by alwaysbetonhakari** [NatroTeam/NatroMacro#470]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

add a feature that lets you choose how many seconds you want to wait 

### How will this improve Natro Macro?

makes it easier to bugrun because sure i can lower the amount of bees but it doesnt affect that much.

### What is your Discord username?

saitamaisdagoat

**Comment by DullSmallmega176** [comment]
technically already in the macro, when attacking stuff, it's based around how many bees you have in your hive, and also there's "wait x amount of seconds after convert" which is not related to attacking i guess![image](https://github.com/NatroTeam/NatroMacro/assets/133727755/4c1128cd-2586-4bd9-8d33-bdfd84b110dc)
