### ISSUE TITLE
Drift comb not working

### ISSUE THREAD

**Issue by spinnysheep** [NatroTeam/NatroMacro#472]
### Have you searched the existing bug reports?

No

### What happened?

the drift comp thing doesnt work , i have the supreme saturator and i have put it as one in the settings.

### Steps to reproduce

1.start macro with drift comb
2.macro a while
3.character is not where its supposed to be macroing

### What would you expect to happen?

the macro to rearange itself back to the position of the supreme saturator

### Natro Macro version

1.0.0.1

### What is your Discord username?

Lexui26

**Comment by Noobyguy775** [comment]
https://discord.gg/natromacro : join and read the troubleshooting guide
