### ISSUE TITLE
natro bug killing bug

### ISSUE THREAD

**Issue by bloonsfan** [NatroTeam/NatroMacro#473]
### Have you searched the existing bug reports?

No

### What happened?

so sometimes when the macro kills bugs for a quest since it uses the cannon it forgets the bees aren't there and are still coming making it leave before it actually killed  anything

### Steps to reproduce

1. polar bear quest
2. bug run throughs

### What would you expect to happen?

it would leave before killing the bugs

### Natro Macro version

v1.0.0.1

### What is your Discord username?

azulathezula

**Comment by Noobyguy775** [comment]
You can decrease your hive bees in settings tab for it to wait longer
