### ISSUE TITLE
Rejoin after 8+ failed resets

### ISSUE THREAD

**Issue by ThrowawayMoment** [NatroTeam/NatroMacro#474]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I noticed sometimes Natro Macro will get completely stuck, because it keeps spawning on the spawn as if it had no hive upon rejoining a different server. I personally think either walking on all the hives and converting anything (to set the spawn) or rejoining the server would be a nice feature, to prevent prolonged issues such as being stuck on this 1 dastardly spawn.
![Screenshot 2024-05-26 140737](https://github.com/NatroTeam/NatroMacro/assets/146147126/09a7d4f3-3919-490c-924d-bc707edc9047)

### How will this improve Natro Macro?

It could completely prevent near-infinite loops and major time loss of the macro being stuck in a loop of resetting because of spawn issues in-game.

### What is your Discord username?

thecolor_orange (im in the official natro macro discord server)

**Comment by DullSmallmega176** [comment]
it's alr in the macro![image](https://github.com/NatroTeam/NatroMacro/assets/133727755/7ae95e51-aaf4-4ccf-9039-7a69c5282083)
