### ISSUE TITLE
More Quest Options

### ISSUE THREAD

**Issue by Joeytjuhh** [NatroTeam/NatroMacro#476]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add more bears to the quest tab so you have to spend less time playing by yourself to get a translator for example.

### How will this improve Natro Macro?

Spend less time yourself and get items faster overnight for example the translator or pedal.

### What is your Discord username?

yourlocalss

**Comment by Noobyguy775** [comment]
#388
