### ISSUE TITLE
Item Counter

### ISSUE THREAD

**Issue by OzoneX07** [NatroTeam/NatroMacro#477]
### Have you searched the existing suggestions?

No

### What is your suggestion?

A feature in the misc. section that goes through your in-game item list and goes through everything you have to count them all. Every time you use it, it would tell you want you've lost or gained and how much of it.

### How will this improve Natro Macro?

It just makes it a little easier to see what you've gotten/lost after a night or a couple of of days of macroing instead of having to eyeball it. or guess.

### What is your Discord username?

lmly.lio

**Comment by Noobyguy775** [comment]
merging with #413
