### ISSUE TITLE
my macro isnt working correctly (it isnt jumping)

### ISSUE THREAD

**Issue by pawelgdx** [NatroTeam/NatroMacro#478]
### Have you searched the existing bug reports?

No

### What happened?

i am trying to macro but it isnt jumping

### Steps to reproduce

1.fix macro
2.fix macro
3.fix macro

### What would you expect to happen?

i was hoping for my macro to jump to the cannon and not running against the wall

### Natro Macro version

v1.0.0.1a

**Comment by Noobyguy775** [comment]
https://discord.gg/natromacro
