### ISSUE TITLE
jump glitch?

### ISSUE THREAD

**Issue by pawelgdx** [NatroTeam/NatroMacro#479]
### Have you searched the existing bug reports?

No

### What happened?

i am trying to macro but it isnt jumping

### Steps to reproduce

1.fix macro
2.fix macro
3.fix macro

### What would you expect to happen?

i was hoping for my macro to jump to the cannon and not running against the wall

### Natro Macro version

v1.0.0.1a

### What is your Discord username?

no_names.123

**Comment by pawelgdx** [comment]
nah

**Comment by Noobyguy775** [comment]
Join the discord. https://discord.gg/natromacro
