### ISSUE TITLE
Sprout detector

### ISSUE THREAD

**Issue by rinat42069** [NatroTeam/NatroMacro#48]
### Have you searched the existing suggestions?

Yes.

### What is your suggestion?

Detection of sprouts.
Options to toggle for what sprouts do you want to be informed.
Would be a great feature because legendary and supreme sprouts are cool.

### How will this improve Natro Macro?

They get easy loot. :Wow

### What is your Discord username?

ihavebeenpwned

**Comment by Noobyguy775** [comment]
Detection of sprouts already in fields is impossible

Detection of the message in chat/bottom right is a good suggestion, although i can think of a few downsides
