### ISSUE TITLE
'Slimline' gathering pattern creates AutoHotKey V2 warning message

### ISSUE THREAD

**Issue by ThrowawayMoment** [NatroTeam/NatroMacro#480]
### Have you searched the existing bug reports?

No

### What happened?

When using the Slimline gathering pattern, AutoHotKey generates a warning message and prevents Natro Macro from gathering as a result. This is the provided message:
![Screenshot 2024-05-28 014854](https://github.com/NatroTeam/NatroMacro/assets/146147126/9e33cfda-422e-4079-8123-077fe2d45374)

### Steps to reproduce

1. Select a field to gather in (I used stump)
2. Select the Slimline gathering pattern with drift correction
3. Let the macro attempt to run Slimline in the provided field

### What would you expect to happen?

The given screenshot with the error should occur, where AHK unexpectedly gets a string instead of what it wanted.

### Natro Macro version

1.0.0.1

**Comment by DullSmallmega176** [comment]
it's alr fixed, all that's changed was the syntax of the pattern, if you want i can send it over in dm's
