### ISSUE TITLE
Going off the field

### ISSUE THREAD

**Issue by yourgamer69** [NatroTeam/NatroMacro#481]
### Have you searched the existing bug reports?

Yes

### What happened?

So basically while I was macroing with the latest version and all was going smoothly until I fell off the field for no reason, my display scale was at 100%, movespeed correction was on, and also my graphics quality is set to one, but I don't know why when I macro it just falls off the field

### Steps to reproduce

1. Just use the macro
2. Macro at mountain top field
3. Wait a little bit

### What would you expect to happen?

I expected for the macro to just work properly

### Natro Macro version

v1.0.0.1

**Comment by DullSmallmega176** [comment]
There's a lot of fields where the only option is using a custom pattern or using stationary (some great examples. cactus, mountain top, clover, stump, and probably others). and mainly this is mostly user error in most cases (examples, not having your walkspeed correct, not having supreme saturator but still wanting to use field drift comp, sometimes lag i guess, and the pattern itself), and there's really nothing to aling towards that's reliable in mountain top. (and also there's alr a post about field drift in the knowledge base in natro)

**Comment by yourgamer69** [comment]
@DullSmallmega176 Ingame it said "Walkspeed: 32.2", and I set that walkspeed, I also do not want to use field drift comp.

**Comment by Noobyguy775** [comment]
It's not our job to patch your settings making you go out of the field - if you need settings you can join our discord and copy them from there.
