### ISSUE TITLE
Ant macro

### ISSUE THREAD

**Issue by JonasJosiahKingofGuyana** [NatroTeam/NatroMacro#483]
### Have you searched the existing suggestions?

No

### What is your suggestion?

as there is a crab kill feature would it be possible to make an ant pass field collector and also another feature is amulet macros: put in your required amulet and then it macros until you get it

### How will this improve Natro Macro?

Amulets are a massive part of the game
ant field is annoying

### What is your Discord username?

jonasthelegend

**Comment by DullSmallmega176** [comment]
there's already ant challenge in the macro but it stands still just to do quests (and there's also collect ant pass), and to be honest, there is no point of automating ant challenge because of how complicated it is between hives and whatever, same thing with windy bee from another suggestion

**Comment by JonasJosiahKingofGuyana** [comment]
What about the automating amulets suggestion?

**Comment by DullSmallmega176** [comment]
why 😭, it will just be standing still, 9 times out of 10 will the amulet be bad than doing it manually

**Comment by JonasJosiahKingofGuyana** [comment]
No silly not jusy ssas i meant ant amulet stick bug amulet king beatle
amulet moon amulet you get the point as of currently the macro just kills
the mob and if you select it, it will choose the one you got when getting
the amulet, if you get what im saying.

If im being stupid just tell me

**Comment by Noobyguy775** [comment]
#57
