### ISSUE TITLE
waiting before going in field

### ISSUE THREAD

**Issue by alwaysbetonhakari** [NatroTeam/NatroMacro#485]
### Have you searched the existing suggestions?

No

### What is your suggestion?

make a feature that lets you add how much seconds you want to wait before going into the field for bugruns 

### How will this improve Natro Macro?

it would make collecting the items after every bugrun easier

### What is your Discord username?

saitamaisdagoat

**Comment by Noobyguy775** [comment]
Already possible via. Hive bees in settings/Wait x seconds after converting
