### ISSUE TITLE
Fully autonomous

### ISSUE THREAD

**Issue by Perets2207** [NatroTeam/NatroMacro#486]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Make an Linux distro who only start natro macro and farm 25/8.

### How will this improve Natro Macro?

1. Optimization.
2. Better virtual machines compatibility.
3. More and more accounts on one PC.

### What is your Discord username?

@subtogash

**Comment by Noobyguy775** [comment]
That would require an entire language swap (aka rewriting all of the code) which is probably not worth the effort. plus, windows is already fine for performance as long as you don't have too much bloatware
