### ISSUE TITLE
Expanding Planters section

### ISSUE THREAD

**Issue by Mongyyy** [NatroTeam/NatroMacro#487]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

The feature would plant planters accordingly to their special 1months cooldown bonuses, for example, you could set natro to plant a paper planter every month for the guaranteed super smoothie as well as every other planter and their guaranteed waxes.

### How will this improve Natro Macro?

I'd LOVE to see this feature because of how it would benefit the collection of all the waxes

### What is your Discord username?

mongy_got_real

**Comment by Noobyguy775** [comment]
#425
