### ISSUE TITLE
bugrun suggestion

### ISSUE THREAD

**Issue by Zeerunsyou** [NatroTeam/NatroMacro#488]
### Have you searched the existing suggestions?

No

### What is your suggestion?

add it so u can choose how long ur player waits before collecting a bugs loot cause for some reason my player will try to collect bugs loot before its even dead

### How will this improve Natro Macro?

so newer players can somewhat use bugruns 

### What is your Discord username?

zeerunsyou

**Comment by Noobyguy775** [comment]
#485
