### ISSUE TITLE
Mythic Auto Hatcher

### ISSUE THREAD

**Issue by rileylol72** [NatroTeam/NatroMacro#49]
### Have you searched the existing suggestions?

No

### What is your suggestion?

My suggestion is to make an mythic autohatcher by the until legendary method. sometimes it can take time to do until legendary to get mythics. there is a auto basic bee hatcher so I was wondering if this could be a possibility. until legendary saves your royal jelly instead of getting mythics the way of until mythic. this would be made for the same purpose as the gifted basic bee hatcher. to not sit there for an hour hatching eggs. It will auto click "use another" until it gets a mythic that gets detected.

### How will this improve Natro Macro?

So they can save their royal jellys while not having to do until mythic or sitting there for awhile and hatching royal jellys.

### What is your Discord username?

rileylol72_45103

**Comment by Noobyguy775** [comment]
The "Until Mythic" Auto-jelly setting achieves the same effect as "Until Legendary," so I don't really see why this would be useful
