### ISSUE TITLE
Honey Mask Equip for conversion

### ISSUE THREAD

**Issue by CLHoofie** [NatroTeam/NatroMacro#491]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

When converting a balloon blessing on the "every" setting make the macro equip the honey mask if the user has it for extra convert speed and then reequip the previous mask. Should definitely be an option because it would only benefit blue.

### How will this improve Natro Macro?

The honey mask greatly increases convert speed compared to the other masks in the game and when converting a big balloon blessing this could save lots of time allowing my time spent to be gathering then converting there for causing increased honey production.

### What is your Discord username?

mozzarellabreadstik

**Comment by DullSmallmega176** [comment]
HE HE HELL NAWWWWWW, same thing with honey mask, it will be such a reliability problem trying to re-equip the mask you were initially using (diamond mask or demon mask as great examplea) and overall it will waste so much time anyways
