### ISSUE TITLE
windows defender

### ISSUE THREAD

**Issue by Proffset134** [NatroTeam/NatroMacro#492]
### Have you searched the existing bug reports?

No

### What happened?

i am trying to download it, but it dosent let me beacuse it says something with windows defender and i cant download it

### Steps to reproduce

1. downloading the file
2.extracting the file 
3. double tap the start button
4. winddows defender pops up

### What would you expect to happen?

to let me join

### Natro Macro version

the latest

### What is your Discord username?

calle0538

**Comment by Noobyguy775** [comment]
You should be able to click __More info__ and then __Run anyway__. The detection is a false positive.

The files have been sent to microsoft, and they are pending review. After that, these errors should go away.
