### ISSUE TITLE
Easier Remote Control Commands

### ISSUE THREAD

**Issue by Joeytjuhh** [NatroTeam/NatroMacro#494]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

At the moment of writing this the commands are not that easy to remember. So my suggestion is that we have easier commands or slash commands like "/bugrun <bug> <loot?> <on/off>". 

### How will this improve Natro Macro?

Well, it would be easier to use and remember instead of checking back in the server if you forgot a command. I sometimes have that I do ?set bugrunladybugskill instead of bugrunladybugscheck. As check is not really fitting if it bassicly kills them.

### What is your Discord username?

yourlocalss

**Comment by ninjubaer** [comment]
We're aware that it would probably be user friendlier but slash commands require a connection between discord and `status.ahk` and that comes with downsides such as
higher resource consume and worse Compatibility (Websockets are not supported natively in Windows 8 and before)

this might be something for the future but it has very low priority

**Comment by Joeytjuhh** [comment]
> We're aware that it would probably be user friendlier but slash commands require a connection between discord and `status.ahk` and that comes with downsides such as higher resource consume and worse Compatibility (Websockets are not supported natively in Windows 8 and before)
> 
> this might be something for the future but it has very low priority

And the normal text commands? Is that an option?

**Comment by ninjubaer** [comment]
i'm not exactly sure what you mean by that...

**Comment by Joeytjuhh** [comment]
Like the "?set <very long word>" command, can that be easier like "?set bugrun ladybug kill true/1". Instead if "?set bugrunladybugscheck 1"
