### ISSUE TITLE
Natro Macro

### ISSUE THREAD

**Issue by samuelgamin** [NatroTeam/NatroMacro#495]
### Have you searched the existing bug reports?

No

### What happened?

idk why but everytime i start it it work fine but its failing by finding a bee hive slot (im new btw for this) but i wanna know what i do wrong 
![Schermafbeelding 2024-06-04 144955](https://github.com/NatroTeam/NatroMacro/assets/171693937/d562b3cb-6ef5-4704-8b35-146b3586f4be) idk if this picture wil work to show

### Steps to reproduce

1. i restarted roblo and then set it on
2. it saying reconnect succes and that things
3. and then it said failed finding hive slot everytime

### What would you expect to happen?

idk what to say here

### Natro Macro version

1.0.0.1

### What is your Discord username?

samsam_gaming

**Comment by Noobyguy775** [comment]
probably some of your graphics settings, anyway join the discord for support, https://discord.com/invite/natromacro
