### ISSUE TITLE
My natro macro doesnt work

### ISSUE THREAD

**Issue by Sxuja11z** [NatroTeam/NatroMacro#496]
### Have you searched the existing bug reports?

Yes

### What happened?

My character keeps resetting when ever i turn nitro macro on to farm

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

My nitro macro making millions of honey every day

### Natro Macro version

1.0.0.1

### What is your Discord username?

sxuja11z

**Comment by ninjubaer** [comment]
check out our [discord](https://discord.gg/natromacro) for help
