### ISSUE TITLE
does not go convert when bag is full or 95%

### ISSUE THREAD

**Issue by crazyman1231231** [NatroTeam/NatroMacro#498]
### Have you searched the existing bug reports?

Yes

### What happened?

i was macroing and then when my bag was full it didnt go convert

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

it should go convert and start macroing ahain

### Natro Macro version

1.0.0.1

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
