### ISSUE TITLE
Setting Presets

### ISSUE THREAD

**Issue by Exoticz-Pro** [NatroTeam/NatroMacro#499]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Can you please make a Presets feature, where macro settings are saved and someone won't have to change everything manually. This will really help lots of people out who have 2 or more accounts and/or others ask to macro for them because they can't. Hope this becomes a feature. :)

### How will this improve Natro Macro?

Users with multiple accounts won't have to keep changing every sing;le setting and can just toggle between 2 saved setting layouts.

### What is your Discord username?

titanium_white_fennec_freestylin

**Comment by Noobyguy775** [comment]
#77
