### ISSUE TITLE
infinite reset bug on new macro

### ISSUE THREAD

**Issue by progamerbssrizzler** [NatroTeam/NatroMacro#50]
### Have you searched the existing bug reports?

Yes

### What happened?

each time i start it it just resets my avatar how do i fix this

### Steps to reproduce

1.start
2.reset
3.rage

### What would you expect to happen?

i expected it to start macroing

### Natro Macro version

natromacro-096

**Comment by Noobyguy775** [comment]
Join the discord and ask for help there. This is not a bug, thanks!
