### ISSUE TITLE
I NEED HELP I BEG U

### ISSUE THREAD

**Issue by j12010** [NatroTeam/NatroMacro#505]
### Have you searched the existing bug reports?

No

### What happened?

when i activate the cannon movement method it bug and my character cant get the cannon becuz he keep walking to the right indefinitely

### Steps to reproduce

1.i put the macro to work
2.i put my hive number (1-6)
3.my character bug and he cant take the cannon

### What would you expect to happen?

i need him to take the cannon

### Natro Macro version

1.0.0.1

### What is your Discord username?

j12010/2

**Comment by Noobyguy775** [comment]
https://discord.gg/natromacro
