### ISSUE TITLE
Fast RJ Rolling Macro

### ISSUE THREAD

**Issue by ayriouss** [NatroTeam/NatroMacro#506]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Manually using Royal Jelly to roll for a specific bee can take a long time, but if you just drag the royal jelly to the bee you are rolling INSTEAD of pressing the roll again button resets the cooldown, allowing for if automated with a macro, an extremely fast bee rolling time. In the GUI, players could possibly choose what bee they'd like to roll for such as a gifted Bucko Bee. The "Auto-Mutator" GUI could possibly be implemented into the same GUI as this, giving the additional ability to add a mutated attribute to the bee. The GUI could be called "Royal Jelly Smart-Roller" or "Royal Jelly Fast-Roller", related names like that.

### How will this improve Natro Macro?

 If this feature this was implemented into Natro Macro, players would not have to manually waste time rolling jellies for a bee they want, and they would save lots of time especially when rolling for a rare bee such as a Buoyant Bee with a bar mutation, or just any bee in general. With the fact that this could almost instantly roll bees, this could be a very useful tool.

### What is your Discord username?

ayrious13

**Comment by Noobyguy775** [comment]
Thanks for the detailed issue!

Merging with #484 due to the functionally being tracked there
