### ISSUE TITLE
Download on mac (apple)

### ISSUE THREAD

**Issue by baeked05** [NatroTeam/NatroMacro#507]
### Have you searched the existing bug reports?

No

### What happened?

having trouble starting the program, when i click (start.bat), it only leads me to the apple store/notes or comes up as an error.

### Steps to reproduce

1. download natromacro.main
2.enter and click start.bat
3.

### What would you expect to happen?

open program to start natro macro farm

### Natro Macro version

main

### What is your Discord username?

cwru

**Comment by Noobyguy775** [comment]
read #254
