### ISSUE TITLE
Bucko Bee quests: retro blocks blocking path to ant challenge

### ISSUE THREAD

**Issue by Macisialek** [NatroTeam/NatroMacro#508]
### Have you searched the existing bug reports?

Yes

### What happened?

The retro blocks are blocking the path when macro wants to do ant challenge for bucko bee quests. Thats basically everything. (Its pretty important to me because im doing these quests for tide popper)

### Steps to reproduce

1. Just enable bucko bee quests.

### What would you expect to happen?

![image](https://github.com/NatroTeam/NatroMacro/assets/132828952/da4b56ba-03d5-4c04-80fc-fbe04d8ccb09)
these are the blocks that are blocking the path

### Natro Macro version

1.0.0.1a

### What is your Discord username?

macisialek

**Comment by DullSmallmega176** [comment]
allready fixed in the most current dev version :tm:. but if you want i can send over the file if needed, it's just a path that anyone can code and change

**Comment by Macisialek** [comment]
Sorry for the late reply. It would be great if you could send the file to me :)

**Comment by Noobyguy775** [comment]
changed in the upd, no more bricks :(
