### ISSUE TITLE
Mon natro macro ne fonctionne pas correctement.

### ISSUE THREAD

**Issue by Darkmega46** [NatroTeam/NatroMacro#509]
### Have you searched the existing bug reports?

Yes

### What happened?

Il fait tout les champs du jeux pour se reset juste après alors qu'il devait juste faire un seul champs.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

Que sa fonctionne.

### Natro Macro version

1.0.0.1

### What is your Discord username?

dark_meg

**Comment by misc-et** [comment]
Thanks for your report. This issue sounds like it may be due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
