### ISSUE TITLE
error going to hive

### ISSUE THREAD

**Issue by AlphaQ8566** [NatroTeam/NatroMacro#51]
### Have you searched the existing bug reports?

Yes

### What happened?

when i go to the hive it doesn't step on the or any platform i didn't even touch my keyboard in the video

https://github.com/NatroTeam/NatroMacro/assets/152464857/f9313a4b-df99-49d3-92c8-7fafeba91a68

![image](https://github.com/NatroTeam/NatroMacro/assets/152464857/fa9fd2b4-4b20-4d8f-bc66-41501ecf98f2)

### Steps to reproduce

use it and wait for the full backpack and to travel home

### What would you expect to happen?

step on my hive and convert my pollen to honey

### Natro Macro version

0.9.7

### What is your Discord username?

alphaq8566

**Comment by Noobyguy775** [comment]
It's probably due to your movespeed, anyway, this is not a bug, please ask for help on our [Discord](https://discord.com/invite/natromacro/)
