### ISSUE TITLE
don't convert my baloon 

### ISSUE THREAD

**Issue by kerox827** [NatroTeam/NatroMacro#510]
### Have you searched the existing bug reports?

Yes

### What happened?

hello i got a problem with the macro she doesn't take the canon and doesn't sell my backpack and my baloon plz help

### Steps to reproduce

1.i do nothing is like the beginning i use it
2.
3.

### What would you expect to happen?

https://github.com/NatroTeam/NatroMacro/assets/172142621/0a3c067c-c3e4-4cf6-add8-e26ecf71f68c

that doesn't sell my baloon help plss

### Natro Macro version

v.1.0.0.1a

### What is your Discord username?

kerox and my #add is kerox0777

**Comment by kerox827** [comment]
we don't see on the video but i show natro macro and is whrite converting baloon

**Comment by ssilz** [comment]
Your Roblox language **needs** to be set to English in order for the macro to work.

**Comment by misc-et** [comment]
Thanks for your report. Please follow the suggestion above to change your Roblox language, and you can check our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or raise a help ticket there for further support.
