### ISSUE TITLE
Keeps resetting 

### ISSUE THREAD

**Issue by Yobruh1178** [NatroTeam/NatroMacro#511]
### Have you searched the existing bug reports?

No

### What happened?

Every time I start it just moves my camera a little bit and resets my character and it just does it over and over again.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

well, I expected it to stop after doing all the things to get it to work, but it just continues to move my camera and reset my character.

### Natro Macro version

v1.0.0.1

### What is your Discord username?

yo_emery

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
