### ISSUE TITLE
report on command

### ISSUE THREAD

**Issue by rhni** [NatroTeam/NatroMacro#513]
### Have you searched the existing suggestions?

No

### What is your suggestion?

id be cool if natro macro (remote control) would have report on command like ?report 

### How will this improve Natro Macro?

i want it cause i dont wanna wait sometimes and some other ppl dont wanna wait eithier

### What is your Discord username?

woodyatbeach

**Comment by misc-et** [comment]
Thanks for this suggestion. As the hourly graphs are already frequent, this is unlikely to be a high priority, however I'll add it to https://github.com/NatroTeam/NatroMacro/issues/20 as a possible future addition.
