### ISSUE TITLE
Memory Match Bug

### ISSUE THREAD

**Issue by ssilz** [NatroTeam/NatroMacro#514]
### Have you searched the existing bug reports?

Yes

### What happened?

When traveling to a mm the macro can sometimes falsely detect the mm without it actually reaching it. And instead of resetting and trying again, it just stands still for 8 minutes then resets.

_I just wanna clarify that this is a pretty rare occurrence and has happened twice for me as far as I know_ 

In the first example it even died, but due to it thinking it found the mm it stands still at the hive for 8 minutes

![Screenshot_20240613_141937_Discord](https://github.com/NatroTeam/NatroMacro/assets/69845785/2a0ee454-2350-48e5-ae2d-817ef61b7410)
![Screenshot_20240613_145523_Discord](https://github.com/NatroTeam/NatroMacro/assets/69845785/12058cf1-1faa-4892-bb98-85151a98dcc1)

### Steps to reproduce

1. Enable any memory match (so far has happened with mega and night mm)
2. Start the macro and wait till it happens
3.

### What would you expect to happen?

I expected it to detect that there is no memory and try again.

### Natro Macro version

1.0.0.1a

### What is your Discord username?

ssilz

**Comment by Noobyguy775** [comment]
Adding to #501, thank you very much for reporting!
