### ISSUE TITLE
Loot Reports

### ISSUE THREAD

**Issue by politotitolol** [NatroTeam/NatroMacro#517]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

In the hourly graphs, another image or section could be implemented to show what fruit/loot is picked up. For example, 3,000 strawberries picked up. It could be a graph or just a simple statistic.

### How will this improve Natro Macro?

Many users, like me, macro for crafting items, not for honey. And it’s inconvenient to pause the macro and check the inventory all the time. This feature, in conjunction with RC, could make for an excellent tool for ingredients.

### What is your Discord username?

polikfc123

**Comment by misc-et** [comment]
Thanks for this suggestion, loot reports at some frequency would likely be a popular addition. I'll close this issue and add it to https://github.com/NatroTeam/NatroMacro/issues/20
