### ISSUE TITLE
be able to choose which account you are opening

### ISSUE THREAD

**Issue by cobalt-source** [NatroTeam/NatroMacro#519]
### Have you searched the existing suggestions?

No

### What is your suggestion?

for remote desktop protocol it could help if you added some type of chromium to get your roblox acc info, then you will be able to choose which account you want to reconnect with

### How will this improve Natro Macro?

it would help me build my fuzzy alt easier, because it is a hassle figuring it out other ways

### What is your Discord username?

cobalt_2

**Comment by misc-et** [comment]
Thanks for your suggestion. Generally the macro will not include features that require integration with third party software, for a range of security and other reasons. You can set the account to reconnect with by ensuring you are logged in to the correct account on your default Roblox app (see Default Apps in Windows settings), but enabling login to different Roblox accounts is not something the macro would be able to support.
