### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by gaegcheong** [NatroTeam/NatroMacro#52]
### Have you searched the existing bug reports?

No

### What happened?

대포를 안타고 그냥 넘어가는데요 속도가 31.2 인데 그렇게 맞게 설정해도 안되요

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

해결해주세요

### Natro Macro version

최근

### What is your Discord username?

현진

**Comment by Noobyguy775** [comment]
디스코드에 참여하여 한국어 채널에서 도움을 요청하세요.
https://discord.com/channels/1012610056921038868/1050966850818814093
