### ISSUE TITLE
Reseting bug glitch 

### ISSUE THREAD

**Issue by 00DirtyDan00** [NatroTeam/NatroMacro#520]
### Have you searched the existing bug reports?

No

### What happened?

when i start the nitro it reset my charcter at the hive and does not move. I watch some videos and i followed what they said and it still does not work for me.

### Steps to reproduce

1.press start on the macro 
2.it reset the first time to get ready to move 
3. then resets over and over and never ends 

### What would you expect to happen?

move to a sertin field and start collecting pollen. 

### Natro Macro version

v1.0.0.1

### What is your Discord username?

0_dirty_dan_0

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
