### ISSUE TITLE
the macro keeps auto resetting, i just dowwloaded it so im very thankful if someone helps me fix this issue.

### ISSUE THREAD

**Issue by shunshu01** [NatroTeam/NatroMacro#521]
### Have you searched the existing bug reports?

No

### What happened?

whenever i start the macro it always resets.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i expected it to work, but no it keeps resetting 

### Natro Macro version

v1.00.01

### What is your Discord username?

shun_shu

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
