### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by goodiesx** [NatroTeam/NatroMacro#523]
### Have you searched the existing bug reports?

No

### What happened?

it reconnects but doesnt claim hive just stands in one  place

### Steps to reproduce

1.it reconnects
2.stands in place
3.it for some reason also reconnects my roblox app that has a different user logged in it

### What would you expect to happen?

that it knows how to reconnect

### Natro Macro version

1.0.0.4

### What is your Discord username?

goodiesc

**Comment by ssilz** [comment]
The macro will always use the account logged into the Roblox app since it uses deeplink, unless you use the browser reconnect method (not recommended)

**Comment by misc-et** [comment]
You can also change your default Roblox app to be the one that you would like to use via Default Apps in windows settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
