### ISSUE TITLE
Blank 'Pattern Shape' options :P

### ISSUE THREAD

**Issue by SirRellCell** [NatroTeam/NatroMacro#524]
### Have you searched the existing bug reports?

No

### What happened?

I tried to choose a pattern shape to macro pepper but it kept on being blank:
![image](https://github.com/NatroTeam/NatroMacro/assets/173502164/df87dfaf-e315-4800-98dd-65ff74b83c86)
im not sure if im using it wrong but it's just blank!

### Steps to reproduce

reproduce?

### What would you expect to happen?

it's hadn't been like that before so i expected pretty much it being there

### Natro Macro version

Nature_macro_v10.0.1a

**Comment by SirRellCell** [comment]
I hope you could inform me on this problem or fix it, thanks :)

**Comment by ssilz** [comment]
Try redownloading the macro. If you want to keep your settings you can just copy all files in the settings folder then transfer them into the settings folder of the newly downloaded natro (the new folder will first appear when you run the macro)

**Comment by misc-et** [comment]
Yep, try re-downloading the macro as suggested and if you have further issues, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or raise a help ticket there for support.
