### ISSUE TITLE
Shiftlock not working

### ISSUE THREAD

**Issue by Mrjamedd** [NatroTeam/NatroMacro#526]
### Have you searched the existing bug reports?

No

### What happened?

I was macroing with shiftlock enabled but my macro was not using shiftlock

### Steps to reproduce

1. Makeing thr macro click shift
2. Above
3.above

### What would you expect to happen?

I expected shiftlock to acctivate

### Natro Macro version

V 1.0.01

**Comment by misc-et** [comment]
Thanks for your report. If you would like to use shift lock, ensure you are using the web browser version of Roblox, as the Microsoft Store version does not support it. 

If you are still having difficulties or need help switching Roblox versions, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
