### ISSUE TITLE
Natro macro is broken

### ISSUE THREAD

**Issue by Deficy** [NatroTeam/NatroMacro#527]
### Have you searched the existing bug reports?

No

### What happened?

When i start it it seems fine but when it gets to the field it normally places the sprinklers so it does that then it walks straight then like curves and stops and just resets i have been trying to fix it for a while it is not working help me 

### Steps to reproduce

1.i
2.dont
3.know

### What would you expect to happen?

its supposed to go to the field place sprinklers then do the pattern that i set it to do in natro macro

### Natro Macro version

latest one 1.0.0.1

### What is your Discord username?

Deficy

**Comment by misc-et** [comment]
Thanks for your report. This sounds like it is due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
