### ISSUE TITLE
vicious bee killing 

### ISSUE THREAD

**Issue by SkyesBees** [NatroTeam/NatroMacro#529]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Have the macro detect the red circles from vicious bees attacks or find an easier way to limit deaths when fighting vicious bee or other threats.

### How will this improve Natro Macro?

while the macro runs with the vicious bee kill cycle going, once the bee is discovered it can take the player a long while to kill the bee (bees catching up from the cannon and repetitive dying) if the macro can detect attacks and avoid them, killing the vicious bee would be quicker and allow players to return to gathering sooner as killing the bee can take a long time when the player is only on the field for a short while before dying. 

This sort of detection could also be useful for normal bug runs to prevent the character from running into the bugs and killing themselves. this could also help to avoid mondo chick. if the change requires reading larger portions of the screen, the macro could then lead to detecting and picking up nearby tokens in the future.

### What is your Discord username?

SeltzerGames

**Comment by Noobyguy775** [comment]
If this is implemented, it'll probably cause more deaths and lost stingers.

Detecting the Supreme Saturator already causes enough problems, and the attack indicator directly below the character and slowly fades in, which makes it very hard to detect reliably
