### ISSUE TITLE
Natro sometimes ignores F2/F3.

### ISSUE THREAD

**Issue by ajd07** [NatroTeam/NatroMacro#532]
### Have you searched the existing bug reports?

Yes

### What happened?

For some reason, Natro will not pick up that you pressed F2/F3 at times. I don't even know what causes it.

### Steps to reproduce

1. Start macro
2. Something triggers (maybe like collecting or something?)
3. Attempt to press F2/F3 to pause/stop the macro.

### What would you expect to happen?

You'd expect it to well... stop the macro.
But it doesn't! It just ignores the inputs entirely??? Then doesn't randomly?

### Natro Macro version

v1.0.0.1a

### What is your Discord username?

pockies

**Comment by misc-et** [comment]
Thanks for your report. This may be due to some other PC settings / factors rather than the macro itself. To help us look into it a little further, though, could you provide more information about when exactly it happens, a video of the issue, and a screenshot the webhook at the time that it happens?

**Comment by ajd07** [comment]
I'll have to try to get it to trigger again. I have to use FN then a number key so maybe that has to do something? There's nothing that goes through the webhook since Natro ignores the input entirely and keeps going when it does occur.

**Comment by ajd07** [comment]
![image](https://github.com/NatroTeam/NatroMacro/assets/69254409/45a1de21-307b-469d-ace2-c014c1b3064f)
I attempted to press F2 and F3 multiple times while it was spam resetting, I had to directly go to the UI to stop the macro.

**Comment by misc-et** [comment]
Apologies for the slow reply - I was on break. It does sound likely to be an issue with settings, rather than a bug. If it's still happening, see our [Discord server](https://discord.com/invite/natromacro) for support.
