### ISSUE TITLE
Server hopper for windy bee

### ISSUE THREAD

**Issue by Hector1404** [NatroTeam/NatroMacro#535]
### Have you searched the existing suggestions?

No

### What is your suggestion?

It would join a random server, check if the wind shrine is shaking (idk how to say it but checking if windy bee is spawned) and if it isn't join another server again and repeat

### How will this improve Natro Macro?

many people need cloud vials either for boosts, getting windy bee or quests and the 1 hour cooldown makes it very time consuming and annoying to spawn the bee on your own

**Comment by misc-et** [comment]
Thanks for this suggestion. It may be possible to detect a current windy bee in a server, but it would be difficult for a macro to locate it in fields, avoid attacks, and defeat it, so I'll close this suggestion.

**Comment by Hector1404** [comment]
It doesnt need to kill it, js find it

Em seg., 1 de jul. de 2024 11:36 PM, misc ***@***.***>
escreveu:
