### ISSUE TITLE
continually resetting

### ISSUE THREAD

**Issue by saltbug** [NatroTeam/NatroMacro#536]
### Have you searched the existing bug reports?

Yes

### What happened?

whenever i start up the macro and it loads the server, im just standing there, resetting.

### Steps to reproduce

1. Boot up natro macro so it loads BSS

### What would you expect to happen?

To select a hive slot and go to the selected field

### Natro Macro version

V1.0.0.1

### What is your Discord username?

bugsaltforsomereason

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
