### ISSUE TITLE
Auto Nectar bottling

### ISSUE THREAD

**Issue by TheGold25** [NatroTeam/NatroMacro#537]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I use a lot of manual planters for resource gathering, and so I have a lot of a few nectars and none of others. I think that if it was possible to make nectars auto bottle when over a set percent, lets say like 60% and the viles are less than 10 then it would bottle it. Now for the stickers that are possible, well you could make it optional to get the stickers and do a reset and path or just not include it (I wouldnt be too offended not having one but its up to the team if its possible). Also another side note more manual planters cycles would be a nice addition.

### How will this improve Natro Macro?

I think that this would help a lot of people, especially with more end game equipment needing viles, and it also acts as a storage of viles that way you can have them for the future with boosts and other things. Especially if you made it compatiable for both manual and auto planters as a toggle on or off.

### What is your Discord username?

TheGold25

**Comment by misc-et** [comment]
Thanks for your suggestion and this detail. I'll close and add to existing suggestion https://github.com/NatroTeam/NatroMacro/issues/282
