### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by Gardi09** [NatroTeam/NatroMacro#539]
### Have you searched the existing bug reports?

No

### What happened?

It is not reconnecting me to a public server

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

For it to recconect to a public server

### Natro Macro version

1.0.0.1

### What is your Discord username?

liongardi

**Comment by misc-et** [comment]
Thanks for your report. This may be due to your settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
