### ISSUE TITLE
Reset Loop

### ISSUE THREAD

**Issue by VoxNiphili** [NatroTeam/NatroMacro#540]
### Have you searched the existing bug reports?

No

### What happened?

Yea, I keep getting my character resetting.

### Steps to reproduce

1. Start up Natro
2. Set up field i'm in
3. Start

### What would you expect to happen?

Pauses, resets character.

### Natro Macro version

Latest

### What is your Discord username?

somerando1470

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
