### ISSUE TITLE
Natro macro in the background

### ISSUE THREAD

**Issue by Sushi37** [NatroTeam/NatroMacro#541]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Natro should add a feature to allow to use the Natro macro in the background. 

### How will this improve Natro Macro?

This could help a lot of people to do their task or anything else while they use Natro macro on the same device, which some people might not have a different device to do their task or use Natro macro, which could help a lot if the Natro macro could be in the background while others could be doing tasks.

### What is your Discord username?

sushishi1064

**Comment by lordlevstar** [comment]
you can do this via rdp, there is no other way

**Comment by DullSmallmega176** [comment]
same post as https://github.com/NatroTeam/NatroMacro/issues/542 but worded differently

**Comment by misc-et** [comment]
Thanks for your question, as suggested this can be achieved using for example RDP, but not as a feature of the macro itself. 

For more info and support, see our [discord server](https://discord.gg/natromacro)

**Comment by Sushi37** [comment]
okay thanks
