### ISSUE TITLE
A feature to add a black screen

### ISSUE THREAD

**Issue by Sushi37** [NatroTeam/NatroMacro#542]
### Have you searched the existing suggestions?

No

### What is your suggestion?

This feature just adds a black screen while you macro.

### How will this improve Natro Macro?

I think this might be helpful if this feature was added because let's say that I and others would like to keep their device on to macro while they go to sleep and to have this black screen this might use less power because it's only a black screen that pops up and it could help so that bright lights from the screen would not bother others while they sleep or doing anything else

### What is your Discord username?

sushishi1064

**Comment by DullSmallmega176** [comment]
technically there is RDP and just simply *turning off your monitor* <---(but this will break or not after a rejoin)
so at the moment there really isn't anything that could be done but this is an interesting suggestion

![image](https://github.com/NatroTeam/NatroMacro/assets/133727755/18c96c57-74c2-44bd-ba65-2a3708c559a2)

**Comment by misc-et** [comment]
As Dully has mentioned, see https://github.com/NatroTeam/NatroMacro/issues/541
