### ISSUE TITLE
Hive Hub AFK 

### ISSUE THREAD

**Issue by LilTRok** [NatroTeam/NatroMacro#543]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I think that adding Hive Hub afk a feature because my computer consistently disconnects from the game while afking and having a macro to reconnect automatically would be a very useful feature

### How will this improve Natro Macro?

It will provide even more to the incredible versatility of Natro Macro

**Comment by misc-et** [comment]
Thanks for this suggestion, closing as it's been suggested in https://github.com/NatroTeam/NatroMacro/issues/379
