### ISSUE TITLE
Path to Red Field booster sometimes fails (misses doorway)

### ISSUE THREAD

**Issue by rpertusio** [NatroTeam/NatroMacro#544]
### Have you searched the existing bug reports?

Yes

### What happened?

- Path to red booster (while set to Move method 'Cannon') misses the doorway to Red HQ
- Fails multiple times a day (
- Happens on multiple PCs and multiple accounts.
- Discord shows occasionally other people experience the same issue

### Steps to reproduce

1. Set Movespeed correctly
2. Set macro to Red booster

### What would you expect to happen?

Should travel through doorway (but it is short by 1 and it runs into the doorway)

### Natro Macro version

1.0.0.1

### What is your Discord username?

CPx4

**Comment by rpertusio** [comment]
Path gtb-red.ahk can be adjusted with the following line:

	nm_Walk(1, FwdKey)

to be added on line 50 (immediately following:  	nm_Walk(8, FwdKey, RightKey)  )

**Comment by rpertusio** [comment]
Submitted a Pull Request in the private repo to fix this.

**Comment by misc-et** [comment]
thanks very much for putting through a fix for this! it's a common issue.
