### ISSUE TITLE
lower level people

### ISSUE THREAD

**Issue by 123dp3** [NatroTeam/NatroMacro#547]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Hi I am a lower bee swarm player and I love to use this program and when I use this hardwhere it always gos to the 25 discoverd bees canin and I dont have this so the sytem gliches out and I cant use this if possable can you make it so the lower level people can use this program  

### How will this improve Natro Macro?

it will benift me and othe rmico users because I can use this program properly

### What is your Discord username?

123dp3

**Comment by 123dp3** [comment]
here is a vido to help 
[Uploading Untitled video - Made with Clipchamp.zip…]()

**Comment by misc-et** [comment]
You can use the macro with fewer than 25 bees by selecting move method walk in the Natro settings tab, instead of move method cannon. 

Check our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
