### ISSUE TITLE
error starting macro

### ISSUE THREAD

**Issue by yaco01** [NatroTeam/NatroMacro#548]
### Have you searched the existing bug reports?

No

### What happened?

![image](https://github.com/NatroTeam/NatroMacro/assets/175175287/36bfbdde-ef32-48f5-a60c-6d067ad2dd6a)

### Steps to reproduce

1. When I start the macro I get the alert that the GUI offset cannot be detected in the game
2. Then when I accept the alert the only thing the macro does is restart the character, it never moves
3. 

### What would you expect to happen?

![problema](https://github.com/NatroTeam/NatroMacro/assets/175175287/17b702ca-db18-49ce-9ded-b3f57c87f536)

I would like you to help me with this problem I have.

### Natro Macro version

Natro_Macro_v1.0.0.1

### What is your Discord username?

yaco_01#1099

**Comment by misc-et** [comment]
Try the steps listed in the pop up message. 

If you're still having the issue, check our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
