### ISSUE TITLE
Add CV2

### ISSUE THREAD

**Issue by TheCukitoDev** [NatroTeam/NatroMacro#55]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Use cv2 to collect every toven and kill puphsrooms,... 

### How will this improve Natro Macro?

because this will make the macro better

### What is your Discord username?

.cukito

**Comment by zspz** [comment]
@TheCukitoDev
Implementing token detection through OpenCV is much easier said than done. There would be false positives and other objects being detected in any untrained model. It would likely not provide nearly as much benefit relative to the effort required to implement.
One thing to note: if it were that easy to add certain AI solutions to BSS macros, it would already be done by others and you would see many other macros.
