### ISSUE TITLE
Jump Power Calculator!

### ISSUE THREAD

**Issue by MohamadAlawedat** [NatroTeam/NatroMacro#551]
### Have you searched the existing suggestions?

No

### What is your suggestion?

New Players don't have the fancy boots from Mountain top or somewhere else. the Jump power is low, so add a setting for jump power and calculate like you do with walk speed

### How will this improve Natro Macro?

When it goes to collect from the ticket, blueberry, and strawberry dispensers, it fails to collect them. This will somewhat guarantee you get the most you could out of those dispensers because it attempts to do it 2 Times so you 'll probably get collect it everytime without fail

### What is your Discord username?

KillerFrust#2226

**Comment by misc-et** [comment]
Thanks for this suggestion, as with your other post your issues are likely to be due to a problem with your settings rather than a macro bug. I'd recommend checking the discord server for troubleshooting information and to raise a support ticket.
