### ISSUE TITLE
coconut crab macro detects falling coconuts 

### ISSUE THREAD

**Issue by wlven-wow** [NatroTeam/NatroMacro#552]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

make it so that the macro can detect falling coconuts and avoid them when activating the coconut crab macro

### How will this improve Natro Macro?

i want this feature to be added since instead of relying on luck and bee power to just kill the crab and staying alive, we can actually kill the crab automatically with no issues depending on bee power and luck. this benefits those who are in around early-mid game and it just makes it easier to kill the crab. 

it solves inconsistency and just makes it more easier for people to use

### What is your Discord username?

wlven

**Comment by wlven-wow** [comment]
is this suggestion just bad towards the point no one bothers with this

i get that the better the level the better you’ll kill the crab, but all of my bees are level 12+, so none of them miss any attacks

i usually kill the crab in 5 minutes without macro, so this feels like an annoying problem to me, especially since the coconuts will fall based on where you are, making them hit me half the time while it goes to the corner

**Comment by peacocksir** [comment]
This would be very hard to implement, and would take a lot of testing and not even be that good either. Killing crab is also thought of as something you do yourself and is a hard task for the macro to do.
