### ISSUE TITLE
bessmas bug

### ISSUE THREAD

**Issue by GANDALV1** [NatroTeam/NatroMacro#554]
### Have you searched the existing bug reports?

No

### What happened?

I am having a problem because i can't select anything on the beesmas thing

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I would expect  the macro to enable the beesmas options

### Natro Macro version

1.0.0.1

### What is your Discord username?

GANDALV

**Comment by Noobyguy775** [comment]
Should be fixed on all recent versions (0.9.7+)
