### ISSUE TITLE
Auto sticker printer

### ISSUE THREAD

**Issue by AmoebalokaxD** [NatroTeam/NatroMacro#555]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add an auto sticker printer. This function will automatically put an egg of your choice in the sticker printer,

### How will this improve Natro Macro?

This will be very important for completing the Beesmas 2024 quests, because there are many quest that require specific stickers.

### What is your Discord username?

amoebaloka

**Comment by DarkReaper7626** [comment]
this already exists
its in the boost section
