### ISSUE TITLE
Detect sticker spawns

### ISSUE THREAD

**Issue by DarkReaper7626** [NatroTeam/NatroMacro#556]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

make natro detect when a sticker spawns using the rainbow message in the corner and pings the user so they can go collect it 

### How will this improve Natro Macro?

this would help immensly with getting the stickers for the beesmas quests as you could more efficiently macro stickers as you would only need to check on it when a sticker spawns instead of praying it spawns where you will walk and being able to collect it

### What is your Discord username?

.giftedbasicbee

**Comment by TheInfernoWarior4** [comment]
I completely agree, I was just writing a suggestion just like this

**Comment by Noobyguy775** [comment]
sadly this is functionally impossible
