### ISSUE TITLE
bug with cannon

### ISSUE THREAD

**Issue by bareber** [NatroTeam/NatroMacro#557]
### Have you searched the existing bug reports?

No

### What happened?

Hello, I have a problem, i bet on afk farm and i dont have a cannon running and for this i cant get to the pollen that i need.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

video is big sorry i cant give video

### Natro Macro version

1.0.0.1v

### What is your Discord username?

barber_azamat

**Comment by bareber** [comment]
Uploading Видео без названия — сделано в Clipchamp (1).mp4…

**Comment by misc-et** [comment]
Thanks for your report. This issue can happen due to incorrect settings or using an old version of the macro, please see our [discord server](https://discord.gg/natromacro) Knowledge Base for further information or you can raise a help ticket there for support.
