### ISSUE TITLE
SNOWBEAR KILLER

### ISSUE THREAD

**Issue by meherchw** [NatroTeam/NatroMacro#559]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add a snowbear killer, this is so important because it allows to get the most out of the beesmas catalog. The snowflakes needed for most items in the catalog total to hundreds of thousand snowflakes and macroing in fields only gives around 500 to a thousand per night. Having a snow bear killer that's a high level gives approximately a few thousand per night allowing a player to accumulate enough to buy most items in the catalog plus snowflakes are very op during beesmas for full grinds considering full stack abilities

### How will this improve Natro Macro?

It's such a crucial part of beesmas especially to save up for all endgame items. For 2024 the Beesmas catalog has so many items and being able to purchase most of them makes buying end game items easier. To be specific, having a snowbear killer would produce snowflakes in the hundreds every hour and a half and having this macro overnight would be overpowered. Even if the snowbear is above a players level, fighting it at all produces rings of snowflakes which can add up to thousands in a night. overpowered. I believe this is also very helpful for lower level players too so they can further in the game and use the snowflake buff for grinding.

### What is your Discord username?

meher

**Comment by ALiteralDodo** [comment]
I mean it's possible but that'd be hard to do considering natro cant always know where a bear is, best it'd do is move in randoms spots while jumping for a minute and you gotta hope ur bees can kill the sb

**Comment by Noobyguy775** [comment]
Not really possible/in the scope of the macro

Most of the time it would die anyway, especially at high levels
