### ISSUE TITLE
Sticker Printer

### ISSUE THREAD

**Issue by kkout2** [NatroTeam/NatroMacro#560]
### Have you searched the existing suggestions?

No

### What is your suggestion?

A part of the macro where like the dispensers and such are, add a Sticker Printer section. It buys whatever egg(s) you want it to and it uses the egg every hour.

### How will this improve Natro Macro?

I personally want this because beesmas requires a lot of stickers and this would help not only me, but also others to get stickers while macroing.

### What is your Discord username?

coolbeans1000

**Comment by misc-et** [comment]
This is already in the macro, and can find it in the Boost tab (together with Sticker Stacker).
