### ISSUE TITLE
Respawn waiting

### ISSUE THREAD

**Issue by NightKnight0406-bit** [NatroTeam/NatroMacro#561]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add a delay after each Respawn so the Character waits like 5 or 10 seconds or a custom number that the player can insert themself

### How will this improve Natro Macro?

For me its a problem with Bugruns in BSS where my Character is "collecting" the items but my bees arent even there to kill the Monster 

### What is your Discord username?

NightKnight0406

**Comment by Noobyguy775** [comment]
already exists in settings tab
both hive bees and wait *x* time after convert achieve this
