### ISSUE TITLE
Closing and not reopening roblox

### ISSUE THREAD

**Issue by Yuhdeds** [NatroTeam/NatroMacro#562]
### Have you searched the existing bug reports?

No

### What happened?

I have the microsoft version of roblox installed and it keeps closing it when i startup the macro.

### Steps to reproduce

1.
2.
3.
o

### What would you expect to happen?

l

### Natro Macro version

v1.0.0.1

### What is your Discord username?

yuhdeds

**Comment by Noobyguy775** [comment]
Join the discord for support
https://discord.gg/natromacro
