### ISSUE TITLE
MICRO IS NOT WORKING

### ISSUE THREAD

**Issue by athenaPURRR** [NatroTeam/NatroMacro#563]
### Have you searched the existing bug reports?

No

### What happened?

Everytime I enable micro, its keeps resetting me none stop. 

### Steps to reproduce

1. updat5e my micro script
2. change the graphic 
3. search in youtube for help on how to fix my micro when it's bugging

### What would you expect to happen?

for my micro to stop constantly resetting me.

### Natro Macro version

Natro Macro v1.0.0.1

**Comment by XRay71** [comment]
Please see #540
