### ISSUE TITLE
Cannot get character to move to field

### ISSUE THREAD

**Issue by potatomanref** [NatroTeam/NatroMacro#564]
### Have you searched the existing bug reports?

No

### What happened?

Using Natro Macro v.1.0.0.1 with Bee Swarm Simulator.
The character just keeps resetting, or resets, goes to hive, and moves in a circle and resets. I cannot get the character to go to any field. I appreciate your help!

### Steps to reproduce

1. Start Bee Swarm Simulator
2. Start Natro Macro with Bamboo in field, and walk d
3. Run Macro

### What would you expect to happen?

The character should go to the field and start making honey

### Natro Macro version

1.0.0.1

### What is your Discord username?

potatomanref; anne78c@gmail.com

**Comment by Noobyguy775** [comment]
Join the discord for assistance
https://discord.gg/natromacro
