### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IdiotStickMoron** [NatroTeam/NatroMacro#565]
### Have you searched the existing bug reports?

Yes

### What happened?

When I macro It will grind once after claiming the hive, the first grind goes just fine everything works. But when the macro resets to start the next cycle the macro resets 10 times, rejoins, and repeats. If the macro doesn't stay in the game grinding it can't get the wealth clock, and it makes getting mother bears gingerbread house more difficult to stack bears over night.

### Steps to reproduce

1. I start the macro
2. It claims the hive and uses the cannon to get to strawberry
3. It works fine and resets, going back to my hive
4. It resets 10 times and joins again repeating everything

### What would you expect to happen?

It obviously shouldn't reset 10 times and rejoin, it should just grind and claim wealth clock.

### Natro Macro version

V1.0.0.1a

### What is your Discord username?

IdiotStick

**Comment by Noobyguy775** [comment]
https://discord.gg/natromacro
