### ISSUE TITLE
sticker printer tool

### ISSUE THREAD

**Issue by kindasmart1247** [NatroTeam/NatroMacro#567]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Added onto the auto sticker printer could be an auto discard option, allowing the user to select (like a popup list with the names/pic's of each sticker with a check box next to the stickers) which stickers they don't need along with an option to keep certain stickers or even have a detect and save option for the stickers needed for quests. 

### How will this improve Natro Macro?

I noticed that its quite a pain trying to make space for better stickers and having to go back and fourth from the sticker book to the quests a lot to figure out which stickers I don't need and which ones I do. Having the sticker sorter would remove the headache of making sure the right ones are kept and non-important stickers discarded.

### What is your Discord username?

._.9076

**Comment by Noobyguy775** [comment]
dupe of #438
