### ISSUE TITLE
macro doesn't garthers in the selected field but go into some random places and starts collecting pollen at that place ex: king bettle tunnel

### ISSUE THREAD

**Issue by kylerisagamer** [NatroTeam/NatroMacro#569]
### Have you searched the existing bug reports?

Yes

### What happened?

macro sometimes not gathering/ placing planters but just going to someplace like king bettle or be at the 35 bees zone entrance and gather at that place other than pepper as i selected  

### Steps to reproduce

1.start macro with the selected fields / planter section
2.begin to claim hives and start to gather as it used to 
3.after sometimes macro return then doesn't follow what it used to

### What would you expect to happen?

it should work like before 

### Natro Macro version

1.0.0.1

### What is your Discord username?

kylerisagamer

**Comment by Noobyguy775** [comment]
you enabled those features, so the macro goes to do them

**Comment by kylerisagamer** [comment]
not its just staying gather at king beetle and i know what i enabled and what it suppose to be

> you enabled those features, so the macro goes to do them

**Comment by kylerisagamer** [comment]
and sometimes it doesn't gather with the pattern i selected its just using the large X not Xsnake or cornerXsnake
