### ISSUE TITLE
Quest Detection

### ISSUE THREAD

**Issue by calissilly** [NatroTeam/NatroMacro#570]
### Have you searched the existing bug reports?

Yes

### What happened?

Please add an option where you can edit or change the current quest you are on. When I use the quest feature within the macro, it doesn't detect if I've done quests myself and am on a different quest. For example, I stopped macroing while on the "Riley Bee: Medley" quest and did quests myself until the "Riley Bee: Rampage" quest. When I go back to macroing, the macro still tries to complete the Medley quest. I've only used the macros quest feature on Riley Bee's quests, but I believe that this issue occurs with all the other quest givers.

### Steps to reproduce

1.Enabling A quest
2.Cycling through quests yourself

### What would you expect to happen?

The macro still tries to complete the past quest.

### Natro Macro version

1.0.0.1a

### What is your Discord username?

Blackxcle

**Comment by Noobyguy775** [comment]
use the discord for support regarding this
https://discord.gg/natromacro
