### ISSUE TITLE
run speed

### ISSUE THREAD

**Issue by tmcrasheddat** [NatroTeam/NatroMacro#571]
### Have you searched the existing bug reports?

Yes

### What happened?

when i was using the macro, i collected a haste and then the macro stopped doing the pattern the same i came back to my pc after and my character was not on the field 

### Steps to reproduce

1.i close macro
2.re open macro
3.and repeat

### What would you expect to happen?

for the move speed to alter with the haste and it should automatically update

### Natro Macro version

Natro_Macro_v1.0.0.1

**Comment by Noobyguy775** [comment]
fixed by general troubleshooting, look in knowledge base in the discord server
