### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by UnknownHideout** [NatroTeam/NatroMacro#572]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Basically macro will check every single location, where sticker could spawn and will claim it.

### How will this improve Natro Macro?

Stickers is the one of main mechanics right now, stickers needs for Beesmas event, you can trade or them or use them for boosts.

### What is your Discord username?

unknown_hideout

**Comment by Noobyguy775** [comment]
not realistic
