### ISSUE TITLE
Automatic Tabby Love Picker

### ISSUE THREAD

**Issue by Puffy1787** [NatroTeam/NatroMacro#575]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

For the collect section you could add one for tabby love dropped by the tabby bee just like the baby love. This would make the process of getting x1000 tabby love much easier

### How will this improve Natro Macro?

This would benefit many people who use natro macro because it greatly reduces the amount of time needed for manually grinding for the tabby love token.

### What is your Discord username?

puffy1020

**Comment by Noobyguy775** [comment]
The baby love detection just looks for when baby love is active, nothing else, and I don't see a use for seeing what tabby love you have
Plus, you can get max tabby love in like 50 hours of macroing anyway
