### ISSUE TITLE
Neonebrry auto feeder

### ISSUE THREAD

**Issue by Zealoussssss** [NatroTeam/NatroMacro#576]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I suggest a neonberry auto feeder, it would be super useful for getting the blob bumble bee sticker and a good thing to get mutations

### How will this improve Natro Macro?

I think people will use it cince its hard to come by this beesmas cince its a sticke for onetts litt art

### What is your Discord username?

My discord username is Henrik :)

**Comment by Noobyguy775** [comment]
You can already feed multiple neonberries at once
