### ISSUE TITLE
Natro Macro not working when screen is off.

### ISSUE THREAD

**Issue by GreenBob94** [NatroTeam/NatroMacro#578]
### Have you searched the existing bug reports?

Yes

### What happened?

When i turn my screen off to macro, i stop getting updates on discord, my character constantly resets, the macro will close roblox and try to open it indefinately.

### Steps to reproduce

1.Start the macro
2.Turn off the screen
3.Wait 20 mins
4.Turn on screen

### What would you expect to happen?

The macro to carry on as normal when the screen is off

### Natro Macro version

v1.0.0.1

### What is your Discord username?

GreenBob94

**Comment by Noobyguy775** [comment]
Not an issue with the macro, though there are ways around it, join the discord for help
https://discord.gg/natromcaro

**Comment by bylbatron** [comment]
как решить эту проблему?
