### ISSUE TITLE
Converting balloon problem

### ISSUE THREAD

**Issue by SomethingSpecial0** [NatroTeam/NatroMacro#579]
### Have you searched the existing bug reports?

No

### What happened?

It wont let me convert my balloon

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

Me converting my balloon at the time I want it to

### Natro Macro version

1.0.0.1

### What is your Discord username?

something_special0

**Comment by Noobyguy775** [comment]
It's your balloon setting in the **Settings** tab
