### ISSUE TITLE
Nectar Condenser 

### ISSUE THREAD

**Issue by Jacob31gone12i** [NatroTeam/NatroMacro#580]
### Have you searched the existing suggestions?

No

### What is your suggestion?

This feature would have the macro collect nectars and then if it gets to a certain point (12 hours of what ever nectar) it would then go to the nectar condenser and condense the nectar into a vial  and this can continue to happen for 1-10 times and then there would be a option to go back to the regular nectar gather settings

### How will this improve Natro Macro?

I would like this feature to be added in because with the new update items now require nectar vials (like the coco canister and endgame tools) and with this feature in the macro this can help players grind for these items without having to manually go back and stopping the macro just to do this a couple of times. This can also help players keep these nectars full when they or someone else turns off the macro.

### What is your Discord username?

Jacob_31gone12i #6535

**Comment by Noobyguy775** [comment]
Merging w/ #282
