### ISSUE TITLE
Getting stuck on ramp bug

### ISSUE THREAD

**Issue by Terzim32** [NatroTeam/NatroMacro#582]
### Have you searched the existing bug reports?

No

### What happened?

When i would macro it wouldnt jump and it wouldnt work

### Steps to reproduce

1. I just start the macro
2.
3.

### What would you expect to happen?

![Roblox 7_27_2024 11_07_46 AM](https://github.com/user-attachments/assets/b5091d78-9d22-4ed8-b0bb-7c3cf2081e04)

### Natro Macro version

v1.0.0.1

### What is your Discord username?

Terzim

**Comment by Noobyguy775** [comment]
not a bug, join the discord for assistance
https://discord.gg/natromacro
