### ISSUE TITLE
add sticker options

### ISSUE THREAD

**Issue by Drobability** [NatroTeam/NatroMacro#583]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

make it so that when you roll for a sticker or when you find a sticker the macro detects which sticker you got and automatically discards or keeps it depending on a list in the options

### How will this improve Natro Macro?

this will help with inventory management and for long time macroing since stickers get deleted after 2 days if not kept and unwanted stickers would take the space this could also be done for beequips

### What is your Discord username?

drobability

**Comment by Noobyguy775** [comment]
Merging w/ #438
