### ISSUE TITLE
the macro isnt clicking and i cant find the setting either

### ISSUE THREAD

**Issue by R3LMmods** [NatroTeam/NatroMacro#585]
### Have you searched the existing bug reports?

Yes

### What happened?

the natro macro wont click and i cant find the setting whatever i do it wont click or go to the right feind and click in the shape i selected                                            

### Steps to reproduce

1.q
2.q
3.q

### What would you expect to happen?

q

### Natro Macro version

v1.0.0.2

### What is your Discord username?

th3r8dgd_32707

**Comment by Noobyguy775** [comment]
join the [discord](https://discord.gg/natromacro) and ask for help
