### ISSUE TITLE
Murmur

### ISSUE THREAD

**Issue by TamaraLiz** [NatroTeam/NatroMacro#586]
### Have you searched the existing bug reports?

No

### What happened?

Since it auto updated in the AM, the macro no longer works. I just continue to be auto murdered. I went directly to the link to update, in case something didn't get downloaded but the problem persists. 

### Steps to reproduce

1.f1 start
2.continue to die endlessly 
3.f3 give up

### What would you expect to happen?

for the macro to stumble a few times until it actually begins harvesting sweet sweet honey.

### Natro Macro version

1.0.0.2

### What is your Discord username?

tamaraliz

**Comment by Noobyguy775** [comment]
join the [discord](https://discord.gg/natromacro) and ask for support there, this is a common error with settings

**Comment by TamaraLiz** [comment]
I am a member of the discord group, however I’m not able to post. It asks
to follow, but apparently I don’t have a server to link it to. Either way,
I can’t ask for help there, otherwise that would have been the first step.
Also it was working correctly before the update, how can the settings have
been messed up?
Would be nice to just receive the answer on the post. Not just go somewhere
else where I can’t post anyways 🥲

Tamara Liz Rivera Hyde
www.tamaraliz.com
