### ISSUE TITLE
Natro not macroing

### ISSUE THREAD

**Issue by 912nolooni** [NatroTeam/NatroMacro#587]
### Have you searched the existing bug reports?

Yes

### What happened?

Every time I hit F1 or click it, It reopens Roblox to enter a server, But I'm already in a server? then it says "attempting public server" and doesn't work any further (after a while it rejoins/finds a new server and does the same thing over and over)

![image_2024-07-28_180557764](https://github.com/user-attachments/assets/6dbb435c-a0fe-4774-92a7-553485e80330)

### Steps to reproduce

1. Hit F1
2. Wait for Roblox to open
3. Look at Natro and see it doesn't work 

### What would you expect to happen?

For the macro to start working normally

### Natro Macro version

v1.0.0.2

### What is your Discord username?

freezedriedpickle

**Comment by 912nolooni** [comment]
Natro is broken :weary:

**Comment by Noobyguy775** [comment]
you need to claim your hive first

**Comment by 912nolooni** [comment]
NO REALLY? I CNAT DO THAT CAUSE ALL IT DOES IS LOOK FOR A PUBLIC SERVER
