### ISSUE TITLE
Natro is broken

### ISSUE THREAD

**Issue by Bilaluyar123** [NatroTeam/NatroMacro#588]
### Have you searched the existing bug reports?

No

### What happened?

Literaly every time I press the F1 key macro autojoins a bss server and doues nothing just that I tried everyething so fix your thing

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

To work normaly

### Natro Macro version

1.0.0.2

### What is your Discord username?

Jiraya69420

**Comment by Bilaluyar123** [comment]
file:///C:/Users/bilal/Videos/Roblox/robloxapp-20240729-0112566.wmv
here just look

**Comment by 912nolooni** [comment]
Same thing to me. look at the issue below

**Comment by Bilaluyar123** [comment]
What below where

**Comment by 912nolooni** [comment]
below ours, it says natro isnt working ( close to that)

**Comment by 912nolooni** [comment]
Natro so broken :**weary**:

**Comment by Noobyguy775** [comment]
> file:///C:/Users/bilal/Videos/Roblox/robloxapp-20240729-0112566.wmv here just look he macro does not show up cuz I recorded from roblox but yea you got the idea

we can't access your local files, open your file explorer and drag it into the comment

anyway, join the [discord](https://discord.gg/natromacro) and ask for support there.
