### ISSUE TITLE
Monster loot not being collected

### ISSUE THREAD

**Issue by GeoEli1** [NatroTeam/NatroMacro#589]
### Have you searched the existing bug reports?

Yes

### What happened?

Natro macro does collect pattern before bees kill monsters and resets while most/all of loot is still there
Usually happens after reset right before clover field in full bug runs
https://medal.tv/games/roblox/clips/imJ0p1qUxyYHlK64k/d1337ERxKFUL?invite=cr-MSxTTlksNjU5NjE0NzUs

### Steps to reproduce

1.Usually happens after character reset and bees are resting, which disallows them from killing mob
2.Character does collect pattern while mob is alive and doesnt get most/all items
3.

### What would you expect to happen?

Clip sumbitted in "what happened"

### Natro Macro version

1.0.0.2

### What is your Discord username?

GeoEli

**Comment by Noobyguy775** [comment]
adding to #502
