### ISSUE TITLE
Going to the Red Cannon, and then Slide down and reset

### ISSUE THREAD

**Issue by HoneyPerPollen** [NatroTeam/NatroMacro#59]
### Have you searched the existing bug reports?

No

### What happened?

**I started my Mountain Top macro, everything with speed is simple and nothing was wrong.**

So, to make sure it was working, I watched it jump up the ramp, go to the red cannon, and for some reason, it had went left for a little, and **repeatedly spamming "A", then resetting.**

### Steps to reproduce

It just happens everytime I start my Macro, so I don't know how to reproduce this bug, and it's still occuring, like something permanent.

### What would you expect to happen?

It's very unclear, but something should trigger the bug.

### Natro Macro version

latest (0.9.7)

### What is your Discord username?

hellopixels

**Comment by Noobyguy775** [comment]
Join the [discord](https://discord.gg/natromacro/) and open a ticket in macro-support, this isn't a bug
