### ISSUE TITLE
Reset macro

### ISSUE THREAD

**Issue by 10HHFFGTV** [NatroTeam/NatroMacro#591]
### Have you searched the existing bug reports?

Yes

### What happened?

What to do if Macro just resets and everything goes nowhere, nothing just resets, what to do, I have not been able to solve this problem for a month

### Steps to reproduce

1.I turn on macro
2.He looks around
3.starts resetting without stopping

### What would you expect to happen?

Idk

### Natro Macro version

1.0.0.2

### What is your Discord username?

homak228

**Comment by luvcappy** [comment]
Have you found a way to resolve this issue? The same thing is happening to me.

**Comment by Eclipse-Sky** [comment]
have you fixed this error, its happening to me to

**Comment by Noobyguy775** [comment]
@Eclipse-Sky @luvcappy @10HHFFGTV 
this error is a general issue with settings

join the discord and check the knowledge base post "Troubleshooting Guide"

**Comment by Dame123the** [comment]
when i go to the server i cant find trouble shooting guide
