### ISSUE TITLE
Hive Number Incorrect

### ISSUE THREAD

**Issue by LilTRok** [NatroTeam/NatroMacro#592]
### Have you searched the existing bug reports?

No

### What happened?

When the macro claimed my hive, it put the wrong hive number into the settings, causing it to jump too early and miss the red cannon. the macro kept resetting constantly to attempt it again.

### Steps to reproduce

1. Go to bss
2. choose a hive slot thats 4 5 or 6
3. set your hive slot setting to 12 or 3

### What would you expect to happen?

The macro would jump before reaching the red cannon, and reset. this loop would continue

### Natro Macro version

1. 0. 0. 2.

**Comment by Noobyguy775** [comment]
if you're setting the number itself to the wrong hive slot, then of course the macro will fail

If it's still failing after reconnecting, then record a video of it happening

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
