### ISSUE TITLE
Planters and memory match not working latest update

### ISSUE THREAD

**Issue by TinyNStrong** [NatroTeam/NatroMacro#594]
### Have you searched the existing bug reports?

No

### What happened?

Updated to newest version and now planters and memory match no longer work. Tried redownloading and nothing. 

### Steps to reproduce

1.update to newest version 
2. change setting to my settings 
3.run macro 

### What would you expect to happen?

cycle death loop through resetting as the program false to find the planters.

![image](https://github.com/user-attachments/assets/03475678-01a4-43e3-981b-97cc4f6a0a0f)

![image](https://github.com/user-attachments/assets/915a6a93-6251-43fb-9822-4751695083c0)

### Natro Macro version

1.0.0.2

### What is your Discord username?

TinyNStrong#3346

**Comment by Noobyguy775** [comment]
harvest all your planters in game, press f5 and clear all the planters there

1.0.0.2 did not change any lines relating to memory match/planters+
besides a path change which does not affect this
