### ISSUE TITLE
Nature Macro resetting

### ISSUE THREAD

**Issue by Eclipse-Sky** [NatroTeam/NatroMacro#595]
### Have you searched the existing bug reports?

No

### What happened?

I sent my Nature Macro up I start it up, then it resets twice like normal then just jumps at my hive then resets me again over and over. Ive tried resetting every setting. ive uninstalled it and reinstalled it and even tried the older version. Nothings working.

### Steps to reproduce

1.start macro 
2.reset twice the jump 
3. then keep resetting or try and place sprinkler down and it trys to farm at your hive.

### What would you expect to happen?

not work

### Natro Macro version

1.0.0.2

### What is your Discord username?

sawyer2889

**Comment by Noobyguy775** [comment]
see #591
