### ISSUE TITLE
remote control bot/app pause usage

### ISSUE THREAD

**Issue by SKETCHYSTUFFYT** [NatroTeam/NatroMacro#596]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

an add-on to the remote control bot/app to pause instead of stopping so when you need to use the PC for a second or someone has to but doesn't understand how to press f2 the default command would be ( ?set pause ) I don't think many would use it but I think it would be useful 

### How will this improve Natro Macro?

it would save the per hour the session honey and make it so you can restart from where you left off like in Spider Field without resetting I also would want it so when I'm trying to do something and I'm at a place I would want to pause it so when I get back I can do what I wanted to do then it would just be ready for me to turn it on again OR IF I FORGET to unpause I fix it bc I do it a lot 

### What is your Discord username?

mrhamable

**Comment by peacocksir** [comment]
There is already a command for this, ?pause, and ?unpause. Has the same effect as pressing f2
