### ISSUE TITLE
natro macro bug

### ISSUE THREAD

**Issue by FuFus-roblox** [NatroTeam/NatroMacro#598]
### Have you searched the existing bug reports?

No

### What happened?

in the macro i always walk a little more left so when im using it ill leave the area and i cant farm in the right area of bee swarn

### Steps to reproduce

1.just install it
2.open it
3.use it and youll see a walking error

### What would you expect to happen?

i expect for it to get adjusted

### Natro Macro version

1.0.0.2

### What is your Discord username?

hampter_poaahdjddj

**Comment by ssilz** [comment]
If you're talking about leaving the field while gathering, also called drifting, use these gather settings for all your fields, and make sure your movespeed is set correctly in the macro.
![bestpatternforxsnake.png](https://github.com/user-attachments/assets/83ab8c97-af47-44bb-8f90-83ff25e11860)

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).

Also read the comment above if you are drifting out of the field.
