### ISSUE TITLE
Keeps resetting my character loop

### ISSUE THREAD

**Issue by Dame123the** [NatroTeam/NatroMacro#599]
### Have you searched the existing bug reports?

Yes

### What happened?

I got the macro changed some of the gather settings and now when I activate the macro it just keeps resetting my character in a loop.

### Steps to reproduce

1.Start macro
2. looks around
3.resetting loop

### What would you expect to happen?

To work

### Natro Macro version

v1.0.0.2

### What is your Discord username?

dame_123

**Comment by ssilz** [comment]
Idk if this link works @here but if you're in the natro discord server, take a look through this.

https://discord.com/channels/1012610056921038868/1190781175116079185

**Comment by Dame123the** [comment]
i cant access the guide if thats where it leads.

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
