### ISSUE TITLE
Movement issue?

### ISSUE THREAD

**Issue by DSJ-star** [NatroTeam/NatroMacro#600]
### Have you searched the existing bug reports?

Yes

### What happened?

so basically when my macro starts it jumps a little early before the ledge where the red cannon is, and then it jumps again but this time it jumps onto the sign next to the red cannon, and simply it doesn't work, thus making my macro not work.

### Steps to reproduce

1.?
2.
3.

### What would you expect to happen?

maybe it to like work correctly i dont really understand what it meant by steps to reproduce lol.

### Natro Macro version

V1.0.0.2

### What is your Discord username?

daniels14258

**Comment by ssilz** [comment]
Have you set your hiveslot correctly? and is your movespeed set correctly as well?

If you think those settings are correct, read this troubleshooting guide thoroughly and make sure everything is as it should be.
https://discord.com/channels/1012610056921038868/1175954578605346947

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
