### ISSUE TITLE
macro

### ISSUE THREAD

**Issue by human970** [NatroTeam/NatroMacro#601]
### Have you searched the existing bug reports?

No

### What happened?

When i try and macro and turn off my monitor it switches and joins into microsoft roblox and then it stops working.

### Steps to reproduce

1.dont know
2.
3.

### What would you expect to happen?

for it to work

### Natro Macro version

1.0.0.2

### What is your Discord username?

Poo_nug1214

**Comment by human970** [comment]
> Don't turn off your monitor then. some work while turned off some don't

is there a way to fix this?

**Comment by human970** [comment]
is there a way to fix this problem

**Comment by peacocksir** [comment]
There is no way to fix this issue, it works with some pc’s and not others.
