### ISSUE TITLE
Reseting bug

### ISSUE THREAD

**Issue by hieeeeeeeeeeeeeeeee** [NatroTeam/NatroMacro#602]
### Have you searched the existing bug reports?

No

### What happened?

Every time i would open Natro Macro and started it. it would make me reset.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I expected for a smooth experience

### Natro Macro version

1.002

**Comment by Dame123the** [comment]
its happening to me too

**Comment by peacocksir** [comment]
This is a user issue, you have not set up the macro correctly. Please join our discord server and check the knowlage base channel: you can join at https://discord.gg/natromacro and check the troubleshooting guide post in that channel.
