### ISSUE TITLE
Macro crashing computer

### ISSUE THREAD

**Issue by karschsp** [NatroTeam/NatroMacro#603]
### Have you searched the existing bug reports?

Yes

### What happened?

When I run the macro, after a period of time (sometimes 10 minutes, sometimes an hour) my entire computer just dies. Like, completely shuts down.  This is a recently built machine.  AMD Ryzen CPU, GeForce 4060, 32GB RAM, etc. I have no issues running any other games such as GTA, Fortnite, COD, Roblox, etc.
when i start up the macro everything seems to work and then in the first 2-30mins of the macro running my pc will just crash. its very random because when i uninstall and reinstall the macro it works for longer. for example, yesterday i had the macro running for at least 2 hours but then when i stopped for a little bit and ran it again my pc crashed almost instantly. i've looked this issue up on google and even in the discord server and have had no luck so i'm wondering if anyone could help me solve this.
The only commonality I can see is that when i come back to the game after my pc crashes my bag is always full so it means every time my pc crashes it's after i'm done gathering pollen.

### Steps to reproduce

1. Run the macro
2. Let it run until the pollen is collected
3. Observe PC crash (maybe?)

### What would you expect to happen?

I would expect the macro to run without it crashing my PC. :) 

### Natro Macro version

v1.0.0.2

**Comment by peacocksir** [comment]
Does this only happen when running natro? Does it happen as well when playing Roblox or just using natro

**Comment by karschsp** [comment]
It only happens when running the macro. It’s not a huge issue now because I moved it to another (older) computer that we had around, but yeah it was definitely only happening when running the macro.
If you’re not hearing any other reports of this issue, you can close it. It was just really weird.

**Comment by peacocksir** [comment]
Most likely a issue with your computer, never seen this before so I will close.
