### ISSUE TITLE
macro pine tree

### ISSUE THREAD

**Issue by vertigomaster2005** [NatroTeam/NatroMacro#605]
### Have you searched the existing bug reports?

No

### What happened?

idk what happened i have my macro just set to macro in pine tree my movespeed and everything is correct and when i walk up to the canon instead of taking it my character just starts inching to the left back towards the hives

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

normally it would walk to the canon use the canon and i would glide to pine then i would start my macro

### Natro Macro version

1.0.0.2

### What is your Discord username?

kai150146

**Comment by ZacHamilton** [comment]
Can anyone say Sun Bear?  Seems like golf edition bss changed things.

**Comment by vertigomaster2005** [comment]
I found a fix to it I just had to reinstall natro

**Comment by peacocksir** [comment]
Issue fixed
