### ISSUE TITLE
Generated a New server link and it is not working!!

### ISSUE THREAD

**Issue by SrJubi** [NatroTeam/NatroMacro#606]
### Have you searched the existing bug reports?

yes

### What happened?

so, today i renewed my server, and went to take a new server link, as usual, copied the invite from server configs, pasted in a new tab, copied from the top GUI and when i tried to paste the new server link, it just started to reject, as if it was not bee swarm page, or not from Onett bee swarm, and so now i cant use my server link on Natro, also no response from support on Discord, and i already did everything i could do, reinstaled the files, re-generated a new server link, downloaded older versions of natro, and still the problem wasn't fixed. 1
![image](https://github.com/user-attachments/assets/c23c5de0-6af4-4638-a736-2fcfc559d9a8)
 Please help!

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

fix the issue.

### Natro Macro version

1.0.0.2

### What is your Discord username?

Asteroth

**Comment by ssilz** [comment]
What does the private server link look like?

Is it like this one
 https://www.roblox.com/games/1537690962/Bee-Swarm-Simulator?privateServerLinkCode=K89dSXdUO35Q8CKiKm2U3LZish_oEBG4

**Comment by SrJubi** [comment]
i can paste the Link in here, it looks the same 


https://www.roblox.com/pt/games/1537690962/Bee-Swarm-Simulator?privateServerLinkCode=06774456805863286848563141707677

**Comment by SrJubi** [comment]
You could also join, the link works fine, but when i try to paste it on Natro it just wont work

**Comment by SrJubi** [comment]
i just copied and pasted your link and it worked

**Comment by SrJubi** [comment]
But my link do not work

**Comment by SrJubi** [comment]
BRUH, it was the /pt/ that was causing it to fail, thank you for the help man

**Comment by ssilz** [comment]
Oh cool, glad you got it to work

**Comment by peacocksir** [comment]
You have to paste the link into browser first cause Roblox changed the link format and ?sharecode= links do not work.
