### ISSUE TITLE
marco not zooming out and keeps killing me in place

### ISSUE THREAD

**Issue by Beeohbee1972** [NatroTeam/NatroMacro#608]
### Have you searched the existing bug reports?

No

### What happened?

the camera rotates to the front but then doenst zoom out and then i die, respawn and then this repeats until roblox doesnt let me back in

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

it normally zooms out to the required level then the macro proceeds 

### Natro Macro version

1.0.0.2

### What is your Discord username?

Beeohbee1972

**Comment by peacocksir** [comment]
This is a common issue we see which is a user issue. Please check the knowlage base channel on our discord server: https://discord.gg/natromacro read the troubleshooting guide post.
