### ISSUE TITLE
Pepper and Stump Field Options for Selecting Boosted Gather Fields

### ISSUE THREAD

**Issue by MrTopGamey** [NatroTeam/NatroMacro#609]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Recently, I've found that the macro was grinding at Pepper Field and Stump Field whenever it was boosted from Red Field or Blue Field Booster. Later, I looked around on the macro and noticed missing options in the Select boosted gather fields section. I looked up the BSS's Wikipedia and they have said it can merely provided when their Stump Snail's respawn cooldown is on or has at least 35 bees.
The main suggestion is to include the options of Stump Field in the Blue category and Pepper Field in the Red category. Same thing with Coconut Field default settings, it is turned off. Therefore, the Stump and Pepper fields are set to be turned off by default until the players have defeated the Stump Snail and it is on respawn cooldown or obtained at least 35 bees to bypass the Windy Bee Gate (35 Bee Zone).

### How will this improve Natro Macro?

This will open up to new options for Macro users to decide whatever fields they'd like to grind on when boosted by field boosters. As I said before, if they defeat the Stump Snail or have at least 35 bees, they can enable the option to start gathering on specific fields to expand their experience on Macro.

### What is your Discord username?

mr.topgamey

**Comment by peacocksir** [comment]
I will add this sometime later, not soon though.

**Comment by peacocksir** [comment]
Reopening to keep on issues list
