### ISSUE TITLE
Invert L/R on coconut default settings 

### ISSUE THREAD

**Issue by DubiousDodo** [NatroTeam/NatroMacro#61]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Without the supreme saturator Field Drift Comp doesn’t work well or at all, and since how coconut field is shaped, if the default Xsnake is off just a little bit it will fall off the edge onto the ticket tent and make no honey. Inventing the L/R will make it align on 2 solid and long walls making it nearly impossible for it to fall off  

### How will this improve Natro Macro?

People without supreme saturator won’t fall off in coconut field 

### What is your Discord username?

DubiousDodo

**Comment by zspz** [comment]
Thanks, this will be added in the upcoming patch!
