### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IdiotStickMoron** [NatroTeam/NatroMacro#610]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro doesn't zoom out and will only work until it has to claim wealth clock. I've tried everything I can think of to try to fix it.

### Steps to reproduce

1.Start macro
2.Use cannon to go to rose
3.grind in rose for 30 min or until bags fills
4. walk to hive convert
5. go back to rose unless its been an hour, go claim wealth clock
6. reset after claiming
7. reset 9 or 10 times then rejoin and repeat

### What would you expect to happen?

It was supposed to zoom out after resetting the first time

### Natro Macro version

V1.0.02

**Comment by peacocksir** [comment]
This is likely an issue with Roblox, you are probably spawning on the spawn plate at spawn and not at your hive. This is an issue that does not happen often and is with Roblox.

**Comment by IdiotStickMoron** [comment]
No, I'm not spawning on the spawn plate. I'm spawning fine, the issue is
that the macro isn't zooming out before anything. It only works once after
I join because it's automatically zoomed out when I join.

**Comment by peacocksir** [comment]
Never seen this issue before, please join [our discord server](https://discord.gg/natromacro) and make a support request.
