### ISSUE TITLE
Vicious bee fleeing isn't detected by the marco, causing it to continually try and attack nothing.

### ISSUE THREAD

**Issue by WetLink009** [NatroTeam/NatroMacro#611]
### Have you searched the existing bug reports?

No

### What happened?

Whenever vicious bee flees, it continues to attempt to continue the process to kill it, and is unable to do so as it's not there. With lower hive levels, this is quite common, as it's more difficult to kill.

### Steps to reproduce

1. Find and attack vicious bee
2. Either die repeatedly or have the return trip take too long
3. Vicious bee flees, and the macro doesn't detect it.

### What would you expect to happen?

The macro proceeds to run in circles attempting to fight a vicious bee that isn't there.

### Natro Macro version

1.0.0.2

### What is your Discord username?

@wetlink009

**Comment by peacocksir** [comment]
In a future release, I will try to improve this detection.

**Comment by peacocksir** [comment]
Reopening to keep on issue tab

**Comment by Noobyguy775** [comment]
adding to #502
