### ISSUE TITLE
natro macro loves reseting my character

### ISSUE THREAD

**Issue by Schzean** [NatroTeam/NatroMacro#612]
### Have you searched the existing bug reports?

No

### What happened?

every time i start the macro it lets me reset even though i entered everything correctly in the settings and everything else and im also in the correct hive slot and it works when it lets me rejoin but after that it says traveling to rose and it gets stuck and then does the process of reseting my character over and over again

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i expect to see the macro doing fine and doing it macro things

### Natro Macro version

1.0.0.2

### What is your Discord username?

schzean

**Comment by reggietorres** [comment]
your config is bad

**Comment by peacocksir** [comment]
You probably have messed up your settings, this is a user issue not an issue with the macro. Please join the discord server for support: https://discord.gg/natromacro
