### ISSUE TITLE
Killing mobs

### ISSUE THREAD

**Issue by Soloxgames** [NatroTeam/NatroMacro#613]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Hello, I know this would be a pain in the ass to do, but making it so you can auto kill spiders wolf's and other big mobs, not lady bugs and rhino beetles would be very helpful im sure this has been suggested before but I would love if this becomes a thing :D

### How will this improve Natro Macro?

Better grinding

### What is your Discord username?

Im not in the discord as of right now.

**Comment by peacocksir** [comment]
Sorry, do you want it to be able to kill spider, werewolve etc? Because that is already a feature
![image](https://github.com/user-attachments/assets/3ea670cb-d65b-441d-ad3e-f347b5e5737b)
