### ISSUE TITLE
Natro Macro Virus?

### ISSUE THREAD

**Issue by Abysxl** [NatroTeam/NatroMacro#614]
### Have you searched the existing bug reports?

No

### What happened?

I pressed "START" for the Natro Macro and it brought to a screen saying "Windows Protected Your PC" does Natro have a virus (I downloaded the most recent one)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

If I turn of Windows Security for Natro Macro will it corrupt my computer?

### Natro Macro version

V1.0.0.2

### What is your Discord username?

abysxlkord

**Comment by robloxgamer99636** [comment]
No, it’s safe.

Windows is warning you that it hasn’t registered the software, basically meaning it doesn’t know it - and that could potentially make it a threat.
Of course, Natro Macro is safe to use, and if it were malicious, Windows would outright tell you.

To run Natro Macro, click the underlined “More info” button and press run anyway.

**Comment by reggietorres** [comment]
what he said, if you were to actually read the warning, you wouldn't be here piling up the issues tab with a non issue, at least on the dev's part

**Comment by peacocksir** [comment]
Not a virus, all of the source code is public and available for anyone to look over.
