### ISSUE TITLE
natro macro is virus

### ISSUE THREAD

**Issue by biskyyy555** [NatroTeam/NatroMacro#615]
### Have you searched the existing bug reports?

No

### What happened?

Trojan/PowerShell.Runner  Trojan.Win32.Drop.kkwkwe Suspected Of Win32.PhishingPE.Heur  
is all viruses there

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i want to know if it actually safe

### Natro Macro version

newest

### What is your Discord username?

.vapka

**Comment by biskyyy555** [comment]
I think that natro macro is unsafe

**Comment by peacocksir** [comment]
Just closed another issue like this, it is not a virus. All of the code is open source and available for anyone to look over. It is a false positive because the macro clicks keys for you.
