### ISSUE TITLE
OCR Status

### ISSUE THREAD

**Issue by lkspodmol** [NatroTeam/NatroMacro#616]
### Have you searched the existing bug reports?

No

### What happened?

When I'm macroing on my main pc, the OCR status is enabled, but when I'm macroing on my laptop, it says disabled and error jumps out every hour that it expected a number, but received a string (smth like that). 

### Steps to reproduce

1. Idk how. 

### What would you expect to happen?

Could someone please help me with it and tell me how to turn it on? 

### Natro Macro version

Newest - 1.0.0.2

### What is your Discord username?

_luka5_

**Comment by lkspodmol** [comment]
![IMG_20240805_000034](https://github.com/user-attachments/assets/d014c938-9b61-4f8a-af27-89fa78dd4bf2)

**Comment by peacocksir** [comment]
Please DM me on discord so we can talk about this issue. Never seen this before and might be a issue with the macro or a setting on your laptop. (money_mountain on discord)
