### ISSUE TITLE
drifting off of field

### ISSUE THREAD

**Issue by gamingentf** [NatroTeam/NatroMacro#617]
### Have you searched the existing bug reports?

No

### What happened?

i am trying to set up the macro but i keep going out of the field. this is a problem because i cant keep reseting overnight.

### Steps to reproduce

1.start macro in certain field
2.it auto walks out of field

### What would you expect to happen?

you should be out of the field after a while.

### Natro Macro version

Natro Macro v1.0.0.2

### What is your Discord username?

p_j9016

**Comment by peacocksir** [comment]
Join our discord server for support, this is a common issue we see when people either aren't using the correct pattern (cornerXsnake works to prevent drift) or they just don't know the features. If you have the supreme saturator, then you can enable field drift compensation to prevent it drifting out of the field.

**Comment by uxmamoghal-stack** [comment]
field drift

**Comment by uxmamoghal-stack** [comment]
What is "field drift["](https://theantimicro.com/) in Natro Macro?

**Comment by 101Symbol101** [comment]
Please refer to the Discord server for non bug related inquiries

**Comment by uxmamoghal-stack** [comment]
Can we play Natromacro using controllers ?
