### ISSUE TITLE
move planter location in stump

### ISSUE THREAD

**Issue by comkys** [NatroTeam/NatroMacro#618]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

move planter location to the bottom edge of stump field as to not interfere with killing stump, causing drift which doesn't get corrected to the point it leaves the field (the harvest message covers up your tokens such as haste or bear bee etc)

### How will this improve Natro Macro?

so u don't have to manually harvest and switch out ur planter location etc. every time u want to kill stump :3

### What is your Discord username?

@comkys

**Comment by peacocksir** [comment]
Increase your resolution so that way the message does not cover the buffs. You can also turn on field drift compensation for it so that way it does not drift out of the field while killing the stump. If you need more help make a support request on our discord server.
