### ISSUE TITLE
Add macro options for hive hub field

### ISSUE THREAD

**Issue by BenDoverEatYourSocks** [NatroTeam/NatroMacro#620]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an option to macro in the Hive Hub field.

### How will this improve Natro Macro?

The reason I want this is because you can farm sticker sprouts and getting tool stickers are easier here.

### What is your Discord username?

qweqeqweqewqwe

**Comment by peacocksir** [comment]
This is already planned for the next release. Duplicate of #185
