### ISSUE TITLE
Macro Wont Open?!?!

### ISSUE THREAD

**Issue by Hello-Hello1982** [NatroTeam/NatroMacro#621]
### Have you searched the existing bug reports?

Yes

### What happened?

![image](https://github.com/user-attachments/assets/0280efec-1d2e-4c49-a7ea-416226fccba5)
when i download macro and extract all i get to the part where it says start that i have to click but when i double click it wont open i have tried like reinstalling 10 times now and my friend showed me how he downloaded it but still it dint work please help

### Steps to reproduce

1. download macro
2. extract all
3. try to open macro

### What would you expect to happen?

macro to open

### Natro Macro version

1.0.0.2

### What is your Discord username?

hello_hello6260 and display name is Tobben_Weedborg

**Comment by peacocksir** [comment]
You might have to confirm some prompt on windows, like windows smart screen, if you need further help please join [our discord server](https://discord.gg/natromacro), and make a support post.
