### ISSUE TITLE
Natro bug (v1.0.0.2)

### ISSUE THREAD

**Issue by ritryxx** [NatroTeam/NatroMacro#622]
### Have you searched the existing bug reports?

Yes

### What happened?

When I start the macro? she always kill me and she not work...

### Steps to reproduce

1. I launch the game
2. I open and start the macro
3. The macro kill me on repeat

### What would you expect to happen?

I thought it would farm automatically like in version 1.0.0.1

### Natro Macro version

1.0.0.2

### What is your Discord username?

ritryxx

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
