### ISSUE TITLE
field drift issue, and found (potentionally)

### ISSUE THREAD

**Issue by rzndom** [NatroTeam/NatroMacro#624]
### Have you searched the existing bug reports?

Yes

### What happened?

before 1.0.0.2 it was fine, but now when i macro in the coconut field (field drift compensation, supreme saturator, every setting correct aswell as resolution and other things), it drifts to the right, and either lands in the light blue maze, or rarely in the sunflower field, and i dont know if this helps, but i think it happens because the blue portal is very simular to the supreme saturator.  i need to use s size and 1 width to not drift out so much, but it happens 30% of the time still
![bss](https://github.com/user-attachments/assets/4441846b-daf7-4de9-8f8c-7fe56f0638ba)

### Steps to reproduce

1. update to 1.0.0.2
2. buy supreme saturator and use field drift compensation
3. macro in coconut field
4. wait 4-8 cycles
5. 

### What would you expect to happen?

i expect the macro to drift out of the field and roam around either in the light blue maze or in the sunflower field

### Natro Macro version

1.0.0.2

### What is your Discord username?

.random__.

**Comment by peacocksir** [comment]
You can easily fix this issue, you can just change your macro settings to where it macros and the portal and maze aren't in view. Its kind of hard for us to fix something like this, not much we can do here.
