### ISSUE TITLE
The gifted auto hatcher bug.

### ISSUE THREAD

**Issue by PLXduBRC3** [NatroTeam/NatroMacro#626]
### Have you searched the existing bug reports?

No

### What happened?

When i started the misc, it continuesly tried to find the basic egg then after a long moment it said.
 "We didn't detect basic egg." When i had over 150 of them and 200 RJ.

### Steps to reproduce

1. My friend tolded me that theres a special misc for a gifted basic egg hatcher i did exactly like he said to enter it. Nothing was wrong for now.

2. Then i looked whats the warning were about i did none of this and i started the auto hatcher.

3. And then i realised that something was wrong i though this was because i did something wrong since this my first time doing this misc. Once i realised it wasn't my fault i continusly cherched for the problem there were in the auto hatcher, and i realised that the problem is that the mouse was in a blind spot. I didn't find any way of fixing this by myself. (Sorry for bad english)

### What would you expect to happen?

I excepted the misc to work exactly like my friend explained me; to click on the basic egg and continusly open until i have no more egg or i get the gifted basic bee. But i encountered too much problem so i had to do it manually which was suffering.

### Natro Macro version

Natro macro v1.0.0.2

### What is your Discord username?

onehandman7776_41687

**Comment by peacocksir** [comment]
I will look into this issue and hopefully be able to fix it soon. Thanks for reporting. It could also be a user issue, make sure you are using a commonly supported resolution and that nothing is interfering with it.

**Comment by peacocksir** [comment]
Reopening to keep on issues tab

**Comment by Noobyguy775** [comment]
@PLXduBRC3 hi there, 
I have tested this on two accounts and both can detect the basic eggs.
Make sure you don't have any colour filters/image sharpening that could be affecting the detection.
You can join our [discord](https://discord.gg/natromacro) and look for the [Knowledge Base](https://canary.discord.com/channels/1012610056921038868/1024403525498835066) channel, where you'll find guides about the macro, specifically, your issue would be under inside "Checking your graphics settings"
