### ISSUE TITLE
Collect/Kill problem

### ISSUE THREAD

**Issue by Karanjot121** [NatroTeam/NatroMacro#628]
### Have you searched the existing bug reports?

No

### What happened?

In the collect/kill section for the macro when i try click claim clock tickets it never claims it this issue has been going on for a week or more and I've tried restarting my pc redownloading the macro again but nothing ever works and even check if i have the collect clock tickets selected which i do.

### Steps to reproduce

1.Open natro macro 
2.go to collect/kill
3.click on collect clock tickets

### What would you expect to happen?

I would want the macro to claim the clock tickets which it doesn't do.

### Natro Macro version

1.0.0.2v

### What is your Discord username?

iliketoplayfortnite433

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
