### ISSUE TITLE
Macro Wont work

### ISSUE THREAD

**Issue by MSN1307** [NatroTeam/NatroMacro#629]
### Have you searched the existing bug reports?

Yes

### What happened?

when i turn on the macro it keeps on resting. all it does is looks behind me then infront of me then it resets me.

### Steps to reproduce

1.i put what field i want to marco on 
2.i press and keeps on resting me

### What would you expect to happen?

if you can please tell me what to do differently.

### Natro Macro version

the newest one 1.0.0.2

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this ](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
