### ISSUE TITLE
Movement issues involving the cannon

### ISSUE THREAD

**Issue by samutaroo** [NatroTeam/NatroMacro#630]
### Have you searched the existing bug reports?

Yes

### What happened?

Upon downloading this macro, I found that when I click Start (F1), it moves as expected along the walls of the hives. but once it jumps and makes it to the cannon, rather than stopping,  it continues walking right past it instead of going in it. my character hits the wall beside the Honey Wreath until eventually it resets again and repeats.

I figured that since the cannon didn't work, I'd instead use Walk as my Move Method, which did infact work out, but when my bag came full, and i returned to my hive, it would walk right past my hive, get stuck on the honey dispenser, and then reset with all my pollen.

I have a feeling that the macro is forgetting to click "e" to interact but im not sure how to deal w/ that. I also made sure to check my Movement Speed without haste, put in my Hive Slot and # of bees.

### Steps to reproduce

1.Download Natro Macro
2.Disable all features in Collect/Kill
3.Change Gathering to Mountain Top
4. Apply Speed, Slot, and Bee #
5. Start Macro

### What would you expect to happen?

My character should have paused and went into the cannon to the Mountain Top, rather than walking past it.

### Natro Macro version

v1.0.0.2

**Comment by peacocksir** [comment]
This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).

**Comment by noaluca** [comment]
Did you ever figure it out? i’m having the EXACT same issue!
