### ISSUE TITLE
custom guiding star announce messages

### ISSUE THREAD

**Issue by iwanttodiepls** [NatroTeam/NatroMacro#631]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

this feature would be under the "Announce Guiding Star" option, it would simply allow you to type a message you would like sent when a guiding star gets used, (EX: guiding popped, guiding star xD, etc etc)

### How will this improve Natro Macro?

i want this feature cause i think its pretty cool xD, dont think this will get implemented but i would like it! 

also, you can make fun of your friends if youre macroing with them, which i find pretty funny lols

### What is your Discord username?

lucasv269420

**Comment by peacocksir** [comment]
I guess i can add something like this, but it will not be happening soon (not in v1.0.1). Please DM or ping me in the natro server if you have any questions (money_mountain)
