### ISSUE TITLE
Macro is not taking me to a field, but still places sprinklers and tries to farm.

### ISSUE THREAD

**Issue by sOwOuls** [NatroTeam/NatroMacro#632]
### Have you searched the existing bug reports?

No

### What happened?

I start the script, it does its usual steps of resetting. However, it does not take me to the field I want to farm in. I've reinstalled the macro twice, gone to the discord for help, and nothing I've come across has been able to fix it or improve the issue. I have no idea how to reproduce it. Below is a video of what is happening, images of all my natro settings and the natro files that are currently on my pc.

https://youtu.be/-VkOFE7RPYY 
![Boost](https://github.com/user-attachments/assets/53b5133c-ba3b-439b-9962-6e637fef3a43)
![Collect-Kill](https://github.com/user-attachments/assets/57538c36-91d2-42ed-a311-0140fb2b1432)
![Gather](https://github.com/user-attachments/assets/93a5b0a5-fd78-4831-89a7-7fb8c21b0be8)
![Planters](https://github.com/user-attachments/assets/5d555093-89f7-43fb-a85f-147512a6155f)
![Quests](https://github.com/user-attachments/assets/8262e2f1-d251-4ec8-a0ac-cdb1a0501fdc)
![Settings](https://github.com/user-attachments/assets/8afe4edf-b075-495e-8d1d-2ece3e6c87a7)
![Status](https://github.com/user-attachments/assets/9273d73c-d478-453e-9722-2fe2d793504f)
[Natro Macro v1.0.0.2 - Not taking to field.zip](https://github.com/user-attachments/files/16549156/Natro.Macro.v1.0.0.2.-.Not.taking.to.field.zip)

### Steps to reproduce

Not sure

### What would you expect to happen?

Script does not take me to the field I want to farm in

### Natro Macro version

v1.0.0.2

### What is your Discord username?

sowoulz

**Comment by peacocksir** [comment]
Its a user issue, you have clock enabled on the collect tab which means it will be going to the clock first before going to farm. Turn that feature off if you want it to only farm, however do note the clock gives you free tickets every hour. If you need further help, please make a help post on [our discord.](https://discord.gg/natromacro)

**Comment by sOwOuls** [comment]
> Its a user issue, you have clock enabled on the collect tab which means it will be going to the clock first before going to farm. Turn that feature off if you want it to only farm, however do note the clock gives you free tickets every hour. If you need further help, please make a help post on [our discord.](https://discord.gg/natromacro)

So the status tab saying "traveling: Strawberry" (im not) means im going straight to the wealth clock?
