### ISSUE TITLE
Pine field walk to hive getting stuck

### ISSUE THREAD

**Issue by Doominator1** [NatroTeam/NatroMacro#633]
### Have you searched the existing bug reports?

Yes

### What happened?

so basicly it doesn't walk far enough towards the mountain and walks into the wall behind the bear. and then fails to make honey so resets and loses it all. 
*I was on the right walkspeed with movespeed comp enabled

### Steps to reproduce

1. Use 60fps+
2. use lines, medium, 6, without drift comp

### What would you expect to happen?

It should walk far enough towards the mountain to walk past the bear and glide. down to hive

### Natro Macro version

v1.0.0.2

### What is your Discord username?

YourSodium

**Comment by Noobyguy775** [comment]
this should be added in a near release, if you need it now, use this 

https://discord.com/channels/1012610056921038868/1246659114503770153
