### ISSUE TITLE
ошибка недостающий файл

### ISSUE THREAD

**Issue by phohuf** [NatroTeam/NatroMacro#635]
### Have you searched the existing bug reports?

Yes

### What happened?

Я скачал макрос открываю его нажимаю start.bat и мне выдаёт ошибку
сначала я пытался всё исправить но ни чего не выходила и выдавало вот такой текст 
![Снимок экрана (69)](https://github.com/user-attachments/assets/12843144-87b7-4717-adea-e79c0e432303)

### Steps to reproduce

1.открытие 
2.старт
3.ошибка

### What would you expect to happen?

я бы хотел увидеть рабочий макрос

### Natro Macro version

1.0.0.2

### What is your Discord username?

sasanya_22

**Comment by peacocksir** [comment]
Поскольку я не могу это прочитать, следуйте этому руководству ниже. Оно на английском языке, поэтому вам придется перевести.

This is a user issue. You have not followed the setup properly and have done something incorrect. You can follow [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) guide to do some basic troubleshooting steps. If [this](https://docs.google.com/document/d/1Z90fR-wibJT59uGwsPKRdVwYgViMYVRT5D_3pDF9ho0/edit?usp=sharing) does not work, please join [our discord server](https://discord.gg/natromacro).
