### ISSUE TITLE
After reset wait

### ISSUE THREAD

**Issue by bigbossa231** [NatroTeam/NatroMacro#636]
### Have you searched the existing suggestions?

No

### What is your suggestion?

to wait a few seconds before going to kill or doing somting els

### How will this improve Natro Macro?

is going to be better i thick

### What is your Discord username?

_viktor.j__

**Comment by peacocksir** [comment]
Lower your bee settings, and you can change "Wait <blank> seconds before converting" in settings tab as well. If your talking about a delay before going to kill mobs, this has already been suggested and will likeley be worked on soon.
