### ISSUE TITLE
I can't open Natro at all.

### ISSUE THREAD

**Issue by R1lzyy** [NatroTeam/NatroMacro#639]
### Have you searched the existing bug reports?

Yes

### What happened?

I have extracted Natro and downloaded it from the official source but when I try to open to Start.bat file it does nothing.

### Steps to reproduce

1. Download natro macro
2. Extract File
3. Try to start natro macro

### What would you expect to happen?

I expected to see the menu and the settings so I could start using it!

### Natro Macro version

v1.0.0.2

### What is your Discord username?

I do not have Discord

**Comment by Therogamer** [comment]
Have you installed autohotkey? If not install it from here: https://www.autohotkey.com/

**Comment by ChoonMan013** [comment]
i have the same problem and i installed the auto hotkey and changed everything on my computer to the correct settings and it sill wont open

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.

**Comment by Lazence** [comment]
downloaded auto hotkey and it still wont open :\
