### ISSUE TITLE
vicious bee webhook/hourly report not working properly

### ISSUE THREAD

**Issue by 2fifty** [NatroTeam/NatroMacro#640]
### Have you searched the existing bug reports?

Yes

### What happened?

webhook for vicious bee always says that it didnt defeat vicious bee no matter what,  i got like a 100 stingers since i started my macro and hourly report still says 0 vic bees defeated, even if i search myself for defeats i cant find any

### Steps to reproduce

turned on vicious bee macro

### What would you expect to happen?

webhook not working

### Natro Macro version

1.0.0.2

### What is your Discord username?

250_w

**Comment by misc-et** [comment]
Closing as a likely settings issue. If you still require help with it, please feel free to reopen.
