### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cykadyczny** [NatroTeam/NatroMacro#641]
### Have you searched the existing bug reports?

No

### What happened?

i was using macro in bee swarm simulator and my character kept reseting how to fix it?

### Steps to reproduce

1.i don"t understand
2.bcuz i am 
3.polish

### What would you expect to happen?

idk im polish

### Natro Macro version

v1.0.0.2

**Comment by ShakeAndWiggle20** [comment]
also happens for me

**Comment by 912nolooni** [comment]
are you using any shaders or anything like that (bloxstrap?)
