### ISSUE TITLE
Night time detected at day time

### ISSUE THREAD

**Issue by BlackGr2vity** [NatroTeam/NatroMacro#642]
### Have you searched the existing bug reports?

Yes

### What happened?

When i try to macro and i have Vicious bee macro on, everything seems to be fine at first but when it gets to the field it needs to gather in, it detects night and starts looking for vicious bee, and now I don't know if it is a bug or my PC bugging out. How to fix it!

### Steps to reproduce

1.Goes in the macro field it is supposed to macro on
2.Detects night at day time
3.Looks for vicious bee at the day time

### What would you expect to happen?

I would love for it to be fixed, because i need stingers and I am a red hive! Thank you

### Natro Macro version

v1.0.0.2

### What is your Discord username?

blackgravity

**Comment by Noobyguy775** [comment]
#380
