### ISSUE TITLE
Im asking a question

### ISSUE THREAD

**Issue by Hello432964** [NatroTeam/NatroMacro#644]
### Have you searched the existing bug reports?

Yes

### What happened?

Im not sure but does natro macro work on 1366-768 display resolution? My issue is that natro macro is not working and just keeps on reseting me again and again, and when it doesnt, it doesnt do anything. Plz help.

### Steps to reproduce

1. Run Natro
2. Watch yourself reset
3. Research, but nothing works

### What would you expect to happen?

I wanted the macro to work so i could afk while getting billions of honey. Ive seen it work,. but it hasnt been working for me.

### Natro Macro version

1.00.002

**Comment by misc-et** [comment]
Yes, it does work at that resolution. Thanks for your report. This is likely to be an issue with other settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
