### ISSUE TITLE
My issues with the product

### ISSUE THREAD

**Issue by Newstart1873** [NatroTeam/NatroMacro#645]
### Have you searched the existing bug reports?

Yes

### What happened?

So I'm not sure if this was Intentional or what. My macro every time I start my macro and let it run for awhile, I tend to disconnect around 8-10 hours into the session (probably due to internet) but when it reconnects it walks around for like 15 seconds in circles doesn't claim a new hive and then rejoins the game again, this then goes on for a couple hours or however long it takes me to wake up/get back from school or whatever and turn it off, in the case i dont turn it off and pause it to claim a hive and unpause it, its broken causing it to keep rejoining untill i FULLY close the macro and reopen it in files or however someone does this. This tends to make my computer overheat and causes lag to my computer. Hope this gets fixed

### Steps to reproduce

1.Simple turn macro on
2.have bad internet connection
3.wala

### What would you expect to happen?

I would like to expect it to reclaim the hive and restart the entire process so I can get my fully asleep or away loot. I would like to macro for a couple days at a time but i cant due to this issue.

### Natro Macro version

Its done it over every version ive had so far. The one currently i think is 1.0.0.2

### What is your Discord username?

Ceola_23, dm me for further detail if needed or questions. I dont have screenshots or videos as i havnt really thought about that till now.

**Comment by 912nolooni** [comment]
What i did is delete any other roblox apps like the microsoft store one, that fixed the same issue, i do not know what is wrong with yours though

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
