### ISSUE TITLE
Polar Bear Quest

### ISSUE THREAD

**Issue by NoNoNoHub** [NatroTeam/NatroMacro#646]
### Have you searched the existing bug reports?

Yes

### What happened?

Polar Bear quest Keep showing old quest and cannot not be completed.
Polar bear quest turn in quest but does not show the new quest on the list, it still keep the old one so the quest can never be done.

### Steps to reproduce

1.complete a polar bear quest and let the macro turn in 
2.n/a
3.n/a

### What would you expect to happen?

maybe new update to the macro

### Natro Macro version

1.0.0.2

**Comment by Daschinja97** [comment]
Is it the Quest Strawbery Kiwers or something Like that ?

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/669
