### ISSUE TITLE
A problem with the macro

### ISSUE THREAD

**Issue by JakoeF** [NatroTeam/NatroMacro#647]
### Have you searched the existing bug reports?

No

### What happened?

Mi macro is everything good, but when i put on farming he always leaves the field, i mean like it starts good but later leaves the field, thats horrible to me

### Steps to reproduce

1.Well, when I start the macro it's normal, it picks up everything I ask
2.The problem is that when I put him to farm in a field, he starts normal, puts the sprinklers and everything normal, but as he farms more he gets out of the field
3.I've tried many configurations, different patterns and even so with different configurations it always happens to me, and it's in any field that it happens to me

### What would you expect to happen?

I would like to solve that problem

### Natro Macro version

1.02

### What is your Discord username?

jakoef_

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
