### ISSUE TITLE
im trying to go to the pineapple field but it keeps bringing me to the strawberry field. it also keeps resetting me. (im new to macro)

### ISSUE THREAD

**Issue by mango2144** [NatroTeam/NatroMacro#648]
### Have you searched the existing bug reports?

Yes

### What happened?

when it walked to the 5 bee zone it reset and went to the strawberry field instead of the pineapple.

### Steps to reproduce

1.i put in the right settings
2.
3.

### What would you expect to happen?

go to pineapple, sit there and collect pollen

### Natro Macro version

2

### What is your Discord username?

mango

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
