### ISSUE TITLE
Rose field cannon bug

### ISSUE THREAD

**Issue by Doominator1** [NatroTeam/NatroMacro#650]
### Have you searched the existing bug reports?

Yes

### What happened?

I afk farm on the rose field with cannon movement method, sometimes the parachute (black and yellow one) deploys too early and flies onto the top of the red hive building. It then thinks its in the rose field starts doing snakexcorner and falls into the sunflower field. And it also ends up reseting with all my pollen instead of going to the hive.
My guess is sometimes when there is a ping spike and the cannon fires late, the macro doesn't account for this time delay.

Please message me on github or discord if you want anything that will help, or have a solution.

### Steps to reproduce

1. rose field farming
2. all the default settings for the rose field
3. I don't have any haste/speed boost bees
4. I don't have very good fps, its around 10-30 most of the time and around 90-130 ping

### What would you expect to happen?

The parachute should deploy and glide down into the rose field. (instead of the top of the red hive building)

### Natro Macro version

v1.0.0.2

### What is your Discord username?

Yoururainium

**Comment by Doominator1** [comment]
btw i now am resorting back to the walk method instead of cannon because it is consistant
IMPORTANT: The glider misalignment happens only about 25% of the time

**Comment by Puffy1787** [comment]
I'm pretty sure your issue is the movespeed you have set in natro macro. Go to settings in bee swarm and scroll until you see movespeed (without any haste or bear bee). Then go to the natro macro settings and input the same number under movespeed. Also make sure you have movespeed correction turned on.

**Comment by Doominator1** [comment]
> I'm pretty sure your issue is the movespeed you have set in natro macro. Go to settings in bee swarm and scroll until you see movespeed (without any haste or bear bee). Then go to the natro macro settings and input the same number under movespeed. Also make sure you have movespeed correction turned on.

Im not dumb bruh, I did all of that and double checked it, its prob just cuz my pc is garbage.
