### ISSUE TITLE
A setting to add seconds to make the macro wait before looting a bug

### ISSUE THREAD

**Issue by Von2Crazy232** [NatroTeam/NatroMacro#652]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an option to put however much time a person wants the macro to wait before looting the bug

### How will this improve Natro Macro?

I have 35 bees and putting the macro bee number at 1 doesn't make it wait at all it just instantly loots then misses 90% of my bug loot which makes me extremely mad. I think its because the macro resets then instantly goes to the bugs when tries to loot when my bees are still resting If this option isnt available maybe add an option to make it wait however many seconds after resetting.
Thank you for your time.

### What is your Discord username?

vovoreal

**Comment by misc-et** [comment]
This option exists as 'Wait X seconds after convert' in the settings tab of Natro.
