### ISSUE TITLE
automatically use sticker printer

### ISSUE THREAD

**Issue by Shiyueeeee** [NatroTeam/NatroMacro#653]
### Have you searched the existing suggestions?

No

### What is your suggestion?

automatically use sticker printer every 1 hours, could first be only use basic egg and add other options later

### How will this improve Natro Macro?

sticker printer is also a type of 'collect' i think

### What is your Discord username?

shiyuue

**Comment by Therogamer** [comment]
The macro already has this... Boost > Lower Right > Stickers

**Comment by Dekudicklicker** [comment]
its not working tho, doesnt ever go to the sticker printer anymore.
