### ISSUE TITLE
the dandelion field macro doesn't work properly

### ISSUE THREAD

**Issue by SillyCat-0** [NatroTeam/NatroMacro#654]
### Have you searched the existing bug reports?

No

### What happened?

when you select dandelion field and start the macro, it makes you go past the field and collect barely anything, please can you fix this? thanks in advance

### Steps to reproduce

1.select the dandelion field macro
2.press f3 to start
3.watch as you run right through the field next to the ladder of clover

### What would you expect to happen?

a working macro for dandelion field

### Natro Macro version

the latest version

**Comment by Puffy1787** [comment]
There are two reasons why you might be drifting off the field. One is your movespeed. Go to settings in bee swarm and scroll until you see movespeed (without any haste or bear bee). Then go to the natro macro settings and make sure the number matches. Also make sure you have movespeed correction turned on. The second reason could be that you don't have drift comp on. Drift comp will prevent you from going off the field as long as you place a super saturator. If you don't have a super saturator then the best option is to use corner x snae which auto aligns itself by going in the corner.
