### ISSUE TITLE
Announce Guiding Star Warnings

### ISSUE THREAD

**Issue by remizuwu** [NatroTeam/NatroMacro#656]
### Have you searched the existing suggestions?

No

### What is your suggestion?

To have a warning when you enable the announce guiding star option in Natro that says something along the lines of "Your account may be at risk for using it" blah blah blah

### How will this improve Natro Macro?

I've seen numerous people get banned and / or warned when using the Announce Guiding Star option and I think it wouldn't hurt to add a reminder that it is a possibility

### What is your Discord username?

Remizu

**Comment by comkys** [comment]
that's definitely not it, ive been using it for months on end remi😭.
