### ISSUE TITLE
resetting bug

### ISSUE THREAD

**Issue by juju-him** [NatroTeam/NatroMacro#658]
### Have you searched the existing bug reports?

Yes

### What happened?

it keeps making me reset

### Steps to reproduce

1.stop making me reset
2.go to the field i want it to go
3.make this work again

### What would you expect to happen?

i expect for this macro to not make me reset

### Natro Macro version

v2

### What is your Discord username?

marion522

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
