### ISSUE TITLE
sticker printer not working

### ISSUE THREAD

**Issue by Dekudicklicker** [NatroTeam/NatroMacro#660]
### Have you searched the existing bug reports?

Yes

### What happened?

Even with it selected, my game never goes to the sticker printer, ever, even if there is nothing to do but gather, it will not ever go to the sticker printer anymore.

### Steps to reproduce

1.select sticker printer option
2.start
3.wait

### What would you expect to happen?

for me to be able to get my eggs in the sticker stack automatically like with any other beeswarm mechanic the macro has been doing

### Natro Macro version

v1.0.0.2

### What is your Discord username?

Dekudicklicker

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
