### ISSUE TITLE
repeatables break natros pathing system

### ISSUE THREAD

**Issue by Guyguymanmanthingit** [NatroTeam/NatroMacro#661]
### Have you searched the existing bug reports?

Yes

### What happened?

whenever you pick up a quest from at least bucko or brown bear that requires a blue only field (at least) it will do a placeholder(?) path which it goes to bamboo field and then resets 

https://github.com/user-attachments/assets/e3baf0e7-d385-4262-b5da-0569b5960109

### Steps to reproduce

1. make natro get a bucko/brown bear quest and make it gather in the field
2. n/a 
3.n/a

### What would you expect to happen?

it should successfully travel to the requested field as normal instead of just doing a placeholder

### Natro Macro version

1.0.0.2

**Comment by Guyguymanmanthingit** [comment]
https://github.com/user-attachments/assets/ad105e39-b6b8-4044-9285-84b786ae1a5c

heres another variation of the placeholder path

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
