### ISSUE TITLE
Auto Legendary until mythic

### ISSUE THREAD

**Issue by DX3500** [NatroTeam/NatroMacro#665]
### Have you searched the existing suggestions?

No

### What is your suggestion?

having auto legendary until mythic is great for most midgame players, since it cost less royal jellies to roll for mythic than to use auto mythic. where of course it will stop when it detects a mythic.

### How will this improve Natro Macro?

it takes long to manually do legendary until mythic, so hopefully this can be added

### What is your Discord username?

1.azra

**Comment by misc-et** [comment]
This would be achievable in the implementation of https://github.com/NatroTeam/NatroMacro/issues/731
