### ISSUE TITLE
Mask changing in macro

### ISSUE THREAD

**Issue by Dimjustdatguy** [NatroTeam/NatroMacro#667]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I would like this feature to be added to Natro Macro because it would be beneficial to be able to switch into Demon mask, or Diamond mask etc. while macroing. 

### How will this improve Natro Macro?

The person could be doing something like Coconut crab or Mondo chick. Especially Coconut crab since the user needs to be pretty good to kill it whilst macroing. It could also help when doing repeated quests that may require a certain pollen color if the user has different quest givers chosen, such as: Someone trying to get Dark scythe and/or hydroponic planter, they could be a red hive so switching into the diamond mask when doing a bucko quest could help.

### What is your Discord username?

dimdadiggagod

**Comment by DullSmallmega176** [comment]
overall the idea can be a "good" thing but to implement this will be a PAIN, you'll have to consider so many variables considering movement, and jump.

a really great example is Night memory match, yes it can get there but it's really unreliable in the path
