### ISSUE TITLE
Stump Field Booster Check 

### ISSUE THREAD

**Issue by llenfy** [NatroTeam/NatroMacro#668]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Hi, I am a blue hive and I macro in the field boosted by the blue booster and I kill my snail everytime it spawns. In the new update Onett added the Stump Field in the field cycle and I cannot enable the option to ignore stump field boost. I have added it and for now I haven't seen any issues. You can contact me on discord.

![BoostedFieldsFix](https://github.com/user-attachments/assets/64e3d037-1af0-4767-ad85-9a4aa611199c)

### How will this improve Natro Macro?

Since the stump field booster isn't deactivateable (unless you don't kill your snail) you cannot use the Gather in Boosted field feature. With this fix more users can use the gather in boosted field option.

### What is your Discord username?

.lenfy

**Comment by DullSmallmega176** [comment]
this is already being worked on.

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/609
