### ISSUE TITLE
Field Drift Compensation Massive Issue

### ISSUE THREAD

**Issue by IveDunnit** [NatroTeam/NatroMacro#670]
### Have you searched the existing bug reports?

Yes

### What happened?

The field drift compensation uses neon blue pixels on the screen from the supreme saturator to know where to move the player to compensate for field drift. Unfortunately, the bottom of the Hydroponic planter shares the same neon blue as the supreme saturator. This makes the player compensate toward the planter instead of the supreme saturator.

### Steps to reproduce

1. Macro in a field with a hydroponic planter

### What would you expect to happen?

If there is any field drift, the player should be compensated to the sprinkler rather than the planter.

### Natro Macro version

v1.0.0.2

### What is your Discord username?

who_dunnit

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/739
