### ISSUE TITLE
Bee bear quests

### ISSUE THREAD

**Issue by hailey2012** [NatroTeam/NatroMacro#672]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Make bee bears cub buddy quest by making a macro for it. makes the quest much easier. For the sticker part make the macro go to the field to plant or harvast the sticker planter, use sticker seeker, etc.

### How will this improve Natro Macro?

It would be so much easier to get cub buddy

**Comment by misc-et** [comment]
Thanks for your suggestion. There aren't plans to add the main questlines like this to the macro, as our aim is to reduce some of the more grindy repetitive elements rather than play the game for you (plus Beesmas is now over!).
