### ISSUE TITLE
missing stickers

### ISSUE THREAD

**Issue by Qbeeflames** [NatroTeam/NatroMacro#674]
### Have you searched the existing bug reports?

No

### What happened?

My stickers have been missing lil by lil now Im missing hourglass sticky hand  and more, Its also happening to my friends, Always happens after I set off Macro. Im lvl 18-19 red hive . it sucks dont know what to do

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

you tell me

### Natro Macro version

1.0.0.2

### What is your Discord username?

Qbee aka Edishoney

**Comment by misc-et** [comment]
Have you enabled the sticker stacker in the boost tab? As this is the only way the macro can use stickers. If you're still having an issue, please see our [Discord server](https://discord.com/invite/natromacro) for support.
