### ISSUE TITLE
Add a video feature 

### ISSUE THREAD

**Issue by Wes2600** [NatroTeam/NatroMacro#676]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add a feature like the screenshots one but a "Livestream" instead 

### How will this improve Natro Macro?

It is a quality of life feature that will help people trouble shot problems that they have or see why they died or see what is happening when they get spikes of high amounts of pollen/honey.

### What is your Discord username?

Wes__2600

**Comment by misc-et** [comment]
Thanks for this suggestion, at this time we are not looking at adding video to the discord remote control feature, though this is perhaps something that can be considered in the future.
