### ISSUE TITLE
planters

### ISSUE THREAD

**Issue by Joni7f** [NatroTeam/NatroMacro#677]
### Have you searched the existing bug reports?

Yes

### What happened?

i pressed f5 to see where my planters are cleared all and also claimed them manually. Then started the macro again and it wanted to collect the planters and didnt registerd that  i already did that after that i closed the macro and reopend it and now it wont place planters anymore

### Steps to reproduce

1.pause macro (f2)
2.press f5 if not already done where all the planter status is 
3.claim them manually and then start macro again

### What would you expect to happen?

it shouldnt place the planters

### Natro Macro version

newest 1.0.0.2

### What is your Discord username?

Joni

ps: i wanted to add a video but its too big only 10 mb allowed. i am having this problem now for the 2nd time the first time i just didnt macored overnight and the next day everything worked as before

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
