### ISSUE TITLE
Bug that I have a solution for that also a suggestion

### ISSUE THREAD

**Issue by Doominator1** [NatroTeam/NatroMacro#678]
### Have you searched the existing suggestions?

No

### What is your suggestion?

make it instant convert if it fails to walk back to the hive instead of resetting character, because I lose a lot of honey that way, also add a screenshot or a video of what happened to cause you to not get to the hive to debug it and stuff.

### How will this improve Natro Macro?

yes

### What is your Discord username?

yoursodium

**Comment by Noobyguy775** [comment]
#374
