### ISSUE TITLE
PRESETS!

### ISSUE THREAD

**Issue by ww1ndy-official** [NatroTeam/NatroMacro#68]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I have an idea to add presets, there should be some set presets (for example: Midgame-Pine-Field
and this should be editable throughout the macro to change if needed, but i think that presets would make this macro even better then it already is simplifying the program
Thankyou!

### How will this improve Natro Macro?

This feature will make the program simpler, aswell as making it easier to use. And making it better to macro for whats just right for you!

**Comment by XDe0** [comment]
Very cool idea! Fully agree with you

**Comment by zspz** [comment]
I think this is a great idea, it is similar to #77 so I'm merging the two 😄
