### ISSUE TITLE
Keeps restarting

### ISSUE THREAD

**Issue by kmyung128** [NatroTeam/NatroMacro#681]
### Have you searched the existing bug reports?

No

### What happened?

When i run the macro, it constantly kills my character and then eventually kicks me off the server. 

### Steps to reproduce

1. I uninstalled the macro and reinstalled
2. I restarted the game
3. Cleared all my cache and history. 

### What would you expect to happen?

To have it fixed. 

### Natro Macro version

1.0.0.2

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
