### ISSUE TITLE
My macro always resets whenever it starts

### ISSUE THREAD

**Issue by FeeshyBoopkins** [NatroTeam/NatroMacro#682]
### Have you searched the existing bug reports?

Yes

### What happened?

I do everything correctly,yet macro still goes in a loop of resetting and resetting over and over again. Please fix this as soon as possible.

### Steps to reproduce

1. Open macro
2. Click start (F1)
3. Watch the reset loop begin

### What would you expect to happen?

The macro resets once or twice, then it begins its job as normal.

### Natro Macro version

v1.0.0.2

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
