### ISSUE TITLE
Red Data Support (Analytics) & Goo Quests for Bucko & Riley

### ISSUE THREAD

**Issue by Megadragon779** [NatroTeam/NatroMacro#683]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

In the hourly reports they provide mainly blue data, and I get that macroing is better supported for blue so it’s more useful to get those in first, but still I would like to see data about my flame uptime, dark heat uptime, and how often my scorching star goes off, and like how big it gets and other red related data. Also I don’t grind gifted bucko bee’s quest but in gifted riley bee’s goo related quest such as “clean-up” and just “goo” I would like to enable an option to allow the macro to use gumdrops to complete that quest. Just so that it can get more quests done

### How will this improve Natro Macro?

Red Support, only in a data perspective though so that red can find better ways to macro. Mainly the goo quest though, would be very useful as red would not need to have a gummy bee in the hive to complete without burning through all there gumdrops, also could be useful for blue so they can grind up more quests

### What is your Discord username?

reigning_king

**Comment by Noobyguy775** [comment]
#20
the gumdrops while questing thing is coming soon too
