### ISSUE TITLE
running macro causes roblox to crash after 20-30 minutes

### ISSUE THREAD

**Issue by schustez** [NatroTeam/NatroMacro#685]
### Have you searched the existing bug reports?

Yes

### What happened?

Every time I attempt to run the macro roblox will freeze after about 30 minutes. I know it has nothing to do with my computer as roblox can run perfectly fine for a long time with no problems but only when running the macro it has problems. I also know it's most likely not the natro program aswell since i can use things like the autoclicker and still have no crashing problems. only when running the macro I have these problems. 

### Steps to reproduce

1.start natro macro
2.let run for about 30 minutes
3.game crashes

### What would you expect to happen?

the macro should run just fine with no crashing
![IMG_0385](https://github.com/user-attachments/assets/dfda329f-5a86-441f-8ff5-0d44206b5de0)

### Natro Macro version

i redownloaded the macro the day im writing this so the latest version

### What is your Discord username?

schustez

**Comment by dreadmp3** [comment]
ram issue or roblox anticheat tweaking

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with your PC / settings, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
