### ISSUE TITLE
auto gifter

### ISSUE THREAD

**Issue by kotiklaim** [NatroTeam/NatroMacro#691]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

its using treats on bees 

### How will this improve Natro Macro?

it gonna make gift process easier

### What is your Discord username?

kotiklaim

**Comment by Noobyguy775** [comment]
using treats on bees can already be done in game, but an auto jelly that searches for a specific bee (with options for mutations/gifted) is on the way
