### ISSUE TITLE
Onett's lid art loot

### ISSUE THREAD

**Issue by Lavawheat** [NatroTeam/NatroMacro#692]
### Have you searched the existing bug reports?

No

### What happened?

I am not sure if you guys knew but when the macro uses the onett's lid art, it doesn't pick up all the loot (at least for me)

### Steps to reproduce

When the macro uses the the lid art, it goes to half the circle and then falls of the circle edge and tries to get the red of the loot but only end up getting 2.

### What would you expect to happen?

I would expect it to pick up all the loot inside the loot circle

### Natro Macro version

1.0.0.2

### What is your Discord username?

Lavawheat

**Comment by misc-et** [comment]
Thanks you for this report. Unfortunately, it was missed during Beesmas. We can look into it during a future Beesmas, if the issue persists.
