### ISSUE TITLE
bug when claiming hive

### ISSUE THREAD

**Issue by S00Rand0m** [NatroTeam/NatroMacro#696]
### Have you searched the existing bug reports?

No

### What happened?

when it loads in a new game it does not get a hive and keeps going leaving game, joining game, trying to get a hive fail and going back to step one. al the settings are right

### Steps to reproduce

1.standing for at least 3 seconds on a hive thing
2.
3.

### What would you expect to happen?

stop the bug

### Natro Macro version

v1.0.0.2

### What is your Discord username?

soorandom1

**Comment by DullSmallmega176** [comment]
this does not give much information, look at the troubleshooting guide in the discord server
discord.gg/NatroMacro
