### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ShayanAhmaddd** [NatroTeam/NatroMacro#699]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Hello,
My suggestion is to add a variety of colors..

### How will this improve Natro Macro?

Because white is too bright and everyone likes dark mode more

**Comment by DullSmallmega176** [comment]
![image](https://github.com/user-attachments/assets/ae386187-96c8-4c13-88c9-d90b6a1e592e)
there's already Gui themes, but making custom themes are really difficult

(as in you gotta know a lot to make your own .msstyles themes/files)

**Comment by Noobyguy775** [comment]
lakrits, concaved are core are the dark themes iirc
