### ISSUE TITLE
King beetle 

### ISSUE THREAD

**Issue by icarus-170** [NatroTeam/NatroMacro#702]
### Have you searched the existing bug reports?

Yes

### What happened?

When the macro tries to kill the king beetle, it blocks if i did it before

### Steps to reproduce

1.kill king beetle
2.setup natro to kill it
3.lanch the macro

### What would you expect to happen?

a detection that there is no king beetle

### Natro Macro version

the lastest

### What is your Discord username?

icarus_170

**Comment by DullSmallmega176** [comment]
there's already one in place to my knowledge, it'll try two times or (iirc) because it didn't find the health bar, either next hour or estimate wait time for it to spawn next

it has been a bit of time since i last seen it do it but overall it would just waste a little bit of time

**Comment by Noobyguy775** [comment]
#502
