### ISSUE TITLE
Doesn't collect stocking loot

### ISSUE THREAD

**Issue by greivous02** [NatroTeam/NatroMacro#703]
### Have you searched the existing bug reports?

Yes

### What happened?

i had the collect stockings on to get some extra loot every hour and noticed it doesn't collect the three items that appear

### Steps to reproduce

1. set macro to collect brown bears stockings
2. wait for it to go there and press e
3. watch it reset instead of collecting the loot

### What would you expect to happen?

make it collect the loot, all that needs to be done is walk forward and a bit to the left and right

### Natro Macro version

1.0.0.2

### What is your Discord username?

greivous02

**Comment by misc-et** [comment]
Thanks you for this report. Unfortunately, it was missed during Beesmas. We can look into it during a future Beesmas, if the issue persists.
