### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by victorbulota** [NatroTeam/NatroMacro#706]
### Have you searched the existing suggestions?

No

### What is your suggestion?

You should add an option that you can change the setting of the macro or make it do certain action such as disconnect (so you can connect via your phone to do some things and) and make it reconnect after. People would write these commands on their discord server.

### How will this improve Natro Macro?

If you leave for a long period of time, you could set the macro’s setting to so a bug run and collect mats, before you leave, and then you realise that you have enough mats, so you want it to collect honey.

It could also make the user able to remotely disconnect his account from discord so he can log on, change some things you buy things and when he is done, he just leave the game and the macro will auto join the game, using the new things he bought/made.

### What is your Discord username?

.bulota

**Comment by Noobyguy775** [comment]
this already exists

https://discord.com/channels/1012610056921038868/1088923608295936000
