### ISSUE TITLE
START.bat won't open.

### ISSUE THREAD

**Issue by santan5332** [NatroTeam/NatroMacro#708]
### Have you searched the existing bug reports?

No

### What happened?

When I double-clicked the batch file, the loading thing on the cursor popped up for a bit, but then it didn't open. Also, I tried to get help by posting a thing on the discord server, but nobody helped :(

### Steps to reproduce

1. Download Natro Macro
2. Extract all
3. Double-click batch file

### What would you expect to happen?

Natro to open

### Natro Macro version

v1.0.0.2

### What is your Discord username?

dingdong66

**Comment by Noobyguy775** [comment]
Ill help you on the discord
