### ISSUE TITLE
Decide after what time to search for the neon blue pixel 

### ISSUE THREAD

**Issue by VolTixxiTloV** [NatroTeam/NatroMacro#709]
### Have you searched the existing suggestions?

No

### What is your suggestion?

The title explains it.

### How will this improve Natro Macro?

The "every so often" doesn't cut it for me. Usually during a session I have to readjust many times.

### What is your Discord username?

asopnmqw

**Comment by Noobyguy775** [comment]
sounds like you have an underlying user issue, join the discord for support (https://discord.gg/natromacro)
