### ISSUE TITLE
Respawns instead of converting

### ISSUE THREAD

**Issue by Lokkasnicht55** [NatroTeam/NatroMacro#713]
### Have you searched the existing bug reports?

Yes

### What happened?

when the bagpack is full, it walks to the hive. But it doent stops at the hive but walks to the club dispencer and reaspawns.

### Steps to reproduce

1.Starting
2.
3.

### What would you expect to happen?

To stop at the hive and convert. (I have the right hive listed)

### Natro Macro version

1.0.0.2

### What is your Discord username?

Lokkas_

**Comment by Lokkasnicht55** [comment]
I wateched tutorials and lokked at every setting but I cant get it to work.

**Comment by Noobyguy775** [comment]
join the discord for support (https://discord.gg/natromacro)
