### ISSUE TITLE
Ant Challenge

### ISSUE THREAD

**Issue by Jaboism** [NatroTeam/NatroMacro#714]
### Have you searched the existing bug reports?

No

### What happened?

Macro isnt executing Ant challenge or bucko bee quests for me. I have restarted it multiple times and cant complete it or reach ant challenge

### Steps to reproduce

1.
2.
3.
idk

### What would you expect to happen?

idk

### Natro Macro version

Newest one

### What is your Discord username?

laazure

**Comment by Noobyguy775** [comment]
join the discord for support (https://discord.gg/natromacro)
