### ISSUE TITLE
Drift Comp 

### ISSUE THREAD

**Issue by Peppermint39** [NatroTeam/NatroMacro#716]
### Have you checked the existing suggestions?

Yes.

### What is your suggestion?

I feel like the basic sprinkler should also be compatible with drift comp because theres only 1 basic sprinkler to place, the Supreme Saturator is very expensive and requires 10 grandmaster badges to unlock.

### How will this improve Natro Macro?

It would help gathering issues in specific fields like Cactus and Clover. It would also benefit players without 10 grandmaster badges and 55B honey trying to increase their pollen collection for those fields, because stationary gathering is slow.

**Comment by Noobyguy775** [comment]
see #573
