### ISSUE TITLE
Remotely control macro via a bot like discord for easy tweaking?

### ISSUE THREAD

**Issue by BeeNoANo** [NatroTeam/NatroMacro#719]
### Have you searched the existing suggestions?

No

### What is your suggestion?

1. I feel like this would be good because it's quite inconvenient when you're hanging up your phone at home and going somewhere but sometimes you want to see how your progress is going.
 
2. I think I can use a bot model similar to the bot in discord, where I will give tokens to natro marco and it will host you a bot that can control marco remotely and do many features.

3. The bot can take screenshots (check to see if he left the field or got an error), can reset the process, can start the process, can change his field, take screenshots of tasks to Check to see how far the task has been completed

Thank for read!

### How will this improve Natro Macro?

As I said above

### What is your Discord username?

nothinghere1341

**Comment by Noobyguy775** [comment]
I just closed an issue exactly like this lol
#706
