### ISSUE TITLE
Wont let me move to another server. 

### ISSUE THREAD

**Issue by Qbeeflames** [NatroTeam/NatroMacro#720]
### Have you searched the existing bug reports?

No

### What happened?

I get error when macro changes to another server. I see it trying over and  over cant get back in. Please help

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

please tell how to fix it please

### Natro Macro version

1.0.0.2

### What is your Discord username?

Qbee aka Edishoney

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
