### ISSUE TITLE
Not collecting wealth clock and other collect stuff

### ISSUE THREAD

**Issue by Bryce702** [NatroTeam/NatroMacro#721]
### Have you searched the existing bug reports?

No

### What happened?

For some reason, My macro will NOT go for the wealth clock along with multiple other collect stuff. Sometimes it will go for some things, or none at all.

### Steps to reproduce

1. I go to rose field as my only field
2. and user some of the collecting stuff 
3.I restart my macro and start it but it doesn't work

### What would you expect to happen?

For the macro to do what it is supposed to

### Natro Macro version

Im new and don't know how to check?

### What is your Discord username?

bryce_11178

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
