### ISSUE TITLE
Macro Gather breaks after some a few hours

### ISSUE THREAD

**Issue by AvirajB21E** [NatroTeam/NatroMacro#726]
### Have you searched the existing bug reports?

Yes

### What happened?

https://github.com/user-attachments/assets/b670e386-0848-4a8c-b0f9-2875901e0827

After a few hours of macroing whenever it goes to gather it goes to the corner of pine since i have corner x snake but instead does the loop in the video i have attached with is rotating and moving towards the ramp then going to polar bear and going to the corner hen gliding over cactus and back to pine corner and repeating until gather time is up (see video). When goes back to hive it also starts randomly spazzing out and some times it ends up in mushroom or honey dispenser and resets like 5 or 6 times. It does other tasks other than gather fine though.This makes me gain 0 honey and it works for the first few hours??? This suddenly just started happening i even have drift comp off and changed my graphics to 4 but there is nothing on this bug anywhere?? Please help

### Steps to reproduce

1. Set macro in pine with default pine settings and cornerxsnake with drift comp on or off
2.Macro for a few hours until it breaks
3.When it goes to gather watch it do what ive described

### What would you expect to happen?

The macro to gather in pine with cornerxsnake pattern fine and not break after a few hours and do the loop ive described 

### Natro Macro version

10.0.2 (newest)

### What is your Discord username?

@dogeinsane

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. For example, it may be rejoining a different version of Roblox that you have installed, with incorrect game settings, if that's set to be your Windows default. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
