### ISSUE TITLE
my macro always resets for 10 mins or more

### ISSUE THREAD

**Issue by IMBETTERTHANU12287** [NatroTeam/NatroMacro#727]
### Have you searched the existing bug reports?

No

### What happened?

 my macro always resets for 10 mins or more

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

to stop from doing that

### Natro Macro version

1.0.0.2v

### What is your Discord username?

x_pro12287

**Comment by DullSmallmega176** [comment]
this seems like a user error issue, Make a post in the [Macro Help](https://discord.com/channels/1012610056921038868/1073389106568122378) channel.
