### ISSUE TITLE
Stop gathering after reaching set amount of pollen

### ISSUE THREAD

**Issue by VolTixxiTloV** [NatroTeam/NatroMacro#729]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

After reaching the set amount of pollen the macro will stop gathering in the field and move to a different field set by the player.

### How will this improve Natro Macro?

For finishing spirit bear quests so the macro doesn't still farm in a wrong coloured field or a low level one.

### What is your Discord username?

asopnmqw

**Comment by misc-et** [comment]
Thanks for your suggestion. Currently the user can rotate fields and this can partially achieve what you are looking for. Stopping at set pollen would be a little more complex, and also beyond the scope of the macro in that it is not designed to specifically complete the main questline tasks for you.
