### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by bigbootylatina123** [NatroTeam/NatroMacro#73]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I don't know how this would work but being able to sync the natro macro logs between devices.

### How will this improve Natro Macro?

I want this feature because I have to switch between my laptop and pc to macro when i want to use my pc, but this messes up my planters setting (I think) and the macro just does nothing the entire macro trying to find my planters

**Comment by zspz** [comment]
You can already copy and paste the settings folder between sessions if you want to do this.
