### ISSUE TITLE
Nectar Condenser / Nectar Pot, Sticker Printer.

### ISSUE THREAD

**Issue by Platon01** [NatroTeam/NatroMacro#730]
### Have you searched the existing suggestions?

No

### What is your suggestion?

It would be good, if the Macro was able to detect if we have more than 12 H of Nectar so it can create a certain amount of Nectar Vial, and ( Enable or disabled ) _**collect the sticker if it spawns on Coconut Field**_.
And for Pot, detect if the number of nectar the player want is the same as the player want, if yes then it goes to it and stock ( collect ) the nectar. For sticker printer, make so we can use star egg, Gifted Silver, Gold, Diamond and Mythic. 

### How will this improve Natro Macro?

By making it more efficient to all players 

### What is your Discord username?

whitesb

**Comment by misc-et** [comment]
Thanks for your suggestions - these have already been made separately in other posts, so I'll close this here.
