### ISSUE TITLE
Gathering Field Demo and Representation

### ISSUE THREAD

**Issue by LilTRok** [NatroTeam/NatroMacro#734]
### Have you searched the existing suggestions?

No

### What is your suggestion?

My suggestion is that because we have so many different ways to farm and macro in different feilds, creating a picture of the feild that you choose in the gather tab, and have it show you a picture of the feild, and how the settings will Affect the run. For example, Pineapple patch is shown in a picture. Select lines as your pattern. The picture will show you how the pattern will go. it will draw lines across the feild to show the run, where the sprinkler will be placed, and will show the pattern lines.

### How will this improve Natro Macro?

I would like this feature because it will be incredibly useful for people who want to grind stickers, as it will show the patterns and people can change the macro to their wants, and it will show what each pattern looks like and people can evaluate the pros and cons of each. 

### What is your Discord username?

liltrok

**Comment by misc-et** [comment]
Thanks for your suggestion. This would be achieved in https://github.com/NatroTeam/NatroMacro/issues/276.
