### ISSUE TITLE
Atuo nectar condenser

### ISSUE THREAD

**Issue by Lavawheat** [NatroTeam/NatroMacro#735]
### Have you searched the existing suggestions?

No

### What is your suggestion?

A setting in the planter section to automatically store vials. 

### How will this improve Natro Macro?

If a person macros for a long time and uses this setting, they would have 10/10 vials for all of the nectars. This is beneficial because if they stop macroing/macro breaks, they don't have to wait hours for their nectars to be filled again. They could just get their vials to get their nectar high again.

### What is your Discord username?

lavawheat

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/282
