### ISSUE TITLE
Bear Morph not working with 35 bee zone

### ISSUE THREAD

**Issue by rbaxim** [NatroTeam/NatroMacro#736]
### Have you searched the existing bug reports?

No

### What happened?

When the macro is going to the 35 bee zone with bear morph, it fails to make it up the shortcut (by shortcut i mean like)
![image](https://github.com/user-attachments/assets/d15244ff-5be8-4e51-8988-3b0945b0015c)

### Steps to reproduce

1. Get Bear Morph
2. Try climbing up the 35 bee zone shortcut 
![image](https://github.com/user-attachments/assets/72bf6d15-afd0-4cc2-b187-dfa3efbf7c5c)

### What would you expect to happen?

I expected the macro to climb up to the 35 bee zone using the shortcut
![image](https://github.com/user-attachments/assets/4554455f-7641-4cb2-9e8b-4fea366985c1)

### Natro Macro version

1.0.0.2

### What is your Discord username?

rbaxim

**Comment by misc-et** [comment]
Thanks for your suggestion. Do you have a screen recording of the issue, so we can see how it fails? 
Also, when going to the 35 bee zone, it will always try twice, so if it fails the first time it should make it on the second (as it is less likely to have bear morph both times).

**Comment by misc-et** [comment]
Closing this report due to inactivity, but please feel free to reopen if you are still having the issue.
