### ISSUE TITLE
Stingers

### ISSUE THREAD

**Issue by Onurkata1213** [NatroTeam/NatroMacro#737]
### Have you searched the existing bug reports?

Yes

### What happened?

why does it use my stingers when fights with bugs or bosses? i cant get a vicious bee anymore

### Steps to reproduce

1.starting the macro
2.going to sleep
3.no stingers

### What would you expect to happen?

well i hope it wont use my stingers anymore

### Natro Macro version

v.1.0.0.2

### What is your Discord username?

onurkata123

**Comment by misc-et** [comment]
Disable 'Attacking' in the hotbar slot of the Boost tab in Natro, if you have it enabled. Otherwise, please see our [Discord server](https://discord.com/invite/natromacro) for support.
