### ISSUE TITLE
Mongo kill wait time after kill

### ISSUE THREAD

**Issue by dah121557** [NatroTeam/NatroMacro#74]
### Have you searched the existing bug reports?

Yes

### What happened?

Mongo wait time is too long after kill

### Steps to reproduce

1.
2.
3.
Wait to kill mongo 

### What would you expect to happen?

After kill go and collect your rewards

### Natro Macro version

9.7

### What is your Discord username?

Dah121557, dad121557

**Comment by Noobyguy775** [comment]
Update to the latest version, and use the manual option.

**Comment by Noobyguy775** [comment]
Sorry, I misread this, ill see if I can fix it

**Comment by Noobyguy775** [comment]
It takes so long right now because it must ensure Mondo hasn't wandered off-screen, which could be changed with a better camera angle/rewrite of the current system. I'll look into it and see if there's something I can do that would be better than the current system

**Comment by zspz** [comment]
This is a duplicate, refer to #56.
