### ISSUE TITLE
Natro Macro start file not working

### ISSUE THREAD

**Issue by kubaandel** [NatroTeam/NatroMacro#741]
### Have you searched the existing bug reports?

Yes

### What happened?

START file not "starting" I downloaded newest version from Discord, then with help from Youtube, Reddit and friends I extracted your file and opened your file. But it doesnt matter if I double click or right click it won't open. I tried to change Windows Scale and layout to 100% etc. Do you know why please? Because from what I found other people have problems on another stage.

### Steps to reproduce

1. downloaded files
2. extracted these files
3. failed to open Start file

### What would you expect to happen?

Its just picture from my files with that Start file

### Natro Macro version

1,0,0,2

### What is your Discord username?

.kubamax

**Comment by wikiepeidia** [comment]
disable antiviruses including windows defender or if you would need some protection add it to the whitelist or somesort. if start.bat fail just download ahk 2.0 and go t submacros/natromacro.ahk and run it like natro back then

**Comment by misc-et** [comment]
I'll go ahead and close this, but it's still happening and you need further support, please see our [Discord server](https://discord.com/invite/natromacro) for help.
