### ISSUE TITLE
Natro Macro QOL Update

### ISSUE THREAD

**Issue by Zarness** [NatroTeam/NatroMacro#742]
### Have you searched the existing suggestions?

No

### What is your suggestion?

1st:
When the user spawns in the normal area (like when you join the game), and not the hive the macro will reset, i have quite often seen scenarios where it will keep resetting and not spawning on hive and this will waste a lot of time, so add a feature where if it doesnt spawn on hive it will go forward align camera above the player so it sees the ground and check for the spawn plate by using the image method and if it locates it then it can go forward and use the normal loop used for arranging player character when it comes down via glider to hives after collecting in pine.
2nd:
Adding more checks to it, so the bugs like when it doesnt click on wind shrine box/falls off the shrine or miss aligns or anything like that, and game freezes(game freezes will take 10 words to fix because Myu(myurius) helped me fix them), so it can check the screen to see if the user has muss aligned or macro hasnt clikced and do the loop again
3rd:
(Maybe) Add an AI?? (If it's possible ofc) That learns from it's surroundings and if there are any problems with the player like incorrect hive slot and haste problems let's say, to adapt to the conditions?

### How will this improve Natro Macro?

Its a QOL update it will make the life of a lot of users easier

### What is your Discord username?

zarness_(Zarness(da best honored duck) is display name, i am banned from natro server because i said r word to my internet)

**Comment by misc-et** [comment]
Thanks for your suggestions. 
1. This has been suggested previously
2. It would be helpful if you could clarify exactly which checks you would like to see, and provide more detail regarding the game freezes you mention.
3. There aren't plans to add AI to Natro Macro at this time

**Comment by misc-et** [comment]
Closing this report due to inactivity, but please feel free to reopen if you are still having the issue.
