### ISSUE TITLE
bear bee: bear morph speed recognition

### ISSUE THREAD

**Issue by Sheagun** [NatroTeam/NatroMacro#743]
### Have you searched the existing bug reports?

Yes

### What happened?

Every time Bear Morph is active the player gains aditioninal speed, the macro does not recognize this abilitys movementspeed stat change and proceeds to move like the movementspeed has not been altered. this caused the macro to fail collecting items dropped by for example the honey wreath. It will walk off the path its supposed to follow and is not able to collect the honey tokens in this example. This mostly happens when bear morph is active and also 5 haste tokens or more at the same time.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I expected to see the macro adapt to the base speed change and move accordingly.

### Natro Macro version

v1.0.0.2

### What is your Discord username?

Sheagun

**Comment by misc-et** [comment]
Hi, can you provide a video of the issue, a screenshot of your settings in game, and screenshot of movespeed in the macro without haste?

**Comment by misc-et** [comment]
Closing this report due to inactivity, but please feel free to reopen if you are still having the issue.
