### ISSUE TITLE
Mini avatars aren’t supported 

### ISSUE THREAD

**Issue by AZ790** [NatroTeam/NatroMacro#744]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Mini avatars cannot be used because they cause the macro to keep on resetting the character. 

### How will this improve Natro Macro?

This will improve natro macro because people won’t be worrying about whether or not they can use a specific avatar just to macro.

### What is your Discord username?

nxxt_

**Comment by misc-et** [comment]
Thanks for your report. It is possible that we can alter the hive confirmation checks, however this is fairly complex and so for now, we ask that users continue not to use small avatars as a simple solution.
