### ISSUE TITLE
nartro macro

### ISSUE THREAD

**Issue by jpv0202** [NatroTeam/NatroMacro#746]
### Have you searched the existing bug reports?

No

### What happened?

nartro macro taking 1 min befor the charachter to move

### Steps to reproduce

1.start natro macro
2.let it reset your charachter 
3.and now it is stuck at hive for a min

### What would you expect to happen?

tha macro makes less bc of it

### Natro Macro version

natro macro v_0,0,2

### What is your Discord username?

jpv0202

**Comment by misc-et** [comment]
Duplicate post.
