### ISSUE TITLE
natro macro

### ISSUE THREAD

**Issue by jpv0202** [NatroTeam/NatroMacro#747]
### Have you searched the existing bug reports?

yes

### What happened?

nartro macro taking 1 min befor the charachter to move

### Steps to reproduce

1.start natro macro
2.let it reset your charachter 
3.and now it is stuck at hive for a min

### What would you expect to happen?

 i make less bc of the bug

### Natro Macro version

natro macro v_0,0,2

### What is your Discord username?

jpv0202

**Comment by misc-et** [comment]
This is due to a new roblox update, which changed the UI. You can find a fix at our discord server, in macro-help. It will be resolved in a future release of the macro.
