### ISSUE TITLE
Canon bug

### ISSUE THREAD

**Issue by Bypass420** [NatroTeam/NatroMacro#748]
### Have you searched the existing bug reports?

No

### What happened?

First : I cant join the discord server support section

Main bug: canon going at wrong place

### Steps to reproduce

1.Canon alway going at clover field
2.after walking to ticket clock
3.Reseting and doing the same thing

### What would you expect to happen?

Explain me how to fix it and be happy to use your macro and maybe support in the future.

### Natro Macro version

v1.0.0.2

### What is your Discord username?

bypass420

**Comment by misc-et** [comment]
Duplicate post.
