### ISSUE TITLE
Macro not Keeping old Ant Amulet and resetting everytime it enters a new ant challenge

### ISSUE THREAD

**Issue by Dryx24** [NatroTeam/NatroMacro#752]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro is not Keeping the old Ant Amulet and it always resets everytime it enters a new ant challenge, getting only a low score although i have full level 16 blue hive, having issues to progress in the automatic bucko quest
![Screenshot_20240921-131418_Discord](https://github.com/user-attachments/assets/69848c32-71de-4e10-9763-4daabb4187e3)

(In the first ss you can see that the old amulet with 8 score was already on the screen and bc of that it automatically restated character getting only a score of 1)

### Steps to reproduce

1.Getting bucko quest that requires Ant Challenge 
2.Doing Ant Challenge for the first time in the cycle of the macro and not Keeping correctly the Amulet 
3.Doing by second time the challenge 

### What would you expect to happen?

After doing the above steps it resets everytime you get into Ant Challenge getting super low scores

### Natro Macro version

v1.0.0.2

### What is your Discord username?

dryx24

**Comment by Noobyguy775** [comment]
#502
