### ISSUE TITLE
Macro (for all devices. ex: Macbook pro, iphone, ipad)

### ISSUE THREAD

**Issue by redmystery123** [NatroTeam/NatroMacro#753]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Make a macro for bee swarm the same as windows. But the device is for all devices including a macbook pro, mac, ipad, etc. Please make this. I have a hard time grinding in bee swarm fighting coconut crab. Thanks!

### How will this improve Natro Macro?

All bee swarm players can grind.

**Comment by Noobyguy775** [comment]
1. Macroing on almost any phone is impossible. If not the lack of programs, you have technical constraints. Compare the size of an average phone vs the size of an average computer. This goes for tablets as well.
2. Natro Macro is made in AutoHotKey, which means that the program can only be run on devices running the Windows operating system
- If you want to macro on a mac device, consider using existance macro - https://discord.gg/hhHfmE63Y9
