### ISSUE TITLE
Macro is trying to complete an old bucko bee quest when I turned off bucko bee quests

### ISSUE THREAD

**Issue by Trintoz** [NatroTeam/NatroMacro#754]
### Have you searched the existing bug reports?

Yes

### What happened?

whenever I check on my macro, it sometimes ended up doing the ant challenge for no reason, the only quests that I turned on was Riley bee, which at the time the quest was just abilities, and the macro wasn't even turning in the riley bee quests. I checked my macro, bucko bee's quests and gather interrupt were turned off, but it still had what quest it was trying to complete there, and the ants were still marked as incomplete. I tested the theory further by turning the quests back on, this time I had bucko bee: skirmish, which involves collecting from the blue flower field. I turned completing bucko's quests and gather interrupt off, and sure enough, the macro just kept going to blue flower field for no reason. I completed and handed in the quest, and yet it was still going to blue flower field and gathering for no reason.
![image](https://github.com/user-attachments/assets/67dcfc22-6c55-4dac-ad01-6542190b72dd)

### Steps to reproduce

1.Turn on a repeatable quest npc (try with bucko)
2. allow the macro to read a quest involving either a field or ants, but DON'T allow it to complete the quest
3. turn the npc's quests off
4. complete and turn in the quest yourself
5. turn the macro back on

### What would you expect to happen?

Currently, the macro will probably continue to try complete the quest you already handed up, making it go to places you don't want it to go
What should happen is when I turn the quest off, it should stop trying to complete the quest when it can't even read the right quest to complete

### Natro Macro version

1.0.0.2

### What is your Discord username?

trintoznovaura

**Comment by Trintoz** [comment]
quick update: checked macro status, my theory was right, it's collecting for bucko when I turned it off
![image](https://github.com/user-attachments/assets/144928d9-3a87-4220-af41-b9fbade567b2)

**Comment by misc-et** [comment]
Is this issue still happening? If so, was your macro paused or stopped when you turned the quests on and off?

**Comment by misc-et** [comment]
Closing this report due to inactivity, but please feel free to reopen if you are still having the issue.

**Comment by Trintoz** [comment]
I have tried it again, it is in fact still happening, didn’t realise you sent the first message sorry
