### ISSUE TITLE
macro restarting and then my pc is on lock screen

### ISSUE THREAD

**Issue by amGlitched** [NatroTeam/NatroMacro#755]
### Have you searched the existing bug reports?

Yes

### What happened?

Every day I use the macro when I need to go somewhere, but after 20-40 minutes it pops up an error message on discord saying " Error: Image file cancel.png was not found in:". After that it attempts to reconnect but my pc is on the lock screen while the macro still runs.
![Screenshot 2024-09-22 190342](https://github.com/user-attachments/assets/c7191111-10a2-438a-afe4-97a91842ff34)
![Screenshot 2024-09-22 190352](https://github.com/user-attachments/assets/cdb84082-6a84-42fa-acfa-1d8f2ab3198f)
![Screenshot 2024-09-22 190405](https://github.com/user-attachments/assets/7292e109-3516-4506-99f1-29328300750f)

### Steps to reproduce

1. Start the macro after claiming a hive
2. Leave my household while macro still runs
3. Wait 20-40 minutes until the error message pops up on discord

### What would you expect to happen?

The macro should just run normally until I am back

### Natro Macro version

1.0.0.2

### What is your Discord username?

amglitched

**Comment by Noobyguy775** [comment]
See the "image file not found" in knowledge base on our discord - https://discord.gg/natromacro
