### ISSUE TITLE
@ user on discord when wild windy bee is detected

### ISSUE THREAD

**Issue by Peppermint39** [NatroTeam/NatroMacro#757]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I've looked at other posts and someone had said it could be possible to detect a windy spawn, but the post was closed because the guy who had closed it said it would be difficult to macro a windy bee. Sending a status message from the macro with an @ on discord so the user knows that one has been found in the server.

### How will this improve Natro Macro?

For the Spirit Bear quests that involve windy bee tokens

### What is your Discord username?

sirmintthefirst

**Comment by Noobyguy775** [comment]
Possible, but the macro would have to scan the bottom right of the screen constantly, which takes up resources and probably is not worth it
