### ISSUE TITLE
Wealth clock notifications

### ISSUE THREAD

**Issue by HBRT12** [NatroTeam/NatroMacro#758]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

If you're playing without macroing, you could leave natromacro in the background to time the wealth clock automatically and notify you when it's ready. For example, the macro is open in the background and detects when the game opens to start the timer. After the hour is up, the macro would open a popup saing something along the lines of 'wealth clock is ready' it should also have a popup when it detect that you've collected the wealth clock. You could use image detection to detect when the clock has been collected to restart the timer automatically. These features would be off when the macro is playing the game, but on/activatable if the player is in control

### How will this improve Natro Macro?

This feature would help players since it eliminates the hassle of keeping track of time/setting different timers.

### What is your Discord username?

hbrt12

**Comment by misc-et** [comment]
This is a nice suggestion to track timers during active play, however would be a fairly large task to implement, and may have sufficient use to be warranted (ie by the number of players actively playing for long time periods in a row).
