### ISSUE TITLE
Slots

### ISSUE THREAD

**Issue by who-asked7** [NatroTeam/NatroMacro#759]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Make so that you can save multiple settings, for example you save one where its only for grinding honey, and another one for bug runs, i think this would be cool as you wouldnt have to change the settingss every time.

### How will this improve Natro Macro?

This will save a lot of time and will be really helpful cause you wouldnt have to change the settings over and over again.

### What is your Discord username?

who_asked77

**Comment by Noobyguy775** [comment]
planned, and this is a dupe
