### ISSUE TITLE
only press keys in roblox client

### ISSUE THREAD

**Issue by oeper** [NatroTeam/NatroMacro#760]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

try to make natro macro only press keys in the roblox client

### How will this improve Natro Macro?

people can do other things on their pc while macroing

### What is your Discord username?

oeper

**Comment by Noobyguy775** [comment]
AHK's [`ControlSend`](https://www.autohotkey.com/docs/v2/lib/ControlSend.htm) does not work with Roblox.
