### ISSUE TITLE
Equipping Honey Mask

### ISSUE THREAD

**Issue by MarshyPoooop** [NatroTeam/NatroMacro#762]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I have a suggestion for matti macro. Add an option to toggle on “equip honey mask” to covert at hive quicker. This will also automatically do the diamond mask parkour to re-equip it back on.

### How will this improve Natro Macro?

This will improve Natro Macro because honeymask adds quicker convert so you’ll earn more honey 

### What is your Discord username?

marshmallowbeemasteryt

**Comment by Noobyguy775** [comment]
#85
