### ISSUE TITLE
Natro Macro keeps reseting

### ISSUE THREAD

**Issue by SkimoRB** [NatroTeam/NatroMacro#763]
### Have you searched the existing bug reports?

No

### What happened?

the natro macro won't stop resetting my character

### Steps to reproduce

1.open macro and start
2.resets
3.and resets over and over

### What would you expect to happen?

I expect that the Macro will do its job.

### Natro Macro version

1.0.0.2

**Comment by Noobyguy775** [comment]
https://github.com/NatroTeam/NatroMacro/issues?q=is%3Aissue+is%3Aclosed+Resetting
