### ISSUE TITLE
Movespeed correction not correcting enough

### ISSUE THREAD

**Issue by Bobaget** [NatroTeam/NatroMacro#765]
### Have you searched the existing bug reports?

Yes

### What happened?

I have a lot of bees that spawn haste tokens so I usually have 10x haste and just walk too far left every time and end up walking out of the field

### Steps to reproduce

1. I have a lot of haste tokens so almost always have 10x haste
2. I am in pine tree
3. I have diamond sprinklers and place them in upper left
4. I use e_lol pattern shape m length , 3 width

### What would you expect to happen?

I don't fully know what this is asking but what I expect to happen is that if I have 10x haste it will correct or at least only go slightly to far left but it only takes like 7 times to start walking out of the field
If this question is asking what I expect to happen if you follow all those steps I expect  that you go too far left you go about the distance of 2 tacky planters too far left every time.

### Natro Macro version

1.0.0.2

**Comment by Noobyguy775** [comment]
This is probably a user issue;see the troubleshooting guide in the discord

Drift is not just caused by movement speed, it is also caused by lag, which can amplify the drift as movespeed correction is also affected by lag.
