### ISSUE TITLE
natro macro suggetion 

### ISSUE THREAD

**Issue by beegamefun** [NatroTeam/NatroMacro#767]
### Have you searched the existing suggestions?

No

### What is your suggestion?

in planters have the abilite to scan the planter to check if puffshrooms are available since I and lots of other players like doing puffshrooms. It would be really convient for that option since you will be able to use multiple planters instead of just trunging planters + off.

### How will this improve Natro Macro?

It will benefit natro macro since people will be using the puffshroom feature a lot Ibeleive.

**Comment by Noobyguy775** [comment]
Manual planters, holding mode.

It holds your planters all full grown until you confirm that they are smoking/not smoking
