### ISSUE TITLE
my macro suddenly stopped workin

### ISSUE THREAD

**Issue by Sneakyrar** [NatroTeam/NatroMacro#768]
### Have you searched the existing bug reports?

No

### What happened?

when i started up my macro, it went to the corner of the hives area like the ramp up to the ticket shop and the red cannon and just stood there then 10 seconds later it rests character

### Steps to reproduce

1.turn on macro
2.wait till it gets to that corner
3.then watch

### What would you expect to happen?

i expected it to jump over it and fire the cannon to get to the pine tree forest

### Natro Macro version

1.0.0.2

### What is your Discord username?

sneakyrl

**Comment by misc-et** [comment]
If this is still happening, check your hive slot is specified correctly in the settings tab of the macro - 1 is closest to the cannon, or see our [Discord server](https://discord.com/invite/natromacro) for support.
