### ISSUE TITLE
Weird Movement

### ISSUE THREAD

**Issue by XQZ-JM002** [NatroTeam/NatroMacro#770]
### Have you searched the existing bug reports?

No

### What happened?

My bug report is about the weird movement I've been having during macroing. All of my settings are correct, and my computer display settings are exactly how they should be. Yet I still get these weird movements, and my macro randomly drifts a different way. It could say "Traveling to spider" and id be standing still or be in a completely different field. Ive tried resetting my computer and reinstalling the macro but it doesnt seem to bee helping. So i ask for your help. i would really appreciate it.

### Steps to reproduce

1.  Install the macro.
2. Run macro for a few hours
3. Get random drifts and not be where im supposed to be 

### What would you expect to happen?

after around an hour to 2 or 3 hours into the macro it starts drifting and going to random places around the map when it says i should be somewhere else.

### Natro Macro version

i'm using version 1.0.0.2

### What is your Discord username?

mango_pear_96234

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
