### ISSUE TITLE
Different "profiles"

### ISSUE THREAD

**Issue by Oofer495** [NatroTeam/NatroMacro#771]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

My suggestion is to add different "profiles" to Natro. I've seen suggestions of similar name and description but my idea is different. I think that Natro should implement the ability to change between different settings for different accounts. For example, Profile 1: Your main account, with all of your settings such as hive slot count and movement speed, and a Profile 2: A fuzzy alt or less-good alt where you don't have to change all those settings and can be switched to and started for quick macroing.

### How will this improve Natro Macro?

I believe that this will improve Natro Macro as it's more of an ease-of-access feature that also doubles as an efficient way to allow players to quickly start their Macro and go if they're in a rush and cannot reconfigure at that moment, or for players that struggle with the changing of multiple settings multiple times.

### What is your Discord username?

theonemoth (Moth-Boi)

**Comment by misc-et** [comment]
Thanks for your suggestion. This functionality would also be able to be achieved by the proposed implementation of the other Profiles suggestion, which may be in a future release.
