### ISSUE TITLE
Item Grind

### ISSUE THREAD

**Issue by JasonRP83** [NatroTeam/NatroMacro#773]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

A mode in Macro that **specifically sets the macro to grind out and get that specific item by any _selectable_ means necessary** like crafting, memory matches, quests, etc.

Players could **select multiple items at once** (similar to how Wind Shrine is) and could type out **how much of that specific item is needed for whatever reason / purpose.**

It would also be able to do stickers, **searching around the map for all known locations of hidden stickers**, as well as **farming in the field where the selected sticker is found** more often.

### How will this improve Natro Macro?

It would help _alot_ if the item is hard to get or takes a ton of time to achieve. (_cough cough star treats cough cough_)

For example, I need 50 Blue Extracts to make a diamond mask.
The Macro would **focus on** trying to **grind out and find Royal Jellies, and Blueberries in order to make them via Blender.** It would also **automatically do Riley Bee's quests until the amount of _[insert item]_ is collected by the Macro.**

now it may seem a little selfish but i honestly just want this to make grinding for my diamond mask and petal belt like 100x easier lol

### What is your Discord username?

impostorjason

**Comment by misc-et** [comment]
Hi, thanks for your suggestion. I can see why this might be helpful but we wouldn't typically implement such a feature, because the aim of the macro is not to play the game for you. It would also be somewhat complex to implement, because the options would vary so heavily based on user game stage, # bees, equipment etc.
