### ISSUE TITLE
Guiding setting

### ISSUE THREAD

**Issue by flaviu00** [NatroTeam/NatroMacro#774]
### Have you searched the existing suggestions?

No

### What is your suggestion?

when the macro sees the guiding was activated, make it go in the field where the guid is, and also make a setting to disable some fields where you dont wanna farm the guid

### How will this improve Natro Macro?

it will be good for alts especially, to grind in fields that u dont want to have guid there later

### What is your Discord username?

i_lel

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/337
