### ISSUE TITLE
Nectar condenser macro 

### ISSUE THREAD

**Issue by Gjgod** [NatroTeam/NatroMacro#776]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

This feature will detect when you have over 12 hours of a certain nectar and it will condense it into a vial if you turn the setting on for each nectar. 
This part may be a bit harder to program, but if a nectar sticker spawns, the macro will go to the field and pick it up .

### How will this improve Natro Macro?

It’s no secret that every hive color wants to have full nectars when they boost. Blue hives have to do this while macroing, but red and white hives only need the 24 hours of nectar when they do a 30 minute boost. This will make them reluctant to macro nectars since they can easily be macroing materials using manual planters. However, all the nectar that you DO get from manual planters usually ends up going to waste. So, this will allow hives that macro for mats and not honey to have nectars ready for boosting.

### What is your Discord username?

gjgod

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/282
