### ISSUE TITLE
Vicious Bee Hop Macro

### ISSUE THREAD

**Issue by onlyno0m** [NatroTeam/NatroMacro#778]
### Have you searched the existing suggestions?

no.. _(but now yes.)__

### What is your suggestion?

Although quite simple, I wonder if this is possible but are you/your team able to make some sort of vicious bee hop macro. Although there is already one, it  is either gatekept or old (2 years of age). This would allow a little branch of variety in the macro, and this could possibly be put in the misc section where I found this suggestion page. Although there is already a vicious bee macro for every night, it isn't as a efficient as a vicious bee hop macro. What the feature would do is it would cycle through random public servers, and it would detect whether it is night time or not. Then what it would do is go in the same cycle that the already currently existing vicious bee macro already does which could save a small portion of your time. If it does not find a spike then it will leave the server and keep cycling. Although already stated before I believe that the already existing vicious bee macro just isn't as efficient as a macro that just searches for vicious bees nonstop. I personally am a red hive, and I use stingers a lot for attack, boosts, and etc and being stuck to the old macro in a field around 20 mins (day time) and wait for night which isn't even guranteed a vicious bee is just to slow for me to progress quicker in the game (doing boosts to make more honey.) The amount of stingers I could get in a week of nonstop macroing could take a vic hop macro 1.25 days, and would save my cpu from toasting even though it already is.  That's all I really have to say, but I think a lot of players who can't access those luxuries would be very happy if something like this was added.

### How will this improve Natro Macro?

How will this improve Natro Macro? Well There will be more uses for the macro and add a lot more efficiency which could make the community happy or give you/team a good pat on the back. The macro is used for being afk, and this will improve the usefulness of the misc section, although it is quite useful (especially basic bee hatcher which has a special place in my heart) Adding something that a lot of people need for quick progression such as getting a vicious bee early game in the spam of only like 10 hours because of a vic hop. I personally would use the macro all day everyday if there was a vic hop macro, and it is something that would be held as a crown of glory in the misc section due to it's large amount of useful ness.

If this was read at all I thank you for all the work you/team have already put into this amazing macro, I will respect your decision if this is declined, and thank you for your time, and have a great day.

### What is your Discord username?

onlyno0m

**Comment by misc-et** [comment]
Thanks for your suggestion. This idea has already been suggested, see https://github.com/NatroTeam/NatroMacro/issues/12, so I'll close this one.
