### ISSUE TITLE
why i fold the screen down and when i lose network then it doesn't select the network

### ISSUE THREAD

**Issue by manhtuan301** [NatroTeam/NatroMacro#779]
### Have you searched the existing bug reports?

No

### What happened?

why i fold the screen down and when i lose network then it doesn't select the network

### Steps to reproduce

1.why i fold the screen down and when i lose network then it doesn't select the network
2.
3.

### What would you expect to happen?

why i fold the screen down and when i lose network then it doesn't select the network

### Natro Macro version

1.0.0.2

**Comment by manhtuan301** [comment]
why i fold the screen down and when i lose network then it doesn't select the network

**Comment by manhtuan301** [comment]
why i fold the screen down and when i lose network then it doesn't select the network

**Comment by misc-et** [comment]
Hi, your query is a bit unclear, but the macro can't itself re-connect your PC to the internet if connection is lost. If this is not the issue, please provide more detail and screenshots, or see our [Discord server](https://discord.com/invite/natromacro) for support.
