### ISSUE TITLE
network

### ISSUE THREAD

**Issue by manhtuan301** [NatroTeam/NatroMacro#780]
### Have you searched the existing bug reports?

No

### What happened?

why i fold the screen down and when i lose network i cant select team

### Steps to reproduce

1.im discontech
2.
3.

### What would you expect to happen?

why i fold the screen down and when i lose network i cant select team

### Natro Macro version

1.0.0.2

### What is your Discord username?

noob

**Comment by misc-et** [comment]
Thanks for your report. It's a little unclear what the issue is, but this is likely to be an issue with settings, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
