### ISSUE TITLE
slot 3 pathing after reset

### ISSUE THREAD

**Issue by dndlawless** [NatroTeam/NatroMacro#781]
### Have you searched the existing suggestions?

No

### What is your suggestion?

i’ve been thinking that it should be possible to do this, i was wondering if there’s a way that if you have it set to slot 3 every time you spawn you walk forwards for like 5 seconds until you hit your hive and then walk back like when you fly in from farming at pine to convert balloon or just start normal gtf script if you have no balloon so if you spawn at the join spawn point after resetting it doesn’t reset again and it could save time by only needing one reset no matter it could also increase reliability so you don’t have to rejoin if it resets 9 times it could also be done in other slots by walking to the side a bit while walking forwards

### How will this improve Natro Macro?

it would give more reliability and slightly more time

### What is your Discord username?

onlylawless

**Comment by misc-et** [comment]
Thanks for this suggestion, this could be addressed as part of https://github.com/NatroTeam/NatroMacro/issues/186, so I'm closing this separate issue.
