### ISSUE TITLE
Riley bee rampage quest improvement

### ISSUE THREAD

**Issue by NimbusRod** [NatroTeam/NatroMacro#783]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Currently, when macro completes rampage quests, it just does bugruns to try and get rage tokens, which is very ineffective, because mobs die before rage token bees even have a chance to spawn their token. instead it would be nice if there would be an option to make macro go kill commando chick/stump snail while doing the quest which would massively speed up the completion of a quest.

### How will this improve Natro Macro?

Increase the rate of completing riley bee quests

### What is your Discord username?

golden_sock

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/538
