### ISSUE TITLE
Polar Bear macro not working

### ISSUE THREAD

**Issue by Danik277** [NatroTeam/NatroMacro#784]
### Have you searched the existing bug reports?

No

### What happened?

Polar bear macro doesn't work properly. After it does about 3 quests succesfully, im pretty sure it assigns the wrong quest in the macro. For example, the quest it got stuck on was High Protein Bug Bar, but in natro macro, it identified it as Scorpion Salad. Now for the next 6 hours every 20 minutes it would kill the scorpions and get pollen from rose thinking it was on that quest, and then thinking it was done, go to polar bear and try to submit it. It obviously wouldn't work so natro macro would just do scorpion salad over and over until I turned it off. 
![scorpion salad](https://github.com/user-attachments/assets/7db0a97b-ca1d-4ad8-b324-dd21726a300a)

### Steps to reproduce

1. Turn on polar bear quests
2.
3.

### What would you expect to happen?

I mean i expected it to do the right quest as in high protein bug bar not just cycle scorpion salad endlessly. 

### Natro Macro version

1.0.0.2

### What is your Discord username?

danish13_1

**Comment by misc-et** [comment]
Thanks for your report. This issue has already been reported, see https://github.com/NatroTeam/NatroMacro/issues/669.
