### ISSUE TITLE
Gumdrops 

### ISSUE THREAD

**Issue by TopG23** [NatroTeam/NatroMacro#785]
### Have you searched the existing bug reports?

No

### What happened?

Hi there. I started using Narta Mactro a few weeks ago and have had no issues with it until now. I noticed that when I turn it on and it goes to the field I want it to, it drops a few gumdrops. The only issue with this is that I am trying to save my gumdrops for other things, but every time it goes into the field, I want it to drop a few. I tried looking into the setting to see if there is an option to turn this off but I didn't see any. Could you please let me know if this happens automatically and there is no way to stop it or do I have to do something in the settings that I didn't see. 

### Steps to reproduce

1. When I turn it on, it goes to the field I want. This happens every time even when my backpack is full and when it goes back to the field
2.
3.

### What would you expect to happen?

I would like for it to stop using Gumdrops automatically 

### Natro Macro version

Natro_Macro_v1.0.0.2

### What is your Discord username?

matrix17_1

**Comment by misc-et** [comment]
It sounds like you have your gumdrops in hotbar slot 1. Put your sprinkler there instead, as it's trying to place the sprinkler.
