### ISSUE TITLE
it doesnt click bug

### ISSUE THREAD

**Issue by adarktheme** [NatroTeam/NatroMacro#787]
### Have you searched the existing bug reports?

No

### What happened?

cant join the discord server for some reason it doesnt work but whenever I activate the macro and go to the field it doesnt click it just walks around and i dont gain alot of honey because of this

### Steps to reproduce

1.1
2.2
3.3

### What would you expect to happen?

https://medal.tv/games/roblox/clips/iSVbcGyvK8udlDnLC?invite=cr-MSw5OXgsMjA2NzQyMjExLA

whenever macro starts it just walks around and if I press f4 it doesnt walk around and it just clicks

### Natro Macro version

10.02

### What is your Discord username?

adarktheme

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. If it's still happening, please see our [Discord server](https://discord.com/invite/natromacro) for support.
