### ISSUE TITLE
Vicious bee night decticion

### ISSUE THREAD

**Issue by bananaman122** [NatroTeam/NatroMacro#789]
### Have you searched the existing bug reports?

No

### What happened?

Ok so im gathering in a field and it randomly detects that it night time when its not. Then it goes through the entire vicious bee cycle while its not night. 

### Steps to reproduce

1.start macro with kill vicious bee setting on 
2.let it work in a field for bit
3.It will detect night time when its not night

### What would you expect to happen?

the macro to only detect night time when its night

### Natro Macro version

1.0.0.2

### What is your Discord username?

mrcandies48

**Comment by misc-et** [comment]
This can be an issue with your graphics settings, though it is known that the macro can be sensitive to obstruction (eg, when under a tree) or dusk, which may be addressed in a future update. For now, to check graphics, please see our [Discord server](https://discord.com/invite/natromacro) for support.
