### ISSUE TITLE
Gifted Basic Bee Auto Hatcher

### ISSUE THREAD

**Issue by Garagaragas** [NatroTeam/NatroMacro#790]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I suggest instead of always using royal jelly that there is a feature for the Gifted Basic Bee Auto Hatcher to use event bee jellies instead. For example i have a non gifted cobalt bee and i replaced it with a basic bee, then used its jelly on the slot i want gifted basic bee to be.

### How will this improve Natro Macro?

Just a small improvement

**Comment by dndlawless** [comment]
what’s the point of this how can you afford the basic eggs but not rj

**Comment by misc-et** [comment]
I'm not sure I see the benefit either - is there a game stage where it is likely that royal jellies are costly, but the user is able to afford the basic bee eggs and ready to roll for gifted basic bee?

**Comment by misc-et** [comment]
Thanks for your suggestion. Closing as not planned for now, unless we have additional requests for this functionality.
