### ISSUE TITLE
Item stat sheet

### ISSUE THREAD

**Issue by The-True-Steward** [NatroTeam/NatroMacro#793]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

An item stat sheet would keep track of all items collected during the macro session, like glues, field dice, etc.  If you have your macro set to use the blender or use certain items to boost, it can also show how many items were lost during the session

### How will this improve Natro Macro?

This feature would be useful for keeping track of your material loss/gain, especially when doing bug runs or planters, or memory matches. It would be significantly more convenient than trying to guestimate how much of a certain material you gained. Thank you for your time and consideration.

### What is your Discord username?

Tinytimberland5

**Comment by misc-et** [comment]
Thanks for your suggestion. A similar suggestion has been made, though slightly different, so I'll link your suggestion there and close this one so that they can be considered together. https://github.com/NatroTeam/NatroMacro/issues/627
