### ISSUE TITLE
the macro keeps resetting my roblox character

### ISSUE THREAD

**Issue by NotYoGirl111** [NatroTeam/NatroMacro#796]
### Have you searched the existing bug reports?

Yes

### What happened?

whenever I start the macro it always goes to the reset button and keeps doing it over and over and over again.

### Steps to reproduce

1.i start tbe macro
2.resets my character
3.over and over over again

### What would you expect to happen?

i expected to be able to afk on bee swarm and this is not what i thought i would expect

### Natro Macro version

v1.0.0.1

### What is your Discord username?

svrcp_jojo

**Comment by toneysix** [comment]
Try to use newest version, 1.0.0.2

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Try changing your avatar to a standard size, if it's non-standard right now. Otherwise, please see our [Discord server](https://discord.com/invite/natromacro) for support.
