### ISSUE TITLE
Natro bug.

### ISSUE THREAD

**Issue by Al-xxSk** [NatroTeam/NatroMacro#797]
### Have you searched the existing bug reports?

No

### What happened?

So when i use macro, it always resets me after 1:20 - 1:30 minutes of gathering,and i have my gather time set to 13 minutes
No mather what i try, it always resets me after 1:20 - 1:30 minutes.

 Thanks...ALex
![Snímka obrazovky 2024-10-23 144641](https://github.com/user-attachments/assets/1b457378-b725-4541-b57f-042141d67c5c)

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

So i expect the macro to weork as i want it, if i set it to gather for 13minutes, i want it to gather for 13minutes

### Natro Macro version

10.0.2

### What is your Discord username?

#Felda_SK4133

**Comment by toneysix** [comment]
Full log please

**Comment by misc-et** [comment]
I can see that you are receiving an error message of inactive honey. This suggests that for example, there may be a graphics issue, or your roblox/game language may not be English. Thanks for your report. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
