### ISSUE TITLE
Natro Macro Boost Pepper Patch

### ISSUE THREAD

**Issue by unconcerningtaxevasion** [NatroTeam/NatroMacro#798]
### Have you searched the existing suggestions?

No

### What is your suggestion?

In the Macro boost tab in the "Select boosted gather fields" there is no option for pepper patch.

### How will this improve Natro Macro?

It will improve the macro because it will give us more customization for our Macro

### What is your Discord username?

unconcerning_tax_evasion User ID:718233232927228016

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/609
