### ISSUE TITLE
My character does not move after i reset.

### ISSUE THREAD

**Issue by Arda-bit-png** [NatroTeam/NatroMacro#799]
### Have you searched the existing bug reports?

No

### What happened?

When i start the macro and it resets my character, it just doesn't move. It doesn't reset again either. After like 20 to 30 seconds it resets my character again. It keeps going in a loop like that.

### Steps to reproduce

1.The macro resets me when i start it
2. I respawn and it stays like that for a minute or 20 to 30 seconds.
3. It resets me and now its a loop like that.

### What would you expect to happen?

I expected it to work normally.

### Natro Macro version

1.0.0.2

### What is your Discord username?

dauntless_manifesto

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Try changing your avatar to a standard size, if it's non-standard right now. Otherwise, please see our [Discord server](https://discord.com/invite/natromacro) for support.
