### ISSUE TITLE
Error: 'Script file not found: 1'

### ISSUE THREAD

**Issue by zspz** [NatroTeam/NatroMacro#8]
# ❗❗❗ IF YOU HAVE THIS ERROR ❗❗❗
- Download [Heartbeat.ahk](https://github.com/NatroTeam/NatroMacro/blob/main/submacros/Heartbeat.ahk) and replace your existing one in Natro Macro v0.9.6.
- If you need help doing this, ask in [Discord](https://discord.gg/natromacro).
- This bug is uncommon, and only occurs when the macro crashes for an unknown reason. Therefore, it is not an urgent fix and the fix will be included in v0.9.7.

<br><br>

### Have you searched the existing bug reports?

Yes

### What happened?

![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/28ffd977-cc51-4339-a4b5-09d44fad429a)

### Steps to reproduce

Error is caused by incorrect launch parameters of Natro Macro when restarted by Heartbeat.ahk

### What would you expect to happen?

Macro should have restarted the macro without any error message, and automatically started the script (F1).

### Natro Macro version

v0.9.6

### What is your Discord username?

xspx

**Comment by zspz** [comment]
keeping this open as a known bug in v0.9.6

**Comment by NotMyRealNamezzz3** [comment]
:( im having this trouble

**Comment by ForetellerADA** [comment]
Since 11/21/2023, the bot has stopped working correctly, it comes to the field digs for about 15 seconds, then restart, then it worked correctly
