### ISSUE TITLE
Go to stickers sprout

### ISSUE THREAD

**Issue by Icarus170** [NatroTeam/NatroMacro#800]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

It would be cool if natro could detect the message "there will be sticker sprout soon" in the bottom right corner of the screen when you're playing, and go to the sticker hub to farm until the stickers spawn is over

### How will this improve Natro Macro?

It would allow people to do quest easily and get stickers

### What is your Discord username?

icarus_170

**Comment by misc-et** [comment]
Thanks for your suggestion, this would be cool, however unfortunately it is likely to be somewhat unreliable as the message only appears briefly on the screen, and may be missed by the macro.
