### ISSUE TITLE
poler bear 

### ISSUE THREAD

**Issue by 10opsann** [NatroTeam/NatroMacro#802]
### Have you searched the existing bug reports?

No

### What happened?

i dont know why but my macro for some reason gets stuck in strawberry skewers and i dont know why

### Steps to reproduce

1.it gets the quest 
2.looks at what it is
3.and says its a diffrint one

### What would you expect to happen?

i really dont know pls just fix it it really ruins how many poler baer quest i can do (i do not know if it is a coincidence with strawberry skewers but idk)

### Natro Macro version

v1.0.0.2

### What is your Discord username?

gooberman2 or gooberman

**Comment by 10opsann** [comment]
pls fix :D

**Comment by misc-et** [comment]
Thanks for your report. This issues has already been reported, see https://github.com/NatroTeam/NatroMacro/issues/669.
