### ISSUE TITLE
The Macro doesn't want go to red canon

### ISSUE THREAD

**Issue by roihan123** [NatroTeam/NatroMacro#803]
### Have you searched the existing bug reports?

No

### What happened?

The macro doesn't want to go to red canon.. because the mouse update when it tryna go to canon.. this happend often after the new GUI update, i know because i use bloxstrap and i also got this issue and thankfully i can change it back to old GUI and it works well again but now bloxstrap remove that custom old GUI. now it broken again.
![Screenshot 2024-10-31 134831](https://github.com/user-attachments/assets/e113fc41-e6e8-4312-bae2-51849f47745b)

### Steps to reproduce

1. start the macro like usual
2. from the hive, player should go to red canon but in my case the player stop before go to canon (because of mouse update)
3. because the player cannot go to canon.. now it drifed all over hub but the field

### What would you expect to happen?

let me know if u need more example.. i can show videos or my natro settings

### Natro Macro version

1.0.0.2

### What is your Discord username?

roihan123

**Comment by misc-et** [comment]
Hi, can you provide a screen recording of the issue?

**Comment by misc-et** [comment]
Closing this report due to inactivity, but please feel free to reopen if you are still having the issue.
