### ISSUE TITLE
Planters+ loot option

### ISSUE THREAD

**Issue by BluneWaffle** [NatroTeam/NatroMacro#804]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Instead of the macro planting planters for nectars, you would select a loot option that would plant your planters in fields that give a specific item (that you would choose, kinda like the memory match options). For the special drops with cooldowns there could a a built in cooldown, then the macro would see if it got the item and if it didn't the cooldown would reset. I have found someone else who recommended something similar however they only spoke about monthly/36 day cooldown items whereas I'd like an option that does not only that but also gives non-cooldown loot.

### How will this improve Natro Macro?

This is mainly for the blue hives that are struggling getting swirled waxes for the tide popper, personally I never went blue so I wouldn't know the pain but it took my friend like 4 months just to get all the swirled waxes and neither of us could remember how long was left on the cooldown for the planters.

### What is your Discord username?

BluneWaffle

**Comment by misc-et** [comment]
Thanks for your additional suggestion for non-monthly planters, and for detecting cooldowns.

Re detecting cooldowns: This would be difficult as the loot is only listed briefly on screen, and there would likely be false negatives. 
Re non-monthly cooldowns: Great idea, and I believe this is already planned to be added as part of addressing the [earlier related suggestion.](https://github.com/NatroTeam/NatroMacro/issues/425)

I'll close this suggestion but reference it there.
