### ISSUE TITLE
Vic hop macro

### ISSUE THREAD

**Issue by Cool73an** [NatroTeam/NatroMacro#805]
### Have you searched the existing suggestions?

No

### What is your suggestion?

A Vicious hop macro.
 So basically what this does is that it hop till a server till it finds a server that its night in,then it claim hive and start checking pepper, mountain,clover,spider,rose and cactus. Then it does the same thing again it hop till another serer where its night in.
 Hope you guys can maybe make this possible. :)

### How will this improve Natro Macro?

I think this feutre will be great for both red hives and white hives. This is cause Red and White need a lot of stinger (atleast red) so thats why i think u should add a vic hop to the macro. I think this will be great for every person if they is really in need of stingers. 

### What is your Discord username?

mcniklas

**Comment by misc-et** [comment]
Thanks for your suggestion. This idea has already been suggested, see https://github.com/NatroTeam/NatroMacro/issues/12, so I'll close this one.
