### ISSUE TITLE
constant reseting of the character until the macro gets stoped completely.

### ISSUE THREAD

**Issue by AceKkay** [NatroTeam/NatroMacro#808]
### Have you searched the existing bug reports?

Yes

### What happened?

I have a bug where your character is waitng for 30 seconds. After that it filps the camera like normal and ALWAYS resets the playermodel. It will keep on doing it server hoping until you stop the macro completely.
![image_2024-11-05_180549367](https://github.com/user-attachments/assets/3a8ac5a3-a8c8-4339-b462-f08ca8d91f94)

### Steps to reproduce

1.start macroing
2.macro does the reseting 
3.after the 10 resets its gonna hop onto a new server and repeat the speps 2 and 3 until it gets stopped

### What would you expect to happen?

i would expect the macro to work normally like it did everytime untill now

### Natro Macro version

10.0.2.2

### What is your Discord username?

"Ace_K"   or   "acek08hyper"

**Comment by AceKkay** [comment]
if anything given is not enought to confirm the bug I hope I can help further on

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a big. Try changing your avatar to a standard size, if it's non-standard right now. Otherwise, please see our [Discord server](https://discord.com/invite/natromacro) for support.
