### ISSUE TITLE
Failure to recognize “high protein bug bear” and “Strawberry skewers” polar quests

### ISSUE THREAD

**Issue by Burtosis** [NatroTeam/NatroMacro#809]
### Have you searched the existing bug reports?

Yes

### What happened?

Polar quests “high protein bug bear” and “strawberry skewers” go unrecognized as quests on several PC all set to the specifications given.  

### Steps to reproduce

1. Obtain either quest
2. Start fresh install Natro, enable polar quests, start macro
3. Observe the macro failing to identify the quest 

### What would you expect to happen?

Quest is recognized and updated in the macro so it can be completed automatically. 

### Natro Macro version

1.0.0.2

### What is your Discord username?

Tanystropheus10

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/669
