### ISSUE TITLE
Able to export/import a setting

### ISSUE THREAD

**Issue by NPVNYT** [NatroTeam/NatroMacro#811]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Im using many alts for bss. Able to export/import may help me easier to change settings

### How will this improve Natro Macro?

i think its easier to set up macro for one of my alt

### What is your Discord username?

NPVN

**Comment by misc-et** [comment]
This functionality would be achieved with the implementation of https://github.com/NatroTeam/NatroMacro/issues/77.
