### ISSUE TITLE
keep going left

### ISSUE THREAD

**Issue by mitchellrevill123** [NatroTeam/NatroMacro#812]
### Have you searched the existing bug reports?

No

### What happened?

it keeps going left and not jumping i need to grind honey

### Steps to reproduce

1.
2.
3.d
d

### What would you expect to happen?

![image](https://github.com/user-attachments/assets/a038d2ad-794b-48fd-af17-11439ea89991)

### Natro Macro version

v1.0.0.2

### What is your Discord username?

mitchlikesyou

**Comment by misc-et** [comment]
This may be either related to user settings, or a known issue with resetting, due to a new Roblox update. For support or a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
