### ISSUE TITLE
Natro not doing stump snail

### ISSUE THREAD

**Issue by Icarus170** [NatroTeam/NatroMacro#813]
### Have you searched the existing bug reports?

Yes

### What happened?

I have the settings to kill the stump snail but natro is just not doing it, but it does all the rest normally tho
![image](https://github.com/user-attachments/assets/32c0ef6e-cfe9-4d53-9052-bbeb21681cec)

### Steps to reproduce

1.Have the settings to kill stump snail
2.Launch natro 
3.Watch it not doing it but you dont know why

### What would you expect to happen?

Kill the stump snail

### Natro Macro version

the lastest

### What is your Discord username?

icarus_170

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be a local issue, rather than a bug. Please see our [Discord server](https://discord.com/invite/natromacro) for support.
