### ISSUE TITLE
My macro broke for some reason

### ISSUE THREAD

**Issue by SketchyRay** [NatroTeam/NatroMacro#814]
### Have you searched the existing bug reports?

No

### What happened?

i dont know what happened or how to fix it but whenever i start my macro it turns the camera angle like normal yet it just resets after that for no reason, i've tried re-installing it but it didnt work and i dont know what to do.

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i expect it to work like normal, and not reset at hive constantly

### Natro Macro version

v1.0.0.2

**Comment by Boss60092** [comment]
Mine keeps reseting over 10 times. This is 100% a bug and its annoying for users that have that bug.
![Skärmbild 2024-11-12 002507](https://github.com/user-attachments/assets/93df8c6b-6806-4a33-bc07-d87cba2581c3)

**Comment by Sp1t87** [comment]
![2024-11-12_02-30-44](https://github.com/user-attachments/assets/09761fb3-b362-4ad7-aa03-5e181f1f3edc)
=(

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).

https://github.com/NatroTeam/NatroMacro/issues/816
