### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Boss60092** [NatroTeam/NatroMacro#815]
### Have you searched the existing bug reports?

Yes

### What happened?

Well first my macro won't find what hive to pick when it joins. Second i have to claim my hive for it to start BUT when i try to start it something happens every time, and idk if y'all have experience it but it keeps reseting me like over 10 times.(i have a picture).

Hope Natro Macro can fix this
=Boss60092

### Steps to reproduce

1.i already wrote it down. 
2.
3.

### What would you expect to happen?

1.Remove the spam restets
2.Fix small bugs
3.It sometimes glicthes on pepper field.

### Natro Macro version

im using the newest one yet.

### What is your Discord username?

lclcfan5413

**Comment by workmonitored** [comment]
Same here... Tried with older version/new version. Tried with different settings. Tried resetting settings. Tried downloading a new copy and using it. It keeps killing me... over and over (reset so to speak)

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).

https://github.com/NatroTeam/NatroMacro/issues/816
