### ISSUE TITLE
resetting

### ISSUE THREAD

**Issue by MrDynamic5596** [NatroTeam/NatroMacro#816]
### Have you searched the existing bug reports?

Yes

### What happened?

No matter what i put my settings as, my macro just does one gather cycle, and then when it resetns my character it resets it 9 times closes roblox then rejoins, and it was not doing this earlier today

### Steps to reproduce

1. idrc
2.
3.

### What would you expect to happen?

i cant fix it, please help

### Natro Macro version

im not sure

### What is your Discord username?

Mr.Dynamic5596

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).

**Comment by Irocody** [comment]
Hey, I'm having the same problem, i went to the discord sever but i cant see anything, and its not like its loading because i clicked on one of my other GC and it worked completely fine.

**Comment by Noobyguy775** [comment]
should be fixed in the lastest update!
