### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by DJ1324** [NatroTeam/NatroMacro#817]
### Have you searched the existing bug reports?

No

### What happened?

eveytime i start it it fails to see where it must go and keeps reseting

### Steps to reproduce

1. i try to move it to see if it will respond 
2. closing it and starting it again
3. reset the settings

### What would you expect to happen?

for it to work and to do what it needs to do

### Natro Macro version

v1.0.0.2

### What is your Discord username?

DJ

**Comment by PlumpsyTheBest** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/816
