### ISSUE TITLE
Macro keeps resetting at hive

### ISSUE THREAD

**Issue by karkeris00** [NatroTeam/NatroMacro#818]
### Have you searched the existing bug reports?

Yes

### What happened?

Macro keeps resetting at hive because for some reasons it thinks that that account spawns on spawn platform and not the hive also after 9 times it rejoins the game and cycle continues.

### Steps to reproduce

1. Restarted PC
2. Redownloaded macro
3. Redownloaded Roblox

### What would you expect to happen?

I expected after trying all those steps that macro will stop resetting at hive and do what it suppose to do.

### Natro Macro version

v1.0.0.2

### What is your Discord username?

karkeris06

**Comment by lugosieben** [comment]
Hi! Please check this fix in the discord: https://discord.com/channels/1012610056921038868/1305651115374805002
The github will be updated soon aswell.

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/816
