### ISSUE TITLE
resetting

### ISSUE THREAD

**Issue by danol-min** [NatroTeam/NatroMacro#819]
### Have you searched the existing bug reports?

Yes

### What happened?

i was using the macro pretty normal everyday until recently when i started a new day and about turned on bss and macro, it just keep resetting my characters for nearly 10 times then left the games. I try enter a new server when it was still operated, and the macro only claimed the hive, did one thing that i set and then continued on resetting

### Steps to reproduce

1. reset the computer
2.click the resetting all setting section
3.check to see some window setting

### What would you expect to happen?

i expected the macro to be atleast working properly like everytime i used it

### Natro Macro version

v1.0.0.2

### What is your Discord username?

DanolVN

**Comment by Dkrrus1** [comment]
Same problem. Was testing it on 2 laptops and 1 desktop PC. After reconnect all works fine until any reset or death.

**Comment by Azur-e** [comment]
The Bug is because of a very recent update which slightly changes Roblox's color which screws up Natro, join discord server for a fix.

**Comment by Azur-e** [comment]
Discord server: https://discord.com/channels/1012610056921038868/1305651115374805002

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/816
