### ISSUE TITLE
Macros cant work

### ISSUE THREAD

**Issue by Catmolnea1** [NatroTeam/NatroMacro#820]
### Have you searched the existing bug reports?

No

### What happened?

when you turn on the macro after the player dies, he checks where the player is standing, as if the character is standing near the hive but still endlessly resets

### Steps to reproduce

1.Download bloxstrap launcher
2.In the settings bloxstrap, switch the lighting to Future 3 and then back to setting the selected game
3. after that, open the usual roblox launcher (not bloxstrap) and the macro will stop working

### What would you expect to happen?

I would like to know what I can do to fix this problem.

### Natro Macro version

1.0.0.2

### What is your Discord username?

catmol

**Comment by Azur-e** [comment]
The Bug is because of a very recent update which slightly changes Roblox's color which screws up Natro, join discord server for a fix.

**Comment by Azur-e** [comment]
Discord server: https://discord.com/channels/1012610056921038868/1305651115374805002

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/816
