### ISSUE TITLE
re-entry

### ISSUE THREAD

**Issue by Rail2013** [NatroTeam/NatroMacro#821]
### Have you searched the existing bug reports?

Yes

### What happened?

will you help with the error (I immediately say I have an error that when I run the macro, it goes over and that's it and even the mouse doesn't move) it goes over and stands still indefinitely

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

will you help with the error (I immediately say I have an error that when I run the macro, it goes over and that's it and even the mouse doesn't move) it goes over and stands still indefinitely

### Natro Macro version

1.0.0.2

### What is your Discord username?

tortik_yt

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
