### ISSUE TITLE
No ballon alert when killing the stump snail

### ISSUE THREAD

**Issue by Icarus170** [NatroTeam/NatroMacro#822]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

The macro should not send message in the discord webhook to say that no ballons were converted when it's killing the stump snail

### How will this improve Natro Macro?

Less message in the discord webhook so it will be easier to find useful informations

### What is your Discord username?

icarus_170

**Comment by misc-et** [comment]
This is a setting that you can disable, in the status tab of Natro (change Discord settings -> emergency balloon).

**Comment by Icarus170** [comment]
Yes but i would like to have it on because its useful but i think it would
be better for everyone if this would not be activated when Killing long
bosses
