### ISSUE TITLE
Character resets because of zoom distance

### ISSUE THREAD

**Issue by ParallelBlackk** [NatroTeam/NatroMacro#823]
### Have you searched the existing bug reports?

Yes

### What happened?

So every time I start the macro my character keeps on resetting, I've checked my graphics, my avatar is on normal, my sensibility is on 1, windows display at 100%, the reason I think it is, is because when my character resets my camara zooms into the character, but if I manually scroll the zoom away and furthur from my character my macro works, but its annoying to do it manually. Please help.

### Steps to reproduce

1. Start macro
2. Character resets once
3. Resets again and again until I MANUALLY scroll away the zoom

### What would you expect to happen?

So I can let it run over and over once I start it manually, but when i want to do planters then my charcter resets and i cannot manually change the zoom distance

### Natro Macro version

1.0.0.2

### What is your Discord username?

parallelblackk

**Comment by why134** [comment]
same issue since today morning

**Comment by why134** [comment]
i set a O button macro to zoom out.it‘s work initially.now it’s worse,The viewing angle becomes horizontal after zooming.still can’t detect and resetting.

**Comment by kilo19871** [comment]
also having this issue starting today. It was working fine for the past 2 months with no problems at all.

**Comment by NEYMARJr912** [comment]
Same is happening with me

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).

**Comment by why134** [comment]
seem like it’s collect and kill problem,I cancel all of them everything go back to normal.

**Comment by ParallelBlackk** [comment]
> seem like it’s collect and kill problem,I cancel all of them everything go back to normal.

Yea but I don't have anything in my collect/kill, everything is off but it still keeps on resetting.

But after my character resets 10 times, then my roblox restarts and the problems seems to go away.

**Comment by ParallelBlackk** [comment]
> > seem like it’s collect and kill problem,I cancel all of them everything go back to normal.
> 
> Yea but I don't have anything in my collect/kill, everything is off but it still keeps on resetting.
> 
> But after my character resets 10 times, then my roblox restarts and the problems seems to go away.

Nevermind, I have solved the issue after checking the discord link and downloading the new macro, it was a lighting problem that made the macro keep on resetting. Thanos a lot!!

**Comment by misc-et** [comment]
You're welcome! Glad it's working.
