### ISSUE TITLE
macro not booting up

### ISSUE THREAD

**Issue by Motherbear51** [NatroTeam/NatroMacro#827]
### Have you searched the existing bug reports?

No

### What happened?

keeps rebooting at hive and then dies again

### Steps to reproduce

1.
2.
3.
dont know

### What would you expect to happen?

want it to work

### Natro Macro version

1.0.0.2

### What is your Discord username?

Motherbear51

**Comment by Cardigan70** [comment]
I'm experiencing the same problem.

**Comment by MoreAmmonia** [comment]
this bug worries me about a week,i have 4 accounts but half of them is normal

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
