### ISSUE TITLE
it keeps reseting

### ISSUE THREAD

**Issue by noobers-4u** [NatroTeam/NatroMacro#831]
### Have you searched the existing bug reports?

No

### What happened?

it will reset and stay at my hive then it will do the zoom and camera then reset and repeats that process without stopping

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

i to do the zoom sequence go to wealth clock twice then go to pine and corner snake so i can get honey

### Natro Macro version

v1.0.0.2

### What is your Discord username?

the_red_chill.

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
