### ISSUE TITLE
Loadouts

### ISSUE THREAD

**Issue by springtrap99211** [NatroTeam/NatroMacro#832]
### Have you searched the existing suggestions?

No

### What is your suggestion?

A tab or a setting where you can save different loadouts

### How will this improve Natro Macro?

When you switch the settings around alot it can be annoying to find all the right setting, if we have loadouts we can save the setting for a bug run and a macro for honey grinding, also if you have different accounts you would need different settings if they have a different movespeed or dont have the same amount of bees in the hive

**Comment by misc-et** [comment]
Thanks for your suggestion. This would be achieved by the implementation of https://github.com/NatroTeam/NatroMacro/issues/77, so just closing this one.
