### ISSUE TITLE
Natro macaro bug

### ISSUE THREAD

**Issue by drixylxd** [NatroTeam/NatroMacro#833]
### Have you searched the existing bug reports?

No

### What happened?

When I started the macro, it reset the character 2 times as normal. Afterwards the camera turned around, as it does when you spawn at the spawnpoint (not your hive) then it reset again. and so on

### Steps to reproduce

1. Just start the macro
2.
3.

### What would you expect to happen?

Go collect in the fields I chose instead of reseting

### Natro Macro version

1.0.0.2

### What is your Discord username?

drixyl

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
