### ISSUE TITLE
The macro keeps resetting me at hive

### ISSUE THREAD

**Issue by DarkeryShadow** [NatroTeam/NatroMacro#839]
### Have you searched the existing bug reports?

No

### What happened?

the macro keeps resetting me at the hive and it wont start
![Uploading Screenshot 2024-11-21 211511.png…]()

### Steps to reproduce

1.provide me steps on how do i solve this issue
2.reset my macro
3.

### What would you expect to happen?

my macro is fixed and i dont have to grind on my own

### Natro Macro version

1.0.0.2

### What is your Discord username?

@darkenedshadow

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
