### ISSUE TITLE
hello themacro only kills me in a loop without farming polen help me please

### ISSUE THREAD

**Issue by tom45229** [NatroTeam/NatroMacro#840]
### Have you searched the existing bug reports?

No

### What happened?

hello the macro doesn't m!arch she only kills me in a loop without giving me a polen and therefore doesn't loot the tickets and the cole and all her things the thank you for doing the nessaiser please

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

I want the macro to work

### Natro Macro version

v1.0.0.2

### What is your Discord username?

I'm not discord

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
