### ISSUE TITLE
it resets me

### ISSUE THREAD

**Issue by sigma-boysketch** [NatroTeam/NatroMacro#841]
### Have you searched the existing bug reports?

Yes

### What happened?

i keep reseting and it wont do the macro i put all of my beeswarm data but it still doesnt work

### Steps to reproduce

1.i turn it on
2.i get reseted and doesnt work
3.repeat

### What would you expect to happen?

i want it to work beacuse i hate to farm myself (im lazy)

### Natro Macro version

Natro Macro v1.0.0.2

### What is your Discord username?

handsomecat123

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
