### ISSUE TITLE
Gather W /shiftlock

### ISSUE THREAD

**Issue by SuprXa** [NatroTeam/NatroMacro#845]
### Have you searched the existing bug reports?

No

### What happened?

During Gathering shiftlock wownt enable itself for some reason despite gather w shift lock being turned on.

### Steps to reproduce

1.Goes into field
2.Uses boosts
3.Starts gathering without shiftlock

### What would you expect to happen?

The macro should start gather while shiftlock is active

### Natro Macro version

v.1.0.0.2

### What is your Discord username?

sparklingrubiconbottle

**Comment by misc-et** [comment]
Shiftlock can only work with the browser version of Roblox (not the Microsoft store version), so make sure you're using that. For further help please see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
