### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by Snd-V** [NatroTeam/NatroMacro#846]
### Have you searched the existing bug reports?

No

### What happened?

I started the macro normally and noticed something unusual when restarting the macro. It simply wouldn't stop restarting, even though it 
the character spawing in the hive and the camera position is very straight

### Steps to reproduce

1.I started the macro until it restarted
2.After that, the macro did not stop restarting, it restarted 19 times
3.There was no way I couldn't remove it since even re-installing it several times the error persists.

### What would you expect to happen?

I thought the macro would work normally the first time I didn't think it was such a big error

### Natro Macro version

10.0.2

### What is your Discord username?

sndzinhokkk.

**Comment by batsnefs** [comment]
[natromacro.zip](https://github.com/user-attachments/files/17991181/natromacro.zip)
try this version of macro it happens due to a lighting update from roblox
if u dont wanna trust look at macro official server for file
