### ISSUE TITLE
Natro remembers where planters are from prev. sess.

### ISSUE THREAD

**Issue by shushi93** [NatroTeam/NatroMacro#847]
### Have you searched the existing bug reports?

Yes

### What happened?

This is more suggestion than a bug, but i still think i shld classify it as a bug
If i set the manual/ automatic (havent used automatic much but i think ive seen the bug there too) when the macro places a planter, lets say red clay at pepper, then i stop the macro (cos i cant macro overnight) and i start it again the next day, it goes to bamboo to search, and it just keeps doing this many times. Is it possible for the macro to remember where the planters are? or search every field after two or three times planter is not in field and inven.?

### Steps to reproduce

let macro place a planter in a field
let it harvest from field and go to cycle two
stop macro
start macro
macro will go to field in cycle one even if planter is in field in cycle two

### What would you expect to happen?

I'd expect it to remember where it last placed the planter

### Natro Macro version

1.0.0.2

### What is your Discord username?

shashi93

**Comment by shushi93** [comment]
> I haven't replicated this issue, can you try clearing your planter timers, collecting planters in field, and restarting the macro?

havent cleared timers just yet, but i see the issue less these days bcos i only have one cycle, i will revert back to multiple cycles, but try what you mentioned, and see if the issue still persists

**Comment by misc-et** [comment]
Just closing this post due to inactivity, but please feel free to reopen if the issue persists and you need assistance.

**Comment by shushi93** [comment]
I don't seem to have the issue now
