### ISSUE TITLE
Why my planter does not work?

### ISSUE THREAD

**Issue by Megapopper** [NatroTeam/NatroMacro#849]
### Have you searched the existing bug reports?

No

### What happened?

My Natro Macro cannot place planters down. Every time the macro starts, the first thing it does is place the planter. Then, once it finds the planter, it places it down. When it does this, it oddly doesn't press the place button and just sits in the middle of the two buttons that will place it and not place it. Then, it would go back and forth between the egg u.i. and the left side of the gamepass u.i. I checked the debug and it said that I don't have the planter. I researched this problem and it seems nothing like this ever happened to anyone else.
![Screenshot 2024-12-02 205247](https://github.com/user-attachments/assets/5135344f-4611-4ddf-8ec5-b30c989596e1)

### Steps to reproduce

1.Natro Macro will not place planters. 
2. The Natro Macro does not see the planter.
3. The debug says that the planter it tries to place down is not there.

### What would you expect to happen?

The Natro Macro should have seen where the planters are and placed it down without much trouble since everything else works in the macro the way it is supposed to.

### Natro Macro version

1.0.0.2

### What is your Discord username?

(Amu) amuzukiq

**Comment by misc-et** [comment]
This sounds like it may be an issue with mouse or other PC settings. Please see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002) for information and support.
