### ISSUE TITLE
natro macro keeps making me reset

### ISSUE THREAD

**Issue by hexlele** [NatroTeam/NatroMacro#851]
### Have you searched the existing bug reports?

Yes

### What happened?

i start up my natro macro and i press f1 it just does 1 thing resets every like 1 minute pls help me with this i dont know how to fix it i need help

### Steps to reproduce

1.broken
2.always does 360s
3.kept resseting

### What would you expect to happen?

i expected like for it to macro me 4m honey a hour

### Natro Macro version

1.0.0.2

### What is your Discord username?

minihexula_82856

**Comment by misc-et** [comment]
There is currently a known issue with resetting, due to a new Roblox update. For a patch, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
