### ISSUE TITLE
half screen support

### ISSUE THREAD

**Issue by nuggetbott** [NatroTeam/NatroMacro#852]
### Have you searched the existing suggestions?

No

### What is your suggestion?

allow natro macro to work half screen so you can wathc yt orr other sutff 

### How will this improve Natro Macro?

people can still partly usse it to do somthing inside of jsut bee swarm

### What is your Discord username?

nugget7937

**Comment by misc-et** [comment]
This can be achieved using remote desktop protocol. For information and support, see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002).
