### ISSUE TITLE
Suggestion: Automatic Gear Farming in Natro Macro

### ISSUE THREAD

**Issue by Zach56647466458645486548645684** [NatroTeam/NatroMacro#853]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Hi there! I have a suggestion that I believe would improve the game and make progression smoother, especially for players working towards high-level gear like the Gummy Mask or Coconut Canister.

The idea is to add a feature in the Natro Macro where players can select specific gear they want to farm, and the macro would automatically farm the necessary materials and buy the gear once everything is collected.

Here’s how it could work:

	1.	Gear Selection: Players could check a box in the Natro Macro to select which gear they want to farm for, like the Gummy Mask, Coconut Canister, or others.
	2.	Automatic Farming: The macro would farm the required materials for the selected gear automatically, using the best fields and planters for those materials (e.g., glue, enzymes, coconuts, pineapples, etc.).
	3.	Gear Purchase: Once the necessary materials are gathered and the player has enough honey, the macro would automatically purchase the gear.

Why this would be a great feature:

	•	Saves Time: It would help players focus on other aspects of the game while the macro handles the tedious task of gathering materials for gear upgrades.
	•	Efficiency: Automating material collection for specific gear would make the process faster and more streamlined, allowing for quicker progression.
	•	Less Hassle: It would reduce the need for constant field and planter switching, making the game more relaxing for those who want to focus on other tasks.

Overall, it would be an amazing addition to the game that would save time and make progression smoother for everyone working towards those hard-to-get items.

Thanks for considering this suggestion!

### How will this improve Natro Macro?

How will this improve Natro Macro?

This feature would significantly enhance the user experience by streamlining the process of collecting materials for high-level gear. Currently, farming for specific gear materials can be time-consuming and repetitive, requiring constant switching between fields and planters. By adding an option to automatically farm the necessary materials for selected gear, players would save time and effort, allowing them to focus more on enjoying other aspects of the game.

This feature would also make progression smoother, helping players who are working towards difficult-to-obtain gear like the Gummy Mask or Coconut Canister. By automating the process, players can gather materials more efficiently and purchase their desired gear faster, reducing the overall grind and improving the overall gameplay experience.

### What is your Discord username?

Zachman5352424

**Comment by misc-et** [comment]
Hi, thanks for putting this suggestion forward along with a clear explanation of how it would help. I can see how it would be useful, but we wouldn't consider including this particular feature, because the aim of the macro is very much to help with some of the more tedious repeat tasks rather than play the game for you.
