### ISSUE TITLE
Add Spirit bear and science bears quest to the quest tab

### ISSUE THREAD

**Issue by Zach56647466458645486548645684** [NatroTeam/NatroMacro#854]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Hi there! I’d like to suggest adding Spirit Bear and Science Bear quests to the Quest tab in Natro Macro.

Why this would be helpful:

	1.	Improves Quest Management: Including Spirit Bear and Science Bear quests in the Quest tab would allow players to automate these tasks, which often require specific fields or actions, making quest completion smoother and faster.
	2.	Streamlines Gameplay: Managing these quests manually can be time-consuming, especially for players focusing on progression. Automating them would let players focus on other aspects of the game while still progressing through important questlines.
	3.	Supports Mid-Game Progression: These quests are key for advancing in the game, and automating them would greatly benefit players in mid-game stages working towards high-tier rewards.

This addition would make the Quest tab more comprehensive and helpful for players at all levels.

Thanks for considering this suggestion!

### How will this improve Natro Macro?

How will this improve Natro Macro?

Adding Spirit Bear and Science Bear quests to the Quest tab will make Natro Macro even more efficient and versatile for players. These quests often require farming in specific fields or performing tasks like collecting tokens, and automating these would:
	1.	Save Time: Players won’t need to micromanage these quests, allowing them to focus on other gameplay activities.
	2.	Enhance Automation: Including these quests would make the macro even more comprehensive, covering a wider range of tasks.
	3.	Streamline Mid-Game Progression: Spirit Bear and Science Bear quests are crucial for advancing in the game, and automating them would help players progress faster without unnecessary manual effort.

This change would improve the macro’s functionality and benefit players who are aiming to complete these key questlines efficiently.

### What is your Discord username?

zachman5352424

**Comment by misc-et** [comment]
Hi, thanks also for putting this suggestion forward - again, I see how it would be useful, but the decision has always been not to add the main questlines for the same reason (that it's not intended to play the game for you, just to supplement active play by automating some repeated tasks).
