### ISSUE TITLE
Path for when you spawn on the spawn point

### ISSUE THREAD

**Issue by tatarevic1** [NatroTeam/NatroMacro#855]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Instead of resetting the character multiple times until the player spawns at the hive, the macro will navigate from the spawn point, detect the hive, and then follow the normal path.

### How will this improve Natro Macro?

Less time will be wasted, resetting character to spawn at hive can take a long time.

### What is your Discord username?

_rinat

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/186
