### ISSUE TITLE
Natro not keeping ant amulet in RDP session

### ISSUE THREAD

**Issue by shushi93** [NatroTeam/NatroMacro#856]
### Have you searched the existing bug reports?

Yes

### What happened?

Whenever my natro does an ant challenge for bucko quest, it logs as keeping ant amulet, but its always still there, it overshoots the keep button

### Steps to reproduce

1. RDP.exe /v:127.0.0.2 /i:shashi93 /title:"Macroing..." /nodrives /nosound /nowallpaper /o:"keyboardhook:i:1" /w:1366 /h:768
2. turned it on and it did ant challenge
3. Mouse slighlty overshoots keep button

### What would you expect to happen?

It should keep my current amulet, but the GUI is still on the screen

### Natro Macro version

1.0.0.2

### What is your Discord username?

shashi93

**Comment by misc-et** [comment]
thanks for flagging, this is a known issue and will be fixed in a future release.

https://github.com/NatroTeam/NatroMacro/issues/752

**Comment by shushi93** [comment]
@misc-et ok thanks for letting me know
