### ISSUE TITLE
Memory match taking very long to complete and sometimes it does not complete MM

### ISSUE THREAD

**Issue by shushi93** [NatroTeam/NatroMacro#857]
### Have you searched the existing bug reports?

No

### What happened?

(This is very close to #395, the difference is im not sure what causes it)
Whenever i do MM, for some reason it takes 2-5 minutes to complete it, which is a huge waste of time
also sometimes, the macro does nto complete MM, which causes a lot of timwaste as the macro just idles

### Steps to reproduce

1. choose MM
2. (im in rdp sess. btw) let it do MM
(one occurrence)
![image](https://github.com/user-attachments/assets/e25f2328-a6ee-4e0c-b388-f6989a323ae5)
also as you can see it says collected even tho it has one chance left
this also causes some issues, where the macro just idles

### What would you expect to happen?

I would expect it to complete it relativley quickly as prev. it took like 20s to finish (based on what i rmbr)

### Natro Macro version

1.0.0.2

### What is your Discord username?

shashi93

**Comment by misc-et** [comment]
it looks like your natro gui is blocking the screen. try setting the natro gui not to show while the macro is running (settings tab).

**Comment by shushi93** [comment]
> try setting the natro gui not to show while the macro is running (settings tab).

this can be done? ok i'll see
