### ISSUE TITLE
glitter for auto planters 

### ISSUE THREAD

**Issue by hiyjinx** [NatroTeam/NatroMacro#859]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

I think you should be able to use glitter for auto planters, I thought that the tab in auto planters under the planters was for glitters but that’s for the blender. 

### How will this improve Natro Macro?

This will improve getting nectars quickly 

### What is your Discord username?

1miss_rustbell

**Comment by Noobyguy775** [comment]
see #39
