### ISSUE TITLE
Idle mode and custom pattern shop intergrated, visualization pattern, where macro start gathering, sprinkler's place on gather field

### ISSUE THREAD

**Issue by n4tsukii** [NatroTeam/NatroMacro#86]
### Have you searched the existing suggestions?

No

### What is your suggestion?

1. Timers Tab, can annouce when any mob respawn, or when wheal clock is ready.
2. We can choose custom pattern from a list that place at gather tab, just click pattern and scroll down, choose custom pattern....
3. We can see what pattern do, and how it work, and easy to choose the suitable for us

### How will this improve Natro Macro?

make natro macro easier to use

### What is your Discord username?

comrangduabo_

**Comment by n4tsukii** [comment]
nope it's not webhook, sometime i just wanna play bss on my own, don wanna use natro, and it's great if natro can help me with annoucing me whenever a mob repsawn or when weath clock is ready to collect

**Comment by n4tsukii** [comment]
yeh it is

**Comment by n4tsukii** [comment]
okay

**Comment by ugwuchijioke** [comment]
> So like a timers tab

https://faq.whatsapp.com/1191526044909364/?ref=share

**Comment by ugwuchijioke** [comment]
> ### Have you searched the existing suggestions?
> 
> No
> 
> ### What is your suggestion?
> 
> 1. Timers Tab, can annouce when any mob respawn, or when wheal clock is ready.
> 2. We can choose custom pattern from a list that place at gather tab, just click pattern and scroll down, choose custom pattern....
> 3. We can see what pattern do, and how it work, and easy to choose the suitable for us
> 
> ### How will this improve Natro Macro?
> 
> make natro macro easier to use
> 
> ### What is your Discord username?
> 
> comrangduabo_

v.0.6.0
