### ISSUE TITLE
Honeystorm Path does not get to the honeystorm starter

### ISSUE THREAD

**Issue by ouvriermacane** [NatroTeam/NatroMacro#860]
### Have you searched the existing bug reports?

Yes

### What happened?

when enabling the honeystorm in colect (mostly for honey bees Beesmas quest) the macro does not manage to get on the pad to start it. (I have it running on 4 macros all in rdp and none of them get to the pad they are all too far towards the clock)

### Steps to reproduce

1. Enable honeystorm
2. Wait for the macro to go start the storm
3. Watch as it travels too much towards the ticket clock

### What would you expect to happen?

For the macro to go less towards the clock and to start the storm

### Natro Macro version

v1.0.0.2

### What is your Discord username?

ouvriermacane

**Comment by Noobyguy775** [comment]
this will be fixed in the next version coming soon

**Comment by Noobyguy775** [comment]
fixed in latest update!
