### ISSUE TITLE
Cant join discord to see fix for spam reset and also spam reset

### ISSUE THREAD

**Issue by BLOBTheThing** [NatroTeam/NatroMacro#861]
### Have you searched the existing bug reports?

yes kinda

### What happened?

Discord invite redirect and then says unable to accept invite
Mainly want to join to fix issue of spam reset

### Steps to reproduce

1.Trying all discord invite links from github
2.Idk
3.For reset spam i just have the newest version and it is beesmas event,
4.default camera
5.BSS told my speed is 25 so i put that and also 13 bees
6.unsure if putting quests and other bosses to be killed causes issue if they are locked so i dint put them
7.Camera turns 180 twice when respawn at hive and then resets if i select a hive
8.if i select hive it also sometimes goes in about a 3/4 circle and then resets
9.if no hive is selected manually then spam reset occurs and sometimes goes in 3/4 of circle and also does 180 checks before resseting

### What would you expect to happen?

Im not sure but maybe the camera settings or something else since the status only says reseting character although my travel option is walk. Status said once that it failed at claiming hive and that it was travelling to a spot but it just spam reset

### Natro Macro version

1.0.0.2

### What is your Discord username?

BLOBTheThing#2323

**Comment by BLOBTheThing** [comment]
I fiexed it by dissabling the cannon travel and starting with hive so now it is working except for the fact that no cannon travel. The macro keeps moving towards red cannon even after i inputed that i have 16 bees and not 25. after chagning the travel type , it works fine

**Comment by misc-et** [comment]
Thanks for the update. We have also added the reset bug fix to the latest version 1.0.0.3, so you should now be able to use it.
