### ISSUE TITLE
A very usefull idea

### ISSUE THREAD

**Issue by TaxiEllat** [NatroTeam/NatroMacro#864]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I think that you should add a setting that can buy a certain amount of treats and feed to the selected bees so for exampel is "Feed 1 mil treats to vicious bee" in order to do this you have to create a setting "Choose Bee" and "Amount of treats" and "which lvl for the bee (bees) (for the bees one it should also have a option to feed every bee. 

### How will this improve Natro Macro?

It would make lvling upp bees so mutch faster.

### What is your Discord username?

TaxiEllat

**Comment by Noobyguy775** [comment]
this is already a function inside of bee swarm, you can type in the amount you want
