### ISSUE TITLE
Unable to detect in-game GUI offset

### ISSUE THREAD

**Issue by jvzy9** [NatroTeam/NatroMacro#869]
### Have you searched the existing bug reports?

Yes

### What happened?

every time I start the macro I see Unable to detect in-game GUI offset I have done every fix including checking my in game language, being in fullscreen, being at 100% scale,  switching to 1920x1080p (i have a 1440p monitor), i have even uninstalled auto hot key and the macro and tried multiple versions of the macro and still no success]. my best guess is it's a monitor setting I have a MSI - MPG271QRXQDOLED 27" if that helps I would appreciate if anyone has any insight or if maybe there's something I missed, thank you.

### Steps to reproduce

1.launch marco and beeswarm
2.start macro
3Unable to detect in-game GUI offset seconds after I start it 

### What would you expect to happen?

Unable to detect in-game GUI offset will show up at least on my end 

### Natro Macro version

Natro Macro v1.0.0.1-v1.0.0.3

### What is your Discord username?

Jvzy

**Comment by Husseinsay** [comment]
i am having the same problem, i did everything but no solution

**Comment by misc-et** [comment]
Thanks for posting, it's likely there is a setting that's evaded you rather than this being a bug. The best place for support is our  [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002) which includes a guide to resolving this issue.
