### ISSUE TITLE
Macro profiles

### ISSUE THREAD

**Issue by dreadmp3** [NatroTeam/NatroMacro#870]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Macro profiles would be saves for multiple macro patterns or stats - one for main and one for a fuzzy alt, etc.

### How will this improve Natro Macro?

This can improve the efficiency and making it more simple of making another macro profile to use between multiple desktops or ways to gain items that you need. (nectar, item, honey, etc.)

### What is your Discord username?

dread.mp3

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/77
