### ISSUE TITLE
windy bee

### ISSUE THREAD

**Issue by sigmasigmaboy144** [NatroTeam/NatroMacro#871]
### Have you searched the existing suggestions?

No

### What is your suggestion?

we need this in natro macro cause it helps with quest or helps with loot just like vicious bee. if you would add this it would be a game changer for the quest that other people can do  

### How will this improve Natro Macro?

it will help with spirit bear quest. they suck on the 20 quest 

### What is your Discord username?

sigma.sigma.boy114

**Comment by misc-et** [comment]
Thanks for your suggestion. This has been considered and at this time, we are not considering adding a windy bee feature for a few reasons. These include that due to the limitations of macro, it is unlikely to be very effective.
