### ISSUE TITLE
 Inactive Honey

### ISSUE THREAD

**Issue by SlousGrow** [NatroTeam/NatroMacro#872]
### Have you searched the existing bug reports?

No

### What happened?

While farming I get  Inactive Honey and my character resets. What are they doing about it?
![image](https://github.com/user-attachments/assets/a3a32f9b-760d-463e-b5e0-f18f84f760c3)

### Steps to reproduce

1. f1
2. farm
3. reset

### What would you expect to happen?

How to fix that&

### Natro Macro version

1.0.3

### What is your Discord username?

asphaltnine

**Comment by misc-et** [comment]
This sounds like it may be an issue Roblox or other PC settings. Please see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002) for information and support.
