### ISSUE TITLE
natro macro stopped working as it should

### ISSUE THREAD

**Issue by TIGERS2007yt** [NatroTeam/NatroMacro#873]
### Have you searched the existing bug reports?

No

### What happened?

When I click F1 to start macroning, an icon pops up with an error on which it says: wrong language, wrong graphics settings, something bothers me natro macro in the windows window, I checked everything and I have it as macro requires it, I don't know what else I can do to make it work as before, so I'm writing to you

### Steps to reproduce

1. Click F1 to start macroming
2. I get an error window
3. Macro does some weird things like it resets over and over again and works like it shouldn't

### What would you expect to happen?

Macro should work as it was created, not do some weird things
![image](https://github.com/user-attachments/assets/8d03fdb4-180c-4da2-a8b1-a295ae1ac510)

### Natro Macro version

v1.0.0.3

### What is your Discord username?

F'Y'B Nightmare

**Comment by misc-et** [comment]
This sounds like it may be an issue with Roblox or other PC settings. Please see our [Discord server](https://discord.com/channels/1012610056921038868/1305651115374805002) for information and support, including a guide on this error.

**Comment by TIGERS2007yt** [comment]
I've been here for a long time but I don't know how I can get help there with my problem ;p

**Comment by misc-et** [comment]
Check out the knowledge-base there for a post on this issue and how to solve it, and the macro-help channel if you'r still having issues.

**Comment by dogeisawesomely** [comment]
It's been doing that to me too and I don't know how to fix it.
