### ISSUE TITLE
abilty to transfer planter progress/ planters planted across macros 

### ISSUE THREAD

**Issue by hiyjinx** [NatroTeam/NatroMacro#874]
### Have you searched the existing suggestions?

yes

### What is your suggestion?

So some people (like me) dont always use rdp sometimes they use their pc to macro or another device ex a laptop. I'm not 100% sure of how well this implementation would work but my general idea is after a macro is stopped/closed it uploads either a file or a special text to the macro channel and each time the macro gets opened it checks the channel for the file/text. This would be a toggle able feature.

### How will this improve Natro Macro?

This will benefit macro user like me making transitions seamless across devices/ to the rdp, also you could include things like cool down times to further improve efficiency that way the macro knows when stuff is available and doesn't waste time checking it. although i think this should be separate from the planter settings and should have another setting to  be a y/n option   each time the macro opens as some ppl like to play manually and therefore the cool downs would be done already

**Comment by hiyjinx** [comment]
discord username is still the same as my previous comment 1miss_rustbell

**Comment by misc-et** [comment]
Thanks for this suggestion, this functionality will be able to be achieved via the implementation of https://github.com/NatroTeam/NatroMacro/issues/77.
