### ISSUE TITLE
AutoClicker change

### ISSUE THREAD

**Issue by T3chr3v** [NatroTeam/NatroMacro#88]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

For autoclicking, simply use this command:
Click, down

### How will this improve Natro Macro?

The autoclicker as currently runs causes problems when you open menus in Bees

### What is your Discord username?

techrev

**Comment by T3chr3v** [comment]
Thanks for the question. Thinking about it more, there is still good use
for the F4 auto clicker.

IN ADDITION, I like to have a hotkey that does click down for times that
I'm playing on my own. I usually edit Natro Macro and assign one of my
mouse buttons to it. It would be nice to have Click, Down built into Natro
Macro assigned to a key/button.

Thanks,
Jeff

**Comment by zspz** [comment]
This will be possible in the upcoming patch due to Click Duration option being added to AutoClicker.

**Comment by T3chr3v** [comment]
Thank you for your response.

I look forward to checking it out.
