### ISSUE TITLE
Hive auto-claimer

### ISSUE THREAD

**Issue by 425LeoTheLion425** [NatroTeam/NatroMacro#883]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I don't know if this feature already exists, but for example, if your hive number is 4 and then you reconnect, if hive 4 is taken, it goes to hives 1 through 6 to claim the furthest right hive.

### How will this improve Natro Macro?

It would be helpful to people who want to claim hive slot 1, but if it's taken but hive slot 2 isn't, it claims hive slot 2.

**Comment by DullSmallmega176** [comment]
it's already a feature in the macro.
[L:16231](https://github.com/NatroTeam/NatroMacro/blob/750d1d90704e00c6a1d24fc7e408511d10655d94/submacros/natro_macro.ahk#L16231) -> [L:16380](https://github.com/NatroTeam/NatroMacro/blob/750d1d90704e00c6a1d24fc7e408511d10655d94/submacros/natro_macro.ahk#L16380)
