### ISSUE TITLE
Non-Macro Data Reporting

### ISSUE THREAD

**Issue by Mw119** [NatroTeam/NatroMacro#90]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Track and Submit Statmonitor data _without_ having to macro.

This as a suggestion is definitely a little backwards, but I haven't seen info or anywhere to do it otherwise. Personally I prefer just putting my active hours into playing actively and not macro, but I came to Natro purely because of the StatMonitor. I absolutely adore data analysis and having access to a graph output without having to macro sounds like a dream!

I am not suggesting to create some separate program, rather having some toggle within options where after I run Natro with this setting enabled, no automatic input happens via Natro, but all of the data compilation does. 

I ran Natro for half an hour under the pattern "stationary" and then took manual control of my character in-field until the top of the hour. Now I have a report that I am able to reflect on and make meaningful changes to my hive. I am just asking for the constant resetting and walking over to the fields to be disabled but all of the data reporting stay.

### How will this improve Natro Macro?

I believe having access to the StatMonitor for active play sessions would be beneficial to address things like hive composition and where things fall short. Its my understanding that Natro will not provide a more efficient session than a human would, so an "active override" retaining the data output would allow for the end user to process what they need more or less of in their hive. 

### What is your Discord username?

Omega_Pegasi

**Comment by Noobyguy775** [comment]
You can just run statmonitor by itself or do the method aspect said :)

(It's in the `submacros` folder)
