### ISSUE TITLE
Beesmas

### ISSUE THREAD

**Issue by PizzaManIsNotAvalible** [NatroTeam/NatroMacro#91]
### Have you searched the existing suggestions?

No

### What is your suggestion?

When Beesmas occurs add a sticker stack boost in boosts. For example it will say what its stacked to and you can pick which stickers you wanna donate. (Obviously this is an option if people want to donate stickers.) 

### How will this improve Natro Macro?

Boosting just from macroing will be more reachable.

### What is your Discord username?

PizzaMan#6101

**Comment by Noobyguy775** [comment]
Already planned

**Comment by PizzaManIsNotAvalible** [comment]
gocha
