### ISSUE TITLE
Average, maximum, minimum pop stars in hourly report

### ISSUE THREAD

**Issue by NimbusRod** [NatroTeam/NatroMacro#92]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add a stat in hourly report that will show average pop star, maximum pop star and minimum pop star

### How will this improve Natro Macro?

would allow to make server/hive adjustments based on the result

### What is your Discord username?

golden_sock

**Comment by zspz** [comment]
I agree that this would be useful, so I am linking it to #20.
Feel free to give details there!
